### ISSUE TITLE
New Feature: Keep a log of all Jenkins deploys

### ISSUE THREAD

**Issue by cjmachado** [cerberustesting/cerberus-source#1002]
Would it be possible to add some logging to org.cerberus.servlet.integration.JenkinsDeploy servlet? 
We would like to log all successful (HTTP 20X) deploys triggered from Cerberus. 
We wish that the logs could be saved at the database level, for further analysis. The log entries should record the user who triggered the deploy, when it was triggered, and also the complete url that was sent to Jenkins.

Currently, we are experiencing some unattended deploys, for which we cannot find who triggered it.

Thanks!

**Comment by vertigo17** [comment]
You can now access the feature in log Viewer Menu.
You can filter them by Page or Action.

![selection_158](https://cloud.githubusercontent.com/assets/5342048/20116007/d4068ada-a5fa-11e6-990a-358f70125a85.jpg)

**Comment by cjmachado** [comment]
Great!
Thank you very much for your prompt action.
