### ISSUE TITLE
Email encoding error with UserManager2.jsp

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1003]
Hi,

Editing user with UserManager2 cause encoding error

![image](https://cloud.githubusercontent.com/assets/995694/20171532/5f2348ba-a731-11e6-8702-6f958fe333fd.png)

see below =>

![image](https://cloud.githubusercontent.com/assets/995694/20171525/5b2496ec-a731-11e6-86a1-251a06a853de.png)

**Comment by Foudro** [comment]
Fixed with commit 58217e5
