### ISSUE TITLE
Bug on new execution page

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1005]
On this new page 'ExecutionDetail2.jsp' 

![image](https://cloud.githubusercontent.com/assets/995694/20186132/0e4d9358-a76f-11e6-9e6a-8b141ea5c395.png)

Can you reproduce this ?

**Comment by bcivel** [comment]
Hi @vitoo,
No, I cant reproduce. How did you open the page? Is it in an execution context? 
Thanks for the help

**Comment by vitoo** [comment]
ReportingExecutionByTag > 

I click on 'OK' result 
![image](https://cloud.githubusercontent.com/assets/995694/20186522/ab9e43a4-a770-11e6-857a-b5abb11dcb94.png)

**Comment by vitoo** [comment]
It happen in all case, not only in reportByTag

**Comment by vitoo** [comment]
It works on my local version of cerberus ... http://puu.sh/sdGUC/688796487f.png

**Comment by vitoo** [comment]
On our prod cerberus, bug happen only on new test execution, not on old one

**Comment by Foudro** [comment]
Which version of glassfish do you have?

**Comment by vitoo** [comment]
GlassFish Server Open Source Edition 4.1.1 (build 1)


![image](https://cloud.githubusercontent.com/assets/995694/20187861/60d149a6-a776-11e6-9885-7cc681f28c89.png)

**Comment by vitoo** [comment]
Any idea to fix this ?

Thanks

**Comment by bcivel** [comment]
Not yet. Seems to be integration issue.
We try to understand and propose a fix quickly

**Comment by vitoo** [comment]
I will try to "clean" the database 
To see if its a DB issue

**Comment by vitoo** [comment]
I will try to "clean" the database
To see if its a DB issue

Victorien

2016-11-14 9:09 GMT+01:00 Benoit CIVEL <notifications@github.com>:

**Comment by vitoo** [comment]
By importing the server cerberus database in my local cerberus, it works, it's maybe a glassfish issue

**Comment by vitoo** [comment]
Fixed by this commit
