### ISSUE TITLE
New feature => loop step

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1007]
Hello,
I would like to propose a new feature. A loop for a step with value (like loop for).
For my use cases, i have to check in SQL a value for each line. 
The feature would work like : 

VerifyStringEqual     %TOTO(n)(colomn)%    %TITI%
loop on n (n defined on test case)

thank you

Cerberus Version : 1.1.6-SNAPSHOT

Still to implement:
- [x]  Display step header from execution page.
- [x]  Remove answerList of step structure from execution object.
- [x]  Optimise calls to ReadTestCaseExecutionImage from execution page.
- [x]  save on database : loop + conditionval1Init + conditionval2Init
- [x]  Fix bug on Step status when using ConditionFalse loop functions and step not excuted
- [x]  fix bug on saving conditionVal1 and conditionVal2 in testcase page.
- [x]  correct: %SYS_STEP.n.RETURNCODE% to add index.
- [x]  Adding %SYS_CURRENTSTEP_ELAPSED% and %SYS_EXE_ELAPSED%
- [x]  move decodeStringWithSystemVariable from propertyService to VariableService class.
- [x]  Add a parameter to configure the limitation on nb of loop.

**Comment by pfoucray** [comment]
Same there, that would be very handy !!
For example, you need to add 4 products to you basket : The step is always the same.

If you loop, then youmay want to update your properties... including this into loop feature would be then great.

Best regards,
PF

**Comment by vitoo** [comment]
+1

We have an business app, where we need to do 60 times a step (somes actions & controls) so in the test case i use 60 times the same step, on the screen it give a very long test case, that make slow down the browser.

**Comment by vitoo** [comment]
It's making a huge test case, lagging browser 
As you can see in this screenshot :

http://puu.sh/szyCL/e1047e64b2.png

**Comment by pfoucray** [comment]
Lol you guys fear nothing ^^ that's fun to watch !
What we did a few times is to loop a whole test case. it's a bit of a cheat mode, but it works : last action of your test case is "openurl" and you put the URL to launch the same Test Case.
IDK if it could apply in you case, but it's fun as well !

Note : make sure there is an end. For example an "increment" and a value for "nb executions" (stored into a db for example). With an sql update action on "increment +1" and a Fatal Control on "increment + 1" < "nb executions"). Loooooop !!

**Comment by vertigo17** [comment]
I propose to create a new data to be defined at the step level that will have the following values:

onceIfConditionTrue (today behaviour). We execute the step once only if the condiion is true.
onceIfConditionFalse : We execute the step once only if the condiion is false.
doWhileConditionTrue : We execute the step and then execute it again and again as long as condition is true. if condition is always false, step is executed once.
doWhileConditionFalse : We execute the step and then execute it again and again as long as condition is false. if condition is always true, step is executed once.
whileConditionTrueDo : We execute the step as long the condition is true. If condition is always false, step is not executed.
whileConditionFalseDo : We execute the step as long the condition is false. If condition is always true, step is not executed.

**Comment by vertigo17** [comment]
Still to implement:
[ ] save on database : loop + conditionval1Init + conditionval2Init
[ ] Fix bug on Step status when using ConditionFalse loop functions and step not excuted
[ ] Optimise calls to ReadTestCaseExecutionImage from execution page.
[ ] Display step header from execution page.
[ ] correct: %SYS_STEP.n.RETURNCODE% to add index.
[ ] Adding %SYS_CURRENTSTEP_ELAPSED% and %SYS_EXE_ELAPSED%
[ ] move decodeStringWithSystemVariable from propertyService to VariableService class.
[ ] fix bug on saving conditionVal1 and conditionVal2 in testcase page.

**Comment by vitoo** [comment]
I will try today :)

**Comment by vitoo** [comment]
It works fine, thanks !

What if i have 2 different loop in the same testcase ?
If the first loop increment the currentstep_index to 10, the second loop will start at 10 ?

**Comment by vertigo17** [comment]
Good news, I will add quickly the parameter in order to allow the loop to more than 5.

Answering your question : No it will start again at 1.
Each step in independant.
