### ISSUE TITLE
Increased Load Time of a Campaign on ReportingExecutionByTag Page

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1011]
Hello,

We've noticed that the load time of a campaign increased significantly on ReportingExecutionByTag Page.

Se a normal PREPROD analysis has >3500 tests and this could influence the time we take in analysis:
http://cerberus.siege.red/CerberusRegression/ReportingExecutionByTag.jsp?Tag=WEB_THESEUS_ALL_PREPROD_2016111512

Can this be checked?

Thanks,
Best Regards

**Comment by gmoita** [comment]
Can I suggest a change on the sql that is executed to show the information?
We are seeing on the MySQL workbench the query running several times:
SELECT * 
FROM testcaseexecution exe 
left join testcase tec on exe.Test = tec.Test and exe.TestCase = tec.TestCase 
left join application app on tec.application = app.application 
inner join (select MAX(exe.ID) exeid from testcaseexecution exe where 1=1 and exe.tag = '%TAG%' group by exe.test, exe.testcase, exe.Environment, exe.Browser, exe.Country) t on exe.ID = t.exeID
limit 0, 100000
=» This is taking almost 20 seconds each to run on the MySql server

I've made a small change on the query and tested it on the same server and the result was retrieved in less than 1 second. The query I've done is:
SELECT exe.*, tec.*, app.*
FROM testcaseexecution exe 
left join testcase tec on exe.Test = tec.Test and exe.TestCase = tec.TestCase 
left join application app on tec.application = app.application 
inner join (select MAX(exe.ID) exeid from testcaseexecution exe where 1=1 and exe.tag = 'IT150273-2016-11-17T172000' group by exe.test, exe.testcase, exe.Environment, exe.Browser, exe.Country) t on exe.ID = t.exeID
order by exe.Test, exe.Testcase, exe.country
limit 0, 100000

Maybe the "order by" clause is not needed, but I also think it does not impact and could help "reading" the data (my humble opinion).

**Comment by bcivel** [comment]
Hi @gmoita 
Thanks for the proposal.
I tried in my IDE and it's more or less the same result 
<img width="145" alt="capture d ecran 2016-11-17 a 20 44 47" src="https://cloud.githubusercontent.com/assets/5376184/20404794/b450465a-ad06-11e6-9740-d80eeda10fd5.png">
