### ISSUE TITLE
Takescreenshot not working

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1013]
Hello,

We've noticed that Takescreenshot no longer works see executions below:

http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=39049555
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=39049566 

Could this be checked?

Thanks,
Best Regards

**Comment by Foudro** [comment]
Fixed with 30f81b6
