### ISSUE TITLE
missing testdata/properties

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1014]
It looks like the property is not defined:

 
![image](https://cloud.githubusercontent.com/assets/1914659/20351033/1f9e4f3c-ac09-11e6-9f67-7f31f2b30308.png)

And indeed that’s true http://cerberus.siege.red/Cerberus/TestCase.jsp?Test=Checkout%20Delivery%20Delivery%20Method&TestCase=0088B&Load=Load#stepAnchor_5 : 
 
![image](https://cloud.githubusercontent.com/assets/1914659/20351037/24c8be66-ac09-11e6-8a86-c2d4e0dbb44b.png)

So, let’s check who/when deleted it http://cerberus.siege.red/Cerberus/LogViewer.jsp?Test=Checkout%20Delivery%20Delivery%20Method&TestCase=0088B . The last person was IT159999 day 11:
![image](https://cloud.githubusercontent.com/assets/1914659/20351047/2b01937a-ac09-11e6-9070-e29875df5094.png)
 

So, let’s check the test execution history http://cerberus.siege.red/Cerberus/ExecutionDetailList.jsp?test=Checkout+Delivery+Delivery+Method&testcase=0088B&country=CH&environment=PREPROD&build=&revision=&controlStatus=&systemFlt=THESEUS&application=&tcstatus=&IP=&port=&tag=&BeforeDate=&execmax=100
It was ok day 15:
![image](https://cloud.githubusercontent.com/assets/1914659/20351053/30256264-ac09-11e6-9172-d47e4a8897f4.png)
 

So, let’s open the last OK execution http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=39004876:
![image](https://cloud.githubusercontent.com/assets/1914659/20351058/3404ec24-ac09-11e6-959a-777bac140c88.png)
 

So what’s going on? The last time the test was edited was day 11 but it was OK yesterday anda data dissapeared from yesterday to today. Looks like Testadata entry was deleted.
Plase adivse. 

Best regards,
Rui Rodrigues

**Comment by vertigo17** [comment]
Rui, It cannot be that testdata was deleted but must be the testcaseproperty that was deleted.
Maybe it was inside a useStep:
http://cerberus.siege.red/Cerberus/LogViewer.jsp?Test=MADIBA_LIB&TestCase=0001A
It was modified 8 times on the 15th of Nov by it140258 (all after the last OK execution).
The only other possible reason could be that the removal of the property was done directly inside database which is less likely to happen.
I close the ticket. Please reopen if you thing there is a real issue.
