### ISSUE TITLE
Authorities have changed - impossible to load test cases

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1015]
Hi,

We noticed some incoherence on the authorities of the cerberus.

The user "IT15999" no longer have access to the tests on a report campaign (it doesn't load the test cases). It seems related to the users authorities.

![report](https://cloud.githubusercontent.com/assets/14328346/20386253/b3afa1e0-acb2-11e6-977b-131591caa640.png)

Can you please take a look?

Thanks,
Best regards

**Comment by bcivel** [comment]
Hello,
It seems it's not related to user authorisation. 
Could you tell us if you have javascript error in you browser?

**Comment by gmoita** [comment]
We've made the following test on the same machines:
1) with my user (Admin), I can use the full report page
2) with the user not Admin, the testcase execution list (by country) it is not shown
3) added user to group Admin and it is working as 1)

Result on the java script with error is:
GET http://cerberus.siege.red/CerberusRegression/ReadParameter?param=cerberus_executiondetail_use 403 Forbidden
"NetworkError: 403 Forbidden - http://cerberus.siege.red/CerberusRegression/ReadParameter?param=cerberus_executiondetail_use"
TypeError: data is undefined
if(data.value !== "N"){

**Comment by Foudro** [comment]
Fixed By 	b80fd47
