### ISSUE TITLE
User administration changes blocks some options

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#1017]
Previously, when I needed a user to be able to use NewChain button on an environment, user needed to belong to IntegratorNewChain and IntegratorRO group (we have an example on that).
Currently, if I need to set the same kind of autority, when I select IntegratorNewChain, it automatically selects IntegratorRO (correct) and Integrator (incorrect).
I don't want a user to manage environments (higher risk), but I want the user to be able to send NewChain notifications.

**Comment by bcivel** [comment]
@gmoita, I excluded the selection of the role Integrator if selecting IntegratorDeploy
