### ISSUE TITLE
No warning for wrong system

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1019]
Hi,
When editing a test case with the wrong system selected no warning is now showed. Also it is now possible to run a test with the wrong system selected.
Althought it is very usefull we may loose notion for wich system the test case / application is set for. 
Is this a new expected behaviour and not an issue?
Cerberus version: 1.1.8-SNAPSHOT
Thanks.

**Comment by vertigo17** [comment]
This is the new expected behaviour.
We do not filter any longuer the testcase from the system selected.
