### ISSUE TITLE
can't save new property?

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1020]
when adding a new property to a testcase and saving i get the following error: 
![image](https://cloud.githubusercontent.com/assets/1914659/20409407/5b8b6b98-ad11-11e6-92d2-f74328cd2997.png)

To be checked ASAP.

**Comment by bcivel** [comment]
Just checked and I cannot reproduce. Can you give a bit more detail please?

**Comment by bcivel** [comment]
Tested also in prod and cannot reproduce.
Could you provide testcase number and scenario to reproduce?
Thanks

**Comment by ruirpr** [comment]
Example: http://192.168.134.17/Cerberus/TestCase.jsp?Load=Load&Test=Performance+Monitor&TestCase=5093A#propertyAnchor
Add property:
![image](https://cloud.githubusercontent.com/assets/1914659/20409600/31b91d1e-ad12-11e6-9328-5cb03136adc4.png)
Save changes -> error. 

Will try to figure out whats happening.

**Comment by bcivel** [comment]
Just added TOTO and TUTU properties in that testcase

**Comment by ruirpr** [comment]
I can see them. Weird.

**Comment by bcivel** [comment]
Having a look to your sreenshot, I can't see the new parameters (Retry and Period).
<img width="1628" alt="capture d ecran 2016-11-17 a 23 14 31" src="https://cloud.githubusercontent.com/assets/5376184/20410038/83a9eb72-ad1b-11e6-8ec9-8d1e27f93021.png">
Could you clear your browser cache and try again?

**Comment by bcivel** [comment]
When you click on create property, do you have these parameters?

**Comment by ruirpr** [comment]
You're right, clean cache solved it. Sorry for the panic :)

**Comment by bcivel** [comment]
No worry, Let's keep it open, but with the priority a bit lower :-) 
Thanks for the help
Benoit
