### ISSUE TITLE
Multi Run Test Case do not launch Test 

### ISSUE THREAD

**Issue by norecom** [cerberustesting/cerberus-source#1021]
Hi,

I just started using cerberus, and i have an issue with test launching.

Launch Test one by one  works correctly, but when I  launch several test at the same time, nothing happens.

KO MULTI LAUNCH

1) select one test case with 2 country  ( any combinaisons test case or country give the same result)

![multilaunch-1-ko-runtest1](https://cloud.githubusercontent.com/assets/23551732/20425943/39bf1354-ad7d-11e6-8e95-4621e27fd6b8.png)

2) Clic on RUN

![multilaunch-2-ko-reportingexecutionbytag](https://cloud.githubusercontent.com/assets/23551732/20425987/6813c5f6-ad7d-11e6-86d5-e79e09b50aed.png)

OK SINGLE LAUNCH

1) Launch one test case for one country

![singlelaunch-1-ok-runtest1](https://cloud.githubusercontent.com/assets/23551732/20426005/7f32348e-ad7d-11e6-9c94-b4bca9973843.png)

2) Clic on RUN => result screen is displayed, but no result here and also no test tag .

![singlelaunch-2-ko-executiondetail2](https://cloud.githubusercontent.com/assets/23551732/20426043/9ca21002-ad7d-11e6-9684-334c4ef156d5.png)

2) Clic on Old page 
![singlelaunch-3-ok-executiondetail](https://cloud.githubusercontent.com/assets/23551732/20426065/addc4dc4-ad7d-11e6-8ebb-9ee1a3726456.png)

Can you help me?

Thank's

Cerberus Version : 1.1.8-963

**Comment by vitoo** [comment]
Maybe websocket issue relating to #1005

**Comment by norecom** [comment]
Not sure, I've have no Websocket call :/

**Comment by vitoo** [comment]
Here is the error : 

Ajax request not authorized, need to be admin ?

![image](https://cloud.githubusercontent.com/assets/995694/20436827/e49260fe-adb1-11e6-9c60-3a8b552198f4.png)


```
Not Authorised Ressource...
You don't have enough privilege to open this page, Please ask your Cerberus administrator to grant the access.
```

**Comment by Foudro** [comment]
this looks like #1015 and should be solved thanks to b80fd47
Can you confirm?

**Comment by vitoo** [comment]
@norecom use the cerberus docker, so he will need a new version to test this fix

**Comment by norecom** [comment]
Hi, Can I have a new docker version for testing that ?

Thank's

**Comment by vitoo** [comment]
@bcivel @abourdon 

@norecom need docker hotfix with b80fd47

**Comment by bcivel** [comment]
@vitoo will do it today

**Comment by vitoo** [comment]
Thanks

**Comment by norecom** [comment]
Thanks it works
