### ISSUE TITLE
Edit/create Battery not working

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1023]
Hi,
This could be related to issue #1018 
On the new page for battery management /Cerberus/TestBattery2.jsp the add test case is not working as expected.
We can correctly create a battery and add test cases but if we add a new one, all the previous test cases inserted are removed and only the last one added is present.

**Comment by Foudro** [comment]
I am not able to reproduce in prod,
maybe you can describe more precisely your actions?

**Comment by Foudro** [comment]
alright!
this new issue should be fixed thanks to 49e010c
