### ISSUE TITLE
Execution queue is empty ! 

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1024]
Hi,

when trying to run a test case by selecting the environment (in this case PREPROD), the country and "add selection to queue and run" a message "Execution queue is empty !" appears.

![queue empty](https://cloud.githubusercontent.com/assets/14328346/20520505/fc1ac0fa-b09e-11e6-9763-7d6b564d106a.png)

After a short analysis to the test we noticed that the test is not defined for that environment so the environment shouldn't appear on the run list or the message should be more clear.

![testcase](https://cloud.githubusercontent.com/assets/14328346/20520568/3b5587f0-b09f-11e6-8f65-4d2991aa8b2c.png)

Can you please take a look?

Thanks

**Comment by vertigo17** [comment]
You will see on the top of the Queue a red layer that report 1 request was 'not added in the queue'.
If you click on it you will see in a modal the reasons why the execution was not inserted.
We do not display the message directly as there could be hundreds and request with different error and message would quickly become a mess (country do not exist for testcase or env not activated for testcase). Those errors/warning are displayed in a queue in the modal.

**Comment by ruirpr** [comment]
And the environment list could not be restricted to the activated environments for that test?
