### ISSUE TITLE
Characters not correctly displayed

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1027]
Hello,

There is an error with special characters in edit test case page, they are not displayed : 

![edittestcase](https://cloud.githubusercontent.com/assets/18569182/20566492/930c8e16-b195-11e6-998b-90c0bde8deec.JPG)

Thank you

Cerberus Version : 1.1.9-SNAPSHOT

**Comment by abourdon** [comment]
The same from the RunTestCase page:

<img width="927" alt="screen shot 2017-02-02 at 11 05 57" src="https://cloud.githubusercontent.com/assets/1511715/22545174/fed29314-e937-11e6-8802-ff833a40db3c.png">

Renamed this issue as more generic one.

**Comment by abourdon** [comment]
Unable to reproduce because characters are correctly displayed with the current version
