### ISSUE TITLE
Execution page stay in first step

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1031]
Hi,

With last version (on my local version) 

Execution screen stay on first step, progress bar dosnt move : 

![image](https://cloud.githubusercontent.com/assets/995694/20601871/046849ea-b25b-11e6-9eea-05c39bb410a0.png)

Need to refresh the page to get the rest : 

![image](https://cloud.githubusercontent.com/assets/995694/20601770/84e5bafe-b25a-11e6-89b0-16e563d7ddfc.png)

Do you have this issue to ?

**Comment by bcivel** [comment]
Hi @vitoo 
Yes, unfortunatelly automatic refresh has been desactivated due to error with websocket connection we're trying to solve. Hope to fix it asap.

Thanks
Benoit

**Comment by vitoo** [comment]
What is this error ? Because i'm still using a previous version with live websocket updates

**Comment by Foudro** [comment]
Hi @vitoo,
It's working on all our local machines, but when we try to deploy it on a remote server, we can't call the websocket, there is no response.

**Comment by vitoo** [comment]
It works on my remote server

![image](https://cloud.githubusercontent.com/assets/995694/20619856/f72a88be-b2f6-11e6-923b-24df6e4f30e0.png)

Maybe you have proxy blocking this protocol ?

**Comment by Foudro** [comment]
we have a proxy but when we disable it, it is not solving our issue.
But it's good to know that it is working on your server!

**Comment by bcivel** [comment]
Fixed with that commit 0cb35e5110f0802fb6c2dc3f0a2e59108269d1c7
