### ISSUE TITLE
property usestep overwrite

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1035]
Hi,
let's say I have a useStep with property1 defined for CH, IT, VI
then in the testcase where the useStep is used I define the same property1 for CH and IT and a certain action is performed if property1 exists. 
When running the test for VI i would expect that action not to be performed since i'm redinifing property1 in the testcase. What's happening is that the action is executed anyway, i guess it assumes the value from useStep.

Is this the expected behaviour? 

Thanks, 
Rui

**Comment by vertigo17** [comment]
Agree ruirpr, We will fix that.
