### ISSUE TITLE
Session/cookie issue

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1036]
Hi,

I have session issue here, after login : 
![image](https://cloud.githubusercontent.com/assets/995694/20711343/7817e7f0-b63f-11e6-9ba6-01973d33505b.png)

I have to remove all cookie/cache in browser (but it remove for every site) or use Cerberus in a private browsing to get access again 

Do you have this issue too ?

I get this since some weeks, started from 1.8 version

Thanks

**Comment by vitoo** [comment]
To fix this i have to remove this 'JSESSIONID' in 

`chrome://settings/cookies`

![image](https://cloud.githubusercontent.com/assets/995694/20711505/4b2fc068-b640-11e6-94f8-b84706340509.png)

**Comment by abourdon** [comment]
I also got this issue sometimes.

**Comment by vertigo17** [comment]
Not able to reproduce.
