### ISSUE TITLE
screen ExecutionDetail2.jsp do not work when cerberus is under HTTPS (WSS)

### ISSUE THREAD

**Issue by norecom** [cerberustesting/cerberus-source#1043]
Hi 

When acceding ExecutionDetail2.jsp, I've got an error and no test steps are displayed.

the error message : 

ExecutionDetail1.js:34 Mixed Content: The page at 'https://xxxxxxxxxx/Cerberus/ExecutionDetail2.jsp?executionId=1658' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://xxxxxxxxxx/Cerberus/execution/1658'. **This request has been blocked; this endpoint must be available over WSS.(anonymous function)** @ ExecutionDetail1.js:34

ExecutionDetail1.js:34 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.(…)

Does cerberus support HTTPS ? or will support ?

Thanks

**Comment by bcivel** [comment]
Hello @norecom 
Yes, it will suport https. We will solve that issue asap
Thanks for the feedback
Benoit

**Comment by bcivel** [comment]
Fixed by @Foudro with b58744f6b6b971c43c8796e0d3ab378c015a8a5a
Thanks
