### ISSUE TITLE
Call soap action unknown URL

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1045]
Hello,

When you execute an action with a callSOAP or a CallSOAPwithbase, the URL complete is not displayed.
So we can't confirm if it is the good one that is called.
Could you please add this on the new page execution detail ?

Thank you !

**Comment by vertigo17** [comment]
Can you put a screnshot of the result message ? The URL that failed to be called should appear on the result message of the action.

**Comment by vertigo17** [comment]
We will had the Service path on top of the operation called even when return is OK.
