### ISSUE TITLE
With a control set to not 'Fatal', should the execution be KO ?

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1056]
Hi,

In case we need to do a control on an element sometimes not present, 

ex : 'verifyTextInPage'   ...some text ... Fatal : No

If it's not found in Page, and the control is not Fatal, it should not set the test case execution to KO, isnt it ?

Because the test case is KO, i was expecting OK 

Thanks for your help

**Comment by bcivel** [comment]
Hi @vitoo,
The Fatal on control define if the test continue even if the control is KO. But the result of the testcase is KO if one KO has been found.
So it is the normal behavior.
Thanks
Benoit
