### ISSUE TITLE
Add specific conditions in the "Step condition Operation"

### ISSUE THREAD

**Issue by MichaelWil** [cerberustesting/cerberus-source#1063]
Hi,

For each step you can activate the concerned step following the conditions : "Always", "ifPropertyExist" or "never".

I'd like other instructions that may test the following conditions, ifProperty is : 
1- > to a value (to be set)
2- < to a value (to be set)
3- = to a value (to be set)
4- >= to a value (to be set)
5- <= to a value (to be set)

The target that antail this need is : to be able to create a (stable) test that will check the correct behaviour when the fees are free ot not.

Thanks

**Comment by vertigo17** [comment]
Isn't it better to create a testcase per case by securing that the scenario generate the correct fee level.
If you put everything in the same test and only 1 step is executed, that means the test will only cover and control that specific case leaving the others not tested.

**Comment by vertigo17** [comment]
the new conditions will be:
isNumericEqual
isNumericDifferent
isNumericGreater
isNumericGreaterOrEqual
isNumericMinor
isNumericMinorOrEqual
