### ISSUE TITLE
Update SOAP's trim some characters

### ISSUE THREAD

**Issue by mbessa** [cerberustesting/cerberus-source#1069]
Hello,

When user update a SOAP, some trimming occur, for instance: <Timestamp>2014-04-08T14:30:00.000+01:00</Timestamp>
<Timestamp>2014-04-08T14:30:00.000 01:00</Timestamp>

Remove plus sign and SOAP stop working correctly.

Can you check this ? We have to edit several SOAP's in directly in DB because users complain that after edit SOAP stop working.

Thanks!
Marco Bessa

**Comment by Foudro** [comment]
this looks like #1044 and should be fixed thanks to c008944
So it should work in QA
