### ISSUE TITLE
Incoherence between GetNumberOfExecutions and data on database

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#1070]
We are using GetNumberOfExecutions to check the number of executions of specific tests with specific results (just OK, just KO, just FA, etc.).

We've got some complaints from users saying that values were not correct.
I've compared the values and they are not coherent.

Example:
- at 11:07 I've used the GetNumberOfExecutions?nbminuteshistory=240&controlstatus=OK with a specific test (&test=Datamart) and application (&application=IDW); the result was 8457
- at the same time, I've did a query on the database and the result for the whole day (from midnight to 11:07) was just 132 OK

**Comment by vertigo17** [comment]
There were an error on the join on an SQL that increased the nb by mistake.
Also have in mind that the servlet also filter the executions performed on WORKING test cases.
