### ISSUE TITLE
switchToWindow 2 windows same name

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1071]
Hi, if I'm on a window called "La Redoute, Mode française" and use the switchToWindow  "La Redoute, Mode française" this works, right? 
I tryied this and it seems to work but just to make sure... 
http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=40237459

**Comment by bcivel** [comment]
Yes, it's like you saw.
Using switchToWindow will loop on all the opened windows and switch if : 
 - You are on a different page that the original page (comparing windowHandle uuid number)
 - The new window title is the one you defined
