### ISSUE TITLE
Fail to find element and test remains pending

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1072]
Hello,

I'm facing a problem when an object is not found with iOS tests the test remains pending and app keeps opened in iPhone.
See this execution:
http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=40304235

Can you check please?
Thanks
Best Regards

**Comment by bcivel** [comment]
Hi @j0hnsa 
Could you confirm it still happen? I had a look to the last executions and they are all in a normal status (FA/OK/KO).
Thanks
Benoit
