### ISSUE TITLE
ExecutionDetail: add link to Last Executions by country and environment

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#1073]
Hi.
For monitoring and to speed up some analysis, it would be nice if we have on the ExecutionDetail page, near the "See Last Executions" link (can be below or above), a link that could point to the execution list related to the country and environment for which the ExecutionDetail is related.

Example:
ExecutionDetail.jsp?id_tc=38819497 is related to test "Quai30 BOUT EN BOUT" + testcase "1052B1" + Country "FR" + environment "UAT"

The link of "See Last Executions" is showing "/ExecutionDetailList.jsp?test=Quai30%20BOUT%20EN%20BOUT&testcase=1052B1&MySystem=", which lists the last executions for the test case (all environments and countries)

What we would like is to have a link that points to something as "See Last Executions for %COUNTRY% on %ENVIRONMENT%", with the link "ExecutionDetailList.jsp?test=Quai30+BOUT+EN+BOUT&testcase=1052B1&country=FR&environment=UAT&systemFlt=&application=%APPLICATION%"

**Comment by vertigo17** [comment]
Considering that the filter could be with COUNTRY or ENVIRONMENT or even other criterias such as TAG or CONTROLSTATUS, I suggest we create 2 or 3 parameters where we can configure the description of the link and assiated URL with variables.
When the parameter exist, the link will be displayed on the page.

**Comment by Foudro** [comment]
I added the link you asked to the new Execution Detail page. 
We will see in the future if we need it to be more flexible.
Closed with 1c2989a
