### ISSUE TITLE
Some textfields dont trigger the keyboard - iOS

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1077]
Hi,

There are some textfields on the iOS app that dont trigger the Keyboard. 
Below is one example where that issue happens:
http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=40386984

I've tried to add Multiple clicks on that textfield but had no success.
![keyboardscr](https://cloud.githubusercontent.com/assets/16339891/21387315/fe4b5d1c-c76e-11e6-9602-cbe49fed7382.png)

Logs:
[debug] [MJSONWP] Calling AppiumDriver.keys() with args: [["Jupe"],"0a4d7fa3-e1aa-4dc1-b265-c54cffb1526f"]
[debug] [XCUITest] Executing command 'keys'
[debug] [JSONWP Proxy] Proxying [POST /keys] to [POST http://localhost:8100/session/053F907E-A48A-4613-9ED9-BB22D9F9830F/keys] with body: {"value":["J","u","p","e"]}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Keyboard is not present\" UserInfo={NSLocalizedDescription=Keyboard is not present}","sessionId":"053F907E-A48A-4613-9ED9-BB22D9F9830F","status":13}
[HTTP] <-- POST /wd/hub/session/0a4d7fa3-e1aa-4dc1-b265-c54cffb1526f/keys 500 5167 ms - 304 
[HTTP] --> DELETE /wd/hub/session/0a4d7fa3-e1aa-4dc1-b265-c54cffb1526f {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["0a4d7fa3-e1aa-4dc1-b265-c54cffb1526f"]
[debug] [JSONWP Proxy] Proxying [DELETE /session/0a4d7fa3-e1aa-4dc1-b265-c54cffb1526f] to [DELETE http://localhost:8100/session/053F907E-A48A-4613-9ED9-BB22D9F9830F] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"94B1D15D-845D-4852-A419-208EC20CDC16\",\n  \"status\" : 0\n}"
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 38534)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Shutting down Logger process (pid 38535)
[XCUITest] System log exited with code 'null'
[XCUITest] Shutting down iproxy process (pid 38549)
[XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Full reset requested. Will try to uninstall the app 'com.Redoute.RedouteIphone'.
[debug] [XCUITest] Removed 'com.Redoute.RedouteIphone'
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[Appium] Removing session 0a4d7fa3-e1aa-4dc1-b265-c54cffb1526f from our master session list
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[debug] [MJSONWP] Responding to client with driver.deleteSession() result: null

**Comment by bcivel** [comment]
Hi @j0hnsa ,

I had a look to Appium and WebDriverAgent github and I found that you have this error message usually when the textfield is not displayed in the screen. In this case, they advice to scroll to make the field visible and then type text.
https://github.com/facebook/WebDriverAgent/issues/368

So scrolling a bit to make the field visible may help to make it working.

Anyway, for the future tickets, could you please take screenshot on not OK action to help the investigation?

Thanks for your contribution. :-)

Benoit

**Comment by bcivel** [comment]
I keep that ticket open until the issue https://github.com/facebook/WebDriverAgent/issues/368 is fixed.
As explained, as a workaround, you can swipe to make the field visible. Once solved, you will be able to remove the swipe actions.
Thanks

**Comment by bcivel** [comment]
@j0hnsa Could you confirm if it's solved for you?
Thanks
Benoit

**Comment by j0hnsa** [comment]
Hi @bcivel ,

Unfortunately I'm not being able to test this in QA. I don't know if its "new" this blockage but Test starts but doesn't seem to be able to find elements.

http://192.168.134.197/CerberusQA/ExecutionDetail2.jsp?executionId=44126222

I'm guessing this could be related to Outdated or not present dependencies of appium below you can check some logs:

on QA the logs will look like this:
[Appium] New XCUITestDriver session created successfully, session 612ea0ba-c295-490d-b8ac-535285168ed3 added to master session list
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"iPhone","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"automationName":"XCUITest","newCommandTimeout":240,"platformVersion":"10.1","app":"/Users/itsqdtests/Desktop/Payload/La Redoute_PreProd_7.4.2.223.ipa","deviceName":"iPhone 5s","platformName":"iOS","autoDismissAlerts":true,"udid":"e9f4d10b6ac8f0f45c8da072c9aee0639bd0587f","version":"","xcodeConfigFile":"/Users/itsqdtests/appium/conf/appium.xconfig","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","fullReset":true,"sendKeyStrategy":"setValue","showIOSLog":false,"showXcodeLog":true,"useNewWDA":true,"idleTimeout":40,"avoidProxy":1,"nativeWebTap":true,"autoWebviewTimeout":"600","preventWDAAttachments":false,"webviewConnectRetries":30}
[HTTP] <-- POST /wd/hub/session 200 28657 ms - 941 
[HTTP] --> DELETE /wd/hub/session/612ea0ba-c295-490d-b8ac-535285168ed3 {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["612ea0ba-c295-490d-b8ac-535285168ed3"]
[debug] [JSONWP Proxy] Proxying [DELETE /session/612ea0ba-c295-490d-b8ac-535285168ed3] to [DELETE http://localhost:8100/session/724121FF-B41D-49B5-87C1-E43F8B01E9B2] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"6255AD4D-5C6B-4021-8AB5-542A804B0654\",\n  \"status\" : 0\n}"
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 11371)
[Xcode] ** BUILD INTERRUPTED **

[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Shutting down Logger process (pid 11372)
[XCUITest] System log exited with code 'null'
[XCUITest] Shutting down iproxy process (pid 11386)
[XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Full reset requested. Will try to uninstall the app 'com.Redoute.RedouteIphone'.
[debug] [XCUITest] Removed 'com.Redoute.RedouteIphone'
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[Appium] Removing session 612ea0ba-c295-490d-b8ac-535285168ed3 from our master session list
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[debug] [MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/612ea0ba-c295-490d-b8ac-535285168ed3 200 1321 ms - 76 


on PROD:
[debug] [WebDriverAgent] Device: Mar 29 11:09:27 iPhone-de-La XCTRunner[2743] <Notice>: Running tests...
[debug] [WebDriverAgent] Device: Mar 29 11:09:28 iPhone-de-La XCTRunner[2743] <Notice>: Continuing to run tests in the background with task ID 1
[XCUITest] Detected that WebDriverAgent is running at url 'http://192.168.1.142:8100'
[XCUITest] WebDriverAgent started at url 'http://192.168.1.142:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.Redoute.RedouteIphone","arguments":[],"environment":{},"shouldWaitForQuiescence":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"FDA1A64F-3323-43B3-B356-978EB2528922","capabilities":{"device":"iphone","browserName":"La Redoute","sdkVersion":"10.1.1","CFBundleIdentifier":"com.Redoute.RedouteIphone"}},"sessionId":"FDA1A64F-3323-43B3-B356-978EB2528922","status":0}
[debug] [XCUITest] Found WDA derived data folder: /Users/itsqdtests/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy
[XCUITest] Setting '755' permissions to /Users/itsqdtests/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments folder
[debug] [XCUITest] Found WDA derived data folder: /Users/itsqdtests/Library/Developer/Xcode/DerivedData/WebDriverAgent-eueyzmbgvkeojkdwwdighuogsoel
[XCUITest] Setting '755' permissions to /Users/itsqdtests/Library/Developer/Xcode/DerivedData/WebDriverAgent-eueyzmbgvkeojkdwwdighuogsoel/Logs/Test/Attachments folder
[debug] [XCUITest] Setting initial orientation to 'PORTRAIT'
[debug] [JSONWP Proxy] Proxying [POST /orientation] to [POST http://localhost:8100/session/FDA1A64F-3323-43B3-B356-978EB2528922/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"FDA1A64F-3323-43B3-B356-978EB2528922","status":0}
[Appium] New XCUITestDriver session created successfully, session fe78809a-b679-4669-a9ab-577e50373095 added to master session list
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"firefox","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"automationName":"XCUITest","app":"/Users/itsqdtests/Desktop/Payload/La Redoute_PreProd_7.4.2.223.ipa","acceptSslCerts":true,"autoDismissAlerts":"true","udid":"e9f4d10b6ac8f0f45c8da072c9aee0639bd0587f","version":"","newCommandTimeout":"false","platformVersion":"10.1","firefox_profile":"UEsDBBQACAgIACRhfUoAAAAAAAAAAAAAAAAHAAAAdXNlci5qc5VXTW/jNhC991cUPrVATSS73Ut7\nSrMpUGDRFGsEeyQoamQxpkiWHFrxv++QstcflSjlZskz5Myb9x6pGMBz56H5aQVvCCYoawKLrhYI\nzFhUzeGFQla//NgIHeDn33+I5wxlUDMhJTjkWphtFFsIFLpq/Oo6soY9WqsDA++tl7SH1cDAiEpD\nTRno483aAWT0Cg9MBncMHC/ie2AvvOFgELwyW55fAwut7bk1ciK58ranJ2agR1E5qv+iqJH4/2NU\nDD8tX9uO9crUtmd17FyxcVpVeHDWI7XBWhAa2+GZabvdppdH/J5KW785ZQIKrVnfKgStAjIP/0bl\npzJSkbUKaU1uHRhex4yktmIiwzaNVgbWwrnAaCuCujrwGhoRNY42d4Ffpa3c5bIWQUi9eIyOpRlR\n5N11VCLXTiGjRqED9Afq9RUkTmFMrXbijcvW2w54kF4RhX00HFWXlv94N14Fva...
[HTTP] <-- POST /wd/hub/session 200 29684 ms - 2590 
[HTTP] --> POST /wd/hub/session/fe78809a-b679-4669-a9ab-577e50373095/element {"using":"xpath","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeTable[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeTable[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]","fe78809a-b679-4669-a9ab-577e50373095"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/FDA1A64F-3323-43B3-B356-978EB2528922/element] with body: {"using":"xpath","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeTable[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"FD991223-BBBD-43C1-BC90-CC62A60DEFE0","type":"XCUIElementTypeStaticText","label":"Escolha outro país"},"sessionId":"FDA1A64F-3323-43B3-B356-978EB2528922","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"FD991223-BBBD-43C1-BC90-CC62A60DEFE0","type":"XCUIElementTypeStaticText","label":"Escolha outro país"}
[HTTP] <-- POST /wd/hub/session/fe78809a-b679-4669-a9ab-577e50373095/element 200 1132 ms - 187 
[HTTP] --> POST /wd/hub/session/fe78809a-b679-4669-a9ab-577e50373095/element {"using":"xpath","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeTable[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeTable[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]","fe78809a-b679-4669-a9ab-577e50373095"]


Can you check please?

Thanks and Regards

**Comment by j0hnsa** [comment]
Issue can be closed as we have workaround
