### ISSUE TITLE
Get the live status of a report by tag

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1078]
Hi,

We need an URL like ResultCI to know the detailed status of a ReportByTag when we are auto lauching campaign with deployment tool 

To get a json like : 

```json
{ 
"KO": 1,
"FA": 1,
"PE": 3,
"OK":23,
"TOTAL":28
}
```

Is it possible ?
Maybe we can evolv ResultCI to get more information ?

Thank you

**Comment by vertigo17** [comment]
We will create a new version of the ResultCI Servlet moving to ResultCIV001 that will provide that result as well as the already used data from ResultCI calculation.

**Comment by vertigo17** [comment]
This is an example of the result that will be provided.
I replaced OK by "status_OK_nbOfExecution"
The final OK/KO result provided in last version of ResultCI is "result"
{
    "result": "KO",
    "messageType": "OK",
    "message": "CI result calculated with success.",
    "NonOK_prio1_nbOfExecution": 10,
    "NonOK_prio2_nbOfExecution": 17,
    "NonOK_prio3_nbOfExecution": 31,
    "NonOK_prio4_nbOfExecution": 0,
    "CI_OK_prio1": 1,
    "CI_OK_prio2": 0.5,
    "CI_OK_prio3": 0.20000000298023224,
    "CI_OK_prio4": 0.10000000149011612,
    "CI_finalResult": 24.700000762939453,
    "TOTAL_nbOfExecution": 229,
    "status_PE_nbOfExecution": 0,
    "status_NA_nbOfExecution": 4,
    "status_FA_nbOfExecution": 39,
    "status_OK_nbOfExecution": 169,
    "status_CA_nbOfExecution": 0,
    "status_KO_nbOfExecution": 17
    "ExecutionStart": "2016-07-14 05:58:27.0",
    "ExecutionEnd": "2016-11-23 02:02:15.0",
}

Please reopen the issue if an information is missing.
