### ISSUE TITLE
Cant Swipe from bottom to top - iOS

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1079]
Hi,

We cant Swipe from bottom to top. Tried with custom and with default Directions but its not working properly. Below the logs on the logs from appium it seems that can be some misconfiguration:

[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":**{"x":160,"y":378}}**,{"action":"wait","options":{"ms":2000}},{"action":"moveTo","options"**:{"x":160,"y":1}}**,{"action":"release","options":{}}],"84fd3973-f797-475a-9686-bb362fc6d475"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press-wait-moveTo-release
[debug] [JSONWP Proxy] Proxying [POST /uiaTarget/0/dragfromtoforduration] to [POST http://localhost:8100/session/4906B92D-22CE-47C5-839A-A345332D8CEF/uiaTarget/0/dragfromtoforduration] with body: **{"fromX":160,"fromY":378,"toX":320,"toY":379,"duration":2}**
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"4906B92D-22CE-47C5-839A-A345332D8CEF","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/84fd3973-f797-475a-9686-bb362fc6d475/touch/perform 200 5012 ms - 74 
[HTTP] --> GET /wd/hub/session/84fd3973-f797-475a-9686-bb362fc6d475/window/current/size {}

Jo??o Santos

**Comment by bcivel** [comment]
Hi @j0hnsa ,

Please, can you have a look to that issue : 
https://github.com/appium/appium/issues/7558

It seems that another guys had this problem and it has been solved removing the opposite scrolling mode from the platform where appium is setup. Maybe it can help :-)
Could you try and give feedback please?

Thanks

**Comment by vitoo** [comment]
Same issue

If i'm doing swipe UP or Down it's Swiping Up, so it cant' go down

Will look at this appium link

**Comment by vitoo** [comment]
Have you find a workarround to this ? @bcivel @j0hnsa 

I'm automating on iphone 5s (iOS 9.2) simulator

**Comment by bcivel** [comment]
Hi @vitoo .
Just to be sure, you put DOWN, and not Down ?

**Comment by vitoo** [comment]
Yes

And i've tried to swipe custom, it's still going up and not down :(

**Comment by vitoo** [comment]
i should tri appium 1.6, i'm on 1.5

**Comment by vitoo** [comment]
I finnally suceed to automate a real iphone, it start faster than a simulator 😃 

with this parameters 
`{
    "xcodeConfigFile": "/path/to/appium.xcconfig",
	"realDeviceLogger": "/usr/local/lib/node_modules/deviceconsole/deviceconsole"
}`

But i got the same swipe problem than in a simulator.

So iOS testing is stuck for us.

I hope we can find a workarround soon !

Thanks

**Comment by j0hnsa** [comment]
I believe the latest meeting I had with benoit there was an update to driver that fixed the issue. For me its no longer present.

**Comment by vitoo** [comment]
This update date from when ?

**Comment by j0hnsa** [comment]
I think 2 weeks ago

**Comment by vitoo** [comment]
Okay, i'm on the cerberus-testing-1.1.10 release, date from the 21/01/2017

**Comment by bcivel** [comment]
Hi @vitoo,
Since a recent release, the swipe duration in Appium is in ms (despite of the error message that you get).

Could you try to use 3000 instead of 3?

In our configuration, we use 2000.

Which appium version are you using exactly ? 1.6.3 ? 
Thanks
Benoit

**Comment by vitoo** [comment]
It's in release 1.1.10 ?

**Comment by vitoo** [comment]
In release 1.1.10 it works 

My Prod is just before 1.1.10 and i got the previous quoted bug

**Comment by bcivel** [comment]
Thanks for your update.
I close this issue so.
