### ISSUE TITLE
Two save buttons on new edition page test case properties

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1084]
Hi,

on new edition page, on properties there are two save buttons.
Both buttons seems to have the same behaviour.

![sem titulo](https://cloud.githubusercontent.com/assets/14328346/21429906/d1ca749a-c858-11e6-93d2-2ae9ceb273cd.png)

Can you explain why we need two buttons for the same action?

Thanks,
Roberto

**Comment by Foudro** [comment]
Hi,

At first there was only the button at the very bottom just as every other modals, but when the inherited properties are shown it was too long to access to this button that's why we added another one more accessible.
And I confirm that they have the exact same behaviour.

Corentin
