### ISSUE TITLE
pretty != functional != efficient

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1085]
In the new script page, how do i quickly identify properties defined for each country? 
![image](https://cloud.githubusercontent.com/assets/1914659/21438925/493b4372-c883-11e6-9ea1-a4c7c6c1956a.png)

Import steps does not shows name:
![image](https://cloud.githubusercontent.com/assets/1914659/21438989/8a1295e4-c883-11e6-83f2-a472e5cc970e.png)

In a long step is missing add action in the middle of the actions. I have to add to the end, then drag a litlle because everything is so big, then scroll the page, then drag a little
![image](https://cloud.githubusercontent.com/assets/1914659/21439043/bf9a6ea8-c883-11e6-9f27-40ea2bed93a2.png)

As it is right now is a nightmare to work fast.

**Comment by vertigo17** [comment]
Take it easy rui
We don't need to make it ugly to improve what you ask.

**Comment by vitoo** [comment]
Hello,

We need also the step number
When the step n° 64 fails and we have to find it in the list, it could help

Thank you

**Comment by Foudro** [comment]
Done.
We don't only want it to be pretty, we also want it to be fully functionnal and easy to use.
The new page still needs some adjustments, not all users use Cerberus the same way, that's why we need these kind of feedback. So thank you.
