### ISSUE TITLE
Click on pos {x,y} for android and ios devices

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1088]
Sometimes there are some elements that can't be clicked for one reason or another it would be interesting to simulate clicks (tap) on a specific position that we can easily retrieve from appium inspector.

Could this be Implemented?

Thanks
Best Regards

**Comment by j0hnsa** [comment]
Could this be checked? I am using swipe as a workaround and it may solve some of the problems faced when trying to click some objects not identified by appium. issues #1077  #1075 #861

**Comment by abourdon** [comment]
Hi @j0hnsa,

The click action is now able to handle the new **coord** prefix which can takes an x,y coordinates.

Example:

coord=x:10,y:20

Then Cerberus will tap on the {10;20} coordinate.

Beware that x and y are screen relative and so {0,0} defines the upper pixel from the left.

Regards,
Aurélien

**Comment by j0hnsa** [comment]
Hi @abourdon,

Great! I think it will be really handy and it may solve some of the issues I'm facing with iOS automated tests :)

Thanks,
Regards

**Comment by j0hnsa** [comment]
Hi @abourdon ,

This solution didnt made the trick, I was able to test it on QA but maybe the tap isnt long enough to trigger the keyboard, could this be increased?

http://192.168.134.197/CerberusQA/ExecutionDetail2.jsp?executionId=44448905

Thanks and Regards

**Comment by j0hnsa** [comment]
Good thing is that text that was appended isnt appended anymore but it doesnt trigger the keyboard.
