### ISSUE TITLE
test failing but element present on page

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1092]
Hi

i've been experiencing a strange behaviour where the test hangs on a xpath expression that is actually present in the page and site is finished loading. 

screenshot from actual test execution:
![image](https://cloud.githubusercontent.com/assets/1914659/21608446/6fc1c2de-d1b4-11e6-961a-442417a07a4a.png)

and test in PE for a long time and then will fail:
http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=40870809
took 68 minutes to fail

Any ideia about this situation? 

Thanks!

**Comment by ruirpr** [comment]
Another weird behaviour:
![image](https://cloud.githubusercontent.com/assets/1914659/21653180/c99f339c-d2a7-11e6-8131-bcc66eb88d1c.png)
http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=40927316

Step 15 took a lot of time for no aparent reason and indeed cerberus shows 599.078s. But when looking at each action there's no such time: 1.5s + 1.3s + 1.5s is not 599s in my calculator :). So where did all the time go?

**Comment by ruirpr** [comment]
Ok, the time was spent in calculating the property:

![image](https://cloud.githubusercontent.com/assets/1914659/21653479/3746c030-d2a9-11e6-8da5-078c37a3e8d6.png)

But I don't fully get why it took so long when the object as in the page and page was aparently fully loaded.

**Comment by abourdon** [comment]
@ruirpr is this issue still present? If yes, did you faced to a element inside an other frame?

**Comment by htopoff** [comment]
@abourdon 
Hey ! 
I faced an element inside an other frame, how can I point that element as an element path ?

**Comment by htopoff** [comment]
Thanks for your response @abourdon !
But it didn't worked... I think that I'm doing it in the wrong way,
Here is a screenshot of the source page :
![01](https://user-images.githubusercontent.com/38133450/38423528-756d0ee2-39ae-11e8-8077-8090e0cbeed2.PNG)
The selected element is where I want to go.
Then I did that as test case : 
![02](https://user-images.githubusercontent.com/38133450/38423600-b0aabcf2-39ae-11e8-8fd4-5817ed85e789.PNG)
How can I get this frame ?

Regards,
Hadrien

**Comment by abourdon** [comment]
@htopoff,

The `focusToIFrame` action is used to define the iframe context to use when interpreting action/control's element paths.

In other words, when you want to point to an element that is located to an iframe, then you have to call the `focusToIFrame` action to change the iframe context before to point to this element.

To do so, the `focusToIFrame` action takes the element path to the iframe in argument. In your case, `name:recherche` for instance.

After that, you can apply your desired action to your `chp:Nomtie` element.

Finally, don't forget to go back to the default context by using the `focusDefaultIframe`.

@vertigo17, could you please add some details about it as it is missing in the documentation: https://cerberustesting.github.io/documentation_en.html#_action

Hope it helps,
Aurélien

**Comment by htopoff** [comment]
Thank you for your help !
Works well now !
