### ISSUE TITLE
Add screen size to robot

### ISSUE THREAD

**Issue by bcivel** [cerberustesting/cerberus-source#1094]
Today, it is only possible to set screensize from the run page.
It would be usefull to save it at the robot level too.

<img width="516" alt="capture d ecran 2017-01-03 a 17 25 45" src="https://cloud.githubusercontent.com/assets/5376184/21614492/f50e1d00-d1d9-11e6-864f-620e3956cf5a.png">

**Comment by ping0uin** [comment]
I confirm.
it would be usefull to define some specific robot to "simulate" the responsivity of a website for instance.

**Comment by bcivel** [comment]
fixed with my previous commit
