### ISSUE TITLE
testcaselist => can't resize colonm

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1096]
Hello,
I'm forced to use Excel to have an overview of my test case list because I can't resize the colomns in Cerberus to see all the description field.
Could you please add this feature ?

![testcaselist](https://cloud.githubusercontent.com/assets/18569182/21643328/ee0ad846-d287-11e6-8e61-d30a82df8bb7.PNG)

Thank you !

Cerberus Version : 1.1.10-SNAPSHOT-1027

**Comment by bcivel** [comment]
Dear Excel Fan ;-)
Seems to be fixed thanks to @nicodeur commit
Thanks
