### ISSUE TITLE
environment display in reporting by tag

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1097]
Hi, 
would it be possible to show the environment in a more readable way? 
![image](https://cloud.githubusercontent.com/assets/1914659/21649404/87749dc6-d299-11e6-92dd-9f349f595844.png)

When running test for Preview and Preprod, both start with PR... as attached. Maybe a new line over countries? 
![image](https://cloud.githubusercontent.com/assets/1914659/21649931/3f22ea76-d29b-11e6-968f-19eccc7c53a0.png)

Thanks, 
Rui

**Comment by vertigo17** [comment]
Columns have now static and minimum size.
On top of that, toottips are displayed.
