### ISSUE TITLE
Screenshot error with Campaign lanched with execute_campaign

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1104]
Hi,

Campaign launched with execute_campaign script can't return screenshot : 

![image](https://cloud.githubusercontent.com/assets/995694/21764280/8850e39a-d662-11e6-80eb-2fb5bed5ae92.png)

It return : 
![image](https://cloud.githubusercontent.com/assets/995694/21764286/92bd17a4-d662-11e6-8134-425e23b1bb53.png)

**Comment by vitoo** [comment]
So it's the html that is saved and not the screenshot

**Comment by bcivel** [comment]
Hi @vitoo ,
Did you customize the execute_campaign script? Are you using screenshot=1 parameter in that script?
Could you send some URL generated by this script?
Thanks
Benoit

**Comment by vertigo17** [comment]
I understand that the control verifyTextInElement failed because field could not be find.
It did generate a paesource files but no screenshot.
I confirm that it should have created both.
Can you check if the file was created inside the execution folder ?

**Comment by vitoo** [comment]
@bcivel yes screenshot is set to 1 in the script 

Here is a URL example : 
`http://ppicboappcerb01.fra.local:8080/Cerberus//RunTestCase?&&Test=CED&TestCase=0023A&Browser=chrome&Country=RX&Environment=INTE&ss_ip=10.130.114.205&ss_p=4444&Tag=CED_Fast&screenshot=1&outputformat=compact`

@vertigo17 where can i find the good folder ? 

![image](https://cloud.githubusercontent.com/assets/995694/22284974/022d4af8-e2ea-11e6-8fee-98a1094e4cbd.png)

**Comment by vitoo** [comment]
There is no data saved for this testcase execution in  `testcaseexecutionfile`

![](http://puu.sh/tzjC2/9832215f6d.png)

**Comment by vertigo17** [comment]
As far as I know, no. We don't have that issue.
I tested on my side and I get source and screenshot on that control:
![selection_170](https://cloud.githubusercontent.com/assets/5342048/22306487/bf36b81e-e33f-11e6-89e6-ab78d64e99c0.jpg)

Can you send the output of:
ReadTestCaseExecution?executionId=79851
Of course making sure that the testcase has not been modified recently. If it has been modify, please rerun the testcase and replace 79851 by the new execution id.

Do you have any exception in glassfish logs during the execution ?

**Comment by vitoo** [comment]
It's fixed in 1.1.10.1 so we can close

Thanks !
