### ISSUE TITLE
cerberus deleting actions

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1105]
Hi, 
it's not the first time i see this frustrating behaviour but it is hard to replicate or to know exactly what trigered it. I'll try to be accurate:
- duplicated the test http://192.168.134.17/Cerberus/TestCaseScript.jsp?test=Checkout%20Payment%20Payment%20Method&testcase=0332A using the old page

-duplicated to http://192.168.134.17/Cerberus/TestCase.jsp?Load=Load&Test=Checkout+Payment+Payment+Method&TestCase=0332M#propertyAnchor 

-uncheck the usestep in step13 and saved (using the old page because is much faster to work with)

-last step actions were deleted 'Check the label in the back is the same than the one in the website'

**Comment by bcivel** [comment]
Hi, I close this issue as this old page is not available and not maintained anymore.
Don't hesitate to open issue if you have trouble in the new page.
Thanks
Benoit
