### ISSUE TITLE
choose battery to run

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1109]
Hi, 
is it possible to add a dropdown to choose the battery to run? 
![image](https://cloud.githubusercontent.com/assets/1914659/21801425/785e362e-d719-11e6-80dd-cb99ed24c5e9.png)

Thanks,
Rui

**Comment by vertigo17** [comment]
Already available:
![2017-01-10 10_54_29-run test](https://cloud.githubusercontent.com/assets/5342048/21801735/3ab5de08-d723-11e6-92b7-04bf468df768.png)

Logic is that 
**battery** is group testcases and therefor is a criteria to filter a list of testcase (in the choose test section)
**campaing** is a list of testcases + environment + countries so it gets selected on top of the screen.

**Comment by ruirpr** [comment]
oups... thanks!
