### ISSUE TITLE
action drag

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1110]
Hi, sometimes it is not possible to drag the last added action to another position, not sure why
![image](https://cloud.githubusercontent.com/assets/1914659/21810674/a91f9232-d744-11e6-98a1-40e64a0d9e89.png)

**Comment by abourdon** [comment]
@ruirpr is this issue still present? Because I cannot reproduce from my side.

**Comment by ruirpr** [comment]
I'll assume it was something to do with the Firefox Developer Edition i was using. Can't reproduce it for a while now using the regular browser. I'll close this issue and reopen if it happens again. 
Thanks!
