### ISSUE TITLE
unable to launch selenium 3 with "trustAllSSLCertificates" option

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#1112]
In selenium 3, the option "-trustAllSSLCertificates" does not exist anymore.

We are not able to run test cases on our plateforme, due to some unauthenticated certificates. 

When selenium launch the browser, we obtain an error message, on which we have to click on "advanced" button to register an exception... 

Any idea for a bypassing solution?

Thanks for your help ;)

**Comment by bcivel** [comment]
Hi @ping0uin 
You're right, this option seems to be now deprecated by selenium. Now, this option need to be pushed starting new instance of driver in Cerberus.

I'm thinking about creating a flag "trustSSLCertificates" at the robot level, and follow this implementation in Cerberus
http://learn-automation.com/handle-untrusted-certificate-selenium/

I keep you informed

**Comment by ping0uin** [comment]
Hi @bcivel 

I just spend around 2 hours to find a bypassing solution... But I failed.

I tried other version of geckodriver with support of firefox-profile, previous releases of selenium server including the "trustSSLCertificates" option, try to implement a test which accept the security exceptions (but I didn't realise at the beginning that a validation in a "browser pop-up" was required...) etc.

Anyway, I did not find a working solution for now. I will continue to investigate later.
We keep in touch.

;)

**Comment by bcivel** [comment]
Hi @ping0uin, 
The normal behavior when the parameter is taken into account is that this "browser popup" doesn't appear anymore.
I looked for a solution updating the code with the change proposed before and updating the geckodriver to the last version but it still not working. 

I guess it's more a firefox issue (https://bugzilla.mozilla.org/show_bug.cgi?id=1103196).
I checked on chrome and it works fine

**Comment by ping0uin** [comment]
Hi,

ok for firefox. It's a shame, but for now, I just need to make my test cases working.
you said that it works fine with chrome. could you give me some details about your configuration? (versions of selenium, chromedriver...)

I would like to try it with chrome.

Thanks in advance.

**Comment by bcivel** [comment]
Hello,
You can add an invariant type CAPABILITY : acceptInsecureCerts
Then, in the Robot, you can add a RobotCapability : acceptInsecureCerts : true
Thanks
Benoit

**Comment by ping0uin** [comment]
ok, you had this capability in the sources of Cerberus?

For the robot configurtaion, I see it well, I just need to know how to add the acceptInsecureCerts in the list.

**Comment by bcivel** [comment]
No, the capabilities are not hardcoded in Cerberus. They are just forwarded to selenium/appium
So you can put any capabilities you want. You can find a list of capabilities here : 
https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities

So, if you need to add it, you can add an invariant (on invariant page, create Invariant type CAPABILITY with the value acceptSslCerts). Then it will be available in RobotCapability page.
Thanks
Benoit

**Comment by ping0uin** [comment]
finally, I updated my chromedriver version, and with selenium 3, and your advices, it works also for me on chrome.

Thanks a lot for your help. ;)

**Comment by bcivel** [comment]
Hi @ping0uin 
Since Firefox 52.0, it's now possible again to force to trust unsecure certificates.
Notice that with this firefox upgrade, you'll have to upgrade selenium to 3.3.1 version, and GeckoDriver to 0.15 version.

I added new capabilities `acceptInsecureCerts` you can set to your robot and set it to true.
Will be provided in the next release.
Enjoy :-)

**Comment by ping0uin** [comment]
Hi @bcivel ,

great. Thanks a lot for the informations ;)

What's up about the next release?

**Comment by bcivel** [comment]
Bim :-)
I'll launch it in a couple of minutes

**Comment by ping0uin** [comment]
yeah 👯
