### ISSUE TITLE
Page doesn't load completly

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1114]
Hi,

some pages are not loading all the elements and test ends with a CA.

![sem titulo](https://cloud.githubusercontent.com/assets/14328346/21983535/b254ac26-dbe9-11e6-8cf3-9f0c8cb751ae.png)

http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=41322200

http://cerberus.siege.red/Cerberus/TestCase.jsp?Load=Load&Test=Checkout+Summary&TestCase=0064M02_BK

We cannot reproduce it manually even on virtual machines.
Could this be related to firefox version or sellenium?
Can you please take a look and advise?

Thanks

**Comment by vertigo17** [comment]
@RobertoAbraul is that still a valid issue ?

**Comment by RobertoAbraul** [comment]
Hi @vertigo17 , 

this is not replicated today.

Can be closed.
