### ISSUE TITLE
Issue creating New "Application" from new cerberus

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#1115]
Cerberus Version : 1.1.9-979

Hi !
Just wanted to share something here. When having a brand new cerberus, you need to create a "DeployType" key for creating an Application.
As a user of cerberus for the testing / automation part of it, I've never used it.
![image](https://cloud.githubusercontent.com/assets/16115517/22059244/4d015390-dd6c-11e6-91d9-382fb1584a2b.png)

So I went straight into Cerberus DB to find deploytype Table and added a "fake" key to unlock the application creation (deploytype "01" / descriptions "Test")

It could be interesting to make error message more readable for new users !

Regards,
PF

**Comment by vertigo17** [comment]
@pfoucray no need to go on the database to insert the record.
You can use the Deploy Type entry inside menu application in order to create/modify deploy types.

**Comment by vertigo17** [comment]
![selection_169](https://cloud.githubusercontent.com/assets/5342048/22123660/c118e358-de8c-11e6-950d-5b4355cf5fb7.jpg)
