### ISSUE TITLE
Property details in new execution detail page

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1119]
Hello,
In the property tab of the new execution detail page, the property is detailed like this : 
![execution](https://cloud.githubusercontent.com/assets/18569182/22099173/833287c2-de2a-11e6-9fa5-baecaf5fbc61.PNG)
But the nature of the property (second colonm) is not one of the most important value. It would be better to replace the nature by the value calculated for example : 
![executiondetail](https://cloud.githubusercontent.com/assets/18569182/22099263/ee70aae6-de2a-11e6-9f95-30dea2e11649.PNG)
Thank you !

Cerberus Version : 1.1.10-SNAPSHOT-1044

**Comment by bcivel** [comment]
fixed
