### ISSUE TITLE
Properties from steps are not being used if overwritten

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1121]
Hi,
This is a critical regression issue.
If we defined in a step a property for several countries (for example FR, BE and IT) and if we need to overwrite the property for one country (FR only) in the test case then the step property is ignored and in the exceution it will give and error for the other countries (BE and IT) saying the property is not defined.
Will create a test in Cerberus for better understanding and to be used as a non-regression test.

**Comment by ffazendeiro** [comment]
Non-regression test created:
http://cerberus.siege.red/Cerberus/TestCaseScript.jsp?test=Cerberus&testcase=9412A
On the execution http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=41417890 property 2 should have being calaculated using the one defined in the step.

**Comment by ffazendeiro** [comment]
Hi again,
Updated non-regression test case to be more complete.
Now the failing property is the Property 3:
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=41419794 
Thanks.

**Comment by vertigo17** [comment]
Don't forget to change parameter to 'cerberus_property_countrylevelheritage' in order to change the default behaviour in order to consider the heratag per property+country level.
