### ISSUE TITLE
Steps block doesn't load correctly

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1122]
Hi,

steps block on execution detail doesn't load correctly.

This happens after click on other tabs (Properties, execution details, environment, robot). 

![steps](https://cloud.githubusercontent.com/assets/14328346/22101613/126e362e-de2c-11e6-9d9c-66cc272f10fc.png)

Can you please take a look?

Thanks

**Comment by ruirpr** [comment]
I'm facing the same issue
![image](https://cloud.githubusercontent.com/assets/1914659/22102160/5b5245c2-de2e-11e6-9dbb-fe4a47256b07.png)

**Comment by bcivel** [comment]
fixed.
I temporarly disabled the function that allow the menu to be always visible.
