### ISSUE TITLE
open failing action/step from execution result

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1123]
Hi, 
how to open a action/step case directly from the execution result? I can't find how and tha was one feature very used.
![image](https://cloud.githubusercontent.com/assets/1914659/22101913/497d2782-de2d-11e6-9696-6916259658ba.png)

Cerberus1.1.10-SNAPSHOT-1044

**Comment by abourdon** [comment]
A button will be added to the description on the current displayed step

Blocked by #1133

**Comment by abourdon** [comment]
Test case can now be edited from the current displayed step as shown in the screenshot bellow:

<img width="1277" alt="screen shot 2017-01-19 at 17 11 36" src="https://cloud.githubusercontent.com/assets/1511715/22114658/8f38adb8-de6a-11e6-8918-28ef315c751a.png">
