### ISSUE TITLE
See last execution page returns no results

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1124]
When a test fails if we click see last execution we are redirected to TestCaseExecution page but no data is displayed

**Comment by ruirpr** [comment]
Coming from test case script page: 
![image](https://cloud.githubusercontent.com/assets/1914659/22103875/b573ee06-de34-11e6-8959-6210f2ec3e69.png)

**Comment by ruirpr** [comment]
Even when filtering, the results are not correct:
![image](https://cloud.githubusercontent.com/assets/1914659/22103950/054207b0-de35-11e6-914b-7bf315583f08.png)

**Comment by bcivel** [comment]
Fixed in QA
