### ISSUE TITLE
ctrl+c does not work? 

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1125]
Hi, 
i'm having a doubt, ctrl+c does not work on text script fields? 

Cerberus1.1.10-SNAPSHOT-1044

**Comment by bcivel** [comment]
Hi @ruirpr 
Are you talking about ctrl+c to create automatically an action?

If yes, now, if you are on the action description and you click ENTER, it create new line.
If no, could you clarify the need?

Thanks
Benoit

**Comment by bcivel** [comment]
fixed
