### ISSUE TITLE
SOAP request/response no longer available on execution

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1129]
Hi,
When using a SOAP in the test case the request and response are no longer available on the execution for this new version (Cerberus1.1.10-SNAPSHOT-1044).
For example for this execution http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=41322545 the test fails but we cannot check why.
On the previous version we had direct access to the results:
![image](https://cloud.githubusercontent.com/assets/17747042/22103604/b7f2c1a8-de33-11e6-8101-70f798333731.png)
Is it possible to add it on this new version?

**Comment by vertigo17** [comment]
@ffazendeiro the example is coming from a past execution. Can you re-test on a brand new execution ?
NB : This is probably linked to the addition of the new index level that allow to loop on step.

**Comment by ffazendeiro** [comment]
Thanks for the feedback.
Re-tested it but the result is the same:
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=41460891

**Comment by bcivel** [comment]
fixed
