### ISSUE TITLE
inherited properties search and select

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1134]
Currently it's not possible to search (using browser search) or select and copy (at least in firefox) text in the InheritedProperties tab. Could you enable the text? (of course, not editable)

![image](https://cloud.githubusercontent.com/assets/1914659/22115373/9651696a-de64-11e6-9e86-77e96d080df8.png)

Thanks!

**Comment by bcivel** [comment]
fixed
