### ISSUE TITLE
Impossible to add controls to actions

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1135]
Hi,

when trying to add a control to action (green "+") button doesn't do any action and control is not added.

http://192.168.134.197/CerberusQA/TestCaseScript.jsp?test=Cerberus&testcase=9413A&step=1&tabactive=tabSteps

![controls](https://cloud.githubusercontent.com/assets/14328346/22145198/4146ca02-def8-11e6-98cd-83fcd1f687fc.png)

Cerberus1.1.10-SNAPSHOT-1047

Can you please take a look?

Thanks

**Comment by bcivel** [comment]
Fixed with my commit
