### ISSUE TITLE
Data with nature "NOTINUSE" not retrieved

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1136]
Hi,

test stops on properties defined with "NOTINUSE".
It seems that Cerberus could not retrieve data from data lib that are marked with "NOTINUSE" on properties.

http://192.168.134.197/CerberusQA/TestCaseScript.jsp?test=Checkout%20Basket%20Product%20Block&testcase=0014D

Cerberus1.1.10-SNAPSHOT-1047 

Example:
Property defined with "NOTINUSE":
![notinuse](https://cloud.githubusercontent.com/assets/14328346/22147036/c9a6c036-defe-11e6-9033-a5cfb4520669.png)

Test stays PE (property ACCOUNT not calculated):
![account1](https://cloud.githubusercontent.com/assets/14328346/22147143/30c53f68-deff-11e6-9c1b-9eaf9c8368b8.png)

Property defined with "STATIC":
![static](https://cloud.githubusercontent.com/assets/14328346/22147215/7f74705c-deff-11e6-848b-bf0aa608ffe8.png)

Test stays PE (property ACCOUNT calculated):
![account2](https://cloud.githubusercontent.com/assets/14328346/22147257/a80296b6-deff-11e6-95f4-84b40b79cd1c.png)

Can you please take a look?

Thanks

**Comment by vertigo17** [comment]
Can you confirm if we have the issue in PROD or is that just in QA ?

**Comment by RobertoAbraul** [comment]
Hi @vertigo17 ,

issue is only present in QA.

Thanks

**Comment by bcivel** [comment]
Hi @RobertoAbraul 
Seems to be fixed with your mySQL upgrade
http://192.168.134.197/CerberusQA/ExecutionDetail2.jsp?executionId=43202397
Thanks
Benoit
