### ISSUE TITLE
Test Case Execution page - search box

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1137]
Hi,

on Test Case Execution page the search box is out of place.

![search_box](https://cloud.githubusercontent.com/assets/14328346/22150518/454598c2-df11-11e6-9095-713f6d460d3f.png)

Can you please take a look?

Thanks

**Comment by bcivel** [comment]
Hi @RobertoAbraul 
Should be alreday fixed by another commit.
Thanks
Benoit
