### ISSUE TITLE
Description of action/control detail is now missing on the Execution detail page

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#1138]
Description of action/control detail is now missing on the Execution detail page

<img width="1051" alt="screen shot 2017-01-23 at 09 21 52" src="https://cloud.githubusercontent.com/assets/1511715/22196725/d1ce1fa0-e14e-11e6-9584-552ded497d0f.png">

**Comment by bcivel** [comment]
fixed
