### ISSUE TITLE
Quick access to the property creation page does not work anymore

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#1143]
When clicking on the quick access to the property creation page, then nothing appears.

<img width="284" alt="screen shot 2017-01-23 at 11 10 03" src="https://cloud.githubusercontent.com/assets/1511715/22199791/b4d4c7d8-e15c-11e6-80cf-62ee213199b8.png">

In the past, the property page was displayed with a new line filled by the property name to create

**Comment by abourdon** [comment]
Actually, when clicking on the link, then a line is added to the property table even if it is not displayed. But, more annoying, all existing property names are updated to the new one.

<img width="790" alt="screen shot 2017-01-23 at 14 42 59" src="https://cloud.githubusercontent.com/assets/1511715/22206159/682b722e-e17a-11e6-82d2-a0b56c4956a2.png">

We have to fix it quickly

**Comment by bcivel** [comment]
fixed
