### ISSUE TITLE
Test Case Execution - buttons does not perform any action

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1144]
Hi,

on page "Test Case Execution" buttons "first", "previous", "next" and "last" doesn't do anything.

Cerberus1.1.10-SNAPSHOT-1047

![test_buttons](https://cloud.githubusercontent.com/assets/14328346/22203032/d5773542-e162-11e6-9d29-c646e42c72d1.png)

![test_buttons2](https://cloud.githubusercontent.com/assets/14328346/22203046/eac8537c-e162-11e6-9ea7-7b6831760d48.png)

Can you please take a look?

Thanks

**Comment by bcivel** [comment]
fixed.
