### ISSUE TITLE
Save filters message

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1146]
Hello,
Could you please add a success message when user click on save filters in testcaselist page ?
![savefilter](https://cloud.githubusercontent.com/assets/18569182/22205594/d02b388a-e177-11e6-94a5-70e96fa8e9b6.PNG)

For the moment nothing indicates to the user if the save works.

Thank you !

Cerberus Version : 1.1.10-SNAPSHOT-1047

**Comment by bcivel** [comment]
Fixed
