### ISSUE TITLE
Run page dependant of the system

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1147]
Hello,
In run test page, when you try to find for example a battery of test cases. If you are in the wrong system, the list of test cases won't be displayed : 
![runsystem](https://cloud.githubusercontent.com/assets/18569182/22205754/843862a8-e178-11e6-9e1d-d883020e3ae4.PNG)
Could you please remove this rule ? It would be great if the list could be displayed whatever the system.
Thank you !

Cerberus Version : 1.1.10-SNAPSHOT-1047

**Comment by vertigo17** [comment]
Hardcoded system filter has been removed.
I added system combo filter in order keep the feature to filter testcase by system.
