### ISSUE TITLE
Execution time displayed with wrong value

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1148]
Hello,
When a testcase is running, the execution time is displayed with this number : 
![executiontime](https://cloud.githubusercontent.com/assets/18569182/22206878/36abd8e4-e17d-11e6-96a7-8d5e71856e9b.PNG)
Is it possible for you to hide this value until the real value is displayed ?
Thank you!

Cerberus Version : 1.1.10-SNAPSHOT-1047

**Comment by abourdon** [comment]
Duplicate of #1142
