### ISSUE TITLE
Last execution button doesn't work everytime

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1150]
Hello,
When I click on Last execution button, the page doesn't display the good list of test case, for example
This button : 
![lastexec](https://cloud.githubusercontent.com/assets/18569182/22207737/912a66ca-e180-11e6-895f-ff580b68e8ff.PNG)
display : 
![execresult](https://cloud.githubusercontent.com/assets/18569182/22207772/bd274e82-e180-11e6-9548-7ad95774fb87.PNG)
I think the button keeps the last filter I used.
Could you please have a look ?
Thank you!

Cerberus Version : 1.1.10-SNAPSHOT-1047

**Comment by bcivel** [comment]
Hi @R-Loic 
fixed solving another issue on the same page :-)
<img width="1525" alt="capture d ecran 2017-01-24 a 22 21 10" src="https://cloud.githubusercontent.com/assets/5376184/22267273/82344ca4-e283-11e6-9fb6-40ff59788364.png">
