### ISSUE TITLE
Timeout setting in run page

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1151]
Hello,
My test case keeps pending, so I modified timeout in run test page to have 10 sec timeout. (Timeout unit is not indicated in run page)
But even with this setting my test case keeps pending during like 20 min.
Could you please tell me if this is a normal behavior ?
Does timeout work for all actions ? 
my first action is a callsoap.
Thank you !

Cerberus Version : 1.1.10-SNAPSHOT-1047

**Comment by bcivel** [comment]
Unfortunatelly, timeout on run page is used for selenium action, mainly to tune the wait for element.

**Comment by R-Loic** [comment]
Hello @vertigo17 
As you told me, I set the parameter for timeout : 
![parameter](https://cloud.githubusercontent.com/assets/18569182/25955744/56f0f43a-366a-11e7-89cb-9342c7506a86.PNG)
But it didn't work : 
![timeout](https://cloud.githubusercontent.com/assets/18569182/25956876/39724e2e-366d-11e7-93ff-f92265be4368.PNG)
Could you please have a look ?

**Comment by vertigo17** [comment]
Let's see if with the last comit the timeout better works.
Reopen if it still does not timeout.
