### ISSUE TITLE
Should be useful to be able to keep soapData Library in cache

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#1152]
Hi,

In our tests environnements, we have a customer Factory, able to create and record in our database, exactly all the specific customers or users we need for a test. 

this creation is possible by two ways : 
  - UI
  - Soap API

We would like to use the soap API to create customer, in using the Data Library of Cerberus. But it would be very interesting for us to create a user Once, and keep it in a cache (implemented on the data library for instance) during a customizable period. By this way, we will not create a new user at each execution of a test case...

Is this possible?
Thanxx

------

List of actions:
- [x] Add a json column to testcaseexecutiondata in order to save the result (all rows on all subdata)
- [x] Add a method to convert rowData to json and json to rowData.
- [x] Add SYSTEM, COUNTRY, ENVIRONMENT and TestDataLib column into testcaseexecutiondata table.
- [x] Add FromCache column into testcaseexecutiondata table in order to flag the property that comes from cache and cannot be used for the cache.
- [x] feed those new columns with the correct data when calculate property is done.
- [x] Modify engine on TestDatLib in order to get the previous data.
- [x] Add CacheExpire column into testcasecountryproperties table.
- [x] Edit the Cache Expire on property definition (testcase page).

**Comment by vertigo17** [comment]
Yes, what I propose is to add a cacheExpire (in second) at testdatalib level.
If 0, no cache is checked (same as today), 
if >0, we will look inside database for the same DATALIB same COUNTRY and same ENVIRONMENT.
  - if no entries are detected, we retreive the data, 
  - if we find an entry, we pick the latest n rows retreived from that entry.

**Comment by vertigo17** [comment]
@R-Loic also mentioned this need in order to reuse a token calculation during a couple of days instead of at every execution.

**Comment by vertigo17** [comment]
In fact the cache feature will be implemented at property level.
That will allow that any property can be cache (even if not testdatalib).
All the backend is ready and test can start by manually changing the CacheExpire column in testcasecountryproperties table on associated testcase / Properties.
@R-Loic , can you start testing it linked with the token need and confirm that it works OK.
Once confirmed we will implement the GUI impact adding CacheExpire data on testcase screen.

**Comment by R-Loic** [comment]
hi @vertigo17,
Just tried this feature and it works on my side.
What is the unit used in the table ? I set the cacheExpire to 10000 to test, but I don't if it's second ms hour.
Thank you !

**Comment by vertigo17** [comment]
It is in Second.
@ryltar , I guess we can start to add it in the GUI ?

**Comment by vertigo17** [comment]
Gui has been changed and issue is now closed.
@ping0uin , I would be happy to get your feedback on that feature.
