### ISSUE TITLE
Select Box in the "creation robot frame" is unavailable

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#1153]
there is some difference when you create a custom robot in the "run" page, contrary to the "creation robot" page.

<img width="588" alt="creationrobotpage" src="https://cloud.githubusercontent.com/assets/14962879/22243129/4ab857aa-e226-11e6-89b0-5964fb86d211.png">

In the Creation robot page, some field do not propose a list of item like for the browser for instance... This is possibly a source of several mistakes.

**Comment by bcivel** [comment]
Hi @ping0uin ,
You have now a select box on browser and platform, as on the run page, to avoid possibility to use bad values.
Thanks for the contribution
Benoit
