### ISSUE TITLE
"fullScreen" execution option does not working with chromeDriver

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#1154]
The title talks for itself... when we run tests cases on chrome (using chrome driver & selenium standalone server) full screen option does not work.
I think in chrome driver, the full screen option return a default maximum size... 
Is it possible to fix it in cerberus? By adding a default parameter to force the full screen size for instance?

Thanks for your help ;)

**Comment by bcivel** [comment]
Hi @ping0uin 
Should be fixed with the commit	4897e39
Will be available in the next release
