### ISSUE TITLE
Filter by control status on test Case Execution page

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1155]
Hi,

on Test Case Execution page is not possible filter by control status "KO, OK, FA..."

Cerberus1.1.11-SNAPSHOT-1048

![filters](https://cloud.githubusercontent.com/assets/14328346/22243458/5350bb8e-e21f-11e6-93db-9e75e05f78e4.png)

Can you please take a look?

Thanks

**Comment by bcivel** [comment]
Hi @RobertoAbraul 
Fixed with my last commit.
