### ISSUE TITLE
Could be useful to drag & drop an action from a step to another

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#1157]
During our implementation, we met some difficulties about the right granularity level to have in our tests implementation.

What is a step... Which actions or control we have to put into to describe exactly what we need to do in a step... and often, we had to split a step. For now, the only way to split a test is to create an other one and recreate all the actions ans controls we wanted to put into. 

That's why, it could be great to be able to copy directly or move an action from a step to another one. Of course, I understand that a step which is use as library has to be locked...

Is it possible to implement it? did you already thought about this possibility?

**Comment by bcivel** [comment]
Hi @ping0uin 
Yes, useful topic. 
We discussed it implementing the new page and forgot it as it was tricky to implement.
No promised for tomorrow, but I'll have a closer look

**Comment by bcivel** [comment]
Hi @ping0uin 
Finally I lied. I did it before tomorrow :-)
Will be in the next release
Benoit

**Comment by ping0uin** [comment]
great, thanks ;)
