### ISSUE TITLE
SOAP request/response not correctly diplayed

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1158]
Hi,
SOAP request/response are now present on the step execution:
![image](https://cloud.githubusercontent.com/assets/17747042/22285831/1efcaf3e-e2e5-11e6-982f-84ca6e457093.png)
But if we open them we only see that it is a xml file:
![image](https://cloud.githubusercontent.com/assets/17747042/22286179/34e34bfe-e2e6-11e6-8c00-eee20590e92d.png)
No problem for me. We can check the full file in a new windows (and for me it would be better to see the files directly it in a new window rather then in the popup because request/response have usually many lines).
But the issue is: if we choose to see the full file (for the request and for the response) both are redirected to the same file (the request file). We cannot see the reponse file.

Version:
Cerberus1.1.11-SNAPSHOT-1048

**Comment by vertigo17** [comment]
Can you feed the execution ID and associated file content generated ?

**Comment by ffazendeiro** [comment]
For example:
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=41650520 (First Step)

**Comment by R-Loic** [comment]
Hello,
You can click on full file button to get the xml message. But the two buttons display the resquest. Response cannot be reached by this way.

**Comment by vertigo17** [comment]
issue is solved but I am not happy the way I fixed the javascript part.
