### ISSUE TITLE
Test executions does not automatically starts

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1159]
Hi,
When executing several test cases at the same time the execution does not start and they all stays with status NE:
![image](https://cloud.githubusercontent.com/assets/17747042/22287467/f8e2901a-e2ea-11e6-997b-47b4895f5faf.png)
If we click on one the execution it will open the old run-test page and the test case automatically starts to be executed.
For testing purposes, a test case was executed with the tag Execution Test:
http://cerberus.siege.red/Cerberus/ReportingExecutionByTag.jsp?Tag=Execution_Test

**Comment by abourdon** [comment]
Hi @ffazendeiro,

Probably due to an internal network issue. Could you please re-test and tell us if it is working fine?

Regards,
Aurélien

**Comment by ffazendeiro** [comment]
Hi @abourdon,
You're correct. I've retry to launch the same test with the same parameters (just changing the tag) and all looks ok now:
http://cerberus.siege.red/Cerberus/ReportingExecutionByTag.jsp?Tag=Execution_Test2
Should have been a temporary network issue.
Thanks.
