### ISSUE TITLE
TestCaseExecution Page : filters should be server side

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1161]
Hi,

We've found some issues on new TestCaseExecution page:
1.- Testcase filter only displays the options visible on the last 10 executions - for instance if we want to look for all the executions done of a specific test we can only select it if it was executed recently and appears listed on the table.

2.- Refresh Button for the applied filters would be useful.

3.- If we save our preferences with customized filter and then try to load it settings are not saved

Can you check please?
Thanks
Best Regards

**Comment by bcivel** [comment]
Hi @j0hnsa 
Point 2 and 3 should be fixed.
Point 1 is a bit harder to solve. I rename your issue to "TestCaseExecution : filter should be server side"
Thanks
Benoit

**Comment by bcivel** [comment]
fixed
