### ISSUE TITLE
Execution by tag - Filter by bug ID

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1162]
Hi, 

filter by bug ID on reporting by tag is "undefined".

Cerberus1.1.11-SNAPSHOT-1048

![image](https://cloud.githubusercontent.com/assets/14328346/22290436/a6a1d10e-e2f8-11e6-9296-c6c3fa00f1ae.png)

Can you please take a look?

Thanks

**Comment by bcivel** [comment]
Hi @RobertoAbraul 
Fixed with my last commit
Thanks
Benoit
