### ISSUE TITLE
Open in a new tab Toolbar icons on ExecutionDetail2 Page and TestCaseScript Page

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1164]
Hi,

Is it possible to make the buttons in the top toolbar (see attachment) of ExecutionDetail2 and TestCaseScript pages openable in a new tab?
![toolbarbuttons2](https://cloud.githubusercontent.com/assets/16339891/22294549/93df29d2-e30b-11e6-9924-e275f3102f7b.png)
![toolbarbuttons1](https://cloud.githubusercontent.com/assets/16339891/22294550/93e0bf40-e30b-11e6-972e-21c9d7d46df2.png)

Thanks,
Best Regards

**Comment by j0hnsa** [comment]
Hello,

Now its possible in some buttons to open in a new tab but now on ExecutionDetail2 if I click See last executions 22 tabs are being opened:

http://192.168.134.17/CerberusRegression/ExecutionDetail2.jsp?executionId=41745073

Can you check?
Thanks

**Comment by bcivel** [comment]
Hi @j0hnsa 
To standardize the behavior on all buttons, I propose to : 
- Left click redirect in the current page
- Middle click open the target in a new tab
- Right click open a menu that let you choose want you want

<img width="421" alt="capture d ecran 2017-01-27 a 16 02 01" src="https://cloud.githubusercontent.com/assets/5376184/22375364/051b08b0-e4aa-11e6-98cd-33bdb7b418e3.png">

**Comment by j0hnsa** [comment]
Hi @bcivel ,

At least for me your proposition seems very logic, thanks!

**Comment by bcivel** [comment]
Fixed as described.
Thanks
Benoit
