### ISSUE TITLE
verifyTextInElement not supported for type IPA

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1165]
Hi,

When I try to use the control VerifyTextInElement an error message is displayed:

Not executed because Control 'verifyTextInElement' is not supported for application type 'IPA'.
(http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=41697141)
Can this be implemented also for iOS?

Thanks
Best Regards

**Comment by bcivel** [comment]
Fixed
