### ISSUE TITLE
IfPropertyExist without result

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1166]
Hi,

when we try to use condition "ifPropertyExist" we get a warning without any actions or description.
Example: 
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=41697533

![image](https://cloud.githubusercontent.com/assets/14328346/22327809/f78fb212-e3b0-11e6-8c86-5c4cf6bd2052.png)

Property is defined in the test:
![image](https://cloud.githubusercontent.com/assets/14328346/22327827/0a653b0a-e3b1-11e6-8e42-ba3e382f2627.png)

But when running the test for PT (or another country) we get a "warning" but without any actions or description in it so we really don't know what's happened.

![image](https://cloud.githubusercontent.com/assets/14328346/22327868/53d52070-e3b1-11e6-915f-121a1eb84600.png)

The property is also defined in the step library.
![image](https://cloud.githubusercontent.com/assets/14328346/22327950/b38b6b5a-e3b1-11e6-9c4e-5520ee899f4e.png)

Cerberus1.1.11-SNAPSHOT-1050

Are we doing something wrong?

Can you please take a look and advise?

Thanks

**Comment by ffazendeiro** [comment]
Hi,
Actually the condition "ifPropertyExist" is working as expected. The problem in the previous example was the % character. It was removed and the test case works fine.

But there is some small issues regarding the step use:

1. If the property in the step condition is not defined, in the test case execution it does not execute it but the message is not very clear that it was skipped:
![image](https://cloud.githubusercontent.com/assets/17747042/22329030/49cac840-e3b7-11e6-9f57-ebf995848c14.png)

2. When adding the step to another test case the step is imported with no previous definition. I understand that it would be possible to change the added step conditions (can be very useful) but  it would be great if it was pre-filled as in the original:
Defined step:
![image](https://cloud.githubusercontent.com/assets/17747042/22329134/bd4ac662-e3b7-11e6-8466-1db08b85d97a.png)
When added to an test case:
![image](https://cloud.githubusercontent.com/assets/17747042/22329124/b3e31c3c-e3b7-11e6-9f9a-fff51d9e9f05.png)

Would it be possible to fix those two issues?
Thanks.

**Comment by vertigo17** [comment]
Point 1. will be fixed with #1007.
For point 2. can you confirm that this is only a display issue and that loop, and condition is correctly taken from the linked step when executed ?

**Comment by ffazendeiro** [comment]
For point 2. unfortunately it doesn't seem to be only a display issue.
We set the property only for one country (in the used step) and it seems that the step it is always executed (note that the condition property is only defined in the step and not in the case) regardless of the country we execute the test case.
Thanks.

**Comment by ruirpr** [comment]
Hi, 
i confirm is not only a display issue. Imported the following step:
![image](https://cloud.githubusercontent.com/assets/1914659/22391869/cdd22126-e4eb-11e6-8276-ccddfd821740.png)

and it displays without values:
![image](https://cloud.githubusercontent.com/assets/1914659/22391832/8bf9f562-e4eb-11e6-899d-f01035789f34.png)

and when running the testcase, the step is executed only once:
![image](https://cloud.githubusercontent.com/assets/1914659/22391899/0608138e-e4ec-11e6-94b2-91721934616b.png)
