### ISSUE TITLE
adding and saving properties problem with saving - Cerberus1.1.11-SNAPSHOT-1050

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1167]
added EXPECTED_PAGE_TITLE property defined for all countries;
added EXPECTED_PAGE_TITLE defined for UK and removed UK from previous entry;
added EXPECTED_PAGE_TITLE defined for RU and removed RU from previous entry;
saved;
cerberus saved only for RU;

![image](https://cloud.githubusercontent.com/assets/1914659/22330302/83df90c8-e3bd-11e6-9a59-8cc229665339.png)

**Comment by ruirpr** [comment]
added a property 'test' defined for all countries;
added a property 'test' defined for BE;
added a property 'test' defined for UK;
removed BE and UK in the previous entry;
saved;
cerberus saved only the first property:
![image](https://cloud.githubusercontent.com/assets/1914659/22330619/155ff64a-e3bf-11e6-8052-99a5df8b02f5.png)

**Comment by RobertoAbraul** [comment]
Hi,

I had a similar behavior.

I added a property "test" with different values for different countries.
![image](https://cloud.githubusercontent.com/assets/14328346/22330853/381ee726-e3c0-11e6-932f-cdd871c382f4.png)

After save I have only one checked for all countries.
![image](https://cloud.githubusercontent.com/assets/14328346/22330873/47bf9d9c-e3c0-11e6-82d1-8fef1f263935.png)

**Comment by bcivel** [comment]
Fixed
