### ISSUE TITLE
can't save test case after cerberus message - Cerberus1.1.11-SNAPSHOT-1050

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1168]
added a property 'test' defined for all countries; 
added a property 'test' defined for BE and removed BE in the previous entry;
added a property 'test' defined for UK and removed UK in the previous entry;
checked and uncheck several countries but finalized with previous countries options;
saved;
cerberus shows a message saying that at least one property is not defined for one country;
click on NO;
can't save anymore and properties are all defined for at least one county (or im going blind)

![image](https://cloud.githubusercontent.com/assets/1914659/22330457/3e7f63c2-e3be-11e6-8f17-10225acc4a29.png)

**Comment by ruirpr** [comment]
![image](https://cloud.githubusercontent.com/assets/1914659/22330733/a0f94dbe-e3bf-11e6-838a-cf5a26018fab.png)

**Comment by lucashimpens** [comment]
Linked to #1268.
