### ISSUE TITLE
blank step in loop execution

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1170]
The loop execution is correct but there's a blank step in execution result:

![image](https://cloud.githubusercontent.com/assets/1914659/22343224/30420b30-e3ef-11e6-8270-12d090fb018e.png)

http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=41716562

**Comment by vertigo17** [comment]
This is the normal behaviour so far as this step correspond to the first step when the condition is not meet. It is supposed to report the reason why the loop was interupted.
When ticket #1007 will be finished, it will report the message that will explain it.
I close the issue and we could reopen it when all step information will be displayed.
