### ISSUE TITLE
Test case execution hangs and are not closed

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1172]
Hi,
We notice and increase number of test cases execution that hangs (stays with status PE) and does not finish after the defined timeout. This is starting to have a huge impact because the Hub that distribute the tests fro the VM's quickly gets overwhelm with the growing number executions because the VM's are not closing the executions.

For example the execution http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=41750678
had to be canceled in the VM and until then had a execution time for the hanging control of 2060283ms (!!):
![image](https://cloud.githubusercontent.com/assets/17747042/22381746/bb20a9ac-e4ba-11e6-941f-e95ed2b62800.png)

In Cerberus the defined timeout is very inferior:
![image](https://cloud.githubusercontent.com/assets/17747042/22381796/e93ba7b0-e4ba-11e6-93ff-3f7c5f9fdeed.png)

Nonetheless we cannot say for sure in which action/control it hangs (this issue is intermittent and for different Controls/actions) but it is more frequent is the control "verifyElementNotPresent".

We notice also that for some reason if we close the execution on the browser VM because it is hanging the test is restarted automatically. It also be happening automatically because in the report by tag some test are PE again after we have re-run them.

Thanks in advance.

**Comment by abourdon** [comment]
Thanks to the new execution engine (#914), pending executions are now killed after a given timeout.

From now, only multiple executions submitted from the GUI are handled by this new execution engine. Thus, single execution or multiple executions submitted from Cerberus' API services are not taking into account.

Maybe for more coherence we could generalized the use of this new execution engine for any submitted executions? @bcivel, @vertigo17

Regards,
Aurélien

**Comment by gmoita** [comment]
Hi.
Unfortunately it seems that the way it is working can easily put a lot of stress on the selenium hub.
I've tested this yesterday with a hub with 4 nodes * 3 firefox instances with 200 pending executions on the queue and I had to relaunch the queue (the remaining tests) 5 times.
I understand the way of working on the queue per country + environment + application, with the number of entries specified on it, but that means that we can only dimension the queue on one single scenario... otherwise it is failling a lot more than expected.

**Comment by abourdon** [comment]
Hi Guilherme,

When you said you had to relaunch the queue, you mean the selenium hub?

As this discussion is now more related to the new execution engine, could you please continue by commenting on #914 issue?

Thanks,
Aurélien

**Comment by mbessa** [comment]
This is also related with #1202 .

**Comment by bcivel** [comment]
Hi @ffazendeiro 
this is fixed with that commit 581bd12
Don't hesitate to notify us if you find another PE final status
Thanks
Benoit
