### ISSUE TITLE
Error TestCase Creation / "Unkwown Column "UsrCreated" into "field list"

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#1174]
Cerberus Version : 1.1.11-SNAPSHOT-1050

Hi,
Just installed Cerberus on Windows 10.
Tried to create my 1st TestCase, but I can't seem to find the source of that Exception.

![tc creation exception](https://cloud.githubusercontent.com/assets/16115517/22472958/7b2a1520-e7d7-11e6-8f4b-c0083b33697c.png)

I even tried to fill as many fields as possible (in case some are mandatory), but nothing will do.

I know that TC Creation from scratch has already had some bugs. Since I'm working on las Snapshot version, this might be the cause?
Should I come back to 1.1.10 which is more stable ?

Regards,
PF

**Comment by bcivel** [comment]
Hi @pfoucray, 
We could not reproduce this issue in the current dev version.
What is your mySQL server version?
Didi you get any error on database init?

Thanks
Benoit

**Comment by pfoucray** [comment]
I use
- mysql-5.7.17-winx64
- GlassFish Server Open Source Edition 4.1
- NetBeans IDE 8.2
- mysql-connector-java-5.1.40-bin.jar
- Cerberus 1.1.11-SNAPSHOT-1050

Also, yes I got quite a few errors at DB init. I assumed it wasn't "critical" since they "disappeared" after I applied the last few manualy. Can I find those errors in a log somewhere ?

Thank you !
Paul

**Comment by bcivel** [comment]
OK, mySQL version supported for Cerberus is 5.6.xx
Try to uninstall MySQL 5.7 and install MySQL 5.6 instead
Then run the installation again
Thanks
Benoit

**Comment by pfoucray** [comment]
Will do that and let you know.
Thank you !
Paul

**Comment by pfoucray** [comment]
Perfect ! it worked like a charm !! no erros, TC created with success.
Let's play !! :D
