### ISSUE TITLE
empty added step

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1175]
Hi, 
i've been experiencing a blank step when adding from library. Sometimes reloading the page and adding the step again solves the problem. Sometimes it takes a lot of tries.

![image](https://cloud.githubusercontent.com/assets/1914659/22503710/e1117336-e86a-11e6-9e21-693349e50a34.png)

**Comment by ruirpr** [comment]
Note: i searched for 'omni' in the add step popup and the selected one of the results.

**Comment by bcivel** [comment]
Yes, it was a bit tricky to reproduce. But I get it today using TestCase Page :-)
Solved with my last commit
