### ISSUE TITLE
TestCase Execution / Old page still appears

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#1176]
Hi,

When you have non-executed test cases (NE) into an **execution report by tag page**, if you click on the "NE" button into TestCase execution list, you'll land on **the old TestCase Execution page** for a short while, just before it launches the test automaticaly.

![tc toward old page](https://cloud.githubusercontent.com/assets/16115517/22509284/a8ec30a4-e88d-11e6-85ec-f647daa015a5.png)

I think this old page shouldn't show at all, even for a fraction of a second !

Regards,
PF

**Comment by vertigo17** [comment]
When clicking to NE executions, it now redirect to execution queue list screen (this is considering that the reason why execution is NE is that it is queued).
Once manual execution will be ready with issue #739, a new status QU will replace NE for queued execution while NE will be dedicated for manual executions.
