### ISSUE TITLE
Execution+Tag+auto+generated

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#1177]
Hi,

When the execution tag is autogenerated by cerberus
- leave blank and execute
- if you have an error at the execution and click retry/go back (I'm not too sure how it happened precisly)
Cerberus will replace any "space" by a "+" sign.
Encoding and decoding HTML ?

![space and plus](https://cloud.githubusercontent.com/assets/16115517/22509419/4c0fd588-e88e-11e6-90be-17e171060784.png)

Thx for all the work,
Regards,
PF

**Comment by pfoucray** [comment]
Clicking on rerun the test and run the same test again (from tc script and tc execution page will show difference in the tag (the one is good for spaces, the other show + sign)

**Comment by vertigo17** [comment]
Can no longer reproduce the issue.
