### ISSUE TITLE
mandatory field system

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1179]
Hello,
when creating a new application, the system is not mandatory : 
![mandatoryfield](https://cloud.githubusercontent.com/assets/18569182/22509668/599de0a4-e88f-11e6-89d2-ad27e99315d4.PNG)
The field should be mandatory, user should not save without indicate a system.
Could you please add this condition ?
Thank you !

Cerberus Version : 1.1.11-SNAPSHOT-1050

**Comment by bcivel** [comment]
Strange, I could not reproduce.
Nevertheless, I add control on service layer to protect in case it happen again.
