### ISSUE TITLE
is it possible to plug a LDAP to user's administration

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#1180]
we would like to plug Cerberus to our LDAP, is that possible?

Thanks.
ping0uin

**Comment by bcivel** [comment]
Hi @ping0uin,
Yes it should :-) 
We used implementation of jdbcRealm, but you can for sure configure Glassfish to use ldapRealm instead. It's not excluded some things need to be adapted (for example for user creation/deletion...).

I'll have a look. But don't hesitate to give feedback if you have a try on your side :-)

Note that group in Cerberus are TestRO, Test, TestAdmin, RunTest, TestDataManager, IntegratorRO, Integrator, IntegratorNewChain, IntegratorDeploy, Administrator

**Comment by ping0uin** [comment]
Ok great, we are installing a new platform, and I will try this quite soon.
I will let a topic about that ;)

Do you have a more precisely matrix for describes all the rights according to the role?

Thx.

**Comment by ping0uin** [comment]
Hi @bcivel,

do you have some advice to implement it.
I change the glassfish configuration and add in the web.xml the ldap-realm to use, but now... I have some questions about how to interract with the ldap and cerberus in order to manage users/roles.

Should I use a specific application user as admin and give the rights with this account?
Should we keep the all LDAP authentication and just give the role if the check authentication works?
What do I have to change in the code in order to do it properly and share it?

**Comment by bcivel** [comment]
Hi @ping0uin,
When you say change the glassfish configuration, you mean you created a ldapRealm like that?
Am I right?

<img width="773" alt="capture d ecran 2017-02-08 a 22 56 31" src="https://cloud.githubusercontent.com/assets/5376184/22759677/99b8ea5c-ee53-11e6-9646-fbeaed059b05.png">

I'm having a look and will provide a feedback tomorrow

**Comment by vertigo17** [comment]
Target is to integrate https://www.keycloak.org/

**Comment by vertigo17** [comment]
I close the issue as Keycloack integration is closed since last comit.
Will be in next 3.12 release.
