### ISSUE TITLE
Redesign Edit Test Case Button

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#1183]
Cerberus Version : 1.1.11-SNAPSHOT-1050

Minor issue here, but may be perturbating new users : 
On TestCaseScript page, this button is more a "Edit Details" or "Parameter" or I don't realy know...
On ExecutionDetail2 page, it clearly is what it is !!
See Screenshot : 

![buttons](https://cloud.githubusercontent.com/assets/16115517/22555444/036a0494-e964-11e6-87aa-e13c72a42f4b.png)

Best Regards,
PF

**Comment by bcivel** [comment]
fixed
