### ISSUE TITLE
Cannot filter in Execution reporting

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1186]
Hello,
I have an error message, when I try to filter as you can see in the following screenshot : 
![filterexecution](https://cloud.githubusercontent.com/assets/18569182/22639071/72cc20e8-ec4c-11e6-8489-ac1cd44a6a93.PNG)
Could you please have a look ?
Thank you

Cerberus Version : 1.1.11-SNAPSHOT-1050

**Comment by bcivel** [comment]
fixed
