### ISSUE TITLE
Limited fields in execution detail page

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1187]
Hello,
It seems the fields in execution details page are limited to about 2000 characters. I frequentlty manipulate message longer than this limit, so it's not easy to debug.
Could you please remove the limit size ?
Thank you !

![executiondetail](https://cloud.githubusercontent.com/assets/18569182/22639220/302d452c-ec4d-11e6-9768-33515f252ac2.PNG)

Cerberus Version : 1.1.11-SNAPSHOT-1050

**Comment by bcivel** [comment]
fixed
