### ISSUE TITLE
fields not correctly displayed // Execution report by tag

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1190]
Hello, 
When I add a filter in execution page (by Tag), some fields are not displayed correctly : 

![filterexecution](https://cloud.githubusercontent.com/assets/18569182/22683586/df43240c-ed18-11e6-95b9-708dd9b436bf.PNG)
Could you please have a look ?

Cerberus Version : 1.1.11-SNAPSHOT-1066

**Comment by bcivel** [comment]
Hi @R-Loic ,

Could you confirm it still happen on your side?

**Comment by bcivel** [comment]
Fixed
