### ISSUE TITLE
Error with filter in Service library page

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1192]
Hello,
When we use filter in Service library page, it doesn't work and an error message is displayed : 
![errorservice](https://cloud.githubusercontent.com/assets/18569182/22693585/241f0d0e-ed44-11e6-99ed-486d9c9cc88a.PNG)
Thank you !

Cerberus Version : 1.1.11-SNAPSHOT-1066

**Comment by bcivel** [comment]
fixed
