### ISSUE TITLE
How to get Environment Variables on Apps

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1193]
Hello,

I wanted to retrieve environment variables on Apps but neither the getFromGroovy works nor the getFromJS is supported at the moment. 

Can you check and advise how to do it?
TC Execution:
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=41981690

Thanks
Best Regards

**Comment by bcivel** [comment]
Hi @j0hnsa 
getFromJS works for hybrid application. Problem on your execution is that you're executing script that return no result.
But there is no way for the moment to retrieve code variables as you need.
