### ISSUE TITLE
PE status even if execution is done

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1194]
Hello,
In this execution, even if the test is finished, a step is still PE : 
http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=42265728
![pestep](https://cloud.githubusercontent.com/assets/18569182/22780238/50d705d8-eebe-11e6-8059-cf7c4c4a0f2b.PNG)
Thank you

Cerberus Version : 1.1.11-SNAPSHOT-1066

**Comment by vertigo17** [comment]
I beleive that if you refresh the page, it works fine (Step is correctly refreshed) ?

**Comment by R-Loic** [comment]
Hello,
No, it doesn't. If you open the URL, the step is still PE.

**Comment by vertigo17** [comment]
@R-Loic can you retest that case and confirm it is solved.
It should with the last fix done on return code management.
All recent execution are NA due to data.
