### ISSUE TITLE
New feature: import script

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1195]
Hello,
It would be great if we could import the script of an existing test case to a new one.
The duplicate does not answer to this need if the test case destination is already created with functinnal information.
Example : 
For my project, functionnal user create test cases, fill description and label. Then a developer implement the test cases. Ususally, the scripts are almost the same except 2 properties. So if we could import the script from a test case already implemented, the developer will go faster to implement.
Thank you!

Cerberus Version : 1.1.11-SNAPSHOT-1066

**Comment by vertigo17** [comment]
Can you confirm that #260 support the same need ?

**Comment by R-Loic** [comment]
This feature is not anymore needed, adding multiple steps is now implemnted.
