### ISSUE TITLE
closed steps tabs by default

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1198]
Would it be possible to show only the last vertical accordion tab opened and the otheres closed? 
For example, the step not executed because there's no property defined for that country is currently showed open. 
![image](https://cloud.githubusercontent.com/assets/1914659/22883081/4b7cd48e-f1e6-11e6-9d16-eb3a27657fac.png)

**Comment by ruirpr** [comment]
This way would be faster to get a global view: 

![image](https://cloud.githubusercontent.com/assets/1914659/22883152/a8e7d93e-f1e6-11e6-984f-7c4396ed0e10.png)

**Comment by vertigo17** [comment]
Agreed as detail is too big and confuse the screen.
