### ISSUE TITLE
Notifications do not automatically disappear

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#1200]
Notifications remain displayed. Maybe it is a bug because we wait for it to disappear ;-)

**Comment by vertigo17** [comment]
Yes that should disappear after a certain nb of second (that can easilly changed by config).
nb of second should be configurable by status.
Quick of OK --> 2 sec
Longuer for Error --> 5 sec
Even longuer for Warning. --> 10 sec
