### ISSUE TITLE
filter by system does not work?

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1201]
Hi, test dropdown shows everything even if not from selected system. In this example, vccrm tests does not belong to theseus:
![image](https://cloud.githubusercontent.com/assets/1914659/23015645/8a5433a4-f42b-11e6-85f7-698de8f2ff6e.png)

**Comment by vertigo17** [comment]
This is the expected behaviour in order to get the full visibility on the testcases.
