### ISSUE TITLE
Switch to window - new behavior?

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1203]
Hi,
since last deploy of cerberus switch to window have a new behavior.

We have the following situation:
1. Open a article - OK;
2. Click on vendor to open vendor details page - OK;
3. Switch window to new window opened - OK;
4. Close vendor details page - OK;
5. Switch window to go back to product page - NOK, test stays PE forever.

![image](https://cloud.githubusercontent.com/assets/14328346/23060739/f38059f4-f4f6-11e6-8b5e-8c66a6fca0fb.png)

Step4 (Close the new window):
![image](https://cloud.githubusercontent.com/assets/14328346/23060423/8731e6b0-f4f5-11e6-9ad1-d705f0bdaf97.png)

If we don't do the step 4 (close new opened window) and let the two windows opened, it does the switch window correctly (step 5).
![image](https://cloud.githubusercontent.com/assets/14328346/23060449/a2037850-f4f5-11e6-8e26-716874256fde.png)

![image](https://cloud.githubusercontent.com/assets/14328346/23060442/9aad10d4-f4f5-11e6-9b9c-0b4565a722d3.png)

Cerberus1.1.11-SNAPSHOT-1084

Can you please advise?

Thanks

**Comment by bcivel** [comment]
Hello @RobertoAbraul 
I confirm this should be solved in Cerberus. Until it's solved, you can put condition on step 4 to never.
I'll keep you informed
