### ISSUE TITLE
Can't execute several tests simultaneously

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#1205]
Hi,

when I choose to execute several tests in the same time, I arrived well on the report page, but no test is starting automatically.
I keep this screen : 
<img width="1425" alt="capture d ecran 2017-02-20 a 17 11 10" src="https://cloud.githubusercontent.com/assets/14962879/23133085/2174e5d2-f790-11e6-8564-c306612aceca.png">

I have to clic manually on a test case execution, and then, the old-run page appear, the test is executed, and finally I am automatically redirect to the report page of this test case only.

If I return on the "global report", I see this:
<img width="1421" alt="capture d ecran 2017-02-20 a 17 11 59" src="https://cloud.githubusercontent.com/assets/14962879/23133217/a6c02da0-f790-11e6-81df-43542e332ee1.png">

But any test is running automatically.

Is there a Bug? 

I saw that the problem was already met by other users, but was due to a network problem...

any ideas?
Thanks.

**Comment by bcivel** [comment]
Hi @ping0uin,
Could you please provide the error message you have on the queue table? It seems that the execution does not start due to an issue ( probably selenium server unreachable or environment unactive). So you see them in NE status until you click to run it manually. 
Thanks
Benoit

**Comment by ping0uin** [comment]
Hi @bcivel ,

you mean, the datas in the testcaseexecutionqueue table?

**Comment by ping0uin** [comment]
if you mean the queue table in cerberus application (not in BDD), I have this : 
<img width="1388" alt="capture d ecran 2017-02-20 a 18 37 30" src="https://cloud.githubusercontent.com/assets/14962879/23136177/c2939c78-f79b-11e6-99fb-de583e198e03.png">

**Comment by bcivel** [comment]
Unfortunatelly, on this version, error messages are not displayed in the interface. Yes, I mean a couple of values from testcaseexecutionqueue table.
Thanks for the help.
Benoit

**Comment by ping0uin** [comment]
yep, the extract of the BDD gave me exactly the same result... shame.

**Comment by bcivel** [comment]
Hi @ping0uin ,
Another idea, did you set the parameter `cerberus_url`, with your correct cerberus host?
When you use the multiple execution, it use this parameter to run the test.
Thanks

**Comment by ping0uin** [comment]
hi @bcivel,

sorry to answering late, I wasn't at work these past few days.
I just test to change the Cerberus_url parameter, and it works ;)

Indeed, in using docker implementation, the port is not the same, and actually, the value of the parameter was a bit different to the "normal" cerberus url.

Do you know if there is other parameters that could be change because of the docker implementation (BDD port change, glassfish port,...)

Thanks again for your help. Now I can test it deeper, and plan a demonstration ;)
Marc.

**Comment by bcivel** [comment]
hi @ping0uin,
Two port have been binded in docker implementation.
8080 -> 18080 
4848 -> 14848 for glassfish admin console
Hope that help.
Benoit
