### ISSUE TITLE
getfrmodatalib sql problem/help

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1206]
Hi, 
i'm facing a strange situation. This testcase http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=42771187 is failing with 

`java.sql.SQLException: Invalid column name 'AvailabilityMessage'.'..`

But copying the sql exactly as it is in the test execution result and running in netbeans using the same jbdc driver the query runs without problems: 

```
SELECT TOP 1 ROW_NUMBER () OVER (ORDER BY SiteId, CodeLang, ProductId, DocumentId, Dimension1, Dimension2) As Id
    , SiteId
    , CodeLang
    , ProductId
    , DocumentId
    , Dimension1
    , Dimension2, crb.ActiveArticles.AvailabilityMessage
INTO  #TEMP
FROM  crb.ActiveArticles 
WHERE SiteId = 10 AND CodeLang = 'fr-CH'
ORDER BY NEWID ()

SELECT  * FROM  #TEMP  
UNION ALL 
    SELECT  TOP 1  
        ROW_NUMBER () OVER (ORDER BY NEWID ()) As Id
        , a2.SiteId
        , a2.CodeLang
        , a2.ProductId
        , a2.DocumentId
        , a2.Dimension1
        , a2.Dimension2
        , a2.AvailabilityMessage   
    FROM  crb.ActiveArticles a2
    INNER JOIN #TEMP a1 on a1.SiteId = a2.SiteId and a1.CodeLang = a2.CodeLang
    WHERE a2.SiteId = 10 AND a2.CodeLang = 'fr-CH'
    AND  a2.AvailabilityMessage = a1.AvailabilityMessage

DROP TABLE #TEMP
```

Could it be that cerberus is not correctly sending the query? Note that it have two selects. 

Thanks, 
Rui

**Comment by vertigo17** [comment]
Did you try to execute directly the SQL to see the result and confirm the column exist ?
Cerberus usually report the executed select, can you check that it is complete ?
I don't think jdbc support having multiple SQL in the query (although never tried). I would suggest you simplify the SQL or convert to Store procedure.

**Comment by ruirpr** [comment]
Yes, i said

>  copying the sql exactly as it is in the test execution result and running in netbeans using the same jbdc driver the query runs without problems

The return message is

```
Data Library entry Theseus_2PA_SameDelivery (23070) failed . The SQL 'SELECT TOP 1 ROW_NUMBER () OVER (ORDER BY SiteId, CodeLang, ProductId, DocumentId, Dimension1, Dimension2) As Id
    , SiteId
    , CodeLang
    , ProductId
    , DocumentId
    , Dimension1
    , Dimension2, crb.ActiveArticles.AvailabilityMessage
INTO  #TEMP
FROM  crb.ActiveArticles 
WHERE SiteId = 10 AND CodeLang = 'fr-CH'
ORDER BY NEWID ()

SELECT  * FROM  #TEMP  
UNION ALL 
    SELECT  TOP 1  
        ROW_NUMBER () OVER (O
```

and the property message is 

```
Data Library entry Theseus_2PA_SameDelivery (23070) failed . The SQL 'SELECT TOP 1 ROW_NUMBER () OVER (ORDER BY SiteId, CodeLang, ProductId, DocumentId, Dimension1, Dimension2) As Id
    , SiteId
    , CodeLang
    , ProductId
    , DocumentId
    , Dimension1
    , Dimension2, crb.ActiveArticles.AvailabilityMessage
INTO  #TEMP
FROM  crb.ActiveArticles 
WHERE SiteId = 10 AND CodeLang = 'fr-CH'
ORDER BY NEWID ()

SELECT  * FROM  #TEMP  
UNION ALL 
    SELECT  TOP 1  
        ROW_NUMBER () OVER (ORDER BY NEWID ()) As Id
        , a2.SiteId
        , a2.CodeLang
        , a2.ProductId
        , a2.DocumentId
        , a2.Dimension1
        , a2.Dimension2
        , a2.AvailabilityMessage   
    FROM  crb.ActiveArticles a2
    INNER JOIN #TEMP a1 on a1.SiteId = a2.SiteId and a1.CodeLang = a2.CodeLang
    WHERE a2.SiteId = 10 AND a2.CodeLang = 'fr-CH'
    AND  a2.AvailabilityMessage = a1.AvailabilityMessage

DROP TABLE #TEMP

' has an error : 'java.sql.SQLException: Invalid column name 'AvailabilityMessage'.'..
```

Copying the returned sql from the property to the sql client and running it works without problems.

**Comment by ruirpr** [comment]
Here's an example with several 'selects' inside the datalib that works: http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=42843427 so several selects are suported.

**Comment by ruirpr** [comment]
Cerberus have no problem with this version:

```
Data Library entry Theseus_2PA_SameDelivery (23070) retrieved with success. 1 row(s) retrieved  from SQL executed against database 'THES_CMS' JDBCPOOL 'CMS_UAT_SQL' with SQL : 'SELECT TOP 1 ROW_NUMBER () OVER (ORDER BY NEWID ()) AS Id
			, SiteId
			, CodeLang
			, ProductId
			, DocumentId
			, Dimension1
			, Dimension2
			, AvailabilityMessage   
	INTO  #TEMP
	FROM  crb.ActiveArticles 
	WHERE SiteId = 10 AND CodeLang = 'fr-CH'
	

	SELECT  * FROM  #TEMP  
	UNION ALL 
	SELECT  TOP 1  
		ROW_NUMBER () OVER (ORDER BY NEWID ()) AS Id
		, a2.SiteId
		, a2.CodeLang
		, a2.ProductId
		, a2.DocumentId
		, a2.Dimension1
		, a2.Dimension2
		, a2.AvailabilityMessage   
	FROM  crb.ActiveArticles a2
	INNER JOIN #TEMP a1 on a1.SiteId = a2.SiteId and a1.CodeLang = a2.CodeLang
	WHERE a2.AvailabilityMessage = a1.AvailabilityMessage


DROP TABLE #TEMP
' and first row selected with success. Result : [{"dim2":"4","dim1":"2","AvailabilityMessage":"Livré en 5-7 jours ouvrables","KEY":"350066604"}]
```

Working properly.

**Comment by vertigo17** [comment]
Looks like the column really do not exist. What I meant was to confirm that on the result you got from Netbeans SQL the column was there with the correct name (sorry I was not clear).
Have you tried to change column name to crb.ActiveArticles.AvailabilityMessage or possibly change the SQL as follow (although I am not a SQLServer specialist ):

SELECT TOP 1 ROW_NUMBER () OVER (ORDER BY SiteId, CodeLang, ProductId, DocumentId, Dimension1, Dimension2) As Id
    , SiteId
    , CodeLang
    , ProductId
    , DocumentId
    , Dimension1
    **, Dimension2, crb.ActiveArticles.AvailabilityMessage**
INTO  #TEMP
FROM  crb.ActiveArticles 
WHERE SiteId = 10 AND CodeLang = 'fr-CH'
ORDER BY NEWID ()

to 

SELECT TOP 1 ROW_NUMBER () OVER (ORDER BY SiteId, CodeLang, ProductId, DocumentId, Dimension1, Dimension2) As Id
    , SiteId
    , CodeLang
    , ProductId
    , DocumentId
    , Dimension1
    **, Dimension2
    , AvailabilityMessage**
INTO  #TEMP
FROM  crb.ActiveArticles 
WHERE SiteId = 10 AND CodeLang = 'fr-CH'
ORDER BY NEWID ()

**Comment by ruirpr** [comment]
Yes, but still no sucess. Anyway, CSTech tweaked the query and the problem was solved with the query from my previous comment. 
Can be closed, thanks for your help!
