### ISSUE TITLE
does a infinite pool size value exist?

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#1207]
Hi,

In our implementation, we let the selenium hub to manage the executions of our tests cases (in a kind of cloud mod). 
In this configuration, I would like to know if there is a "infinite" value of the pool_size parameter in the definition of the application? 
Like 0 or something...

Thanks.

**Comment by bcivel** [comment]
Hi @ping0uin, 
No, it's not implemented like that. As the implementation is using java threadpool, we must set a defined number of workers.
But notice that you can define as max size 2147483648 simultaneous workers.
Thanks
Benoit

**Comment by ping0uin** [comment]
Roger

Exactly what I've done, put a huge value ;)

thanks.
