### ISSUE TITLE
add a battery test in a campaign does not work

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#1208]
Hi 

I created a campaign, but when I want to add a battery on it, the "add" button is disable...

On the old page TestCampaign.jsp, I can do it, but not in the new version TestCampaign2.jsp.

FI, I have the following version of Cerberus : 1.1.10.1-1048 .

Thanks.

**Comment by bcivel** [comment]
Hi @ping0uin ,
Just to be sure, you already have at least one battery created?
Thanks
Benoit

**Comment by ping0uin** [comment]
of course
<img width="838" alt="capture d ecran 2017-02-23 a 16 40 46" src="https://cloud.githubusercontent.com/assets/14962879/23266023/dbd2e50c-f9e6-11e6-89bc-d8399d8e2b3e.png">

**Comment by bcivel** [comment]
OK, thanks :-)
And if you create a Campaign and try to edit it, the add button is still disabled?
Thanks
Benoit

**Comment by ping0uin** [comment]
yes. And I also cannot add a property in the campaign

**Comment by bcivel** [comment]
Fixed. Will be available in the next release.
