### ISSUE TITLE
calculateProperty weird behaviour

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1210]
Or maybe it's just me doing something wrong. Anyway, I'll try to explain. 

- calculateProperty PRODUCT_LINE
getFromJS var line=Number('%X%'-'%BASKET_ITEMS%'); return line;
resulting in BASKET_ITEMS=0 and PRODUCT_LINE=2 wich is as expected

- open product PRODUCT(2)

- add product to basket and continue shopping

- calculateProperty BASKET_ITEMS_HTML
getFromHtml xpath=//a[@data-cerberus='img_header_basket_mobile']/span 
returning 1 as expected (1 product added to basket and present in basket icon http://cerberus.siege.red/Cerberus/ReadTestCaseExecutionMedia?filename=32/05/42890532/CheckoutBasket-0010T_backup-S2-I2-A9-C1-screenshot.jpg&filetype=JPG&filedesc=Screenshot&r=true )

- calculateProperty BASKET_ITEMS
getFromJs var bsk=Number('%BASKET_ITEMS_HTML%'); if (bsk>0){	return bsk; }else{ return 0; }
and here is the problem. Properties tab show that BASKET_ITEMS has been correctly calculated with value 1
![image](https://cloud.githubusercontent.com/assets/1914659/23303226/ccd1f710-fa8a-11e6-8b3a-4d6e8a06a0d1.png)
but in the step there is still 0 and I'm assuming this 0 is comming from the calculateProperty PRODUCT_LINE where it calls the %BASKET_ITEMS%
![image](https://cloud.githubusercontent.com/assets/1914659/23303246/db3b597c-fa8a-11e6-8df1-8cd6cff6bacc.png)

So, the property is showing the correct re-calculated value but it is not being used in the step.

This is part of a 2 products loop and the same happens in the second iteration as you can see in 
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=42890532
![image](https://cloud.githubusercontent.com/assets/1914659/23303321/4fb8d8b0-fa8b-11e6-9bdd-984d90c1a266.png)
![image](https://cloud.githubusercontent.com/assets/1914659/23303326/570759d4-fa8b-11e6-95cd-1bfe4245f701.png)

I'll leave the testcase Checkout Basket - 0010T_backup as it is so further investigation can be done and change the original one to something that works so i can continune my work. 

Thanks!

TODO list on that task:

- [x] Remove error on decode %toto%
- [x] add decode error only when %system.*% or %object.*% or %property.*% was not decoded
- [x] Trapp potencial error when decode in order to raize FA on corresponding step / action / control
- [x] Reactivate the 2 layer decode in order to allow putting %property.*% inside objects or %object.% inside properties.
- [x] Reactivate the way we guess the %property% inside a decode in order to allow syntax : %titi%PROP% that will decode to %titiPROPVALUE in stead of raizing error on property titi not defined.

**Comment by ruirpr** [comment]
Already changed the library step, so previous test will not have the same behaviour anymore. Now i'm facing the same similar problem in http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=42897193 using property PRODUCT_LINE

in step 5.1 PRODUCT_LINE is calculated with value 2
in step 5.2 PRODUCT_LINE is calculated again with value 2 but Properties tab shows value 1 for PRODUCT_LINE

Again, it seems that it is being correctly calculated but not correctly used. 
This property is calculated before opening a product from datalib due to bug https://github.com/cerberustesting/cerberus-source/issues/809

**Comment by vertigo17** [comment]
I will have a look at your execution next week when I will get access to detail execution provided. My last comit should at least allow recursive property usage. Decode will work when a property name is inside a property value.

**Comment by vertigo17** [comment]
I close the issue as decoding has been refactor and now works better with complex situation.
Please test it and come back to me is not clear or you feel it still not works.
