### ISSUE TITLE
Is XPATH on Page

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1211]
Hello,

Is it possible to implement as an extra option on conditions for executing step something like if the element is present taking as argument some XPATH? This could be really handy for apk testing as I cant execute any JS with appium..

Thanks,
Best Regards

**Comment by vertigo17** [comment]
Yes sure.
Can you confirm that the verifyElementPresent control will work fine ?
If so i will make it available as a condition.

**Comment by j0hnsa** [comment]
Hello @vertigo17,

Yes the verifyElementPresent is working fine for both ANDROID and iOS. 

Thanks,
Best Regards
