### ISSUE TITLE
Create Label for several systems and remove battery moving them to labels.

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1212]
Hello,

It would be great if we could create a label for several systems. Some labels are the same for different applications (for example a customer type or items type).
In this windows we would select the systems needed : 
![labelmultisystems](https://cloud.githubusercontent.com/assets/18569182/23416010/6a53142a-fde1-11e6-8b40-ddb40598c1bd.PNG)
Same idea could be used for application object.

Thank you 

Cerberus Version : 1.1.11-SNAPSHOT-1084

**Comment by vertigo17** [comment]
That ticket will also include the migration from battery to labels.
All battery will be migrated to labels.
