### ISSUE TITLE
agent configuration not used

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1215]
Hi, 
built some tests with the agent 

Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

and the agent

Mozilla/5.0 (Android 6.0.1; Tablet; rv:50.0) Gecko/50.0 Firefox/50.0

and none is working, the browser behaves like allways. (i was expection a redirection like it happens on a real tablet)

The agent was specified in the robot and in the test itself.

http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=43183122

**Comment by bcivel** [comment]
fixed with my last commit
