### ISSUE TITLE
Screenshot image not showing correctly

### ISSUE THREAD

**Issue by mbessa** [cerberustesting/cerberus-source#1219]
Hello,

When you try to open full picture, the output is this:
![image](https://cloud.githubusercontent.com/assets/5825695/23670049/52e0e1dc-035e-11e7-99d7-aa9406084ac7.png)

Example:
http://192.168.134.197/CerberusQA/ExecutionDetail2.jsp?executionId=43198801

The small size image is displayed OK.
![image](https://cloud.githubusercontent.com/assets/5825695/23670107/8ba97b32-035e-11e7-9874-d6928001f18b.png)

Cerberus Version : 1.1.11-SNAPSHOT-1108

**Comment by vertigo17** [comment]
I was not able to fully test as I don't have the issue on my laptop but I forced the content type with https://github.com/cerberustesting/cerberus-source/commit/edda914e3a68325a61b84093ac7e8b67478f13f4 and it should fix the issue.
Please consider that this will only work for new executions.

**Comment by vertigo17** [comment]
Following deploy, this execution is working great.

http://192.168.134.197/CerberusQA/ReadTestCaseExecutionMedia?filename=98/92/43199298/PerformanceMonitor-5091M-S8-I1-A1-screenshot.png&filetype=PNG&filedesc=Screenshot&r=true

http://192.168.134.197/CerberusQA/ExecutionDetail2.jsp?executionId=43199298

![selection_171](https://cloud.githubusercontent.com/assets/5342048/23679937/bdbcfe8e-0389-11e7-8c0e-2580e9a5b19e.jpg)


Please reopen if you still have the issue.
