### ISSUE TITLE
Steps are not ordered sequentially

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1220]
Hi,

we noticed that some tests don't have the steps ordered sequentially.

Example:

We have step 1 and then step 3.

![image](https://cloud.githubusercontent.com/assets/14328346/23670794/d5c6aa8a-0360-11e7-8c1d-51c8546bb907.png)

![image](https://cloud.githubusercontent.com/assets/14328346/23670804/dd982fd6-0360-11e7-820b-5f057afebe6c.png)

![image](https://cloud.githubusercontent.com/assets/14328346/23670811/e27ed0cc-0360-11e7-8100-a3fa980b9a35.png)

Step "3" should be step "2".

Do you know why this happens?

Can  you please take a look and advise?

Cerberus1.1.11-SNAPSHOT-1108 and Cerberus1.1.11-SNAPSHOT-1084

Thanks

**Comment by bcivel** [comment]
Hi @RobertoAbraul 
Having a look to the tracability tab, it seems to be related to testcase that has been saved in old testcase page.

Then, opening it in the new page, you see that the step 2 doens't exist. And if  you save the testcase, it will correct the order puting 1 and 2.

For my point of view, we should not take care of that behavior has we protected it on the new page (it can't happen anymore), if you save like that it will reorder correctly, and even if you keep it like that, it works as expected (as only the order is important).

I would suggest to close the issue unless @vertigo17 want to solve it.
Benoit

**Comment by vertigo17** [comment]
I just saved the testcase and it corrected the data.
Agree, as long as new page makes it impossible to generate sort with +2, I think we can close it.
The sort 1 by 1 is still important not only to have clean display (on that we don't really care as long as the order is correct) but more because can be used in %system.STEP.n.n.RETURNCODE%
I close it.
