### ISSUE TITLE
Report by Status on ReportingExecutionByTag

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1224]
Hello,

If we filter for instance by status removing the OK executions the Report by Status won't show the global view of executions of that report showing only the executions that meet the filters requirements.

Is this new behavior expected?

Thanks and Regards

**Comment by vertigo17** [comment]
Yes it is even if we could:
Leave the country perimeter on top (because impact list of the scope of execution) and put back the status filter on the testcase list.
@bcivel  what do you think about it ?

**Comment by bcivel** [comment]
Yes, I agree that the global graph filtered on specific status can be useless.
I'll put it back to the bottom and filter only the table.

**Comment by bcivel** [comment]
Finally, we keep it like that. Country and Status filters stay at the top.
Filters on top determine what you see in all page.
Specific filters on table have been added by @Ronpiche 

Don't hesitate to reopen if you think it should be different
Thanks
