### ISSUE TITLE
Cerberus doesn't decrypt twice with an object

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1226]
Hello,
Cerberus doesn't decrypt twice the %% when I use an object :
![objecthermes](https://cloud.githubusercontent.com/assets/18569182/23790660/690e669a-0580-11e7-999c-4b9e68dfb630.PNG)
My property is a text one, there is no property type like "getfromApplicatioObject". Is it a normal behaviour ?
http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=43470412
Thank you !

Cerberus Version : 1.1.11-SNAPSHOT-1108

**Comment by vertigo17** [comment]
Yes, getfromApplicationObject make no sens as the definition of the object are done on the application object screen and transversal to every testcases. By default all objects are available from any testcases. No need to define it in property.
The rule is:
%property.toto% require toto to be created inside the corresponding testcase or inherited from used steps or pretesting testcases.
%system.toto% do not require any definition. those are taken from execution context.
%object.toto% require toto to be defined inside object screen. 

decrypt twice add to be removed as it was producing errors. We will reactivate it part of #1210.
I close the issue to follow up the correct one.
