### ISSUE TITLE
Creating Properties (same name and different countries)

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1227]
Hi,

when creating the same Property name with different values for different countries it saves only one for all countries.

The same propertie name (different countries and different values):
![image](https://cloud.githubusercontent.com/assets/14328346/23794732/8a24dd38-0589-11e7-9488-8bf21c3f3e24.png)

After save we have only one with the value of first for all countries.

![image](https://cloud.githubusercontent.com/assets/14328346/23794749/a139e626-0589-11e7-80fc-54920aab9121.png)

Cerberus1.1.11-SNAPSHOT-1108

Can you please take a look?

Thanks

**Comment by ruirpr** [comment]
Hi, 
just noticed that saving new properties for diferent countries is still not working correctly. This was something important and we really expecting to be corrected in the latest release, since is something that causes people to do work twice.
Can you take a look as soon as possible? Thanks!

**Comment by vertigo17** [comment]
I was still able to reproduce the issue.
Click on add property
Name it TOTO
Select only CH country
Put value CH
click again to add a new property
Also name it TOTO
Select only country BE
Put value BE
Save testcase

The script should keep both property with the 2 values but only 1 is sved.

**Comment by bcivel** [comment]
@vertigo17 Strange, I cannot reproduce on my side on my local version, nor on the QA server.
Today, if I follow the step you described, it save both properties.
Could you please make sure you're on the last version?

**Comment by vertigo17** [comment]
Ok I will test again. 
Probably i got some cache the prevent it work. 
Will check during the WE.
