### ISSUE TITLE
Error message when opening testbatteryEdit

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1228]
Hello,
This message is displayed when I open a battery: 
![errormessage](https://cloud.githubusercontent.com/assets/18569182/23797576/d56fdc90-05a0-11e7-87a9-d99cc6ef6466.PNG)
And we can't add or remove a testcase in the battery.
Thanks.
Cerberus Version : 1.1.11-SNAPSHOT-1108

**Comment by bcivel** [comment]
Hi @R-Loic 
Does it still happen on your side? I cannot reproduce on my local application, nor production environmnent
Below is a screenshot of the prod environment on the battery that you try to open on your exemple

<img width="1548" alt="capture d ecran 2017-03-14 a 21 36 07" src="https://cloud.githubusercontent.com/assets/5376184/23921313/878afae4-08fe-11e7-8afc-c703efe0a9cc.png">

**Comment by R-Loic** [comment]
Hello,

Happened again today : 
![errormessage](https://cloud.githubusercontent.com/assets/18569182/24003570/1b4afcc8-0a64-11e7-9359-f778bd426da4.PNG)
Even if I click on OK button, add Testcase is not available : 

![battery](https://cloud.githubusercontent.com/assets/18569182/24003653/569c9a5c-0a64-11e7-9c8f-0c234674c413.PNG)
To be checked together on my PC, seems to happen every time.

**Comment by R-Loic** [comment]
Issue was due to a character present in battery name (tabulation - inserted in database, no possible through GUI).
Not present anymore.
