### ISSUE TITLE
user agent causing test to fail

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1229]
Hi, 
when using the useragent defined in the test:

Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

test fails on verifyElementPresent with the message 'The test case is cancelled due to lost connection to Selenium Server! Detailed error : Permission denied to access property "handleEvent"'
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=43557606 (maybe it's a good ideia to add the agent used to the testexecution results?)

OK when removing the agent
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=43557496

**Comment by ruirpr** [comment]
@bcivel just noticed you updated the testcase. Please, revert the agent when you finish, that's a testcase finished and needed. Thanks!

**Comment by bcivel** [comment]
Hi @ruirpr 
I have been able to reproduce in firefox 48. 
It doesn't happen anymore in firefox 52 + Gecko 0.15 + Selenium 3.3.1
Anyway, the userAgent is now stored in database to help the investigation
