### ISSUE TITLE
URL links aren't properly defined into execution detailed

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#1240]
Cerberus Version : 1.1.11-SNAPSHOT-1052

when using "open URL" action, if you go to execution detailed page and wanna go to that URL, you can read "opened url **URL you set into you tc**. It appears to be alink, but it's empty !

minor bug... but bug :)

**Comment by vertigo17** [comment]
Please provide a screenshot as I cannot reproduce.
Here is a screenshot with latest version and 2 Actions openUrl and OpenUrlWithBase

![selection_172](https://cloud.githubusercontent.com/assets/5342048/24334370/5d4d056e-1269-11e7-97a7-434506f468ab.jpg)

**Comment by bcivel** [comment]
fixed
