### ISSUE TITLE
New feature add stepS ?

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1241]
Hello,
It would be great if we could add severals steps from the following windows. For example, add three steps by selecting them with a checkbox. First check = first steps added. This feature could be a replacement of the "import script from another test case".
![addsteps](https://cloud.githubusercontent.com/assets/18569182/24039527/d6ea7084-0b05-11e7-9423-fe02ce82c27a.PNG)
And maybe split the two buttons on testcasescript : 
"Add a new step"
"Import step(s)"
instead of : "Add step"
From my experience, add several steps is frequent.
Thank you !

**Comment by nicodeur** [comment]
Hi @R-Loic,

I added possibility to add several library.

I close this issue. With this evolution, I don't think that split button on 2 buttons is really needed. I propose than you test this new feature and create a new issue if you think it will bring something to this screen.

Regards,

Nicolas
