### ISSUE TITLE
Execution report by tag - search box

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1243]
Hi,

search box on report by tag doesn't work properly.

Every time we type a character it crashes the browser by doing an report update and doesn't allow us to type a complete word.

![image](https://cloud.githubusercontent.com/assets/14328346/24041235/63cee8c4-0b04-11e7-8d83-9bf2372bc7d3.png)

Maybe a button to confirm the search after we type a word on the box could solve this.

Can you please take a look?

Thanks.

**Comment by vertigo17** [comment]
Has been fixed with the last changes from @Ronpiche.
Please reopen if you still have the issue.
