### ISSUE TITLE
Time values displayed are not the same

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1248]
Hello 
In execution details, the time values displayed are not the same : 
![time](https://cloud.githubusercontent.com/assets/18569182/24192774/5e460898-0ef0-11e7-82b8-12bcd47a4450.PNG)
This happen often, the two values are supposed to be the same (or an addition) depending the unit but they are completly different. The same issue is also present with severals actions in the step.
Thanks !
Cerberus Version : 1.1.11-SNAPSHOT-1108

**Comment by vertigo17** [comment]
This is normal that those 2 values are not strictly the same as step include Action timing but also time spent during decode of condition values of step level. 
But n that case the elapsed calculation was wrong and was corrected and step elapse should always be bigger that the sum of all corresponding elapsed actions and controls.
