### ISSUE TITLE
Issue release 1.1.11 

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1251]
Hello,

With the 1.1.11 release i had 2 issues : 

- run multple KO
- execution are launched in full screen (like F11) - is this normal ?

Should I use the last 1.1.12-snapshot ? I will test it.

Thanks for your help

**Comment by bcivel** [comment]
Hello @vitoo 
Could you please describe your two problems : 

1. Run Multiple KO : Can ou describe what's happen? You're redirected on the report? Stay in the page? Can you have a look to the ExecutionPending page (under the run menu) and see if you see some content? 

2. In fact, it was the behavior expected but it did'nt work on chrome. I fixed it adding the argument -start-fullscreen to the chrome driver. Is it causing problem for your test?

Thanks
Benoit

**Comment by vitoo** [comment]
1.  Redirect to the report, it stays NE, and it's in the queue 
2. On local computer its awkward because it takes all the screen, it was easier to hide the windows before

**Comment by vitoo** [comment]
Does it works for you ? 
Same issue with latest commit

**Comment by bcivel** [comment]
Yes, it works on my side. Which error message do you have in the queue?

**Comment by vitoo** [comment]
<div>Bad answer format. Expected verbose-txt. Check server logs</div>

**Comment by vitoo** [comment]
This error is for a verbose parameters ?

Here is how i've set my params : 
![image](https://cloud.githubusercontent.com/assets/995694/24358135/64b3c1d4-1300-11e7-95d7-23b1373e3523.png)

**Comment by bcivel** [comment]
Hi @vitoo .
That mean you must use verbose-txt for the outputFormat (instead of GUI like you've set).
Anyway, we will fix it removing this check and disabling outputFormat is several test selected.

**Comment by vitoo** [comment]
I still have this error if i select verbose-txt 😢

**Comment by abourdon** [comment]
Hi @vitoo I will take a look tomorrow.

Regards,
Aurelien

**Comment by abourdon** [comment]
Re @vito

Before to investigate, is the `cerberus_url` property well defined? Are you dealing with a proxy when requesting this url?

It could explain why Cerberus complains about bad format.
 
Regards,
Aurélien

**Comment by vitoo** [comment]
Yes my bad, the cerberus_url was not right in local cerberus (database copied from prod)

**Comment by abourdon** [comment]
Great @vitoo,

So this one can be closed isn't it?

Aurélien

**Comment by vitoo** [comment]
This issue is okay now

Little view issue here with the datatable : 

![image](https://cloud.githubusercontent.com/assets/995694/24395179/0dcb6ad0-139f-11e7-909f-aaf5e4cb8d7e.png)

**Comment by vertigo17** [comment]
I will open a new minor issue with only that overlay isue.
