### ISSUE TITLE
Unable to create a new TestDataLib entry

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#1255]
Fresh environment, first entry to create and fail :

<img width="1393" alt="screen shot 2017-03-29 at 10 57 18" src="https://cloud.githubusercontent.com/assets/1511715/24446647/8fadb0f6-146e-11e7-8d0b-4a46e5589b3e.png">

Log error:

<img width="1247" alt="screen shot 2017-03-29 at 10 58 34" src="https://cloud.githubusercontent.com/assets/1511715/24446683/ac410f60-146e-11e7-8a16-4e5e2a8b7942.png">

**Comment by vertigo17** [comment]
Was the database updated with latest version ?
Can you check the testdatalib table has the service column ?

**Comment by abourdon** [comment]
Yes et no I haven't this column. Argh... so the DatabaseVersioningService is bugged?

**Comment by vertigo17** [comment]
Can you check on the glassfish logs if you find entry that correspond to:


        // Adding Service Columns to testdatalib table.
        //-- ------------------------ 1103-1105
        SQLS = new StringBuilder();
        SQLS.append("ALTER TABLE `testdatalib` ADD COLUMN `Service` VARCHAR(255) NULL DEFAULT null AFTER `DatabaseUrl`;");
        SQLInstruction.add(SQLS.toString());
        SQLS = new StringBuilder();

Did you check when applying the script correctly executed ?

What version of database MySQL or Mariadb do you use ?

**Comment by abourdon** [comment]
My version: 1120

What is strange is that this instruction is displayed into the DatabaseMaintenance page:

<img width="688" alt="screen shot 2017-03-29 at 11 22 39" src="https://cloud.githubusercontent.com/assets/1511715/24447701/22bf6e9a-1472-11e7-894a-726539c5991a.png">

And what is also strange is that your entry showing a comment with `1103 - 1105` but with only one instruction.

Very (very) strange...

**Comment by abourdon** [comment]
Probably due to a bad manipulation from my side, but it will be hard to retrieve a correct database state... Maybe using a more solid solution would be better as Liquibase (https://github.com/cerberustesting/cerberus-source/pull/767)
