### ISSUE TITLE
Improvement on environment management

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#1258]
We would like to have the option to specify different url's to the applications, depending on the server where we have the application running.
Currently, the url is being build with tables host + countryenvparam + countryenvironmentparameters, and we can only change the host part of the url, not the context or parameters.

The goal, for our needs is to have the hability to have something like:
![image](https://cloud.githubusercontent.com/assets/5640464/24665007/05ee5a7e-1954-11e7-8fcd-697ba1851c5f.png)

From_Table	cep	cep	host	cep	host	cep	host	host	cep	cep	cep	
From_column	country	environment	server	application	session	IP	secure	port	domain	URL	URLLOGIN	Generated url
row1	UF	PROD	PRIMARY	VCCRM	0	172.25.0.1	N			//vccrm_112.0/4/	/login.xhtml?screenMode=Full&comcode=001	http://172.25.0.1/vccrm_112.0/4/login.xhtml?screenMode=Full&comcode=001
row2	UF	PROD	PRIMARY	VCCRM	1	172.25.0.20	N			/vccrm_112.0/	/login.xhtml?screenMode=Full&comcode=001	http://172.25.0.20/vccrm_112.0/login.xhtml?screenMode=Full&comcode=001
row3	UF	PROD	BACKUP1	VCCRM	1	192.168.134.2	N			/vccrm_112.0/	/login.xhtml?screenMode=Full&comcode=001	http://192.168.134.2/vccrm_112.0/login.xhtml?screenMode=Full&comcode=001
row4	UF	PROD	BACKUP1	VCCRM	2	192.168.134.194	N			/vccrm_116.0/	/login.xhtml?screenMode=Full&comcode=001	http://192.168.134.194/vccrm_116.0/login.xhtml?screenMode=Full&comcode=001
row5	FR	PROD	PRIMARY	THES_RDT	0	www.laredoute.fr	N					http://www.laredoute.fr

(Where cep means table countryenvironmentparameters.)

Is this something that can be done, even if additional clarification is needed?

**Comment by vertigo17** [comment]
Well in fact host table is not used on Cerberus side. That table is ony used on index application.
Cerberus gets the URL to access the application only from cep table at system, country, environment + application level.
I am not sure this is a good idea to add Server and Session level. It will bring significant complexity for an added value not clear to me.

We could define host table at application level but that would also mean a lot of administration.
I suggest we discuss outside git the application that require that level of config.

**Comment by vertigo17** [comment]
I close it and let you open the subject on a separate private email thread better understand the application impacted.
