### ISSUE TITLE
Test case list display issue

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1259]
Hello,

There is an issue with chrome (seems OK on firefox) when user uses zoom on his web browser and displays test case list page: 
![zoomnav](https://cloud.githubusercontent.com/assets/18569182/24760476/15d4095c-1ae9-11e7-9321-8fab04cf2163.PNG)
![issuedisplay](https://cloud.githubusercontent.com/assets/18569182/24760485/1a46c056-1ae9-11e7-814a-2cf3fc868149.PNG)
Thank you !

Cerberus Version : 1.1.12-SNAPSHOT-1118

**Comment by Ronpiche** [comment]
Seems fix with the new navbar ( 2af07243f3416cea385a4cf8767a43206e93aee6 ) and the resize function embedded with it
