### ISSUE TITLE
New feature : massive test case update

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1260]
Hello,
It would be interesting to manage massive update in testcase list. I have already had the following cases : 
- add or modify severals testcase function, 
- modify test case status. 
with "severals" I mean something like 100 test cases. I had to use database to do the modifications but some users don't have acces to Cerberus DB.
It could be added to the new feature "massive labels affectation".
Thank you !

TODO:
- [x] New Update tab
- [x] Function update
- [x] Status Update

**Comment by abourdon** [comment]
Related to #1032
