### ISSUE TITLE
Weird display on ExecutionDetail2 executing test for web

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1261]
Please check this execution:
http://192.168.134.197/CerberusQA/ExecutionDetail2.jsp?executionId=44445980

Thanks and Regards

**Comment by j0hnsa** [comment]
Please note that this test is with CerberusQA to be deployed.
Cerberus1.1.12-SNAPSHOT-1126

**Comment by j0hnsa** [comment]
Hello,

This just happened with IOS test that had a condition to not execute one action if element is not present, test remained pending and stopped on the device and the output can be checked in:

http://192.168.134.197/CerberusQA/ExecutionDetail2.jsp?executionId=44448900

**Comment by abourdon** [comment]
Hi @j0hnsa,

It seems the execution #44445980 does not exist in CerberusQA

And I can see the cerberus_url was not correctly set. It is currently set to the production value.

Please fix it, retry, and let us now.

Regards,
Aurélien

**Comment by j0hnsa** [comment]
Cerberus_url was updated, I will run a campaign on QA as soon as possible to see if its replicated.

**Comment by j0hnsa** [comment]
Issue replicated now on PROD:
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=44934111

Can you check?

Thanks and Regards

**Comment by gmoita** [comment]
If it is still PROD, please check it... I'm reopening issue.

**Comment by abourdon** [comment]
Probably due to the same error as #1274
