### ISSUE TITLE
RU property returns ???????

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1262]
Hi,

for RU a property defined with "БЕСПЛАТНО" during the execution it returns "?????????".

![image](https://cloud.githubusercontent.com/assets/14328346/24793451/0792e93a-1b7a-11e7-89b6-8d741e09654f.png)

![image](https://cloud.githubusercontent.com/assets/14328346/24793531/4f5db84e-1b7a-11e7-819f-534a2951fbcd.png)

![image](https://cloud.githubusercontent.com/assets/14328346/24793462/0eb35f74-1b7a-11e7-8caa-83f3c59d8589.png)

http://192.168.134.197/CerberusQA/ExecutionDetail2.jsp?executionId=44446076

Can you please take a look?

Cerberus1.1.12-SNAPSHOT-1126 in qa

Thanks.

**Comment by RobertoAbraul** [comment]
One more example: http://192.168.134.197/CerberusQA/ExecutionDetail2.jsp?executionId=44446893

![image](https://cloud.githubusercontent.com/assets/14328346/24794717/958f2178-1b7e-11e7-812b-d728b6da9d12.png)

**Comment by vertigo17** [comment]
I was not able to reproduce.
The executions no longuer exist in QA and I created a property with the Russia text and got it calculated with no issue.

Can you provide a new exe with the issue or provide the text that generate the issue ?

![selection_177](https://cloud.githubusercontent.com/assets/5342048/25317135/cec78dc6-2872-11e7-839f-b1ffc3c7f8b7.jpg)
