### ISSUE TITLE
Execution detail - returned value not visible

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1264]
Hi,

On the execution detail, when calculating a property instead of the returned value on the returned message we have the executed query.

Example:
QA (Cerberus1.1.12-SNAPSHOT-1126):
![image](https://cloud.githubusercontent.com/assets/14328346/24796567/52e5b704-1b85-11e7-9142-5e3082804339.png)

Prod (Cerberus1.1.11-SNAPSHOT-1108):
![image](https://cloud.githubusercontent.com/assets/14328346/24796578/5f4f4424-1b85-11e7-8cd1-d7544505d571.png)

Is this a new behavior?

Thanks

**Comment by vertigo17** [comment]
Yes we report the result of property calculation that should include both the detail of the execution + the result.
Do you prefer only the result in case of OK ?

**Comment by j0hnsa** [comment]
Hello @vertigo17,

The only problem we see is that the Calculated value isn't being shown on the page only on Property page. The detail of the calculation can be present as well.

Thanks

**Comment by vertigo17** [comment]
Yes it is. This is just that the message is quite long as full SQL is saved. 
It should appear at the end:
![selection_175](https://cloud.githubusercontent.com/assets/5342048/24931377/5b8665bc-1f0d-11e7-9843-d5df9a5f5e1f.jpg)
Anyway I don't think this is useful at the action level to repeat detail information from the property. I simplified the message when property calculation was successfull:
![selection_176](https://cloud.githubusercontent.com/assets/5342048/24931449/9c7d1af2-1f0d-11e7-8dd2-ead2e54cddda.jpg)
