### ISSUE TITLE
Weird behavior while running tests with the same tag name

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1265]
Hi,

after select one test to run in all countries and put a tag name "0097A", all executions stay "NE".
If we do a refresh or click to load the report the number of tests descreases and then we end with an empty tag, with no results.

http://192.168.134.197/CerberusQA/ReportingExecutionByTag.jsp?Tag=0097A

1º:

![image](https://cloud.githubusercontent.com/assets/14328346/24798881/60ea2172-1b90-11e7-8ea8-01c57fce6917.png)

2º:

![image](https://cloud.githubusercontent.com/assets/14328346/24798910/793c4c78-1b90-11e7-84a6-2ca1825d0455.png)

3º after first "load":

![image](https://cloud.githubusercontent.com/assets/14328346/24798920/8ae9ffb0-1b90-11e7-8399-9d05f26e6e15.png)

4º at the end:

![image](https://cloud.githubusercontent.com/assets/14328346/24798934/94362f80-1b90-11e7-994d-9019673ad824.png)

If we try to open a "NE" (action made on 2º):

http://192.168.134.197/CerberusQA/RunTests.jsp?queuedExecution=129163

![image](https://cloud.githubusercontent.com/assets/14328346/24799131/88800c3c-1b91-11e7-9fc5-f0d5fa2181da.png)

On test case execution of that test, it seems that only two executions runned with the tag "0097A" (the first 2 green):

http://192.168.134.197/CerberusQA/TestCaseExecution.jsp?test=Checkout%20Basket%20Product%20Block&testcase=0097A

![image](https://cloud.githubusercontent.com/assets/14328346/24799230/0757a95c-1b92-11e7-82dd-fab06a7e828b.png)

Cerberus1.1.12-SNAPSHOT-1126 

Can you please take a look?

Thanks

**Comment by abourdon** [comment]
Hi,

It seems your tests have not been correctly started. Probably due to configuration mistake. Did you check the ExecutionPending page? You may retrieve your executions with errors.

Let me know,
Aurélien

**Comment by abourdon** [comment]
It is probably due to the cebrerus_url value which is not correctly set.

Please fix it and try again.

Let us know
Aurélien

**Comment by RobertoAbraul** [comment]
Hi,

Parameter "cerberus_url" updated and it's now ok.

![image](https://cloud.githubusercontent.com/assets/14328346/24911885/5c74eafa-1ec4-11e7-9962-6888d958012b.png)


Thanks.

**Comment by abourdon** [comment]
Ok thanks
