### ISSUE TITLE
still can't see last executions

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1269]
Sometimes this happens:

![image](https://cloud.githubusercontent.com/assets/1914659/24898741/cac53caa-1e95-11e7-994d-db42490c8789.png)

What is the exe.* ?

**Comment by abourdon** [comment]
exe means execution. and for instance, exe.test means the execution's test

Is your filter valid?

Aurélien

**Comment by vertigo17** [comment]
Question is also how can you get there ?

exe.id should not be available to filter (and it appears on your screenshot).
value seems to correspond to Test data and not an execution id.

What was the URL of the page ?
How to reproduce ?

**Comment by vertigo17** [comment]
@ruirpr Is that issue still present ?
If not, can you close it ? If yet, please detail how to reproduce ?
