### ISSUE TITLE
Application filter on ReportingExecutionByTag not working

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1271]
Hello,

the Application filter on ReportingExecutionByTag is not working, could you check please?

Thanks and Regards
Cerberus Version : 1.1.11-SNAPSHOT-1108

**Comment by vertigo17** [comment]
Not even using the search input field ?
I tested it and works fine.

**Comment by abourdon** [comment]
The search via input field works fine from my side too.

What do you mind about the _Application filter_? Did you mean the search input is not applied to it?

Regards,
Aurélien

**Comment by j0hnsa** [comment]
Hello,

I meant the filter on the screenshot:
![filter](https://cloud.githubusercontent.com/assets/16339891/24911921/7e8331e2-1ec4-11e7-9eba-24823d532a3b.png)

I guess it was because I was on:
http://cerberus.siege.red/Cerberus/ReportingExecutionByTag1.jsp

Anyway this would be really usefull to have. For instance for me I have to search 3 different apps in a report with 4200 TC's and my tests are only 64.

**Comment by bcivel** [comment]
Hello @j0hnsa 
Yes, it's a duplication of #1242 .
We will fix it.
Thanks
Benoit
