### ISSUE TITLE
Testcase description in execution detail

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1272]
Hello,

It would be interesting to have the test case description in execution detail. for example in the yellow area in the following screenshot : 

![descriptionexecution](https://cloud.githubusercontent.com/assets/18569182/24906824/abbd58fa-1eb9-11e7-956e-d403c1a806ff.PNG)

Thank you !

Cerberus Version : 1.1.11-SNAPSHOT-1108

**Comment by vertigo17** [comment]
Agree as this is clearly missing to understand what the execution was supposed to test but the zone is already used for execution return message:
![2017-04-11 13_25_29-execution detail](https://cloud.githubusercontent.com/assets/5342048/24906958/6206797a-1eba-11e7-848a-95cb6864d7d8.png)

We put it in between ?
Line 1 : ID - test - testcase - country - environement - return status code
Line 2 : Description of the test case
Line3 : Detail return message of the execution.

**Comment by R-Loic** [comment]
Hello, 
Yes, we can put it here, and maybe modify the color of the return message for more visibility ?
