### ISSUE TITLE
test failed but control still executing

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1274]
Hi, just saw this behaviour
![image](https://cloud.githubusercontent.com/assets/1914659/24918479/77496b26-1ed8-11e7-88f6-0ad36b153e05.png)
http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=44891988

The test is FA but control still executing

**Comment by vertigo17** [comment]
Could you reproduce it ? It seems it only happened once and will be hard to fix if we cannot reproduce.
Looks like the corresponding testcase was modified ad now working OK ?
Can you produce a 'small' testcase that reproduce the issue ?

**Comment by abourdon** [comment]
Probably the same as #1261
