### ISSUE TITLE
Feature Click on pos working on QA but not in PROD

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1277]
Hello,

The feature that was implemented to click on a certain coordinate is working on QA but not in PROD, is there any additional parametrization we are missing?

Example:
http://192.168.134.197/CerberusQA/ExecutionDetail2.jsp?executionId=44745565 
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=44921850 

Cerberus Version : 1.1.12-SNAPSHOT-1128

**Comment by abourdon** [comment]
Check your tests, the SEARCH_BAR property is not filled with the same value between them:

From QA:
<img width="1279" alt="screen shot 2017-04-12 at 11 51 26" src="https://cloud.githubusercontent.com/assets/1511715/24952020/862fb2d2-1f76-11e7-8e75-bee94c57f5dc.png">

From Prod:
<img width="577" alt="screen shot 2017-04-12 at 11 51 01" src="https://cloud.githubusercontent.com/assets/1511715/24952040/986e8202-1f76-11e7-84f6-324b5e66f119.png">

**Comment by j0hnsa** [comment]
Why do you close this issue? the values are the same:
![qa](https://cloud.githubusercontent.com/assets/16339891/24952753/9864dae6-1f70-11e7-820b-6bf3cc197af4.png)
![prod](https://cloud.githubusercontent.com/assets/16339891/24952752/9864c5e2-1f70-11e7-9482-e6ac106d7d89.png)

**Comment by j0hnsa** [comment]
I see it now,
Thanks
