### ISSUE TITLE
not possible to mover cursor in imported steps

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1278]
Hi, 
in imported steps its not possible to move cursor in text fields (arrows and end/home). Also ctrl+c does not work.

![image](https://cloud.githubusercontent.com/assets/1914659/24961585/2f4df0d0-1f91-11e7-93f1-c7cd2d253254.png)

**Comment by abourdon** [comment]
Unable to reproduce. Tabular key works well (as well for moving forward and back) and copy/paste works well also. Tested again Mac OSX & Windows environment.
