### ISSUE TITLE
Filter unselect all doesn't work in testcase list

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1279]
Hello,
Filter doesn't work in testcase list when I click on "unselect all" the display is refreshed and open the url with a new filter : 
![filter](https://cloud.githubusercontent.com/assets/18569182/24961706/f97bb600-1f99-11e7-8612-0ae8aa14afa2.PNG)

URL opened for example :
/Cerberus/TestCaseList.jsp?testCaseTable_length=10&searchField=&unSelectAll=&0001A=on&BE=on&CH=on&ES=on&FR=on&IT=on&PT=on&RU=on&UK=on&VI=on&PL=on&DE=on&RX=on&UF=on&VB-CH=on&VX=on&0001A+-+CheckStatus_1.0=on&FR=on&0001B=on&BE=on&CH=on&ES=on&FR=on&IT=on&PT=on&RU=on&UK=on&VI=on&PL=on&DE=on&RX=on&UF=on&VB-CH=on&VX=on&0001A=on&FR=on&PT=on&BE=on&CH=on&FR=on&IT=on&PL=on&0002A=on&BE=on&CH=on&FR=on&IT=on&PL=on&BE=on&CH=on&FR=on&IT=on&PL=on&BE=on&CH=on&FR=on&IT=on&PL=on

Thank you !

Cerberus Version : 1.1.12-SNAPSHOT-1128

**Comment by abourdon** [comment]
Same behaviour from the BuildContent page, from which the Mass Action has been copied.

The current Mass Action implementation is broken. I will reopen #1032

**Comment by abourdon** [comment]
Actually, #1032 has not to be reopened because this bug also affect other page. Hereafter the list of affected pages:
- Test case list
- Build content
- Executions in queue

**Comment by R-Loic** [comment]
Hello,
For your information, the test case has been created (filter on the test case list page): 
http://demo.cerberus-testing.org:28081/Cerberus/TestCaseScript.jsp?test=GUI%20:%20Test%20Management&testcase=0016A

**Comment by abourdon** [comment]
Funny to see last execution is ok ;-) What do you want to test with it?
