### ISSUE TITLE
MySQLIntegrityConstraintViolationException on Datalib update

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1281]
Hello,

I get this exception when trying to update datalib=Theseus_ANDROID_DISC

 The Test Data Library - Sub data that you are trying to INSERT conflicts with an existing one! Please check for duplicates! com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '23157-Title' for key 'IX_testdatalibdata_01' 

The subdata i wanted to update was to BRAND -> Brand and TITLE ->Title
After this error is thrown the subdata is deleted from the datalib.
![2017-04-13 14_14_00-test data library](https://cloud.githubusercontent.com/assets/16339891/25006106/84d340f6-2053-11e7-84b0-46025931a0e5.png)

Can you check?

Cerberus Version : 1.1.12-SNAPSHOT-1128

**Comment by vertigo17** [comment]
This is due to mysql not beeing case sensitive. 
Last commit will fix that. Until there, you have to delete the old one and insert the new one after the save operation.
