### ISSUE TITLE
Can't filter by test on adding test to a campaign

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1283]
Hello,

We noticed that there is a bug on adding tests to a campaing, steps to replicate:
- go to http://192.168.134.17/Cerberus/TestBattery2.jsp
- click to edit battery
- go to test case tab
- click to add TC
- click to filter Test
- click to unchek all tests (selected by default)

This will trigger the following URL:
http://192.168.134.17/Cerberus/TestBattery2.jsp?batteryKey=+mobile_app_android_v6&id=&battery=+mobile_app_android_v6&description=Campaign+for+Tablet+Android+v6&batteryTestcasesTable_length=25&batteryTestcases2Table_length=10&searchField=&unSelectAll=

Page is refreshed and you go back to  http://192.168.134.17/Cerberus/TestBattery2.jsp

Can you take a look?

Thanks and Regards

Cerberus Version : 1.1.12-SNAPSHOT-1128

**Comment by abourdon** [comment]
Seems to be the same as #1279
