### ISSUE TITLE
GUI interface in Internet Explorer

### ISSUE THREAD

**Issue by mbessa** [cerberustesting/cerberus-source#1284]
Hello,

Using Cerberus Online PROD shared by Loic, I notice that after login screen, Cerberus doesn't load in Internet explorer browser. This is also present in current Cerberus version.
Please look at the difference (firefox - right; IE - left)
![image](https://cloud.githubusercontent.com/assets/5825695/25301843/efde3172-2728-11e7-9aa2-17606a61d80a.png)

Cerberus Version : 1.1.12-SNAPSHOT-1118

**Comment by R-Loic** [comment]
Hello Marco,
Your issue is on IE? you switched the two screenshots I think : "(firefox - right; IE - left)"
Could you please give the IE version you use ?

**Comment by mbessa** [comment]
Yes you are correct. IE is the image on the right.
IE version:
![image](https://cloud.githubusercontent.com/assets/5825695/26149621/d5776fa0-3af2-11e7-8a16-6066a0a4fdd4.png)
