### ISSUE TITLE
Why Label has to belong to a System?

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#1285]
Hi,

I tried to use the label affectation by using the Mass Action developed in #1032, and I've got the following warning:

<img width="804" alt="screen shot 2017-04-25 at 11 07 46" src="https://cloud.githubusercontent.com/assets/1511715/25377485/05916f62-29a8-11e7-9609-55d3bdcc77dd.png">

I'm wondering why this constraint is useful. Why Label has to belong to a System?

**Comment by vertigo17** [comment]
In the current model, a label is attached to a system. Labels are not transversal.
Applying a label to a system on a testcase that do not belong to the same system is a source of confusion.
This is why the rule exist.
NB: The same rule already exist when updating a label 1 by 1 (inside the modal). That restriction is consistent to the existing one.

**Comment by abourdon** [comment]
I already understood this rule but my question was : why label has to belong to a system, i.e
 why this contraint had been applied? Actually, it is just a marker used to group test cases, and grouping rule could be done regardless the system. This way, user could create transversal labels

**Comment by vertigo17** [comment]
Just to avoid ending with too many label when selecting them.

**Comment by abourdon** [comment]
Hm, the system notion is confusing regarding the way test case list is displayed (without system).

Thanks for your answers. Maybe we should rethink of how use and display the system notion in order to be more understandable for user.
