### ISSUE TITLE
robot full screen

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1289]
Hi, 
noticed that running a testcase with a robot set to use fullscreen resolution the execution shows 768*529 in screen size.
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=45524420

running the same testcase with a robot set to 1024x768 the execution shows 1024x768
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=45524727

The machine resolution is 1024x768, so should fullscreen or 1024x768 be the same? 

Thanks!

**Comment by bcivel** [comment]
Hello @ruirpr,
Don't really know your config but could it be : 
 768*529 > The real default resolution of the VM
1024x768 > The value set in your rdp client.

Did you set somewhere the default resolution? For any user?

Thanks for the help
Benoit

**Comment by ruirpr** [comment]
Both tests ran with 1024x768 but it does not show that in execution detail. I dont set the default resolution.

**Comment by vertigo17** [comment]
@ruirpr is that bug still valid ?
