### ISSUE TITLE
error on condition but test OK

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1292]
Hi, 
this test execution http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=45760734 have the following error in the condition:
`Testcase Step not executed with loop 'onceIfConditionTrue' following condition 'ifNumericGreater'. Cannot convert %EVENT_FILTER(count)% to numeric.`
But the result is OK anyway. Shouldn't it be FA? 
I had to find a solution to get an error:
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=45804577

**Comment by vertigo17** [comment]
Yes agree.
That should fail the step and report a FA execution status.
I will fix it.

**Comment by ruirpr** [comment]
Hi, 
i have an execution OK with a failed property in a IF
![image](https://cloud.githubusercontent.com/assets/1914659/26500903/b8736942-422f-11e7-83b7-842d9257e06e.png)

Shouldn't it be FA? 
http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=46817673

**Comment by gmoita** [comment]
Problem persists...
