### ISSUE TITLE
set resolution in testcase

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1294]
Hi, 
would it be possible to define resolution at testcase level or to define the robot to use? 

Thanks!

**Comment by vertigo17** [comment]
Yes, we could (using the same rule we have for UserAgent - already defined at testcase level).
The rule would be the same:
If Resolution at testcase level = resolution at robot level --> Test is executed normally.
If only 1 out of the 2 are not empty, we force it at the execution level.
If both are not empty and different, we fail the execution.

Global idea would be that the test is specfic to that resolution. It test a specific behaviour at a given resolution.

Would that be Ok for you ?

NB : Doing it at robot level is not a good idea as robot are choosen at execution level and for most robot where the test is executed, the result should be the same.

**Comment by ruirpr** [comment]
Hi, 
we just discussed this subjec and it would be useful like this: 

![image](https://cloud.githubusercontent.com/assets/1914659/26443411/31c75264-4130-11e7-86c0-97dc78f1e791.png)

Is it possible? 

Thanks!

**Comment by ruirpr** [comment]
Can this feature be already tested in QA? Thanks!

**Comment by vertigo17** [comment]
No not yet.
The UI is ready and you can start to feed the screensize and/or UserAgent in Robot Constrain tab under testcase page.
The engine is not yet modified. Both UserAgent and ScreenSize will fit your rule (TestCase is the master, if not defined we pick it from robot and if still not defined, it will be fullscreen for screensize and real useragent of the browser used for usderAgent)

**Comment by vertigo17** [comment]
Engine is now ready to be tested in QA.

**Comment by ruirpr** [comment]
Hi, 
just tested and it seems to be working as expected. Thanks!
