### ISSUE TITLE
Button disabled in test case script page

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1296]
Hello,
There is an issue with the testcase script page.
When you delete all the steps, you can't create a new one, the button add step is disabled : 

![image](https://cloud.githubusercontent.com/assets/18569182/25744124/81ed3e9a-3198-11e7-9d57-a854ef61276a.png)

Thank you !
Cerberus Version : 1.1.12-1144

**Comment by ruirpr** [comment]
There's a workarround for that. Delete everything in url after the testcase and hit enter.
