### ISSUE TITLE
Filters on TestCaseList automatically refresh the page

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#1297]
Cerberus Version : 1.1.12-SNAPSHOT-1128

When I'm trying to filter test cases on the TestCaseList page, if I uncheck all the the test cases to filter just one test, I cannot do it, as the page automatically refreshes.
This makes it harder to use the filtering, as I don't want to spend 5 minutes unchecking each test on the list, just to have the one I need.

**Comment by R-Loic** [comment]
Hello @gmoita ,

This issue has already been fixed #1279, that's why I asked a deploy of the new release in PRD redoute.
