### ISSUE TITLE
Remove some invariant property database

### ISSUE THREAD

**Issue by bcivel** [cerberustesting/cerberus-source#1298]
IRT , VC, IDW, ICS

**Comment by gmoita** [comment]
What is the purpose of this?
These needs to be on the property database.
Are you just removing it from the scripts that are creating the invariant PROPERTYDATABASE?
Or are you removing data?

**Comment by bcivel** [comment]
Just remove these four value from the database init script.

**Comment by vertigo17** [comment]
We should not modify old SQL.
In my point of view, either we leave them inside database, either we add delete SQL instruction in database maintenance in order to remove them.

**Comment by vertigo17** [comment]
Entries no longuer exist in standard installation.
