### ISSUE TITLE
Release note Cerberus

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1299]
Hello,
Is it possible to have a release note to know what is new on Cerberus for each release ? 

Cerberus Version : 1.1.12-SNAPSHOT-1128

**Comment by abourdon** [comment]
Good idea, I propose to add it to Github & Web site

**Comment by vertigo17** [comment]
Changelog chapter has been created in documentation with 3 section bug/improvement/warning.
Please feed it when performing a comit.
