### ISSUE TITLE
Search step library case sensitive

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1302]
Hello,

When using the search to locate step on library this search is case sensitive, could this be changed to case insensitive?

Thanks and Regards

Cerberus Version : 1.1.12-SNAPSHOT-1128

**Comment by j0hnsa** [comment]
Also would be good if it could search for substrings.

**Comment by vertigo17** [comment]
![selection_179](https://cloud.githubusercontent.com/assets/5342048/26266219/c3488fbe-3ce4-11e7-8e58-44f6e1bc3e21.jpg)

Solved with last commit.
