### ISSUE TITLE
onceIfConditionTrue execution time

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1304]
Hi it looks like the step conditions take a lot of time to execute, can it be faster? 
Thanks!

**Comment by vertigo17** [comment]
Please provide some details.
A condition evaluation could include a property calculation that needs some time to execute but if no complex decode are required it should be few miliseconds.

**Comment by vertigo17** [comment]
I beleive the issue is no longuer happening or you found the origin of the slowness.
Please reopen with the feedback if the issue is still exist.
