### ISSUE TITLE
New feature switchToWindow with URL

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1305]
Hello,
SwitchToWindow uses the title to switch but in my case html page doesn't have a title, is it possible to use an action like SwitchToWindowsActive ?
Thanks !

Cerberus Version : 1.1.13-SNAPSHOT-1150

**Comment by bcivel** [comment]
Hello @R-Loic 
We a no way to know which window is active or not. We get a list of windows and interate on it checking the title.

Could we implement a check on the url of the window?

I mean we keep the action switchToWindow
if we use title=toto, we check the title like today
if we use url=http://toto, we check the url of the windows.

Can it fit for your needs?

**Comment by R-Loic** [comment]
yes, it will fit ! I rename the ticket to match with the implementation

**Comment by bcivel** [comment]
Development is done. 
Documentation completed.
Testcase has been modified accordingly with your spec.
http://demo.cerberus-testing.org:28081/Cerberus/TestCaseScript.jsp?test=ENGINE%20:%20Action&testcase=0009B
Thanks
