### ISSUE TITLE
Button Add property doesn't work

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1306]
Hello,

The button "add property" in testcase page doesn't work on this version could you have a look please?
test case associeted : 
http://demo.cerberus-testing.org:28081/Cerberus/TestCaseScript.jsp?test=GUI%20%3A%20Test%20Management&testcase=0022A
Thank you !

Cerberus Version : 1.1.13-SNAPSHOT-1150

**Comment by ryltar** [comment]
Fixed with my last commit
