### ISSUE TITLE
add testcase to battery filter does not work

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1307]
- Open http://cerberus.siege.red/Cerberus/TestBattery2.jsp?batteryKey=web_theseus_all&id=&battery=web_theseus_all&description=&batteryTestcasesTable_length=100&batteryTestcases2Table_length=10&searchField=&selectAll=

- Write web_theseus_all in the search field and edit the web_theseus_all battery

- go to testcase tab and click on 'add test case'

- write 0143A in the search box

- click in the test filter

- deselect all tests -> ERRROR -> back to battery list

**Comment by bcivel** [comment]
Hello @ruirpr 
This issue is already solved in the 1.1.12 version.
Could you upgrade your version to have it working for you?

**Comment by ruirpr** [comment]
No, I can't. Thanks
