### ISSUE TITLE
Properties - getFromDataLib missing nature

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1309]
Hi,

on a test case properties, if we define a property "Type : getFromDataLib" it not allow us to define the nature of it (if it is STATIC, RANDOM, NOTINUSE...).
The button to expand option doesn't do any action.

![image](https://cloud.githubusercontent.com/assets/14328346/26401003/a02a9528-407b-11e7-9231-f7fb0afd841c.png)

Cerberus1.1.13-SNAPSHOT-1150

Can you please take a look?

Thanks

**Comment by bcivel** [comment]
fixed with my last commit. Should be OK now

**Comment by RobertoAbraul** [comment]
Hi,

now we have the "Nature" field but the other fields are missing (Row limit, number of retrys...).

![image](https://cloud.githubusercontent.com/assets/14328346/26405640/dc7604ec-408d-11e7-9151-8723c67ff1eb.png)

Missing:
![image](https://cloud.githubusercontent.com/assets/14328346/26405561/98fa97aa-408d-11e7-9aad-c00bd1902c69.png)

Can you please check?

Thanks.
