### ISSUE TITLE
Change the queue default Timeout

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1326]
Hello, 

Can you change the default queue timeout (600 000ms) used when the test in not yet connected with Cerberus ? 

It should be interesting to replace it by the **timeout and retries settings** set by the user in the test executions parameters. 

![queue timeout parameters](https://cloud.githubusercontent.com/assets/29098010/26633735/a64ae9d2-4614-11e7-8b7b-d1ce2b7f401c.png)

Thank you !

**Comment by bcivel** [comment]
Hello @Galand-V 
Both timeout have different behavior. 
I would suggest to add a parameter instead of hardcoding 600000ms
Thanks
Benoit

**Comment by abourdon** [comment]
@bcivel why dynamically compute the queue timeout based on the execution one? For instance : execution time + 3s.
In order to fit with execution needs and avoid to wait 600s where execution wants only 5s...

**Comment by bcivel** [comment]
It's not execution that use that timeout, but every action.

**Comment by abourdon** [comment]
Aah yeah I see. Ok so there is no global timeout for an execution.

**Comment by abourdon** [comment]
In addition, it could be great to rename the current Timeout and Retries parameter to be more explicit
