### ISSUE TITLE
When adding an application objet : use the copy past option for screenshot

### ISSUE THREAD

**Issue by Atecna-Qualite** [cerberustesting/cerberus-source#1328]
When adding an application object, the user should be able to copy past the screenshot directly on the "textbox" instead of recording the screenshot as a jpg to upload it from the computer.

Thanks in advance,

**Comment by bcivel** [comment]
Hi @Atecna-Qualite 
Thanks for the contribution.
We'll have a look to that dependency https://github.com/FineUploader/fine-uploader to make the stuff.
Thanks
Benoit
