### ISSUE TITLE
loop with getfromdatalib property

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1329]
Hi, 
found a weird behaviour, I think.
http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=47206955
doWhileConditionFalse
  ifStringContains %AS400_P_AVAILABILITY(L_AVAILABILITY)% L
    step 5.1 there's a query that returns nothing and is forced to continue 
doWhileConditionFalse
  ifStringContains %AS400_P_AVAILABILITY(L_AVAILABILITY)% L
    step 5.2 Testcase Step not executed with loop 'doWhileConditionFalse' following condition 'ifStringContains'. '%AS400_P_AVAILABILITY(L_AVAILABILITY)%' does contain 'L'

Why 5.2 is not executed if the %AS400_P_AVAILABILITY(L_AVAILABILITY)% is the same for both iterations?

Thanks!

**Comment by R-Loic** [comment]
Hello @ruirpr ,

I can see in your test case that the 2 steps are not set with the same conditions, product_1 is modified between the two steps condition
Let me explain : 
Step 1
During the condition operation step, Product 1 is calculated (Random)
condition is OK, step is running
Calculate property => get a new Product 1 (still Random) 
Step 2 condition operation with the new product => KO

For your information, CalculateProperty is used to force a new calculation of the property.
If you remove it from your step, you won't get this behaviour anymore.

**Comment by R-Loic** [comment]
Hi,
Explanation in my last comment. There is no bug for this issue.
