### ISSUE TITLE
New api to get campaign information

### ISSUE THREAD

**Issue by nicodeur** [cerberustesting/cerberus-source#1331]
Hi,

I would like a new api to get information about a campaign.

I need particulary the information of home page to calculate how many tests are implemented : 
![sans titre](https://cloud.githubusercontent.com/assets/6707556/26832105/a6f2df7a-4ace-11e7-95eb-206628ac3cad.png)

Regards,

Nicolas

**Comment by abourdon** [comment]
The new GetCampaignInformation public servlet has been added to get information about a campaign.

More information can be fetch by simply call this servlet without argument.

Regards,
Aurélien

**Comment by abourdon** [comment]
For information, servlet has been renamed to `GetCampaignTestCases` to be more specific

**Comment by abourdon** [comment]
Hi @nicodeur,

After some private discussion, maybe I was wrong with the implementation regarding the issue's description. I propose the following:

Create a public servlet, named GetApplicationTestCases which takes in argument a application name and produces the list of associated test cases with the following attributes:
- Test
- Test Case
- Description
- Application
- Status

Is this specific fits your need? If yes, I will edit the issue's name and description and develop this servlet.

Let me know,
Aurélien

**Comment by nicodeur** [comment]
Hi @abourdon,
 
Yes, i need that to my report.

Thanks for advance,
Nicolas

**Comment by vertigo17** [comment]
Input:
application

Output json with
testCaseList (Array)
    test
    testCase
    description
    application
    status
messageType
message [optional]
helpMessage [optional]

always http : 200

**Comment by abourdon** [comment]
Resolved with last commit.

Note there is no need to explicitly gives the `messageType` because already defined with the response http status.

Please look at #1342 to have more information about public servlet structure.

Regards,
Aurélien
