### ISSUE TITLE
Errors on test campaign page

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1333]
Hello,

On this page http://cerberus.siege.red/Cerberus/TestCampaign2.jsp
if we click to see details of one campaign this error will be seen:
DataTables warning: table id=viewTestcampaignsTable - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3. No other info is displayed.

Also if we click edit only the description tab displays data.

Can you check please?

Regards

Cerberus Version : 1.1.13-SNAPSHOT-1151

**Comment by j0hnsa** [comment]
Also If filtered by name with the searchbox Multiple filters will appear with the same filter.

**Comment by vertigo17** [comment]
can you provide some screnshots.
I could not reprocude the issue.

**Comment by j0hnsa** [comment]
Hello @vertigo17 

It seems to happen randomly not all the time, but here's the screenshot:

![2017-06-09 14_34_52-testcampaign](https://user-images.githubusercontent.com/16339891/26977769-f2d5679c-4d20-11e7-83a5-0e1af03eb9f7.png)

Regards
