### ISSUE TITLE
Support of Internet Explorer ?

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1336]
Hello,

I try to launch test on IE 11, from cerberus 1.1.12
Internet Explorer start, loginPage is loaded, but :  
-   no elements can be found (id, xpath, class ...)
` Failed to wait because could not find element 'id=lst-ib'
`
- the browser is not closed at the end.**

Do you succeed with IE ?

Thanks

**Comment by mbessa** [comment]
duplicated with: https://github.com/cerberustesting/cerberus-source/issues/1284

**Comment by vitoo** [comment]
Nope, it's not about loading cerberus, but running with selenium/Internet Explorer

**Comment by vitoo** [comment]
Hellon

Any info @bcivel @vertigo17  ?

Thank you

**Comment by bcivel** [comment]
Hello @vitoo 
Yes, I can confirm it works on IE 11.
I you set the execution parameter `getPageSource` to 1 or 2, can you see the element you search on it?
Which version of iedriver do you use?

**Comment by vitoo** [comment]
IEDriverServer.exe   v3.4.0.0
IE 11?0.10240.17443
What is your version ?

Did you start IEDriver as a node of selenium hub ?

` java -Dwebdriver.ie.driver=IEDriverServer.exe -jar selenium-server-standalone-2.53.0.jar -port 5557 -role node  -browser "browserName=internet explorer,version=11,platform=WINDOWS,maxInstances=1"`

getPageSource : 

`Action Failed. Unable to get browser (WARNING: The server did not provide any stacktrace information)
`

**Comment by vitoo** [comment]
Fixed using this : http://www.michael-whelan.net/selenium-webdriver-and-ie11/

(security zone parameter)

**Comment by vitoo** [comment]
Well, typing text is super slow (1 letter / 5 seconds)

do you have this behaviour ?

**Comment by vitoo** [comment]
Using IEDriverServer 32 bits fix the slow typping isuse !

**Comment by bcivel** [comment]
I use IE DriverServer v2.39 and IE 11.0.9600.16426 directly (Not behind a hub) and selenium 2.45.

But you're right, problem seems to have been introduced in a more recent selenium version.
So thanks for your investigation and your comments
