### ISSUE TITLE
Wrong error message in "Behavior or value expected" field

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1337]
Hello,
I have an issue with the following field in test case page : 
![image](https://user-images.githubusercontent.com/18569182/27037135-52681cd2-4f87-11e7-80cc-8c3d57707104.png)
It returns this error when the text has a special character (which is wrong): 
![image](https://user-images.githubusercontent.com/18569182/27037295-c75e92fa-4f87-11e7-9c6d-577c8543529e.png)
Same text without color or special character was OK. (with notepad)
Could you have a look to display a good error message ?
Thank you !

**Comment by vertigo17** [comment]
I guess this is fixed.
I can no longuer reproduce.
