### ISSUE TITLE
Rename fields to make Cerberus more "User friendly"

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1340]
Hello,

I propose to rename the following fields : 
![image](https://user-images.githubusercontent.com/18569182/27043648-23aeb220-4f9b-11e7-9717-d3beef294578.png)
"Test case" would be : "Reference" or "TestCase ID"
"TestCase ShortDescription" would be : "TestCase" 

A new user always fills the field "TestCase" with the scenario but this one can't be modified (In grey on the screenshot). And we sometimes need to modify the scenario.
The good behavior is to use references for this field which don't need to be modified (0000A for example).
So why let the name "Testcase" if we use it for a reference ?
Is this modification possible ?

Thank you !

**Comment by abourdon** [comment]
Hi @R-Loic,

IMHO, TestCase to Reference or Technical Identifier sounds good to me.

However, TestCase short description should not be renamed as TestCase because we will lost the main information of this field.

I think @vertigo17 or @bcivel could better help to this one.

Aurélien
