### ISSUE TITLE
How to write a Cerberus public servlet

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#1342]
Hi all,

I would like to enumerate current recommandations to write a Cerberus public servlet. In addition, I propose some improvements. Idea is to define a way to write Cerberus public servlets to provide an API to formalise these specifications and help developer to create new public servlets.

# Current specification

## Global recommandations
  - Input/Output charset: JSON UTF-8
  - Each servlet is associated to a fixed version number
  - Servlet naming strategy is  the following:
     - First servlet version: `<name>`, for instance: `GetSomething`
     - Second and more servlet version: `<name>V<version number in 3 digits>`, for instance `GetSomethingV002`. Note that sometimes, this naming strategy is also used for the first servlet version. This case, version is equal to `V000`, for instance `GetSomethingV000`
  - Only GET and POST HTTP methods are used. Even if these HTTP methods mean something different (normally GET to read and POST to update), servlet produces the same result whatever the HTTP method used. Thus, there is only one set or parameters defined whatever the HTTP method used.

### Before anything
  - Call the ServletUtil#servletStart()
  - Call the ILogEventService#createForPublicCalls()

### During request parameters parsing
  - For each parameter: check its validity and produce an error message with a description of what's was wrong.
  - Add an helper message to the error message

### During request processing
  - Produce an immutable and permanent result, whatever data model changes. Result must be a mapping between servlet output contract and current Cerberus' data model. Changing the result cause a creation of a new servlet version

### When process successfully ends

  - HTTP status: 200
  - Output structure:
```
{
  "messageType": "OK",
  "message": "Request has been successfully processed"
  <additional servlet's specific attributes>
}
```

### When an error occurs

  - HTTP status: 200
  - Output structure:
```
{
  "messageType": "KO",
  "message": <Error reason phrase>
  "helpMessage": <The help message phrase with an explanation of what server does and an enumeration of its parameters>
}
```

# Some improvements to the current specification

Hereafter some propositions I would like to add to the current specification

## Global recommandations
In addition to the current global recommandations, I would like to add:
  - Each servlet can react to the `help` query parameter and produce the helper message
  - There are two types of servlets: "Getable" and "Postable". Getable servlets will be used to only read data, while Postable servlets will be use to write to Cerberus' data. Thus, no more use of both GET and POST HTTP methods. Read-only servlets will be reachable via GET, while write servlets will be reachable via POST (and could require an authentication if necessary)
  - Servlet naming strategy could always including the version: `<name>V<version>`. In addition, no more restriction on the number of version number digits. For instance: `GetSomethingV1`, `GetSomethingV2`, ...

### Helper message

I would like to completely rewrite helper message to follow the following structure:

```
"serviceInfo": {
    "name": <The servlet's name>
    "version": <The servlet's version>
    "description": <The servlet's description>
    "usage": {
      "method": [GET|POST]
      "parameters": {
         "query" : {
           <query parameter #1>: <description of the query parameter #1>,
           <query parameter #2>: <description of the query parameter #2>,
           ...
        },
        "body" : {
           <body parameter #1>: <description of the body parameter #1>,
           <body parameter #2>: <description of the body parameter #2>,
           ...
        },
      }
    }
  }
```

Explanations:
- Helper message is now JSON structured. This way, we explicitly define mandatory parameters of a public servlet (name, version, description and parameters)
- Helper message has been renamed from `helpMessage` to `serviceInfo` because message is more than a simple helper message:  We send information about servlet to user, including the way to use it

### When process successfully ends

  - HTTP status: 200
  - Output structure:
```
{
  <additional servlet's specific attributes>
}
```

Explanations: No more `messageType` and `message` attributes because we always know operation has been successfully done because of 200 HTTP status.

### When an error occurs

  - HTTP status: !200
  - Output structure:
```
{
  "reason": <Error reason phrase>
  "serviceInfo": {
    "name": <The servlet's name>
    "version": <The servlet's version>
    "description": <The servlet's description>
    "usage": {
      "method": [GET|POST]
      "parameters": {
         "query" : {
           <query parameter #1>: <description of the query parameter #1>,
           <query parameter #2>: <description of the query parameter #2>,
           ...
        },
        "body" : {
           <body parameter #1>: <description of the body parameter #1>,
           <body parameter #2>: <description of the body parameter #2>,
           ...
        },
      }
    }
  }
}
```

Explanations:
- No more `messageType` attribute because we always know operation has not been successfully done because of non 200 HTTP status.
- `message` attribute has been renamed to `reason` to be more explicit
- We always add the service information message

@bcivel, @vertigo17 what do you think about these specification (current recommandations and proposition) ? Feel free to comment, by adding currently recommandation I could forget and challenge my propositions. Idea is to clearly define the way to write a public Cerberus web service. This way we could help developer to create new ones.

Regards,
Aurélien

**Comment by bcivel** [comment]
Hi @abourdon 
Thanks for this contribution. 
Could you include the first part (the current standard) into a contributing file on the repository?

About you proposal of new standard, what you propose sounds good to me. However it mean to define a new version on all our public servlet because output format is quite different.

**Comment by abourdon** [comment]
Hi @bcivel,

Ok I will add the current specification into a file

About version: you mean currently naming strategy as: <name><version>? I forgot these requirement, I edit the issue description.

**Comment by abourdon** [comment]
A first implementation is available from the `org.cerberus.servlet.api.zzpublic` package. A concrete example is given by the new GetTestCases servlet which has been developed for #1331.

I don't think it is necessary to let this issue open only because there is no centralised documentation on how to write public servlet. All documentation can be found from this issue and the Java documentation of related `org.cerberus.servlet.api.zzpublic` classes

Regards,
Aurelien
