### ISSUE TITLE
can't add a library step

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1345]
Hi, 
this just happened:
- added a library step to testcase and did not saved
- removed usetep from testcase and confirmed change, so testcase reloaded without the previous added step as exepcted
- now i cant add any library step

![image](https://user-images.githubusercontent.com/1914659/27326751-4725d94a-55a4-11e7-91bf-7e91c18419df.png)

**Comment by ruirpr** [comment]
It looks like logout and login into cerberus solved the issue

**Comment by vertigo17** [comment]
I guess an intermittent network issue.
