### ISSUE TITLE
Multiple test-cases executed together

### ISSUE THREAD

**Issue by SeniorCanard** [cerberustesting/cerberus-source#1349]
Hello,

I have an issue with several test cases. 
When executed alone : everything is OK. 
But, executed together : nothing happen. 
    I click the "add to queue and run" button 
    The "Execution reporting" page show every test case as "NE"

Other tests cases works perfectly fine together. 
I don't see any differences between the running test cases and the others.

FYI : following issue describe the same error, but the answer is not the solution here (or I did it wrong!)
https://github.com/cerberustesting/cerberus-source/issues/1205

Do you have an hint?  

Thank you.

**Comment by abourdon** [comment]
Hi,

Seems to be same as #1265. Did you check the value of your `cerberus_url` parameter? (inside the Admin/Parameters table).

Aurélien

**Comment by vertigo17** [comment]
Do you see them in execution queue page ?
What does the message say ?

**Comment by vertigo17** [comment]
Please confirm the executions appears in execution queue and report the associated return message.

![image](https://user-images.githubusercontent.com/5342048/27659229-f751473c-5c52-11e7-9eea-eb1efd632615.png)

If 404 is reported, the parameter need to be change to a value that can be accessed from Cerberus itself.

On latest version the PE status in reportingByTag redirect to queue page filtered on tag.

**Comment by SeniorCanard** [comment]
This is what I get when trying to execute these Test Cases. 
![01](https://user-images.githubusercontent.com/27861047/27680761-2f752182-5cbd-11e7-82d9-34ae848bb215.png)
![02](https://user-images.githubusercontent.com/27861047/27680735-0f7c33ca-5cbd-11e7-8027-8c6a684d5d41.png)

**Comment by abourdon** [comment]
Hi @SeniorCanard, you got an unexpected server error. Please give us server logs in order to have more details about it

**Comment by vertigo17** [comment]
You can start by getting the view on Comment.
We only see the beginning of the message.
Please include the popup on the screenshot or hide columns so that full message is displayed.
I will change the default column layout so that we can see more comment.
I will also add the detail information of the Queue execution in case it is really big.

**Comment by SeniorCanard** [comment]
Following, the requested infos : 

![03](https://user-images.githubusercontent.com/27861047/27681438-84b6344a-5cbf-11e7-853c-24f0936670a6.png)
[04.txt](https://github.com/cerberustesting/cerberus-source/files/1111541/04.txt)
