### ISSUE TITLE
Forgot password page improvements

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#1350]
Hi,

Since #1346, we have a new design for our login page and forgot password page (thanks @nicodeur ;-))

This PR has opened some questions about current forgot password page features and the following improvements have been proposed:

- Add title and text on form to precise to user the nature of this form. E.g., : "Please enter your username. An email will be sent to your associated email address with a link to reset your password"
- Rename "Forgot password" button to "Send me an email"
- Rename "Homepage" button by "Cancel"
- Prefer use Javascript to handle action on the new "Cancel" button in order to directly go back to the login page

What do you think about this?

I propose to assign @nicodeur to this issue as it has just been added as Cerberus member.

Regards,
Aurélien

**Comment by Galand-V** [comment]
#1353 maybe could be implemented at the same time even thought this is not a priority
