### ISSUE TITLE
Cerberus -> Appium-Android still work for you ?

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1351]
Hi,

My android tests started to not work while in Cerberus 1.1.11 

Apk app is launched, but no commands are received by appium. 

So, is it an isolated case or you have the same problem ?

Here are my capabilities : 
![image](https://user-images.githubusercontent.com/995694/27490084-48a562ea-583d-11e7-97de-a338d75927c2.png)

Thank you

Cerberus Version : 1.1.12-1144

**Comment by vertigo17** [comment]
No changes has been done on Cerberus that could explain this issues.
@bcivel any idea ?
@ruirpr, can you help sharing th cnf we use to make it work ?

**Comment by j0hnsa** [comment]
Hi @vitoo 

I believe automation name is required and maybe appWaitActivity (had myself a similar problem and may be the same), if you can share some appium logs maybe will be easier to identify the problem, anyway the configuration used by myself looks something like this:
![2017-06-29 09_12_44-robot](https://user-images.githubusercontent.com/16339891/27677915-39cee742-5cab-11e7-9f70-7294989d70c4.png)

Regards

**Comment by vitoo** [comment]
Fixed by upgrading selenium 2.53 -> 3.0.1 ... cool ! 😎 

Here is my how i start appium : 

```batch
start node "C:\Program Files (x86)\Appium\node_modules\appium\bin\appium.js" --nodeconfig "C:\mobile_app\selenium.json" -p 5554 
```
The nodeconfig selenium.json : 
```json
{
  "capabilities":
      [
        {
		  "deviceName": "emulator-5556",
          "browserName": "ANDROID",
          "version":"5.0",
          "maxInstances": 1,
          "platform":"ANDROID",
		  "platformName":"ANDROID"		  
        }
      ],
  "configuration":
  {
    "cleanUpCycle":2000,
    "timeout":30000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "url":"http://10.129.21.49:5554/wd/hub",
    "host": "10.129.21.49",
    "port": 5554,
    "maxSession": 1,
    "register": true,
    "registerCycle": 1000,
    "hubPort": 4444,
    "hubHost": "10.129.21.49"
  }
}
```

**Comment by vitoo** [comment]
Can you launch android campaign without problem ?

If i start one test case at a time, i have every tests OK

If i start campaign, i got 70% of tests KO

With a "failed to wait", it looks like it doesnt wait 7900 ms but 0 ms : 

![image](https://user-images.githubusercontent.com/995694/27740098-0f4b6926-5db1-11e7-800b-63ee36e34a6b.png)

___

I tried to start Android campaign on localhost cerberus, different problem here, the campaign doesnt start at all, server log : 

```
Info:   2017-06-30 16:13:02 WARN  ExecutionWorkerThread:332 - Execution in queue 71 has finished with error
org.cerberus.engine.entity.threadpool.ExecutionWorkerThread$RunProcessException: An unexpected error occurred during test case execution: 404 (Not Found)
	at org.cerberus.engine.entity.threadpool.ExecutionWorkerThread.runExecution(ExecutionWorkerThread.java:380)
	at org.cerberus.engine.entity.threadpool.ExecutionWorkerThread.run(ExecutionWorkerThread.java:326)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.client.HttpResponseException: Not Found
	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:69)
	at org.apache.http.client.fluent.Response.handleResponse(Response.java:90)
	at org.apache.http.client.fluent.Response.returnContent(Response.java:97)
	at org.cerberus.engine.entity.threadpool.ExecutionWorkerThread.runExecution(ExecutionWorkerThread.java:370)
	... 6 more
```

**Comment by vitoo** [comment]
Looks like its fixed when setting pool size to 1, i only got 1 android node 😉 

https://github.com/cerberustesting/cerberus-source/issues/1400
