### ISSUE TITLE
Reset Password functionality

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1353]
Hello, 

It seems like the reset password functionality is not working as expected on internet Explorer : 

The wanted fields are : 
- New Password 
- New Password confirmation

![image](https://user-images.githubusercontent.com/29098010/27534071-06910c3a-5a66-11e7-97f5-5ee40d508ee3.png)

(functional on chrome / Firefox) 

The current field on IE are the following : 
- Current Password 
- New Password
- New Password Confirmation

![image](https://user-images.githubusercontent.com/29098010/27534085-18caed30-5a66-11e7-9dfc-c565456470cd.png)

Thank you

**Comment by nicodeur** [comment]
Hi,

Problem was solved by @Ronpiche on this [commit ](https://github.com/cerberustesting/cerberus-source/commit/d0818fe621c415c55cb32e0323abfb2eab6e0214)

Regards,

Nicolas
