### ISSUE TITLE
Let User Rename "Test"

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1354]
Hello Everyone, 

The question has already been asked few years ago :  #289  .  But it seems important to at least think about it again. 

When you are building an architecture, having the possibility to change the test name could be a real improvement. 

It sure depends on the development effort needed for this feature @bcivel

**Comment by gmoita** [comment]
Even if it can be done, please take into account that this has some risks.
First, not everyone should be able to rename tests (only Admin and TestAdmin should be able to do it).
Second, doing this can cause a huge impact on the database as it has foreign keys (example: I have a test that is running more than 20 thousand times a day, with all the other table dependencies; changing this test takes almost half an hour to run).

**Comment by Galand-V** [comment]
Sure, this should be reserved to admins and with a clear warning message with all the impacts. 

To my point of view, this functionality would be used at the begging of a project. When you created several Test Cases but not enought to have a process depending on it (ex : production go/no go).

**Comment by R-Loic** [comment]
Hello,

I propose to let user admin user rename Test, but it would be great if this modification was not applied on the executions tables. In that case the executions of all test cases would be lost. A warning message would be displayed to warn the user before validation.
I agree with @Galand-V , for the newer tests it will avoid to re-create all test cases created, just to rename the Test.
