### ISSUE TITLE
Weird display of the ExecutionPending table id's checkboxes

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#1355]
Hi,

Strange display on the ExecutionPending table, at the id column. Checkboxes are displayed with three dots into it. These dots avoid me to click on it. Is it just from my side?

<img width="314" alt="screen shot 2017-06-27 at 14 17 16" src="https://user-images.githubusercontent.com/1511715/27587286-154d7464-5b44-11e7-8b54-827f1fc76a57.png">

Regards,
Aurélien

**Comment by Galand-V** [comment]
Hello @abourdon, 

Clear for me in the "execustions in queue" page. 
![image](https://user-images.githubusercontent.com/29098010/27587833-33847098-5b46-11e7-9b78-a6b6534d0d78.png)

**Comment by abourdon** [comment]
What kind of browser and OS do you have?

Actually, I'm on MacOS and facing this issue when using Chrome but everything is good with Safari...

**Comment by Galand-V** [comment]
Windows 10 / Firefox 54.0  is working great. 

I have the same issue as you got on Windows 10/ Chrome 59.0.3071.115 : 
![image](https://user-images.githubusercontent.com/29098010/27594747-f2baaa72-5b5a-11e7-9611-6ff484ebc3ab.png)

**Comment by abourdon** [comment]
Ok so issue seems to be present on Chrome. I set it to a bug
