### ISSUE TITLE
Divide up some informations according to the selected SYSTEM

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#1358]
Hi,

in our use of Cerberus, we realize the the rights allow to a user, and the permissions are not enough.

Some teams are using Cerberus for different tests (mobile and web for instance). To give them a different space to work, we use the SYSTEMS. 

In our example, one for the WEB and another for the AMGP (our public android application).
The problem is that everybody (whatever SYSTEM is allow to a user), can see all the test cases, all the tests, all the application objects, and be able to run every tests.

We already met some problems of duplication of a web test in the AMGP SYSTEM,...

Is that possible in Cerberus to make visible only the things that are linked to its SYSTEM?
(I mean, hide all the applications of another SYSTEM, hide all the test and test cases of these applications, hide all the application objects created for these applications...)

Thanks ;)

Cerberus Version : 1.1.12-1144

TODO

- [x] Only display in combo the system available from user
- [x] allow multiple selection of systems inside combo
- [x] filter testcase list from combo
- [x] filter testcase on TestCase script from combo
- [x] filter applications from combo
- [x] filter executions from combo
- [x] filter datalib from combo
- [x] filter service from combo
- [x] filter label from combo
- [x] filter environments from combo
- [x] filter objects from combo

- [x] filter Tag from combo for mutiple system selection
- [x] filter Datalib for mutiple system selection
- [x] filter Labels for mutiple system selection
- [x] filter executions for mutiple system selection
- [x] filter Applications for mutiple system selection
- [x] filter Applications Object for mutiple system selection
- [x] filter Services for mutiple system selection
- [x] filter Integration Status for mutiple system selection
- [x] filter Environment for mutiple system selection
- [x] filter Build Revision Definition for mutiple system selection
- [x] filter Build Content Definition for mutiple system selection
- [x] filter Build Batch Definition for mutiple system selection and rename to Event

**Comment by cassarreb** [comment]
Hi :)

Has there been any progress on this issue please?

Thanks.

**Comment by glassalle59** [comment]
Any news ?
