### ISSUE TITLE
Do not select all the countries by default in the test case's creation

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#1360]
When we create a new test case, all the counties are selected by default:
<img width="1269" alt="capture d ecran 2017-07-04 a 10 37 57" src="https://user-images.githubusercontent.com/14962879/27822153-fbe5ac24-60a4-11e7-89f3-5c27852ee258.png">

For our utilisation, this means that a new test cases can be executed on every "environment" or for every teams. 
In facts, we could have a different version of our applications in differents QA & DEV environnements. Depends of the Feature Team which working on it.

Is it possible to make all the countries unselected by default? like following : 
<img width="1270" alt="capture d ecran 2017-07-04 a 10 38 17" src="https://user-images.githubusercontent.com/14962879/27822273-6107a0da-60a5-11e7-80b8-0ce629fae46a.png">

Thanks.

**Comment by bcivel** [comment]
Hi @ping0uin ,
For our needs, it's better to have them all selected by default.
I propose to set a parameter to be able to tune the default behavior.
Thanks for the contribution

**Comment by ping0uin** [comment]
sounds enough for us.
Thanks 👍
