### ISSUE TITLE
DataLib : Acces from properties

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1363]
Hello, 

It would be interesting having access to the datalib from the properties of a testCase and have the possibility to edit the lib.

![project_datalib_edit](https://user-images.githubusercontent.com/29098010/27901702-572614e0-6233-11e7-9bcd-ecbf244d4437.jpg)

Selecting the "NewDataLib" would automaticaly open the " Create Data Lib" window.

**Comment by vertigo17** [comment]
duplicate from #747

**Comment by ryltar** [comment]
You can now use autocompletion to find a datalib and edit if datalib exist.

![autocomp](https://user-images.githubusercontent.com/13577630/30743219-02e6af5a-9f9d-11e7-83be-41f07fbd3bfe.PNG)

And you can create the datalib if don't exist

![create](https://user-images.githubusercontent.com/13577630/30743526-4f841018-9f9e-11e7-824a-30d3736bfbe7.PNG)

Same for Application Object : 

Modify 

![objectmodify](https://user-images.githubusercontent.com/13577630/30747844-c0a1f0ca-9fae-11e7-8942-c7bf9a5f85c0.PNG)

Add

![objectadd](https://user-images.githubusercontent.com/13577630/30747767-835ecd0a-9fae-11e7-909c-bfe9ca63f2d7.PNG)
