### ISSUE TITLE
Autocompletion for callservice action

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1366]
Hello,

It would be great to have autocompletion for this field (CallService action).
![image](https://user-images.githubusercontent.com/18569182/27963971-eee2be10-6336-11e7-9345-4d67df80e97f.png)
for example with the syntax %service...
Or a field like :
![image](https://user-images.githubusercontent.com/18569182/27964176-ad3593f6-6337-11e7-90f3-d050925589c4.png)
I have to open a new windows with service library page to remenber the name of the service.
Thank you

**Comment by ryltar** [comment]
You can now call a service with the syntax %service. 

If the service exist, you will have this button and when you click on it, it will open a modal to modify the service

![servicemodify](https://user-images.githubusercontent.com/13577630/30750208-107ba972-9fb6-11e7-8e0e-3d6f9b8d3829.PNG)

![servicemodify1](https://user-images.githubusercontent.com/13577630/30750214-13780bf2-9fb6-11e7-8b7f-7840b8eec7d2.PNG)

Same if service doesn't exist

![serviceadd](https://user-images.githubusercontent.com/13577630/30750289-56492db2-9fb6-11e7-9350-9c4aadd196ea.PNG)

![addservice](https://user-images.githubusercontent.com/13577630/30750295-5b6afa46-9fb6-11e7-8b1c-024a4cb082a7.PNG)

Don't use this now , it doesn't work yet. i must allow the engine to find the correct service with this syntax (%service.toto%)

**Comment by vertigo17** [comment]
@ryltar can we share on that ?
I don't understand the use of adding %service.???% and prefer to clean it before next release.
