### ISSUE TITLE
Get the focus on the new property

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1369]
Hello, 

Can you change the focus for new properties ? 

Current behaviour  : 

1) click on new property 
2) scroll to the bottom 
3) edit the property 

=> with 2 or more properties, you do not see if you created a property field

Wanted behaviour : 

1) click on "new property" 
2) The focus is on the new property field

=> Seems clearer for users

![image](https://user-images.githubusercontent.com/29098010/28008903-a9f521ec-6559-11e7-8bb8-c6ee296acf1d.png)

**Comment by bcivel** [comment]
@Galand-V 
Should be fixed with my last commit.
Enjoy
