### ISSUE TITLE
Change title / H1 for the Test Case page

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1370]
Hello,     

Can you change the title / H1 to  "Edit Test Case" ? 

![sans titre-2](https://user-images.githubusercontent.com/29098010/28011755-b350adec-6563-11e7-95bb-5aef8eba62a4.jpg)

**Comment by vertigo17** [comment]
Edit test case is ambigious as there are 2 data that define the test case.
The 'header' data that correspond to the modal and the 'script' data that correspond to list of steps/action/control + properties.
 
What I propose is to clearly distinguis both area of data by renaming 
Edit Test Case --> Edit Test Case Header (that opens the modal)
Keep 'Edit Test Case Script' as it is.

Making sure that 'Edit Test Case' is replaced by any of the 2 options.

**Comment by vertigo17** [comment]
Labels has been corrected.
