### ISSUE TITLE
Properties sorting : left panel != than right panel

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1371]
Hello, 

Special characters seems to have a different behaviour for the sorting properties process from the left /right panel. 

![sans titre-1](https://user-images.githubusercontent.com/29098010/28012299-a192dd12-6565-11e7-9f77-c50ea84dbb75.jpg)

**Comment by Ronpiche** [comment]
Seems to be corrected on the more recent version
