### ISSUE TITLE
Apply the "delete style left panel" from steps to properties

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1372]
Hello, 

When deleting a step the left panel is colored in red. It is not visible for properties. Can you apply the same style ? 

![sans titre-4](https://user-images.githubusercontent.com/29098010/28012584-885d6f78-6566-11e7-913e-d7a0d4b7cdf0.jpg)

![image](https://user-images.githubusercontent.com/29098010/28012580-807398dc-6566-11e7-80b8-795498403c35.png)

**Comment by nicodeur** [comment]
Hi @Galand-V 

I just test it, it's already fix on last version !

Regards
