### ISSUE TITLE
Executions in queue page : change sorting setting

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1373]
Hello, 

I noticed that the sorting was ascendent in the queue : The smaller id is placed first (older tests)
Can you change the setting, so we can see the latest id first (new tests) ? 

It should be clearer for user to see the latest executions

Thank you,

**Comment by bcivel** [comment]
Hi @Galand-V 
Agreed. It will be consistent with the execution table.
I don't know if you noticed but you can save the sorting setting with the table configuration, in case you change your mind :-)
