### ISSUE TITLE
"No such session"

### ISSUE THREAD

**Issue by SeniorCanard** [cerberustesting/cerberus-source#1374]
Hello,

I'm testing a feature : I complete a form and want to "verify element present" on a div appearing after completing the form. 
I'v tried many thing but the TC is always "FA" with the following text :
![fa01](https://user-images.githubusercontent.com/27861047/28019899-c7d5328c-6582-11e7-9def-05cf4313ef89.png)
Do you know where this error keep coming from ? 

Thanks,

**Comment by bcivel** [comment]
Hello @SeniorCanard 
From your logs, I can see your browser seems to be chrome v57+ and your chrome driver is 2.27 and selenium 3.1.0.

That can be the origin of the error. 

Please, notice that there is a strong relation between the browser version, the chromedriver and the selenium version. If you upgrade your browser, most of the time, you have to upgrade the full stack.

I close that issue but please reopen if the upgrade the recommended version doesn't solve your problem.
https://sites.google.com/a/chromium.org/chromedriver/downloads
