### ISSUE TITLE
Give the possibility to import several steps

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1376]
Hello, 

It would be interesting when clicking on "add Step" to have the possibility to import several steps in the same time. 

The click order would determine the positioning of the steps. 

![sans titre-1](https://user-images.githubusercontent.com/29098010/28055912-501f5e36-661b-11e7-8617-37a46a4313c5.jpg)

**Comment by vertigo17** [comment]
duplicate of #1241
