### ISSUE TITLE
Can't launch campaign

### ISSUE THREAD

**Issue by SeniorCanard** [cerberustesting/cerberus-source#1377]
Hello,

I created new batteries and a new campaign (with the same parameters than existing and running ones).
But the "run test case" screen keep crashing (following picture).

Do you have an hint? 

Thanks

![run test case crash](https://user-images.githubusercontent.com/27861047/28070902-bdb30a50-664e-11e7-83d3-fbad9ca0c0ce.png)

**Comment by vertigo17** [comment]
Can you provide the output of:
ReadCampaign?battery=true&parameter=true&label=true&testcase=true&campaign=campaignname
replacing campaignname by the name of your campaign

As well as:
/ReadCampaignParameter?campaign=campaignname
and
/ReadTestCase?campaign=campaignname

Thanks.

**Comment by vertigo17** [comment]
I beleive the bug no longuer exist so I close it.
Don't hesitate to reopen providing some more detail if it is not the case.
