### ISSUE TITLE
Is Select action working ?

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1378]
Hi,

i'm doing 

openurl https://developer.mozilla.org/fr/docs/Web/HTML/Element/select

select / id=select / valeur1

Result : Failed to wait because could not find element 'id=select'!

version : Cerberus1.1.12-1144

**Comment by TsunaDev** [comment]
Hey,

did you try using XPath instead of a simple id ? It's quite more efficient on big pages

**Comment by vitoo** [comment]
`Failed to wait because could not find element 'xpath=//select[@id='select']'!`

**Comment by bcivel** [comment]
Hi @vitoo 
Yes it's still working.
Your element is under an iframe :-)
Cheers
Benoit

**Comment by vitoo** [comment]
yes, but no iframe in my real test case

Try : 

open url : https://norautofr-re7-metier-live.elosi.com/INTERSHOP/web/WFS/NI-NOFR-Site/fr_FR/uas-mobile-b2c-web-shop/EUR/Default-Start
click class=bt-menu
click data-cerberus=car-header-link
select id=CarselectorSearch option=#tab-vehicule

`Failed to wait because could not find element 'id=CarselectorSearch'! -- Execution forced to continue.`

So it can select option of this select

but i can type in the input just below

**Comment by bcivel** [comment]
Hi @vitoo 
Could you try using 
`select id=CarselectorSearch value=#tab-vehicule`
instead of 
`select id=CarselectorSearch option=#tab-vehicule`

Thanks
Benoit

**Comment by vitoo** [comment]
It's written like this : 
![image](https://user-images.githubusercontent.com/995694/28120952-ec39e4ea-6719-11e7-8c33-23629cb6ccf6.png)

not correct ?

**Comment by bcivel** [comment]
Could you try with `value=#tab-vehicule` please?

**Comment by vitoo** [comment]
Still the same error : `Failed to wait because could not find element 'id=CarselectorSearch'!`

Even if i do a click on id=CarselectorSearch, it doesnt find element, weird thing !

I've found a workarround in JS : `$("#CarselectorSearch").val('#tab-vehicule').change();`

**Comment by bcivel** [comment]
Could you set the parameter getPageSource to 2 ('each Action') and parse the source recorded to confirm button is present when selenium is trying to do the action?

**Comment by vitoo** [comment]
yes CarselectorSearch is present https://gist.github.com/vitoo/0a6c5dbec8bf5102fd1ea8810fec183e

**Comment by vitoo** [comment]
it must be because the web app trigger a ton of javascript that conflict with selenium JS 

So using JS here as workaround
