### ISSUE TITLE
How can a XCUIElementTypePicker value can be selected?

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1383]
Hello,

I tried to use select but Cerberus is expecting a <select>. Click doesn't work either as the element cant be clicked as it is not visible.
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=48577955

Can you tell me how can it be done?

Regards

Cerberus Version : 1.1.13-SNAPSHOT-1151

**Comment by bcivel** [comment]
Hello @j0hnsa 
Could you try to use `type` for that action?

Anyway, could you tell why this element is not visible?
Thanks
Benoit

**Comment by j0hnsa** [comment]
Hello @bcivel ,

At that moment the app had a really small TypePicker but it was redesigned recently and I don't have this problem anymore, and so can be closed this issue,

Thanks and Regards
