### ISSUE TITLE
How can we add a database connection pool while using docker ?

### ISSUE THREAD

**Issue by TsunaDev** [cerberustesting/cerberus-source#1384]

**Comment by bcivel** [comment]
Hello @TsunaDev 
You can create it through glassfish administration console (Port 14848).
The glassfish configuration is saved in an external folder (data). 
So Connection pool will be kept.

**Comment by TsunaDev** [comment]
And with that I can connect any mysql (for example) database on the server and then on cerberus ? Or is it only local databases ?

**Comment by vertigo17** [comment]
The connection pool can connect any type of database (as long as it has some jdbc driver to access it) on any server (can be local or remote).
There are no restriction.

**Comment by TsunaDev** [comment]
Ok thanks !

I've another question about it, how can I had databases connection drivers ?

**Comment by vertigo17** [comment]
I am not an expert of docker but from glassfish point of view, just put the jar file into glassfish/lib/
Then restart Glassfish and configure the database connecting glassfish administration console (Port 14848).
