### ISSUE TITLE
VerifyElementPresent with picture // Sikuli

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1385]
Hello,

The control VerifyElementPresent doesn't work when used with a picture.
Is it already implement? If not, could you pleae add this feature ?
Currently it doesn't work (click on an element => OK and verify same element is present => KO)

![image](https://user-images.githubusercontent.com/18569182/28272164-efc737d0-6b0a-11e7-9fed-6c2191f4d9de.png)
 
Thank you

**Comment by bcivel** [comment]
Should be fixed in the last version
