### ISSUE TITLE
Make the search step not case sensitive ?

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1387]
Hi,

it could be easier if the "import from library" search step were not case sensitive 

If i want to import the SKU related step, i cant find them with "sku" 

![image](https://user-images.githubusercontent.com/995694/28306457-a81b5926-6b9f-11e7-8d97-42226f820210.png)

Thanks

**Comment by vertigo17** [comment]
Feature already implemented in latest version.

![2017-07-18 10_15_07-test case](https://user-images.githubusercontent.com/5342048/28307135-224afbb4-6ba2-11e7-8a53-6a3339f1517c.png)
