### ISSUE TITLE
Issue with robot capabilties and screenshot parameters

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1390]
Hello,

It seems that cerberus doesn't use robot capability when screenshot setting is different from 2.
For example here you will find two executions, the only thing different between them is the screenshot setting (1 for the first and 2 for the second)
First exec : 
![image](https://user-images.githubusercontent.com/18569182/28518284-a3c9c12e-7067-11e7-9a85-2c78d29e04ff.png)

Second exec : 
![image](https://user-images.githubusercontent.com/18569182/28518182-59df49e4-7067-11e7-935a-b5d81d56f320.png)

The first execution failed because of an alert message about security. I've implemented a new capability : 
![image](https://user-images.githubusercontent.com/18569182/28518344-d7722f2a-7067-11e7-88b5-5639e8e3d879.png)

But this one seems not used when screenshot is 0 or 1. Do you think there a link between these parameters ? (I can reproduice everytime)
Thank you !

**Comment by R-Loic** [comment]
Hello @bcivel ,
It works everytime if I use "Take screenshot" control as a workaround.
It seems to be a bug on selenium side, can you confirm ? We will close the ticket in this case.
Thanks!

**Comment by bcivel** [comment]
Hello @R-Loic 
Yes, it seems that taking a screenshot is producing something that make the capability understandable by the browser.
I would say it's a problem on selenium or browser side, with no solution possible on Cerberus side as we just forward capability to the browser.
Thanks
