### ISSUE TITLE
Bug : Cerberus gave me a TestCase Id already existing when i created a new test. 

### ISSUE THREAD

**Issue by MowglieRed** [cerberustesting/cerberus-source#1391]
Hello

I created a new test for a existing system / application, Cerberus gave me a test case ID : 0084A. 
But when i saved the new test, i had an error message : "the usecaseID already exists".
The use caseID 0084A exists.

In fact, in this system / application, i had a test case ID 083A. Cerberus take the last ID and add 1 but Cerberus  formatted the result in 0084A (Five caracters). When it formatted, it don't check that this number exists already.  

It's not blocking issue. 

Peggy.

**Comment by bcivel** [comment]
Hello @MowglieRed 
Should be fixed with my last commit
Thanks for the contribution
Benoit

**Comment by MowglieRed** [comment]
Thanks a lot
