### ISSUE TITLE
Infinite JS loading informations on DataLib Page

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1395]
Hello, 

The page is long to load, maybe resolve this could help improve the performances : 

![image](https://user-images.githubusercontent.com/29098010/28572044-b0c45de2-7145-11e7-923e-cd8c5bdee684.png)

**Comment by bcivel** [comment]
Hello @Galand-V 
I cannot reproduce neither on my machine, nor on the demo version, nor with your production version.

Could you check with another browser to see if you have it again?
Could you tell us on which browser you have the problem?

Thanks
Benoit

**Comment by Galand-V** [comment]
I checked on FireFox and Chrome, it seems like the issue is no longer visible.
