### ISSUE TITLE
Delete Filter section from Environment page

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1397]
Hello, 

The "Filters" Section is a duplicate from the above filters.  Only environment Group is not a duplicate but does not seems usefull. 

Can you delete it ? 

![sans titre-2](https://user-images.githubusercontent.com/29098010/28572740-90e85e1c-7148-11e7-8c87-92d917368204.jpg)

**Comment by gmoita** [comment]
Please do not delete it... group might not be so used, but most important, is to keep the filter above as it is faster to filter on the top rather then on the list.
And when we move from one system to another, filter stays active, which is important as we need to manage several systems.

**Comment by bcivel** [comment]
Hello @gmoita 
OK, understood it will change a bit the habits.
But could you please try using filter table (with the new version of Cerberus). It's much faster to use as you don't have to unselect anymore when you search on filter, and the filters can be stored and retrieved by clicking on save.
Could you please make us some feedback to confirm it can fit for you?

**Comment by gmoita** [comment]
I've tested with another user and feedback was: please don't change it.
Reasons why:
1) Filters are not kept if I change from one system to another
2) Even if filters are saved, we integrate several different systems and environments, so we would have to be changing filters every time we move from one environment to another
3) Managing the filters on the beginning of the page, is faster than on the list (column line)

So, from our point of view, even if it can work, we will spend more time filtering on the columns than on the top filters.

**Comment by Galand-V** [comment]
Hello @gmoita, 

It would be interesting to have the same performance on the column filters. 

To your point of view, is there a way to improve the column filters so you would not need to use the top filters ?

**Comment by gmoita** [comment]
Hi @Galand-V.
With the top filters you can use the keyboard, type all the filters you want and apply the filter only once. On the column filters, you apply the filters one by one and the way the column filters work implies more time. Saying that, performance of the column filters cannot be better than the top filters.
Now, related to usability:
1) I would expect that the column filtering worked in a different way;
    - 1.a) currently, if you have a huge list (like test case numbering) and I need to select some items based on search criteria, we must first unselect all the items and then start to type the search box and filter on the searched items
    - 1.b) why not working like this: when we start searching, all the base filtering for the column is clean and the result of the search is the only thing that can be selected; this is similar to the way that the search box works (the one between the top filters and the column filters
2) if column filters are kept when you move to another system, **without saving the filter specifications**, it will help

**Comment by Galand-V** [comment]
Hello @gmoita, 

Maybe a solution can be found  to improve column filtering system. (#1409)
