### ISSUE TITLE
Have the complete modal when creating a new Environment

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1398]
Hello, 

Currently at the creation, we have the following modal : 

![image](https://user-images.githubusercontent.com/29098010/28572943-34793952-7149-11e7-8f0c-9820d7e37abd.png)
Having the complete one directly could help users creating environment : 

![image](https://user-images.githubusercontent.com/29098010/28572985-54aff8aa-7149-11e7-9181-54c676bcde8f.png)

Otherwise, people should guess that even after creating an environment, they need to clic on "edit" and complete the parameters with additonal settings.

**Comment by R-Loic** [comment]
Hello @Galand-V ,

This is a good issue, seems important to me. Will make cerberus more user-friendly.
It should be the same for application creation.
@bcivel @vertigo17 : Is there any constraints to make add modal the same as edit modal ?

Thank you!
