### ISSUE TITLE
[pool size] Launching campaign with 271 tests gives NE : 504 gateway timeout

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1400]
Hi,

Can you run campaign with more than 200 tests ? (ex : 5 country x 50 tests) 
Did you try with the docker selenium too ?

It gives us a lot of   NE : ERROR : 504 gateway timeout in the queue 
Like i explained here :  https://github.com/cerberustesting/cerberus-docker/issues/18

I use the docker selenium because Cerberus is in an isolated network here.

There is something to config ? 

Thanks for your help

**Comment by bcivel** [comment]
Hello @vitoo,

Can you check this : 
The pool size (Application page, environment section) for your application must be lower than number of concurrent test in the hub.

If it's the opposite, the hub will take too many connnection, and will manage a queue on his side. And after 5 minutes timeout (by default), connection will be killed.

Could you check and give us some detail on settings please?
Thanks

**Comment by vitoo** [comment]
I have 5 country for the same app, and 5 selenium browser available, i should uise a pool size of 1 per app/country i think 

![image](https://user-images.githubusercontent.com/995694/28583926-2e1db818-716b-11e7-9a82-926ac05b356e.png)

**Comment by bcivel** [comment]
So, in your example, you can submit 50 (10 * 5) execution simultaneously, when the hub can handle 5 only.

So you should either set the pool size to 1 and execute all your test once, or set it to 5 and execute one campain per country on cascade.

It's the best you can do in short term. We already identified to refactor this part to take that constaint into account in the Cerberus Queue system.

**Comment by vitoo** [comment]
The 5 min timeout before kill is done by Cerberus ?

Will try to set up more browsers

**Comment by vitoo** [comment]
I've set 7 browsers

and 6 country = 6 pool size

It start good first, but all 7 browsers are busy, and some request goes in the selenium queue, causing some error in queue "bad gateway"

**Comment by vitoo** [comment]
At the end i got 153 error in Cerberus queue, but it looks like its all executed, nothing in NE 😩

**Comment by vitoo** [comment]
So, like we said last day, that would be consitent to do pool size at the robot level

For example i have 5 chrome 5 firefox, for 1 app

**Comment by bcivel** [comment]
Hello @vitoo 
Yes, this development is almost finished. 

In near future, cerberus queing will work with 3 constraints : 
> poolsize at country env application level to protect tested application (like today)
> pool size at the robot level to avoid to submit more execution than a robot is able to manage
> pool size at the cerberus level, to avoid to launch more execution than cerberus is able to suport.

When one a these constraint is reached, the execution will be kept in queue in Cerberus

**Comment by vertigo17** [comment]
Feature is now ready in last commit.
Please note that robot constrain is in fact at robot ip/host level.
This is because there could be different robot all pointing to the same ip/host and capacity is linked to that ip.

**Comment by bcivel** [comment]
Hi @vitoo 
Should be fixed with the @vertigo17  commit
I close the issue as it's fixed and ready for be released.
I try to release by the end on the week
