### ISSUE TITLE
Change default verification parameter to "not fatal"

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1404]
Hello, 

Can you change the default verification parameter to "Not Fatal" ? 

![image](https://user-images.githubusercontent.com/29098010/28630823-9fccd24e-722b-11e7-98a6-2b6ff421a88a.png)

What do you think about this ?

**Comment by bcivel** [comment]
Hi @Galand-V 
No worry about it for me.
I just wonder if it's really necessary to parametrize it, or if just inverting the values is enough.

For me, I would just invert the values, but if other users are really bother about it, please let me know.
