### ISSUE TITLE
Url to load test in cerberus queue ?

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1405]
Hello,

the `GetCampaignExecutionsCommand `return this kind of url : 

` http://ppicboappcerb01.fra.local:8080/Cerberus//RunTestCase?&&Test=CED&TestCase=0007AF12&Browser=chrome&Country=RX&Environment=INTE&ss_ip=10.130.114.205&ss_p=4444&Tag=20170727_CED_Inte&screenshot=1&outputformat=compact
`

But it's doesnt use the queue. Problematic when i load 200+ tests with a script.

Can we have an url to push the execution in Cerberus queue ?

Is it AddToExecutionQueue  ? 
Ready in version 1.1.13 ?

Can we have an example 

Thank you

**Comment by vitoo** [comment]
I need in parameter : campaign  & robot 

Because i have a robot  'iphone' that is a chrome with an iphone user-agent

The `GetCampaignExecutionsCommandreturn  `doesnt return the robot user-agent

**Comment by vertigo17** [comment]
yes it is AddToExecutionQueue 
Public API to interact with Cerberus are specified in the documentation under chapter 26
for ex on that API latest version is 
AddToExecutionQueueV001
Call it with no parameter in order to get the help message.
It already have the robot parameter.

**Comment by vitoo** [comment]
Version 1.1.13 or 1.1.14 needed ?

**Comment by vertigo17** [comment]
Should be fine in 1.1.13

**Comment by bcivel** [comment]
Hi @vitoo 

Below is an example of usage
http://mycerberus/Cerberus/AddToExecutionQueue?SelectedCampaign=MyCampain&Environment=PROD&Browser=firefox&Robot=MyRobot&Tag=toto&OutputFormat=compact&Verbose=0&Screenshot=1&PageSource=1&SeleniumLog=1&timeout=30000&retries=0

Please notice that you've now an official Jenkins pluggin, that is available from Jenkins directly:
https://github.com/cerberustesting/cerberus-jenkins-plugin

Hope that help

Benoit
