### ISSUE TITLE
Variables in the DataLib Parsing Answer field

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1407]
Hello, 

it would be interesting having the possibility to add variables in the parsing Answer of the DataLib page. 

Here is an example : 
![image](https://user-images.githubusercontent.com/29098010/28671073-a3e66182-72db-11e7-8524-97f932ca7d1d.png)

Currently, this is not decoded by Cerberus, the error message is the following : 
![image](https://user-images.githubusercontent.com/29098010/28671129-daed026c-72db-11e7-8e50-efe72a83ad4a.png)

Note : The property has been calculated previously.

**Comment by vertigo17** [comment]
I will add the decode at that level but from what I see, it looks like you want to take a random row of an xml structure.
Datalib is multi row so why don't you try to put an xpath that load all rows and use the nature of property in order to pick a random row from that list ?
