### ISSUE TITLE
Evolution : Send a mail with the report campaign

### ISSUE THREAD

**Issue by MowglieRed** [cerberustesting/cerberus-source#1408]
Hello, 

Some of our users would like to have a mail with the report execution. 

Actually, we asked to outsourcer to develop a script to send a mail. But we are dependant of our outsourcer. 

Is it possible to add a new function in cerberus :  send a mail with the execution report and allow us to stop or start the sending mail directly in cerberus ?

thanks 
peggy

**Comment by vitoo** [comment]
This should be configured at campaign execution level i think (boolean : send email)

If every execution sent an email, nobody will read the too much emails
