### ISSUE TITLE
change filters functioning

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1409]
Hello, 

Maybe the filter functioning can be improve a bit. Here is a proposal : 

- Filters are not selected by default
- if no filters are active on a column => display all
- replace the filtering icon by a search field
- change the positioning of the "validate/close" button
- Behaviour is described below

![first part](https://user-images.githubusercontent.com/29098010/28720575-e16bf508-73ad-11e7-965a-af4b05432c4c.jpg)
![part two](https://user-images.githubusercontent.com/29098010/28720392-5079f36a-73ad-11e7-8e81-ec705eb90734.jpg)
![part three](https://user-images.githubusercontent.com/29098010/28720399-51d9b8a8-73ad-11e7-8abf-58da523fb255.jpg)

**Comment by nicodeur** [comment]
Hi @Galand-V ,

I commited a proposition to facilitate manage of filter. It's a little different that you proposed, but I think you will be happy with this.

Can you test it on [Cerberus demo QA](demo.cerberus-testing.org:28080/CerberusQA/) and say me if those changes are sufficient ?

Thanks a lot.

Nicolas

**Comment by Galand-V** [comment]
Hello @nicodeur,

I tried it, it is really improving the filter functioning. Great Work ! 

The only bug I identified is when you select a filter with the checkbox and do not fill the search input. Clicking on ENTER or TAB has no effect. 

Thank you !

Victor

**Comment by vertigo17** [comment]
@nicodeur I beleive the work is finshed on that issue ?
If yes, can you close it ?

**Comment by nicodeur** [comment]
Hi @vertigo17 ,

Yes after discuss with @bcivel, we prefer keep actual behavior for the @Galand-V bug because it's more logical.

Regards,

Nicolas
