### ISSUE TITLE
New action sikuli highlight

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1411]
Hello,
It could be great to add the highlight action for sikuli : 
![image](https://user-images.githubusercontent.com/18569182/28778451-926a5400-75ff-11e7-9450-9ee077c0ffcb.png)
Use with find() it create a red rectangle around the picture for 2 seconds. It 's really usefull to debug and see where sikuli is clicking.
 This feature will only be used by implementers I think but it's really enjoyable for them.
http://doc.sikuli.org/region.html
What do you think @bcivel about this ?
Thanks !

**Comment by bcivel** [comment]
Hello @R-Loic 
Nice issue. 

In the cerberus-extension-sikuli v 1.1.2 , you can now start with the argument -e followed by the number of seconds to activate that option.

Example : 
`java -jar cerberus-extension-sikuli-1.1.2-full.jar --highlightElement 2`


More information or option : 
`java -jar cerberus-extension-sikuli-1.1.2-full.jar --help`
