### ISSUE TITLE
Cant edit tag on test execution

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1413]
Hello,

We are not able to edit a tag on execution details tab on TestCaseExecution page.

Can you please check?

Regards

Cerberus Version : 1.1.14-SNAPSHOT-1185

**Comment by bcivel** [comment]
Hello @j0hnsa 
Fixed with my last commit

**Comment by bcivel** [comment]
Hello @j0hnsa 
Testcase has been created to ensure it never happen again
http://demo.cerberus-testing.org:28081/Cerberus/ExecutionDetail2.jsp?executionId=2954
Thanks
Benoit
