### ISSUE TITLE
Saving empty properties with no warning

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1414]
Hi,

when saving empty properties there is no warning message and the properties are deleted.

![image](https://user-images.githubusercontent.com/14328346/28817531-68836162-76a0-11e7-9c79-b2266424a07a.png)

After save:
![image](https://user-images.githubusercontent.com/14328346/28817550-74e8daae-76a0-11e7-8e28-746d9ac8d517.png)

Can you please take a look?
Is this the proper behavior?

Cerberus1.1.14-SNAPSHOT-1185

Thanks

**Comment by bcivel** [comment]
Hi @RobertoAbraul 
No, it's not the proper behavior. 
However it's not a regression but it is this behavior since a long time.
We will correct it asap
Thanks
