### ISSUE TITLE
Error converting result

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1415]
If the property does not return any value on the defined length, the default value is set to '0' (for key and fileds).
On Cerberus1.1.14-SNAPSHOT-1185 it seems that the result is no longer an integer:
http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=49092457
The returned keys are:
 [{"Quantity":"1","KEY":"1"},{"Quantity":"0","KEY":"0"},{"Quantity":"0","KEY":"0"},{"Quantity":"0","KEY":"0"},{"Quantity":"0","KEY":"0"}]

On previous Cerberus version the test case was OK with the same parameters:
http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=49071652

**Comment by gmoita** [comment]
Hi. This is critical as we are now not able to run execute the same test case as yesterday.
Please can you treat this as urgent?

**Comment by bcivel** [comment]
Hi @ffazendeiro @gmoita 
This is fixed with my last commit
