### ISSUE TITLE
Issue with test battery displaying

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1416]
Hello,

Test cases in batteries are no more visible even if they are in the list : 
![image](https://user-images.githubusercontent.com/18569182/28825511-ca9ce352-76c6-11e7-8305-8dc68341d2c0.png)

Thank you

Cerberus Version : 1.1.13-1180

**Comment by bcivel** [comment]
Hello @R-Loic 
Should be fixed with my last commit
Thanks
Benoit
