### ISSUE TITLE
Minor visual issues

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1418]
Hello,

We noticed two minor issues on Cerberus display on some pages.
#1:
When clicking the Run testcase again on the RunTestCase page the side menu expands the 1st level then it collapses again

![bug 1](https://user-images.githubusercontent.com/16339891/28829560-186eeeb8-76cc-11e7-868c-12b2fb8f426f.png)

#2:
This one is on editing a testcase battery if we click the tab Test Case where the Test cases are inserted into a battery the column display it way to large for the action button while the Testcase name will be hidden in some displays:

![l_e25e tmp](https://user-images.githubusercontent.com/16339891/28829785-db4004a4-76cc-11e7-9391-dd6feb759369.PNG)

Note that this are minor issues than can just be taken into account on further releases

Regards

Cerberus Version : 1.1.14-SNAPSHOT-1185

**Comment by bcivel** [comment]
Hi @j0hnsa 
Thanks for your remarks.
I fixed the second one. But unfortunatelly, I can't reproduce the first one (with the menu that expand and collapse). Could you give a bit more details to reproduce please? 
Thanks
Benoit

**Comment by bcivel** [comment]
Hi @j0hnsa 
OK, I reproduced on firefox only
