### ISSUE TITLE
Can not delete TestCases from the queue

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1419]
Hello, 

Just before the releave of the Cerberus1.1.14 version, we could set a status on TestCases and have the possibility to delete them. 

It is not possible anymore. Is it the expected behaviour ? 

![image](https://user-images.githubusercontent.com/29098010/28861453-4286f642-7761-11e7-8c99-ca8d959b5e2b.png)

**Comment by bcivel** [comment]
Hello @Galand-V 
Yes, it is the expected behavior.
Execution in queue are no more deleted. All of them are kept. 
You can cancel them if you don't need to run them finally.

More info on the process here : 
https://github.com/cerberustesting/cerberus-source/blob/master/docs/QueueStateWorkflow.odg
