### ISSUE TITLE
TC's Associated to dataLib => modal layout issue

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1420]
Hello, 

There is an issue on the Cerberus1.1.14 DataLib modal page : 

When you click to see associated testCases the following screenshot appears : 

![datalib tc linked](https://user-images.githubusercontent.com/29098010/28861618-f475f34e-7761-11e7-8709-f85b0b78a7a0.png)

**Comment by bcivel** [comment]
Fixed
