### ISSUE TITLE
Wrong behaviour for filters on the report display

### ISSUE THREAD

**Issue by MichaelWil** [cerberustesting/cerberus-source#1426]
Hi,

When displaying a report (for exemple : http://cerberus.siege.red/Cerberus/ReportingExecutionByTag.jsp?Tag=WEB_THESEUS_ALL_PREPROD_2017073112).
When you selec this application : ANDROID_APP_RDT the selection displayed is done for ANDROID_APP_RDT AND FOR ANDROID_APP_RDTNEW which is not supposed to be the case.

Can you please check and fix ?

Thanks
![image](https://user-images.githubusercontent.com/11719918/28864493-002eed66-776d-11e7-93cd-c57dfc5c7870.png)

**Comment by bcivel** [comment]
Hi @MichaelWil 
Fixed with my last commit
Enjoy
