### ISSUE TITLE
Option "Filter on last executions" not open properly

### ISSUE THREAD

**Issue by Anokasv** [cerberustesting/cerberus-source#1427]
Hello, 

On execution detail test case page, when we click on "Filter on last executions", the page that open is not correct.
See attachments.

Can you please take a look?
Thanks.
Ana

Browser: Google Chrome Version 60.0.3112.78 

![image](https://user-images.githubusercontent.com/20952253/28865884-4c96bd90-7769-11e7-8a64-1b3ffdd0be1c.png)
![image](https://user-images.githubusercontent.com/20952253/28865962-73370590-7769-11e7-8f17-3e716d824971.png)

**Comment by bcivel** [comment]
Hello @Anokasv 
Fixed. Will be available in the next release.
Benoit
