### ISSUE TITLE
Enhancement to manage list of objects

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1429]
Hello,
It could be great to limit the view of the list for proposed objects and add a scroll bar:

![image](https://user-images.githubusercontent.com/18569182/28868588-372db9f2-777a-11e7-850f-f03731674bf8.png)
Also if we could add at the top of this list a new button like : "See the object pictures" which can display a new modal with all the picture list (displaying only the picture).

Example, it would be similar to the following modal, without the buttons bot and checkboxes. If we double click on a picture, it would select the object: 
![image](https://user-images.githubusercontent.com/18569182/28871398-ac3ee02c-7784-11e7-9b0e-5e6a1f23db07.png)

These improvement would be apprecieted for sikuli use or when the object list become too long.
Thank you!

**Comment by nicodeur** [comment]
Hi, 

After discuss with @R-Loic , I added tooltip to display image on Sikuli autocomplete instead of create a new popup.

![image](https://user-images.githubusercontent.com/6707556/29510358-cd15f6c4-865b-11e7-97c5-2c37a6103922.png)
