### ISSUE TITLE
Is it possible to run a campaign from command lines ?

### ISSUE THREAD

**Issue by TsunaDev** [cerberustesting/cerberus-source#1430]

**Comment by bcivel** [comment]
Hello @TsunaDev 

Yes, you can check the section public API on the documentation.

Basically, you can call the service http://mycerberushost/Cerberus/AddToExecutionQueueV001 to have more information on parameters to set

For exemple : 
`http://ton.ho.s.t:8080/Cerberus/AddToExecutionQueue?SelectedCampaign=le_nom
_de_ta_campagne&Environment=PROD&Browser=firefox&Robot=MyRobot&ss_ip=127.0.
0.1&ss_p=5555&BrowserVersion=28&Platform=LINUX&Tag=toto&OutputFormat=compac
t&Verbose=0&Screenshot=1&PageSource=1&SeleniumLog=1&timeout=30000&retries=0`

So you can use curl or wget to call this service.
Please, notice that you need to set the parameter `cerberus_url`in the parameter table to have it working properly.
Please, notice also that we have an official jenkins plugin that you can use to trigger execution.

Feel free to comment if it's not clear enough
Thanks
Benoit

**Comment by TsunaDev** [comment]
![oops](https://user-images.githubusercontent.com/30118815/28876987-4c58e33a-779b-11e7-8457-a1346d7edc62.png)

**Comment by bcivel** [comment]
@TsunaDev 
Could you use this service instead?
/AddToExecutionQueueV001  instead of /AddToExecutionQueue

**Comment by TsunaDev** [comment]
@bcivel There is the output with the V001 : 

![image](https://user-images.githubusercontent.com/30118815/28879034-4bcd12e6-77a1-11e7-9561-f342bb0c75a1.png)

I tried with the manualurl set to true with the parameters that come with it but same I get the same error

**Comment by bcivel** [comment]
@TsunaDev 
I apologize, I mixed information from both servlet. The parameter name are quite different.

http://localhost:8080/Cerberus/AddToExecutionQueueV001?campaign=Test_campaign&environment=PROD&browser=firefox&robot=MyRobot&ss_ip=127.0.0.1&ss_p=5555&version=28&platform=LINUX&tag=toto&verbose=0&screenshot=1&pagesource=1&seleniumlog=1&timeout=30000&retries=0

**Comment by TsunaDev** [comment]
@bcivel 
Yes, I already changed it

**Comment by bcivel** [comment]
@TsunaDev Could you tell me which version of Cerberus are you using?
Could you provide also a screenshot of the page CerberusMonitoring?

**Comment by TsunaDev** [comment]
@bcivel 
I'm using the 1.1.13 release 

![image](https://user-images.githubusercontent.com/30118815/28880303-e6120566-77a4-11e7-8f67-eb1008567385.png)

**Comment by bcivel** [comment]
@TsunaDev 
I'm trying to reproduce with no success.

Could you provide the url that you call please?
Do you have access to the server.log file? can you see some errors when opening that URL?
Thanks
Benoit

**Comment by TsunaDev** [comment]
The server.log file only shows the errors that are displayed in this screenshot : 
![28879034-4bcd12e6-77a1-11e7-9561-f342bb0c75a1](https://user-images.githubusercontent.com/30118815/28913204-7fe35d4c-7837-11e7-916f-78a84cd0354a.png)

Here's the URL : http://localhost:8080/Cerberus/AddToExecutionQueueV001?campaign=toto&environment=PROD&browser=firefox&robot=MyRobot&ss_ip=127.0.0.1&version=28&ss_p=5555&platform=LINUX&tag=tata&OutputFormat=compact&timeout=30000&retries=0

**Comment by TsunaDev** [comment]
Ok, I found the problem, I was not loged in Cerberus.
But how can I connect with command lines ?

**Comment by bcivel** [comment]
Hi @TsunaDev 
You got it. Thanks for the help.
I fixed it. I'll try to release the 1.1.14 quickly, to unlock you.

**Comment by TsunaDev** [comment]
@bcivel Ok thanks a lot !

Another question, how can I launch the tests after I added them to the queue ? (I tried to execute http://localhost:8080/Cerberus/ExecuteNextInQueue but it's not working)

**Comment by bcivel** [comment]
@TsunaDev 
Once the test are correctly inserted in the queue, they will be executed automatically.

You can have a look to this workflow to understand how it will work : 
https://github.com/cerberustesting/cerberus-source/blob/master/docs/QueueStateWorkflow.odg

The ExecuteNextInQueue is an old implementation that was used when queuing was managed outside Cerberus.
