### ISSUE TITLE
Fail to decode %system.COUNTRY%

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1431]
Hi,

It seems that the property %system.COUNTRY% is not decoded on the condition operator.
With the previous Cerberus version we have the following control that is to be executed if the system.COUNTRY is different from RU:
![image](https://user-images.githubusercontent.com/17747042/28877848-898c27e0-7795-11e7-91d0-0cc542e4af8e.png)
Now with the same control the system.COUNTRY dosen't seem to be decoded and the condition operator seems to compare the string '%property.COUNTRY%' with 'RU' (property not decoded):
![image](https://user-images.githubusercontent.com/17747042/28877959-d3f8cc02-7795-11e7-814d-777e1c7b69dd.png)

Is there a change on the behavior?
Thanks in advance

**Comment by bcivel** [comment]
Hi @ffazendeiro 
yes it happen on control. This has been fixed yesterday.
Do you have any chance to deploy a new version?
Thanks
Benoit
