### ISSUE TITLE
Result FA with all step OK

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1432]
Hi,

This new version of Cerberus uncovered a masked issue.
When a step condition control was badly defined the result was OK and the final result of the test was OK.
In this case the step was to be executed if a certain text from an element is present but the issue is that the expected element is not present. The test result was OK:
![image](https://user-images.githubusercontent.com/17747042/28881578-8026a97c-77a0-11e7-9050-f49a0a137c46.png)

Now the test result if FA:
![image](https://user-images.githubusercontent.com/17747042/28881599-91acefd0-77a0-11e7-9e79-ce0534213480.png)

I think that now Cerberus has the correct behavior but it would be great if the failed step could have a different color (red or yellow) so it can be quickly identified.

Thanks in advance.

**Comment by bcivel** [comment]
Should be fixed now.
Once error will be found on decode, the test will stop and step and Test will be in FA mode
