### ISSUE TITLE
"Unlimited" step loop

### ISSUE THREAD

**Issue by Heychsea** [cerberustesting/cerberus-source#1433]
Hello,

I wanted to loop over some data in my tests, but it stops at 20 iterations.
How do I go over this limit ?

**Comment by bcivel** [comment]
Hi  @Heychsea 
You can set the `cerberus_loopstep_max`parameter, in the parameter table
Default value is 20

**Comment by TsunaDev** [comment]
@bcivel 

What about a max number of loops bound to the step itself ?
