### ISSUE TITLE
Get URL variables

### ISSUE THREAD

**Issue by TsunaDev** [cerberustesting/cerberus-source#1434]
It would be cool to be able to get the URL variables as properties.

**Comment by bcivel** [comment]
Hello @TsunaDev 
Nice idea. Is it different than #1401 ?
Thanks

**Comment by TsunaDev** [comment]
Yes, on the #1401 I talked about a global property on the execution.
On this one, I'd like to get the variables of the actual URL.

**Comment by vertigo17** [comment]
I would suggest that you use getFromJS with a script that does that job.
Something like:

var searchParams = new URLSearchParams(window.location.search);
return searchParams.get("Parameter");

**Comment by vertigo17** [comment]
Did the method proposed works ?
I let you reopen the issue in case it did not work.
