### ISSUE TITLE
Page Test Data Library - Button "...list of test cases..." with layout unconfigured

### ISSUE THREAD

**Issue by Anokasv** [cerberustesting/cerberus-source#1435]
Hello, 

On page Test Data Library, when we click on "Get list of test cases that use this entry", the layout is unconfigured.

See attchaments.

Use Browser Google Chrome Version 60.0.3112.78

Thanks.

Ana

![image](https://user-images.githubusercontent.com/20952253/28933749-2f9f0f68-7876-11e7-82a3-12d0b4de05d3.png)
![image](https://user-images.githubusercontent.com/20952253/28933758-397ce410-7876-11e7-9cc7-4aaf60a979f0.png)

**Comment by bcivel** [comment]
Hello @Anokasv 
This shhould be fixed now.
Thanks
Benoit
