### ISSUE TITLE
Manual TestCases Executions

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1442]
Hello, 

If the group "Manual" is selected in the TC header, it is impossible to launch it manually.

![image](https://user-images.githubusercontent.com/29098010/29161170-814e9d44-7db5-11e7-9be1-b1995a6fe355.png)

Got the following message : 
![image](https://user-images.githubusercontent.com/29098010/29161229-c27dcdd0-7db5-11e7-90d8-5985f0bce058.png)

Run parameter is in "Manual Execution"

![image](https://user-images.githubusercontent.com/29098010/29161294-fefccaf4-7db5-11e7-834f-b2283d410d3f.png)

**Comment by nicodeur** [comment]
Hi,

I enable to execute a manual execution RunTests page. I enable to launch a manual execution without selected Robot.

Nicolas
