### ISSUE TITLE
Can't create TestCase if some columns are hidden (Show/Hide button)

### ISSUE THREAD

**Issue by Heychsea** [cerberustesting/cerberus-source#1443]
Cerberus version 1.14 SNAPSHOT 1202

**Comment by R-Loic** [comment]
hi @Heychsea ,

I can't reproduice. I can create when colomns are hidden. 
In my case, I can't create a new testcase in testcaselist page when there is no row displayed in the list : 
(create button seems disabled)
![image](https://user-images.githubusercontent.com/18569182/29205056-d2f689f2-7e7a-11e7-8b49-a9478aad435b.png)

Is this the same bug, you found out?

**Comment by nicodeur** [comment]
Hi,

I fixed bug that @R-Loic mentionned. @Heychsea , your bug is fixed too ?

Regards,

**Comment by Heychsea** [comment]
It seems to be fixed, I can't recreate the bug anymore.
