### ISSUE TITLE
What's the best desktop environment on Linux for Selenium ?

### ISSUE THREAD

**Issue by TsunaDev** [cerberustesting/cerberus-source#1444]
Does anyone have an idea ?

**Comment by vitoo** [comment]
The more lightweight the better : LXDE

**Comment by vertigo17** [comment]
Agree with @vitoo the smaller the better. In redoute we use centos
I guess the desktop is gnome. Not optimum but works.

**Comment by vitoo** [comment]
Same in norauto :car:

**Comment by mbessa** [comment]
Yes, we use a slim/custom version of CentOS to make it as light as possible.
Selenium docker official images uses LXDE. 
Basically you can use whatever you want. If you are aiming for 1 or 2 VM's, i'll go for selenium docker images.

**Comment by vitoo** [comment]
The lighter way is phantomjs, it does not need desktop environment

**Comment by TsunaDev** [comment]
Thanks for all these ideas !
