### ISSUE TITLE
[Security breach] Screen TestCaseScript, button add step

### ISSUE THREAD

**Issue by nicodeur** [cerberustesting/cerberus-source#1446]
Hello,

There is a Security breach on Screen TestCaseScript, button add step. If a user doesn't have rights to add a step, button is disabled.

With Firebug/Chromebug etc, we can change status of button to render it as clickable. After that, I wan added a new step.

**Comment by vertigo17** [comment]
You were probably able to add step on the screen but were you able to save it with no error?
Update servlet is supposed to have that control already done and report an error if operation not allowed.

**Comment by nicodeur** [comment]
You are right, I was stopped when I seen my step was added. When I saved, page was refresh, but my new step wasn't added.

Thanks @vertigo17
