### ISSUE TITLE
Cannot select a system with whitespace on its name

### ISSUE THREAD

**Issue by cjmachado** [cerberustesting/cerberus-source#1450]
Successfully created a new system named "Invoice B2C" on Administration->Invariants page. Cerberus properly shows the new system on the systems select element on the top-right corner of the page. 
After selecting the new system, Cerberus reloads the page with the first system selected (AUTODIAG in our installation), but I'd expect to have "Invoice B2C" selected.

Could not find any error messages in the logs.

**Comment by bcivel** [comment]
Hi @cjmachado 
This should be fixed now.
Thanks for your help
Benoit
