### ISSUE TITLE
Warning for property tooltip keeps displayed

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1451]
Hello,

The following tooltip message keeps displayed, even if the property exists : 

![image](https://user-images.githubusercontent.com/18569182/29525693-cfa00e56-8693-11e7-81e0-c1298aa198cd.png)

Could you please have a look ?

Thanks !

**Comment by nicodeur** [comment]
Hi, I fixed it by my last commit.

Nicolas
