### ISSUE TITLE
Open Run test in new tab

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1452]
Hello,

On TestCaseScript.jsp page if we click the scroll button to open in a new tab the Run TestCase button we are redirected to the same page. On TestCaseExecution.jsp page it opens the RunTests.jsp page as expected. Can we have the same behavior on the 1st?

Regards

**Comment by bcivel** [comment]
Hello @j0hnsa 
It should be fixed now
Thanks
