### ISSUE TITLE
Documentation display error

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1453]
Hello,

I can see there are some issues with the display of the new documentation : 

![image](https://user-images.githubusercontent.com/18569182/29617399-027b1622-8815-11e7-96c5-35be3c7f9e20.png)
Could you have a look @bcivel ?

Thanks!

**Comment by bcivel** [comment]
Hi @R-Loic 
It should be fixed now.
Thanks
Benoit
