### ISSUE TITLE
Change locator text information for "switch to iframe" 

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1454]
Hello, 

can you change the default locator text for the action "switch to iframe" ? 
Currenlty : Id of the target iFrame
Wanted : Element path

It is confusing for the user that will think the only locator usable is the id

![image](https://user-images.githubusercontent.com/29098010/29668870-ee589804-88e1-11e7-99fe-3a7af9c892fc.png)

Thank you,

**Comment by vertigo17** [comment]
will change to 'Element path of the target iFrame'
