### ISSUE TITLE
Wrong execution times stored on the Cerberus DB

### ISSUE THREAD

**Issue by Heychsea** [cerberustesting/cerberus-source#1455]
I tried to calculate the actions' execution times using the endlong and startlong values from the testcasestepactionexecution table, the thing is that sometimes the calculated values I get are erroneous.

But even when I get the wrong timers with my query, Cerberus still have the right values.

Where am I wrong ? How are the actions' execution times calculated ?

Here is the query:
`SELECT 
    description, endlong - startlong 'Time'
FROM
    cerberus.testcasestepactionexecution
WHERE
    id = 900 AND description <> ''
        AND description NOT LIKE '%ms%'
ORDER BY step , 'index' , sort`

**Comment by TsunaDev** [comment]
Here you can see the problem : 

Cerberus : 
![time_issue_cerb](https://user-images.githubusercontent.com/30118815/29721782-c6a3c1ca-89be-11e7-8f19-4ad61e68ccc0.PNG)

Data that I get from the database : 
![time_issue](https://user-images.githubusercontent.com/30118815/29721827-cf4414ba-89be-11e7-8dd6-23184d8f816c.PNG)

As you can see there are some  digits that pop up on the db value

**Comment by vertigo17** [comment]
Your sql is making a difference between 2 integer (long) in a timestamp format : YYYYMMDDHHMMSSMMM
Each time the start and end are not within the same minute, you will get that strange result.
Either use the start and end column that are in date format. 
Either you need to convert in date/time format inside the sql before making the difference.

NB: be careful of what you build against cerberus tables. Those table could change without any notification from 1 version to another. Only public servlet are supported and garantee between version.
Depending on how important is what you build, we may create some public view at data level to secure the same thing at database level.
