### ISSUE TITLE
Add a "Comment" section in the Executions Reports 

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1458]
Hello, 

It would be interesting to add notes linked to an Execution to avoid using an external tool to comment it. 

![sans titre-1](https://user-images.githubusercontent.com/29098010/29811859-286bab6e-8ca5-11e7-970c-a4e2225ea96d.jpg)

Tell me what you think about this possible evolution & impacts 

If people are into it, Layout needs to be rework

**Comment by vertigo17** [comment]
make sense to me if we are talking about the comment of the test case.
That means that that comment (just like bugid today) would change on all reportbytag screen attached to that testcase. Also, adding a new execution (that could have a different status) to that same testcase will leave that field unchanged. It would be the same behavior as bugID.
We could allow to update the Bug ID and Comment of the testcase using the testcase modal from that report screen.

**Comment by vitoo** [comment]
Bug ID is not working in 1.1.12 ?

**Comment by vitoo** [comment]
i have open a new bug, but i can't set bug ID 

![image](https://user-images.githubusercontent.com/995694/29872499-29bca9d2-8d90-11e7-933d-1a1eae5c1fe8.png)

**Comment by vertigo17** [comment]
It is Working fine on my side.
The rule is:
If bugID is defined at test case level, the link displayed (at execution level) is taken from 'Bug tracker URL' of the corresponding application.
If no bugID is defined, at testcase level, the link is taken from 'New Bug URL' of the corresponding application.
The purpose of that button is to bring you to the ticketing system of the corresponding application (not to update the ticket ID on the testcase.). Once ticket has been created, it needs to be updated at testcase header level.
Do have the 2 URL correctly configured at application level ?
What I will improve is that when 'New Bug URL' is not defined, not to display the button. I will create a new ticket for that.

![2017-08-30 15_11_24-application](https://user-images.githubusercontent.com/5342048/29874003-9bd36ede-8d95-11e7-8b60-da1ba7e1209e.png)
