### ISSUE TITLE
Bug: Sql library load the wrong dbs

### ISSUE THREAD

**Issue by Heychsea** [cerberustesting/cerberus-source#1459]
I don't even have these invariants anymore...

![bad_db](https://user-images.githubusercontent.com/26014721/29815297-6f093e78-8cb0-11e7-8ff5-59afd2ab7e62.png)

Cerberus 1.1.14-SNAPSHOT-1202

**Comment by vertigo17** [comment]
Will be fixed but keeping in mind that until #1095 is fixed the SQL Library is not really usable so far.

**Comment by Heychsea** [comment]
The issue is almost fixed, if the Database invariant doesn't have a description, it is not listed.
Cerberus1.1.14-1221
