### ISSUE TITLE
Random property : add possibility to specify charset

### ISSUE THREAD

**Issue by memiks** [cerberustesting/cerberus-source#146]
Functional need to randomize generation of customer name.

So they need a random only took letters.

We must modify propertyservice to use value of property to string source of randomize.

**Comment by glassalle59** [comment]
Hello
Is this improvement has been developped ? I tried to use RANDOM NEW with only characters or numbers, not special characters like -

**Comment by vertigo17** [comment]
Looks to me that it is implemented:
https://prod.cerberus-testing.com/TestCaseExecution.jsp?executionId=601813

**Comment by glassalle59** [comment]
Oh thanks I did'nt know how to set it
