### ISSUE TITLE
Save filters URL parameters

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1461]
Hello,

when saving preferencies on filters, it adds the parameters to the URL. 

![image](https://user-images.githubusercontent.com/29098010/29879504-8759185e-8da5-11e7-922a-21e95f0b673f.png)

ex : 0003A-2=on&BE=on&CH=on&ES=on&FR=on&IT=on&PT=on&RU=on&UK=on&VI=on&PL=on&DE=on&RX=on&UF=on&0004A-2=on&BE=on&CH=on&ES=on&FR=on&IT=on&PT=on&RU=on&UK=on&VI=on&PL=on&DE=on&RX=on&UF=on&0004A-3=on&BE=on&CH=on&ES=on&FR=on&IT=on&PT=on&RU=on&UK=on&VI=on&PL=on&DE=on&RX=on&UF=on&0004A-4=on&BE=on&CH=on&ES=on&FR=on&IT=on&PT=on&RU=on&UK=on&VI=on&PL=on&DE=on&RX=on&UF=on&0004A-5=on&BE=on&CH=on&ES=on&FR=on&IT=on&PT=on&RU=on&UK=on&VI=on&PL=on&DE=on&RX=on&UF=on&0004A-6... 

if you try to click again on save, it will add the parameters to the already existing parameters => issue : request too large

![image](https://user-images.githubusercontent.com/29098010/29879618-dcc9333c-8da5-11e7-9f4c-c0bb62d88641.png)

Saving again should replace the existing parameters and not adding it

**Comment by bcivel** [comment]
Fixed
