### ISSUE TITLE
[BUG] Filter by "TestCase Short Description"

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1463]
Hello, 

As you will see in the screenshot attached, the search results are displayed in the filter header column. 

![image](https://user-images.githubusercontent.com/29098010/29917664-e7d1cbb6-8e42-11e7-9658-479425c22ba4.png)

In the screen the search keyword was "VOL"

**Comment by bcivel** [comment]
Hello @Galand-V 
Could you confirm it does not happen anymore with the change of the filters?
Thanks
Benoit

**Comment by vertigo17** [comment]
Yes bug is still there.
We probably need to limit the size of display of both zones. 

![screenshot_20170921_213207](https://user-images.githubusercontent.com/5342048/30714768-5f636964-9f14-11e7-9fe6-8fb59db43ffe.png)

**Comment by bcivel** [comment]
Fixed by @ryltar commits
