### ISSUE TITLE
Services connections : Rename the "Method" / "Operation" fields to "soapAction / Method"

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1464]
Hello, 

When you are trying to add a service to Cerberus, it is mandatory to fill le "method" / "Operation" field in the datalib / Service section. 

![image](https://user-images.githubusercontent.com/29098010/29960805-7762c1d0-8efd-11e7-8e44-222fc5b7e5e9.png)
![image](https://user-images.githubusercontent.com/29098010/29960826-88576838-8efd-11e7-95cd-986dd8b61381.png)

But it seems like that information needed in thoses fields are the same and this is the content of the "soapAction" tag. 

Can you rename thoses field into "SoapAction / Method" as the "Method" is used for REST webservices ?

**Comment by vertigo17** [comment]
Field in Datalib screen will be renamed to 'Operation' in order to match the same name in Service Screen.
