### ISSUE TITLE
Show/Hide content is showing wrong information

### ISSUE THREAD

**Issue by bcivel** [cerberustesting/cerberus-source#1466]
Since documentation modification, show/hide button is showing wrong information

<img width="1596" alt="capture d ecran 2017-09-04 a 12 25 00" src="https://user-images.githubusercontent.com/5376184/30023002-091819e6-916e-11e7-991b-8f8d4ec33ea5.png">

**Comment by vertigo17** [comment]
looks like https://github.com/cerberustesting/cerberus-source/commit/feb057aea3ef03766849af7a0cc567cd2ad0a5a0 fixed the issue.
