### ISSUE TITLE
Cant calculate text property

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1467]
Hello with this new version calculating text properties throws Action Failed. java.lang.NullPointerException
this impacts a lot of tests in our campaings can you check please?
example:
http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=50280507

Regards

Cerberus Version : 1.1.14-SNAPSHOT-1219

**Comment by j0hnsa** [comment]
Issue seems to be related with data-lib's below one more example:
http://192.168.134.17/Cerberus/TestCaseExecution.jsp?executionId=50280498

**Comment by gmoita** [comment]
Please treat this as "VERY URGENT"... High impacts.

**Comment by Galand-V** [comment]
The error message  java.lang.NullPointerException is not specific to the calculate property action. The issue is also reproductible on several functionalities.

**Comment by bcivel** [comment]
I'm investigating it

**Comment by bcivel** [comment]
This is fixed.
