### ISSUE TITLE
BUG : Wrong date autocomplete "Execution report by tag" page

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1468]
Hello, 

It seems like the date used for the autocomplete in the "Execution report by tag" search input is a duplicated from other campains. 

![image](https://user-images.githubusercontent.com/29098010/30157273-217e7fec-93c2-11e7-8320-f11c01c52687.png)

**Comment by vertigo17** [comment]
Tag object has just been created.
All tags that are created before the day where last version was installed will have the same timestamp (cerberus installation timestamp).
All tags created after will have the correct date.
