### ISSUE TITLE
Change the default TestCase Number per page

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1469]
Hello, 

The default sorting for the "testCaseTable_length" is 10. Can you change it to 50 ? 

![image](https://user-images.githubusercontent.com/29098010/30157879-bebe57f4-93c3-11e7-8acd-3c173e6297e2.png)

**Comment by vertigo17** [comment]
Personally I don't like the idea as doing that will hide by default the bottom part of the screen and as a consequence the vertical scroll bar that is quite usefull considering that a lot of informations needs to scroll.

![2017-09-07 12_02_47-test case list](https://user-images.githubusercontent.com/5342048/30158175-ab5e9c2c-93c4-11e7-97e6-4a2dfd4dcd29.png)

![2017-09-07 12_03_37-test case list](https://user-images.githubusercontent.com/5342048/30158177-ab9608ce-93c4-11e7-989d-a4bdd3914846.png)

**Comment by bcivel** [comment]
By the way, @Galand-V, you can change it and store your preferences.
I close that issue but don't hesitate to protest if you disagree.
