### ISSUE TITLE
Industrialize the cerberus campaign execution 

### ISSUE THREAD

**Issue by MowglieRed** [cerberustesting/cerberus-source#1471]
Hello, 

Actually, when we deploy a new version Cerberus in our internal servor, we launch the cerberus campaign manually. 
We'd like to increase the frequency of our deploy. To do that, we want to industrialize the launch of the cerberus campaign to remove the manual launch ! 
We'd like that cerberus schedule a cerberus campaign each days on its servor . 
Thanks a lot 
Peggy

**Comment by vertigo17** [comment]
Cerberus campaign is now executed on a daily basis (every day at 3AM).
Results are available and checked from prod.cerberus-testing.org
