### ISSUE TITLE
Be able to see the detail of a property (or another object) without changing screen (refactoring). 

### ISSUE THREAD

**Issue by MowglieRed** [cerberustesting/cerberus-source#1473]
Hello Benoît

I created the ticket :-) 
For example, when you edit the use case, you can see the properties. And when you need to see the detail of one values of the properties, you must open a new screen to 

the ticket is managed by RYLTAR and BCIVEL. 

Thanks 
best regards
Peggy

**Comment by vertigo17** [comment]
Looks like duplicate of both #1366 and #1363 that are more precise.
If confirmed, @MowglieRed, can you close it ?

**Comment by vertigo17** [comment]
Detail of property on modal is accessible when action is CalculateProperty but the idea would be to display it also for any other Fields as long as we use a property (with %property.PROPNAME%)

**Comment by vertigo17** [comment]
Modal is available anytime the property is used.
