### ISSUE TITLE
Elapsed time of the cerberus campaign : is it possible to increase the numbers of browser stack workers  ? 

### ISSUE THREAD

**Issue by MowglieRed** [cerberustesting/cerberus-source#1474]
Hi Benoît

Saw with @R-Loic, we have only two workers on the browser stack. Actually, a campaign cerberus take 40 minutes. We'd like to add a lot of new use case (200)  in the campaign, i'm afraid that the elapsed time is increasing strongly. 

Is it possible to increase the numbers of browser stack workers  ? 

Loïc / Peggy.

**Comment by vertigo17** [comment]
Maximum we can get (for free) is 2 worker from browser stack. We will have to fit that constrain.
Queue constrain should help increase velocity.
