### ISSUE TITLE
Keypress sur version 1.1.14

### ISSUE THREAD

**Issue by oeeckhoutte** [cerberustesting/cerberus-source#1476]
Hello, 

Je fait tourner des tests sur la version 1.1.14 et j'ai un problème avec une step qui ne s'exécute pas. Lorsque je mets une action keypress et que je mets PAGE_DOWN, il ne se passe rien.
J'utilise la nouvelle image docker publiée ce matin sur un Mac Mini et fais tourner le test sur Chrome. 

Auriez-vous une idée du problème ?

**Comment by bcivel** [comment]
Hello @oeeckhoutte 
I suppose you are using sikuli. Did you try using `Key.PAGE_DOWN` instead?
Are you sure you have the last extension sikuli version?

**Comment by oeeckhoutte** [comment]
Bonjour Benoit, 
J'utilise Selenium. J'ai mis à jour selenium en 2.53.1 dans le dockerfile. 
C'était 2.53.0 initialement. Est-ce que cela pourrait venir de là ?

**Comment by edebureaux** [comment]
Hi,
I am facing with similar issue in Web testcases:
Keypress actions PAGE_UP, PAGE_DOWN, ENTER do not work - I did not test other keypress actions but I assume that issue is the same.
In my testcase, those actions appear as "done" (in green) but actually nothing happens.
Kind regards,
Élodie Débureaux

**Comment by debnet** [comment]
Indeed the keypress is no longer working for unknown reasons, it seems the action is too quick, especially when several keypress actions are chained. A possible walkaround is to add systematically an internal wait between each action.

```java
this.disableHeadlessApplicationControl();

//create wait action
WebDriverWait wait = new WebDriverWait(session.getDriver(), 0l);

//focus the browser window for Robot to work
if (this.focusBrowserWindow(session)) {
	//wait until the browser is focused
	wait.withTimeout(TIMEOUT_FOCUS, TimeUnit.MILLISECONDS);
}

//gets the robot 
Robot r = new Robot();
//converts the Key description sent through Cerberus into the AWT key code
int keyCode = KeyCodeEnum.getAWTKeyCode(property);

if (keyCode != KeyCodeEnum.NOT_VALID.getKeyCode()) {
	//if the code is valid then presses the key and releases the key
	r.keyPress(keyCode);
	r.keyRelease(keyCode);
	 //wait until the action is performed
	wait.withTimeout(TIMEOUT_WEBELEMENT, TimeUnit.MILLISECONDS);
	
	message = new MessageEvent(MessageEventEnum.ACTION_SUCCESS_KEYPRESS_NO_ELEMENT);
}
```

It's ugly but it works.

![image](https://user-images.githubusercontent.com/634832/30400192-5c0785aa-98d6-11e7-898c-82d66909acde.png)

**Comment by bcivel** [comment]
Hello @debnet ,
Not that ugly.... And definitelly better than not working at all.
Thanks for your contribution
Benoit
