### ISSUE TITLE
Customization of last tag executions: improve search box

### ISSUE THREAD

**Issue by helenou** [cerberustesting/cerberus-source#1481]
Hi,

Using "Customize" from Last Tags Executions panel on HomePage, the selection of tag cannot be multiple using the search box:
![capture du 2017-09-21 11-07-59](https://user-images.githubusercontent.com/6005483/30688501-a3c35c46-9ebe-11e7-8643-a5c96f9c7b6e.png)

It is **only validated by Save button** !

Current result, only one at a time:
![capture du 2017-09-21 11-09-08](https://user-images.githubusercontent.com/6005483/30688577-d9fc801c-9ebe-11e7-823f-6f4c73013c4b.png)

One should be able to _**type a tag name and validate with Tab or Enter**_ so that it would do like the dropdown list and give ability to add multiple tag before saving.

![capture du 2017-09-21 11-08-39](https://user-images.githubusercontent.com/6005483/30688512-adf25adc-9ebe-11e7-92dd-fa0ad8bfca4b.png)

**Comment by vertigo17** [comment]
Not sure I understand your request.
You can already select as many tags as you want to be displayed in the homepage.
If you save the modal displayed with 'Test Run QA' and 'Cerberus_12_09_09' both tags status will be displayed in the homepage. Can you confirm ?
Or is that an ergonomy improvement that you want to select multiple tag inside the same Combo wihout beeing forced to do it 1 by 1 ?

**Comment by R-Loic** [comment]
Hello,
It was a misunderstanding of the customization behavior. It's now clear using the cerberus documentation.
Thanks @vertigo17
