### ISSUE TITLE
Character limitation for TAG ?

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1482]
Hello,

I 've met the following error when my tag was too long (when executing a campaign) : 
![image](https://user-images.githubusercontent.com/18569182/30688283-06e44db8-9ebe-11e7-8aba-ac99b9933123.png)
Is the tag limited in character ? 

Thanks

**Comment by vertigo17** [comment]
Good guess ;-) 
Tag is 50 chars max so yes limit reached. 
I propose to extend to 255 (even if te smaller the better).

**Comment by R-Loic** [comment]
Maybe we can keep 50 chars max but add an error message and a GUI limitation for the TAG field in run page ?

**Comment by vertigo17** [comment]
We can do both ;-)
