### ISSUE TITLE
Delete Tags

### ISSUE THREAD

**Issue by SeniorCanard** [cerberustesting/cerberus-source#1483]
Hello,

Today, Is it possible to delete Tags?

We use autocomplete feature on "execution report by tag" screen.

We would like to delete and clean old and obselete tags.

Regards

**Comment by vertigo17** [comment]
There are currently no GUI to delete a tag.
Not sure this is a good idea to delete them as the corresponding 'report by tag page' will no longer be accessible.
Does your tag has no execution ? If this is the case, I can provide an SQL to delete the tags that have no execution.
