### ISSUE TITLE
Define testcase perimeter of Campaign from criterias parameter.

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1486]
Hi,

Adding 4 more optional parameters at Campaign level.
- priority : defined priority on the test case to be added to the queue within a campaign [default all]
- application : application(s) to be added to the queue within a campaign [default all]
- status : label defined in test case [default 0]
- system :  in a system [default 0]

**Comment by ryltar** [comment]
steps:
- Add an invariant with idname: INVARIANTPRIVATE and value : CAMPAIGN_TCPARAMETER
- Add four invariants with idname: CAMPAIGN_TCPARAMETER  and values (priority, status, system, application)

- We need to add a new DAO method, if no label or battery are selected (without LEFT JOIN)
- We need to add in the current DAO (in the WHERE clause), the different testcase parameter campaign (same as the new DAO, we need to do this)

- Add a parameter in the DAO, to limit the number of data which are returned

- In the service, call the two DAO method when it's necessary (conditions)
