### ISSUE TITLE
Issue with execution tags

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1487]
Hello @vertigo17 ,
It seems your last commit broke something with the execution tag, we can't display tags anymore : 
![image](https://user-images.githubusercontent.com/18569182/30958215-b7f84f7c-a43c-11e7-8c2a-19aa5bbff854.png)
Could you have a look please ? 
Thank you !

**Comment by vertigo17** [comment]
Fixed with last commit. Sorry ;-)
