### ISSUE TITLE
Issue with report by tag display

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1489]
Hello!
For this specific tag : http://demo.cerberus-testing.org:28081/Cerberus/ReportingExecutionByTag.jsp?Tag=Validation_2.0_2709
I 've got the error : 
![image](https://user-images.githubusercontent.com/18569182/31007421-e3047bb8-a500-11e7-9b77-e8a8f815a1e3.png)
Could you have a look please ?
(Report is well displayed)
Thank you !
 

Cerberus Version : 1.1.15-SNAPSHOT-1221

**Comment by R-Loic** [comment]
Happened on an other tag : http://demo.cerberus-testing.org:28081/Cerberus/ReportingExecutionByTag.jsp?Tag=Validation_2.0_2909

**Comment by vertigo17** [comment]
That happened because testcase 'GUI : Integration' 0001A has been removed from database.
I will fix the error message but not sure that the removal of the testcase was expected.
