### ISSUE TITLE
Help tooltip improvements.

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1495]
Hello,

There is an issue with the help tooltip : 

![image](https://user-images.githubusercontent.com/18569182/31084898-f50a91ac-a795-11e7-83dd-d94fc86ba453.png)

Could you have a look ?
Description is too long, should we limit it ?

Thanks!

**Comment by cDelage** [comment]
https://github.com/cerberustesting/cerberus-source/issues/1919#issue-396830771
