### ISSUE TITLE
issue with service auto-completion display

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1497]
Hello,
Autocompletion with action call service let the proposition displayed, even if we switch tab : 

![image](https://user-images.githubusercontent.com/18569182/31119676-057b5a98-a832-11e7-8aa2-40d56e26d70d.png)

![image](https://user-images.githubusercontent.com/18569182/31119693-12e4f7fc-a832-11e7-955d-808c8ce8f9e8.png)
Could you have a look please ?
Thank you!

Cerberus Version : 1.1.15-SNAPSHOT-1232

**Comment by nicodeur** [comment]
I fixed this issue by #1504 .

Nicolas
