### ISSUE TITLE
GetFromDataLib property field evolution

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1498]
Hello, 

There is a bug on the GetFromdataLib field 

Step to reproduce : 

1) Create/Edit a property 
2) Select a GetFromDataLib type of property 
3) Type a word in the field
4) Change the kind of property (ExecuteSql,GetFromHtml...) 
5)Type again in the field

=> You will get [already type] + [new letter] everytime you add a letter

![image](https://user-images.githubusercontent.com/29098010/31125044-3b8abc54-a847-11e7-856d-151023e1a1f3.png)

**Comment by nicodeur** [comment]
I rollbacked this features, @ryltar , can you see to reactivate this feature and correct the bug please ?

Thanks for advance,

Nicolas

**Comment by R-Loic** [comment]
Modification of the feature :
 
If datalib doesnot exist, a button appears beside the field property. Same behavior for an edit button if only one datalib exists. 
If several datalibs exist for the same name, drop down menu will appear under the property field.  

First step : 
Enable auto-completion - uncomment code
Add : context : system - country - env - value (if internal) betwen [ ] (for several datalib behavior)
Add: Edit button if one datalib is returned
Add: Create button witout user rights control 

Step 2:
Add: Display edit and create button only if the user has testdatamanager right.
