### ISSUE TITLE
Slowness on TestCaseScript

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1499]
Hello,

Creating a test got much slower for instance just typing one long xpath on a click action is really slow and sometimes stalls the browser. Is there anything that can be done?

Using firefox browser

Cerberus Version : 1.1.15-SNAPSHOT-1232

**Comment by ryltar** [comment]
fixed with this commit 70f8f0b26c7cc3aa83d20b926db85c1753a76e02
