### ISSUE TITLE
forbidden message on testcasescript

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1502]
Hello,

Some users got this issue when loading a testcasescript page : 

![image](https://user-images.githubusercontent.com/18569182/31184598-1bfd98e6-a92a-11e7-9bda-13c6f104c290.png)
It seems the following service returns an error : 

![image](https://user-images.githubusercontent.com/18569182/31184637-4192f70e-a92a-11e7-9a11-69b1bb96876c.png)

It happens for non admin user (example of user who met the issue) : 

![image](https://user-images.githubusercontent.com/18569182/31184706-6fd58e6a-a92a-11e7-87e5-f1e59872baca.png)

Users can't modify the test cases concerned.

**Comment by nicodeur** [comment]
I fixed this issue by fixed #1498 (commit [043e2e5 ](https://github.com/cerberustesting/cerberus-source/commit/043e2e5717a507b08155a3509404254c2f24179f)- Give right on ReadAppService for TestAdmin)
