### ISSUE TITLE
Can't change the name of a duplicated dataLib

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1503]
Hello, 

 Having the possibility to change the name of a duplicated dataLib is no longer possible

![image](https://user-images.githubusercontent.com/29098010/31185261-d3c03348-a92b-11e7-93f6-f61eec37cdcb.png)

**Comment by vertigo17** [comment]
Having a look at the code, I am not sure it ever was possible.
Anyway, here it is but keep in mind that it does not rename the corresponding testcase.
We should do that with care.
