### ISSUE TITLE
Autocomplete CallService newstep

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1504]
Hello, 

The autocomplete is not functional when you add a new step. 

To reproduce : 

1) Create a new step
2) Add a CallService action
3) Type 3 letters of an existing service

=> autocomplete does not work

To make it work : 

1) Create a new step
2) Add a CallService action
3) Save
3) Type 3 letters of an existing service

=> autocomplete works

![image](https://user-images.githubusercontent.com/29098010/31220081-92672070-a9bf-11e7-99ff-d6bc67d6c8e0.png)

**Comment by nicodeur** [comment]
I just commit a fix for this issue
