### ISSUE TITLE
No Key Datas in New DataLibs

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1505]
Hello, 

The key data Field is no longer displayed in new datalibs 

Current : 

![image](https://user-images.githubusercontent.com/29098010/31226836-f6701668-a9d7-11e7-8d4a-f6d0ceb3c119.png)

Wanted : 

![image](https://user-images.githubusercontent.com/29098010/31226863-18b0c934-a9d8-11e7-8b7c-74022d16ef0c.png)

The result is that new DataLibs can't be use anymore

![image](https://user-images.githubusercontent.com/29098010/31227459-34301dca-a9da-11e7-85e0-05da7d61a88b.png)

**Comment by vertigo17** [comment]
Fixed with commit https://github.com/cerberustesting/cerberus-source/commit/e191fd7812f6f55c00886f5ce835e496c60ef9dc
