### ISSUE TITLE
TestCase creation, modify error message

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1507]
Hello,
By launching our daily campaign, we faced a strangely high amount of errors on tests that usually worked just fine. It looks like the TestCase creation is impossible.

In our test, we fill the **Testcase ID** and the **Test case short description** fields with a string containing the **Execution ID** so that every test is unique and do not cause any conflict with existing ones.

However, this error is displaying (screenshot) : 

> The TestCase that you are trying to INSERT conflicts with an existing one! Please check for duplicates! java.sql.SQLIntegrityConstraintViolationException: (conn:128617) Cannot add or update a child row: a foreign key constraint fails.

![readtestcaseexecutionmedia](https://user-images.githubusercontent.com/30227758/31329728-c62f43be-acdb-11e7-900a-28dbe5f665cc.png)

I tried to create a new test case manually only by filling the short description field and let Cerberus assign its ID and gets the same error.

That’s make us think the problem is not in the test case script. Any insights ?
Thanks

Cerberus Version : 1.1.15-SNAPSHOT-1237

**Comment by R-Loic** [comment]
Creation is still available, appliction must be filled.
Wrong error message, should be "Please fill application field" or something like that.
