### ISSUE TITLE
Environment activation selection not correctly loaded on test case header

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1509]
Hi,
The environment activation drop down box selection are not correctly loaded on test case header.

Steps to reproduce:
Created testcase Cerberus-2000A with the following environment activation option:
Active QA: Y - Yes
Active UAT: Y - Yes
Active PROD: N -NO
If we open the tescase URL: http://cerberus.siege.red/Cerberus/TestCaseScript.jsp?test=Cerberus&testcase=2000A and click on the "Edit Test Case Header" and go to the "Activation Criteria" tab we can see that all environment are set as "Yes" (which is not the case!):
![image](https://user-images.githubusercontent.com/17747042/31458583-6955d958-aeb8-11e7-98ee-ba48a362acb9.png)
If we close the "Edit Test Case Header" window and open it again (just close and open - no refresh) now the info is correctly showed (Prod env is set as NO):
![image](https://user-images.githubusercontent.com/17747042/31458880-41d0cb80-aeb9-11e7-98f9-0d99c45c3cdb.png)

Same behavior if we open the testcase header on the "EXECUTION REPORTING BY TAG" page.

This have a huge impact because if we open the testcase header  to change a value (description, comment, label, etc ....) and save it then it will save the test case with all environment activated. We always have to open it twice to ensure the correct values as showed.

From what we could see, this is the only value that is not being correctly displayed/updated on the testcase header.

Also when creating a new testcase the environment by default for PROD was set to "NO" but now it is set as "Yes" by default. 

Cerberus Version: 1.1.15-SNAPSHOT
Database Current Version: 1237

Thanks.

**Comment by vertigo17** [comment]
@ffazendeiro , we will have to check that together as I could not reproduce.
I tested in QA and failed to reproduce.
Anytime I click on Create, the PROD flag is always NO. Anytime I duplicate the testcase, it also default to NO for Production.
When I edit a testcase I always get the right value.

What I detected while trying to reproduce is that warning message on testcase modification is displayed even if in CREATE or DUPLICATE mode which does not make sense. Nothing to do with your issue but still needs a fix.
I corrected it.
