### ISSUE TITLE
send email using soap service

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1510]
Hi, 
i was using a SOAP service to send an email in a testcase.
![image](https://user-images.githubusercontent.com/1914659/31490599-70c31bfe-af3c-11e7-9327-ac72dccee300.png)
![image](https://user-images.githubusercontent.com/1914659/31490604-782bd156-af3c-11e7-8674-931cb4e78e7b.png)

![image](https://user-images.githubusercontent.com/1914659/31490648-93d3cfbc-af3c-11e7-93b8-a81282701857.png)

With the last two cerberus deploys this no longer works. Do you have any ideia why or what needs to be changed? Thanks!

**Comment by R-Loic** [comment]
Hi @ruirpr,
I can see you are using the logo in your mail. Since new logo the url is not the same.
You can use : /Cerberus/images/Logo-cerberus_250.png in your tag pictureUrl.
Tried with SOAP UI works fine!

**Comment by ruirpr** [comment]
Oh thanks a lot, i would never guess it! Working!
