### ISSUE TITLE
Changing Test : Library steps not usable anymore

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1511]
Hello, 

I changed some TC from a "Test" (function) to an other. I tried to open them and got an internal serveur error. 

There were library steps in the TC I moved.  Even if I changed the library step to the new "Test", The column "useStepTest" from testcasestep was not uploaded automatically. It was searching for non exiting datas

Is is possible to make the change for the "useStepTest" column ? 

![image](https://user-images.githubusercontent.com/29098010/31671755-01b1056e-b35b-11e7-89fd-53eee7880b5d.png)

Thank you

**Comment by vertigo17** [comment]
That data is missing data integrity.
I will provide the SQL in order to detect the cases (in case we want to clean them before the fix).
If not, the standard SQL will clean (remove the data with wrong values) and add the integrity link.

**Comment by Galand-V** [comment]
Thank you ! 

I already make the changes on the defective TestCases. But maybe the SQL could be usefull for other people.

**Comment by vertigo17** [comment]
SQL to list the useStep that use an unexisting reference is:

select a.* from testcasestep a
 left outer join testcasestep b on a.usesteptest=b.test and a.usesteptestcase=b.testcase and a.usestepstep=b.step
 where b.test is null and a.usesteptest is not null and a.usesteptest != ''
