### ISSUE TITLE
Add more methods to HTTP REST service

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1512]
Hi,
We have several new test cases that needs to use PUT/DELETE methods.  
Would it be possible to implement all CRUD HTTP Methods for REST Services? (some are already implemented and availebel)
POST - Create (already available)
GET - Read (already available)
PUT - Update/Replace  (to implement)
DELETE - Delete (to implement)

They would be available on the AppServiceList page:
![image](https://user-images.githubusercontent.com/17747042/31674508-de1f4e0e-b359-11e7-955a-53f5b4c499f6.png)

Thanks in advance.

**Comment by vertigo17** [comment]
Test case to implement

**Comment by ryltar** [comment]
add dummy and test case without right method because in prod, we don't have yet listbox feeded by DELETE & PUT

**Comment by nicodeur** [comment]
Waiting release on production cerberus to test and close.
