### ISSUE TITLE
RU char being displayed as ????? in QA

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1514]
Hello,

In QA executing tests from RU the russian chars are displayed as ????
See execution below:
http://192.168.134.197/CerberusQA/TestCaseExecution.jsp?executionId=51625986

Can you check please?
Regards,

Cerberus Version : 2.0.1-SNAPSHOT-1237

**Comment by ryltar** [comment]
It's done !  it's due to glassfish configuration. we need to change it

**Comment by j0hnsa** [comment]
no longer present
