### ISSUE TITLE
Can't delete a TC from the TestCaseList

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1517]
Hello, 

The button delete TC from the "Test Case List" page is no more functional. 

The delete action is functional on the "TestCase Script" page

![image](https://user-images.githubusercontent.com/29098010/31896336-c65f7550-b813-11e7-8a45-68eb225fec3a.png)

**Comment by vertigo17** [comment]
Test Case to implement.

**Comment by nicodeur** [comment]
Hi,
On `PUT` and `DELETE`, you have to create a dummy service test.

You can see witth @vertigo17 for more explaination.

**Comment by ryltar** [comment]
this Test Case is already implemented with the Test Case ID 0017A
