### ISSUE TITLE
cerberus is hanging the browser

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1519]
I was looking for a reason for my computer slowliness and was already blaming Microsoft Windows Defender for always consuming a lot of cpu but it turns out it looks like it’s Cerberus. 
After working for a while with several Cerberus tabs in Firefox 56.0 (32-bit), the browser starts to stall and eventually became impossible to work with. Restarting the browser solves the issue. 
Does anyone else is experimenting this issue?

**Comment by R-Loic** [comment]
Hello
Could you be more specific ?
Is it linked to #1499 ?
Thank

**Comment by vertigo17** [comment]
Could not reproduce.
Please reopen with more information if still relevant.
