### ISSUE TITLE
Add and edit button on BugID field just like the one to edit the tag

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1520]
Hello.

I think that adding and edit button on BugID field just like the one to edit the tag would be really useful and save some clicks (4 at least)

![imagem](https://user-images.githubusercontent.com/16339891/32058081-017dcda4-ba61-11e7-84aa-1197e633de3a.png)

Cerberus Version : 1.1.15-SNAPSHOT-1237

**Comment by R-Loic** [comment]
Hello,

I think it would be interesting to add a new button "Edit test case header" in execution detail : 
![image](https://user-images.githubusercontent.com/18569182/32173007-d4420a24-bd7d-11e7-8177-6fcc90dcab8e.png)
to make appear the edit modal : 
![image](https://user-images.githubusercontent.com/18569182/32173061-fc62bd3c-bd7d-11e7-9882-5f52fb891586.png)
In that case, you could modify the bugID easily.

**Comment by vertigo17** [comment]
Fixed following last commit from @ryltar .
