### ISSUE TITLE
BUG on queue - SRV types

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1521]
Hello, 

SRV campaigns are stoping during the execution : 

![image](https://user-images.githubusercontent.com/29098010/32098357-ad968a58-bb0c-11e7-966c-d557ffd3bc29.png)

The error message is the following : 

![image](https://user-images.githubusercontent.com/29098010/32098383-c7dd1878-bb0c-11e7-8c01-1c032e7575fb.png)

Bad answer format. Expected 'RunID = ' in the output result. Probably due to bad cerberus_url value. Check server logs

This is not link to this specific campaign and is reproducible on other applications

**Comment by vertigo17** [comment]
Was due to a local instability of 1 glassfish instance.
