### ISSUE TITLE
Rework Test in Cerberus

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1522]
Hello,
Is it possible to link TEST to the application (not transversal) ? And rename it as function ?
Why ? 

- The name TEST is not user friendly. Bit confusing for new users / Hard to explain.
- TEST is supposed to be a function so attached to an application.
- Transversal TEST require a perfect communication between teams using Cerberus. Hard to use in practise.
- It would bring a clearer organisation  in Cerberus

Thank you

**Comment by Galand-V** [comment]
This is a good idea @R-Loic !

**Comment by SeniorCanard** [comment]
This would be great!

**Comment by vertigo17** [comment]
Renamed to test folder in order to be less confusing and no longuer mandatory to create them before the test case so you don’t need to synchronize its usage.
