### ISSUE TITLE
Interactive tutorial

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1523]
Hello @nicodeur 

We were talking about this idea, it could be great to add an interactive tutorial for first use of Cerberus.
What do you think @bcivel , @vertigo17 ?

Thanks!

**Comment by nicodeur** [comment]
Hi @bcivel , @vertigo17 , @R-Loic 

I found this js framework to do it : 
* http://introjs.com/ (my prefer !)
* http://guide-js.amireh.net/basic/quickstart.html

I think that shoud be a real added value for cerberus begginer !

**Comment by nicodeur** [comment]
Hello,

I just commit the feature. Please open new issue if you found a bug.

Thanks
