### ISSUE TITLE
appium_swipeDuration parameter

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1524]
Hello,
Cerberus action swipe doesn't work correctly with IOS (version 10.3.2) and Appium (1.7.1)
with CUSTOM coordinates or UP value. Only for a page in our application. (Works for others)

When analyzing with inspector we found out there was a wait implemented with Cerberus : 
Action without Cerberus / with Cerberus below : 

[XCUITest] Received the following touch action: press(options={"x":149,"y":451})-moveTo(options={"x":5,"y":-388})-release(options={})
[XCUITest] Found matching gesture: **scroll**

[XCUITest] Received the following touch action: press(options={"x":149,"y":451})-wait(options={"ms":2500})-moveTo(options={"x":5,"y":-388})-release(options={})
[XCUITest] Found matching gesture: **drag**

This wait in log is in fact the following parameter : _appium_swipeDuration_
We can see the matching gesture is scroll or drag depending of the wait parameter.

We set the value to 0 and now it works for this page. (and still works for the others and for Android)

Should we remove this parameter from Cerberus? Is it used for other actions ? Why was it implemented ?

## Inspector (OK):

XCUITest] Executing command 'getScreenshot'
[JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8100/session/A7FE6C02-874B-43CF-B3A6-74EB8FB98A44/screenshot] with no body
[JSONWP Proxy] Got response with status 200: "{\n \"value\" : \"iVBORw0KGgoAAAANSUhEUgAAAoAAAARwCAYAAAB6j+UAAAAAAXNSR0IArs4c6QAA\\r\\nABxpRE9UAAAAAgAAAAAAAAI4AAAAKAAAAjgAAAI4AAZT\\/I2uFCYAAEAASURBVHgB\\r\\n7L0HeF5HlT6e6t57792WJVnNTZZkWd2yJVlucpHl3h3HdmInTpwekgAJEFpYEsoC\\r\\nS4clsAsLC0vbZVmWGgjpdqpjJ06D3d+283\\/fkd\\/kMNxPkpPAn+fJp+e5z5k558yZ\\r\\nufN9936vzsw5c56l\\/9IzkJ6B9AykZyA9A+kZSM9AegbeUjNw3lvqbtM3m56B9Ayk\\r\\nZyA9A+kZSM9AegbSM2BpAJj+EqRnID0D6RlIz0B6BtIzkJ6Bt9gMpAHgW+wDT99u\\r\\negbSM5CegfQMpGcgPQPpGUgDwPR3ID0D6RlIz0B6BtIzkJ6B9Ay8xWYgDQDfYh94\\r\\n+nbTM5CegfQMpGcgPQPpGUjPQBoApr8D6RlIz0B6BtIzkJ6B9AykZ+AtNgNpAPgW\\r\\n+8DTt5uegfQMpGcgPQPpGUjPQHoG0gAw\\/R1Iz0B6BtIzkJ6B9AykZyA9A2+xGUgD\\r\\nwLfYB56+3fQMpGcgPQPpGUjPQHoG0jOQBoDp70B6BtIzkJ6B9AykZyA9A+kZeIvN\\r\\nQBoAvsU+8PTtpmcgPQPpGUjPQHoG0jOQnoE0AEx\\/B9IzkJ6B9AykZyA9A+kZSM\\/A\\r\\nW2wG0gDwLfaBp283PQPpGUjPQHoG0jOQnoH0DKQBYPo7kJ6B9AykZyA9A+kZSM9A\\r\\negbeYjOQBoBvsQ88fbvpGUjPQHoG0jOQnoH0DKRn4M8OAP\\/3f\\/\\/X\\/vu\\/\\/9v+67\\/+\\r\\nn\\/2\\/\\/\\/efr17\\/8R+\\/t\\/\\/8z\\/94tU4Zebq8TG3JeyNXkm32S...
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAoAAAARwCAYAAAB6j+UAAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAAI4AAAAKAAAAjgAAAI4AAZT/I2uFCYAAEAASURBVHgB\r\n7L0HeF5HlT6e6t57792WJVnNTZZkWd2yJVlucpHl3h3HdmInTpwekgAJEFpYEsoC\r\nS4clsAsLC0vbZVmWGgjpdqpjJ06D3d+283/fkd/kMNxPkpPAn+fJp+e5z5k558yZ\r\nufN9936vzsw5c56l/9IzkJ6B9AykZyA9A+kZSM9AegbeUjNw3lvqbtM3m56B9Ayk\r\nZyA9A+kZSM9AegbSM2BpAJj+EqRnID0D6RlIz0B6BtIzkJ6Bt9gMpAHgW+wDT99u\r\negbSM5CegfQMpGcgPQPpGUgDwPR3ID0D6RlIz0B6BtIzkJ6B9Ay8xWYgDQDfYh94\r\n+nbTM5CegfQMpGcgPQPpGUjPQBoApr8D6RlIz0B6BtIzkJ6B9AykZ+AtNgNpAPgW\r\n+8DTt5uegfQMpGcgPQPpGUjPQHoG0gAw/R1Iz0B6BtIzkJ6B9AykZyA9A2+xGUgD\r\nwLfYB56+3fQMpGcgPQPpGUjPQHoG0jOQBoDp70B6BtIzkJ6B9AykZyA9A+kZeIvN\r\nQBoAvsU+8PTtpmcgPQPpGUjPQHoG0jOQnoE0AEx/B9IzkJ6B9AykZyA9A+kZSM/A\r\nW2wG0gDwLfaBp283PQPpGUjPQHoG0jOQnoH0DKQBYPo7kJ6B9AykZyA9A+kZSM9A\r\negbeYjOQBoBvsQ88fbvpGUjPQHoG0jOQnoH0DKRn4M8OAP/3f//X/vu//9v+67/+\r\nn/2///efr17/8R+/t//8z/94tU4Zebq8TG3JeyNXkm32S5uSaYzi/f73v3u1T+n8\r\nOSn799fvfveK+cvLVPbjE49tWJaMdZVJKfN22yq/8srLr45JNpL6IY+66kufne9P\r\n...
[HTTP] <-- GET /wd/hub/session/f33db358-0e32-4221-8391-da9b52c27016/screenshot 200 151 ms - 743454
[HTTP] --> POST /wd/hub/session/f33db358-0e32-4221-8391-da9b52c27016/touch/perform {"actions":[{"action":"press","options":{"x":149,"y":451}},{"action":"moveTo","options":{"x":5,"y":-388}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":149,"y":451}},{"action":"moveTo","options":{"x":5,"y":-388}},{"action":"release","options":{}}],"f33db358-0e32-4221-8391-da9b52c27016"]
[XCUITest] Executing command 'performTouch'
[XCUITest] Received the following touch action: press(options={"x":149,"y":451})-moveTo(options={"x":5,"y":-388})-release(options={})
[XCUITest] Found matching gesture: scroll
[JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/A7FE6C02-874B-43CF-B3A6-74EB8FB98A44/wda/dragfromtoforduration] with body: {"fromX":149,"fromY":451,"toX":154,"toY":63,"duration":0}
[JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"A7FE6C02-874B-43CF-B3A6-74EB8FB98A44","status":0}
[MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/f33db358-0e32-4221-8391-da9b52c27016/touch/perform 200 7736 ms - 76
[HTTP] --> GET /wd/hub/session/f33db358-0e32-4221-8391-da9b52c27016/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["f33db358-0e32-4221-8391-da9b52c27016"]
[XCUITest] Executing command 'getPageSource'

## Cerberus (KO):
 
[debug] [MJSONWP] Responding to client with driver.getWindowSize() result: {"width":320,"height":568}
[info] [HTTP] <-- GET /wd/hub/session/1d7304ce-0639-42ab-928a-f3ee7986de34/window/current/size 200 1991 ms - 98 
[info] [HTTP] --> POST /wd/hub/session/1d7304ce-0639-42ab-928a-f3ee7986de34/touch/perform {"actions":[{"action":"press","options":{"x":149,"y":451}},{"action":"wait","options":{"ms":2500}},{"action":"moveTo","options":{"x":5,"y":-388}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":149,"y":451}},{"action":"wait","options":{"ms":2500}},{"action":"moveTo","options":{"x":5,"y":-388}},{"action":"release","options":{}}],"1d7304ce-0639-42ab-928a-f3ee7986de34"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press(options={"x":149,"y":451})-wait(options={"ms":2500})-moveTo(options={"x":5,"y":-388})-release(options={})
[debug] [XCUITest] Found matching gesture: drag
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8003/session/E9BFFB07-6602-4002-9622-1269B2D430E3/wda/dragfromtoforduration] with body: {"fromX":149,"fromY":451,"toX":154,"toY":63,"duration":2.5}[info] [Xcode]  3139.84s         Use cached accessibility hierarchy for com.Redoute.RedouteIphone
[info] [Xcode]     t =  3139.84s     Use cached accessibility hierarchy for

**Comment by vertigo17** [comment]
Let's check with Appium version upgrade from #1500 if swipe duration better work before removing it.

**Comment by bcivel** [comment]
Fixed with commit on #1547

**Comment by vertigo17** [comment]
Is swipe duration parameter still used ?

**Comment by bcivel** [comment]
Yes I Kept It. 
But using press().waitAction(timeout).moveTo().release() instead of longPress(timeout).moveTo.release() as advised on appium documentation.
