### ISSUE TITLE
[BUG] Correct the "optional" locator for Keypress action

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1526]
Hello, 

It seems like there is an issue on the keypress action.  A working keypress is now returning the following error : 

The test case is cancelled due to lost connection to Selenium Server! Detailed error : Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.sendKeyEvent]

![image](https://user-images.githubusercontent.com/29098010/32216732-0d1ced16-be26-11e7-96e1-4aae3b931618.png)
executionId=52233517

Thank you

**Comment by Galand-V** [comment]
The error message can also be the following : 
![image](https://user-images.githubusercontent.com/29098010/32216987-dc6224c4-be26-11e7-8515-4432fae5c033.png)

The test case is cancelled due to lost connection to Selenium Server! Detailed error : b is null

**Comment by MowglieRed** [comment]
Check on QA with the non regression test cerberus (@name of the regression test cerberus).

**Comment by nicodeur** [comment]
Hi,

Firefox version > 47 need marionette (gecko driver). By default, selenium is in 2.x version and don't need a gecko driver in browserStack (issue #1539 )

To do : Correct the "optional" locator for Keypress action
