### ISSUE TITLE
Test timeouts before finish when launched with the Queue (app tests)

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1527]
Hi,

When I trigger multiple executions with the Queue (poolsize=1) and the test takes more than expected (5minutes? -> not sure if its less) the execution will stop before it finishes, what is the parameter that controls this? If i trigger single executions the test completes successfully.

some examples:
http://192.168.134.17/Cerberus/TestCaseExecution.jsp?executionId=52245540
http://192.168.134.17/Cerberus/TestCaseExecution.jsp?executionId=52245630

Regards

Cerberus Version : 1.1.15-SNAPSHOT-1237

**Comment by vertigo17** [comment]
Sorry but I don't see anything wrong the the 2 executions:

For the 1st one, 
the queue was added at 5:47:58 PM by it140258
Execution started 17:47:58 (I guess queue was not busy).
Execution stopped at 17:53:52 after a fatal control.
and queue moved to DONE at 5:53:51 PM

For the 2nd one,
the queue was added at 5:47:58 PM by it140258
Execution started 17:53:16 (I guess queue was not busy).
Execution stopped at 17:58:51 after a failed action.
and queue moved to DONE at 5:58:50 PM

There is a parameter that control the time the queue will wait when calling the RunTestCase service: cerberus_queueexecution_timeout
But in case the execution is still running after that timeout, the execution stay in DONE status that is automatically done after an execution finished.
