### ISSUE TITLE
[Idea] - TestCase > Test naviguation button

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1529]
Hello,

What do you think of adding a button on the test case script editor page that links to the test case list of this test case. Something that would looks like this : 

![image](https://user-images.githubusercontent.com/30227758/32335443-3074bc12-bfed-11e7-9457-9333a1516001.png)

and links to this result : 

![image](https://user-images.githubusercontent.com/30227758/32336090-a3bb0b3a-bfee-11e7-9898-4700320a5e61.png)

The test name seems to be carried in the URL (http://.../TestCaseList.jsp?test=CustomerInvoice) so this button would be a link to this URL with the test name generatd dynamically, right ?

I think it can reduce time navigating between the test cases when implemeting several ones.

Thanks!

**Comment by Nouxx** [comment]
Waiting for clarification on Test

**Comment by vertigo17** [comment]
Added shortcut to TestCase List from TestCase Script Page.
![image](https://user-images.githubusercontent.com/5342048/34916076-e6b4d26e-f931-11e7-9c58-d0b8757083e9.png)
