### ISSUE TITLE
[Idea] - Save Execution Settings in Campaign

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1530]
Hello,

I was thinking about the possibility to link the _**Execution Settings**_ to a campaign but without loosing the ability to edit them in the '_Run Test_' page. Something like '_Execution Settings profiles_' linked to a campaign in a single multiplicty (a campaign can have only one profile and a profile can be attached only to one campaign).

![image](https://user-images.githubusercontent.com/30227758/32336918-e8bf6c88-bff0-11e7-9094-23a7ad1e76ab.png)

So that when we click on _**Save Execution Parameters**_, it will save it into the campaign. This can avoid wrong parameters mistakes to non experienced users since these parameters will be set by default by the team who implement the campaign.

**Comment by vertigo17** [comment]
Yes we could add those parameters inside the campaign definition.

![image](https://user-images.githubusercontent.com/5342048/32354689-1f4fe928-c02b-11e7-81bb-bb3aeda9ebcd.png)

We could also add the robotname and add variables in tag definition in order to get a new tag name for each campaign execution. Something like %TIMESTAMP%

**Comment by MowglieRed** [comment]
Execution settings : add a new occurrence in Verbose : empty. If empty, we take the parameters of the campaign.

**Comment by Nouxx** [comment]
Done

**Comment by vertigo17** [comment]
Why did you close that issue ?
For me, we still need to add the parameters inside campaign. 
They should be added into a ned tab. 
Parameters to create are : verbose, screenshots, priority, tag, manual,...

**Comment by vertigo17** [comment]
Available in last release.
