### ISSUE TITLE
bigger screenshot icon

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1532]
Hi, sometimes it's hard to click on the screenshot icon and the word screenshot does not have a link. Can you improve it please? Thanks
![image](https://user-images.githubusercontent.com/1914659/32370667-d4709a50-c085-11e7-8ab2-ddb15a9a1b3c.png)

**Comment by vertigo17** [comment]
Can you provide the link to the execution ?
Just to check that the reason is that the ratio of the picture is too low/high.
A fix has already been made (https://github.com/cerberustesting/cerberus-source/commit/a4ffe0d1534de48657350d9e3012d9dd34999503) that should be in QA for that.

**Comment by ruirpr** [comment]
Example here in step 9.1
http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=52540414

**Comment by vertigo17** [comment]
Confirmed the issue is linked with ratio of the image.
Can you try to reproduce in QA ?
http://X.X.135.30/CerberusQA/
The fix mentioned should solve it.

**Comment by vertigo17** [comment]
Any feedback on that issue? Can you confirm it is fixed in new QA with latest version ?

**Comment by ruirpr** [comment]
Sorry, does not seem very ok 

![image](https://user-images.githubusercontent.com/1914659/33661450-d3383940-da7f-11e7-92f2-07d994942dea.png)
Something like this will be fine, just show a bit of the image top or simply put the link in the word screenshot. 
![image](https://user-images.githubusercontent.com/1914659/33661551-567fedde-da80-11e7-9683-248c1868d3c9.png)

Thanks!
