### ISSUE TITLE
Add fields to the robot edition / crypt password field

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1536]
Hello, 

Can you add/change : 
- a password input field to the robot modal 
- an Username input
- a Host field
- an url being the combinaison of the 3 previous field. This field should not be editable directly by the user. 

![password field](https://user-images.githubusercontent.com/29098010/32450909-ca34c07e-c315-11e7-81a0-9042d021064c.jpg)

After the edition of the robot the password field should be crypted : 

![password field 2](https://user-images.githubusercontent.com/29098010/32451009-131f19ec-c316-11e7-845c-68b05b3a0849.jpg)

**Comment by nicodeur** [comment]
Hi @Galand-V, @bcivel, @vertigo17 

I propose to added a new button on `Robot` Page. We can imagine to add this button at several place on Cerberus.
![image](https://user-images.githubusercontent.com/6707556/32950133-8da80470-cba5-11e7-9eeb-af933065b1ed.png)

This screen will ask : 
   - a select box to modify easily manage password already complete by users. (By default on `New password`. For exemple, select bos should contain `myselenium.com:5623`, `myrobot.net:8465`, `192.168.45.3:2565`, `New Password` (to create a new user/pwd)
   - Host (automaticaly completed by robot information or by host selected with the select box)
   - Port (automaticaly completed by robot information or by host selected with the select box)
   - Username
   - Password

We can persist it into the database by : host_password(id, host, port, username, password)
We will be find how hide the password (an encrypt-decrypt algo ?)

With this solution, we can image to use the username/password on all application, not only for robot part (Like Jenkins credentials). Indeed, user/password is not link to a robot, but is link to a host/port.

What do you think about it ?

Nicolas
