### ISSUE TITLE
Services library and SQL library must be closed to non administrator users

### ISSUE THREAD

**Issue by fchaabani** [cerberustesting/cerberus-source#1537]
Hello,

As Cerberus user with no administrator access I can access to services library and SQL library pages using direct URL, I think these 2 URLs must be disabled for no administrator users by adding an error message.

![readtestcaseexecutionmedia](https://user-images.githubusercontent.com/33456029/32497296-61aa3ebe-c3cc-11e7-8be6-a3618bafa04b.png)

thanks,

**Comment by vertigo17** [comment]
This page is not linked with Administrator but IntegratorRO Profile.
