### ISSUE TITLE
Database maintenance page must be closed to non administrator users

### ISSUE THREAD

**Issue by fchaabani** [cerberustesting/cerberus-source#1538]
Hello, 
As Cerberus user with no administrator access I can access to Database maintenance page using direct URL, I think that this page must be disabled for no administrator users by adding an error message.

![image](https://user-images.githubusercontent.com/33456029/32501638-cdf0553e-c3d8-11e7-9cac-6b4a6188ed15.png)

Thanks,

**Comment by vertigo17** [comment]
Unfortunatly, that cannot be done as the 1st time cerberus is used, Cerberus does not know what user is administrator until database is create but that require the database to be created....
Correct me if I am wrong but there should be no risk leaving that page open for everyone considering that the scripts must be executed each time a deploy is made. Cerberus Administrator should do that action right after the deploy and before any user connect to the system.
Please reopen if you think I missed something and if there is a real issue in leaving that page open for non administrator.

**Comment by gmoita** [comment]
I would also like to have it "locked" to non-admin users.
Can it be locked to non-admin users if the `user` table is accessible and the user id is not an admin?

**Comment by vertigo17** [comment]
This piece of code is not managed inside cerberus but inside the security framework used. 
I guess it is possible but not obvious. 
1st question is more why do we want to restrict this access ?
What do we fear a standard user could do accessing this page ?
