### ISSUE TITLE
Canceled ExecutionQueue TC's displayed on ReportingExecutionByTag

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1542]
Hello,

I think it would be nice if we cancel a campaign execution in the middle of its execution that the tests that still haven't run remain on reporting page so that we could re-submit just those that did not execute. Maybe by creating a button force to Error in TestCaseExecutionQueueList page.

Regards
Cerberus Version : 2.1.0-SNAPSHOT-1249

**Comment by vertigo17** [comment]
Good idea.
