### ISSUE TITLE
Unable to scroll to bottom on some TestCaseExecution pages (CerberusQA)

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1546]
Hello,

I'm having issues scrolling down on some TestCaseExecution pages, take a look at this example:

http://192.168.135.30/CerberusQA/TestCaseExecution.jsp?executionId=39918100

Regards

Cerberus Version : 2.1.0-SNAPSHOT-1249

**Comment by ryltar** [comment]
f9df786adc22b1ebb2e4be4f33aa7282730275b7

this issue appeared when we have long execution details step.
I think that, this issue is solved;

http://192.168.134.197/CerberusQA/TestCaseExecution.jsp?executionId=52540890
