### ISSUE TITLE
Properties sorting : left panel != than right panel

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1549]
Hello, 

It would be usefull to have the same sorting from the left panel and the right panel : 

![image](https://user-images.githubusercontent.com/29098010/32836757-2e912ab6-ca0b-11e7-9897-6d69e4e5d8a4.png)

Thank you 

#1371

**Comment by ryltar** [comment]
I checked and this problem is solved but not the commit is not pushed on PROD environment
