### ISSUE TITLE
[REQUIREMENT] Execution report by TAG - add Report by label

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1551]
Cerberus Version : 2.0.0-1237

Hello,

Can you add a **Report by label** into the "Execution report by TAG" please ?
==> like as Report by Function & Report By Application Environement Country Browser

Thank you

**Comment by vertigo17** [comment]
What I suggest here is that we implement for both STICKER and REQUIREMENT Labels a new panel inside ReportingByTag screen that will list all Labels linked with tag execution and for each of them specifi the result of the full campaign execution.
The layout would be similar to "Report By Application Environment Country Browser" but without any possibility to filter or group as the full list of label would be displayed.
The label hierarchy would be used. ie : parent label would take the full scope of execution of all child labels (with possibility to collapse and expand).

![image](https://user-images.githubusercontent.com/5342048/33807436-5bee5436-ddd7-11e7-9673-2adbc25b1710.png)

**Comment by bcivel** [comment]
Done.
Still pending to report the hierachy but is followed by the ticket #1572
