### ISSUE TITLE
Display problem on Test case list

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1552]
Cerberus Version : 2.0.0-1237

hello,

There is a display problem after I saved a personalized view on "Test case list". 

**Steps :**
1. Go to Test case list
2. On Show/hide, remove some columns
3. Save view
4. Reload the page 

**Results :** 
Some collums titles are not displayed

![cerb1](https://user-images.githubusercontent.com/33724879/32896558-9a04dd00-cae3-11e7-8ef8-69d8839b75ce.png)

**Comment by vertigo17** [comment]
I was not able to reproduce.
Is that systematic ? Is there a special scenario to reproduce ? Can you provide the browser detail ?

**Comment by glassalle59** [comment]
Now, it reproduces without touching the columns. 
I just go to Test case list, then some collums titles are not displayed

I tried to reset all filters and collums but the result is the same.

I use Google chrome Version 61.0.3163.100

**Comment by vertigo17** [comment]
I also never manage to reproduce.
Maybe clean the userPreferences column in user table in order to reset display preferences saved.
It could fix the issue.
If problem still exist, please reopen and detail more the column that you hide before saving in order to try to reproduce.
