### ISSUE TITLE
Problem on the function of Show/Hide 

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1553]
Cerberus Version : 2.0.0-1237

hello,

There is a display problem on the function of Show/Hide 

Steps :

Go to Test case list (or other menu)
Move columns between them
Click on Show/Hide button

Results :
The list is broken

![cerb2](https://user-images.githubusercontent.com/33724879/32897056-e381645c-cae4-11e7-892e-9b2cbe1c3c38.png)

**Comment by ryltar** [comment]
@glassalle59  Hi, can you give me your version of cerberus ?

**Comment by glassalle59** [comment]
Cerberus Version : 2.0.0-1237
