### ISSUE TITLE
Custom swipe not working in the new QA

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1558]
Hi,

When custom swipe is done one error is thrown: **nrecognized selector sent to instance 0x1b3716ef8**

This is important as for instance all tests for RU failed cause I'm unable to make visible russia in country selection page.

[debug] [MJSONWP] Responding to client with driver.getWindowSize() result: {"width":320,"height":568}
[HTTP] <-- GET /wd/hub/session/80a1d72a-bcd4-48e3-b882-f238a35f2508/window/current/size 200 322 ms - 98
[HTTP] --> POST /wd/hub/session/80a1d72a-bcd4-48e3-b882-f238a35f2508/touch/perform {"actions":[{"action":"longPress","options":{"x":153,"y":546,"duration":0}},{"action":"moveTo","options":{"x":153,"y":343}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"longPress","options":{"x":153,"y":546,"duration":0}},{"action":"moveTo","options":{"x":153,"y":343}},{"action":"release","options":{}}],"80a1d72a-bcd4-48e3-b882-f238a35f2508"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: longPress(options={"x":153,"y":546,"duration":0})-moveTo(options={"x":153,"y":343})-release(options={})
[debug] [XCUITest] Found matching gesture: drag
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8003/session/D91CF8E4-58C2-42DF-93E5-74E0FE9FE18F/wda/dragfromtoforduration] with body: {"fromX":153,"fromY":546,"toX":0,"toY":0,"duration":null}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"-[NSNull doubleValue]: unrecognized selector sent to instance 0x1b3716ef8\n\n(\n\t0   CoreFoundation                      0x000000018d442ff8 <redacted> + 148\n\t1   libobjc.A.dylib                     0x000000018bea4538 objc_exception_throw + 56\n\t2   CoreFoundation                      0x000000018d449ef4 <redacted> + 0\n\t3   CoreFoundation                      0x000000018d446f54 <redacted> + 916\n\t4   CoreFoundation                      0x000000018d342d4c _CF_forwarding_prep_0 + 92\n\t5   WebDriverAgentLib                   0x0000000102193490 +[FBElementCommands handleDragCoordinate:] + 600\n\t6   WebDriverAgentLib                   0x00000001021744c8 -[FBRoute_TargetAction mountRequest:intoResponse:] + 208\n\t7   WebDriverAgentLib                   0x000000010216c344 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496\n\t8   RoutingHTTPServer                   0x000000010221e3cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144\n\t9   RoutingHTTPServer                   0...
[HTTP] <-- POST /wd/hub/session/80a1d72a-bcd4-48e3-b882-f238a35f2508/touch/perform 500 24 ms - 5174
[HTTP] --> GET /wd/hub/session/80a1d72a-bcd4-48e3-b882-f238a35f2508/screenshot {}

Regards,
Cerberus Version : 2.1.0-SNAPSHOT-1250

**Comment by Nouxx** [comment]
Is the Selenium version (robot side) is 2.53 or later ?

**Comment by bcivel** [comment]
Hello @j0hnsa 
I pushed a small change. Can you have another try please?
Which appium server version are you using?

**Comment by bcivel** [comment]
I think it could be linked to https://github.com/appium/java-client/issues/762

**Comment by MowglieRed** [comment]
Closed. Already opened with the numer #1547
