### ISSUE TITLE
Search by "TC short description" on TC List screen returns 0 answer

### ISSUE THREAD

**Issue by SeniorCanard** [cerberustesting/cerberus-source#1560]
Sometimes, filters on TC List screen returns 0 results. Here are the details :  

1. I use the "Search..." input in the 'TC short description' column of the 'TC List' screen.
2. The autocompletion finds results.
3. I validate the research.
4. The TC List reload but return 0 answer.

PS : I have no other filter

**Comment by vertigo17** [comment]
We will fix that by implementing a new filter that will no longuer perform a distinct of the column but allow a full text search 'like'
@ryltar already started to work on that:

https://github.com/cerberustesting/cerberus-source/commit/58d603cb5b765eef4a04bbc1d4d65460e76e143c
