### ISSUE TITLE
Send and retrieve file by ftp - new service

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1562]
Hi,

Would it be possible new service for FTP?

The idea is to transfer by FTP a file to test SB that need a file on a specific folder to trigger the execution. 
for this new service we could have the following option:
Get - retreive a file (using name and path) using ftp and store it in menory
Send - send a file (using path) by ftp
Create and send - Create a file (using Cerberus property for the path and name) and send it by ftp
And some properties that could be defined for the service: FTP server (IP); FTP port; FTP user; FTP password; FTP path; File Name (optional); File Path (optional)

In order to protect some misuse of this method we can have a new Parameter key (or somewhere were the access is limited to adm users only) with the list of allowed ftp servers. For example:
**Parameter**: _ftp_allowed_servers_ 
**Cerberus Value**: _127.0.0.1,192.168.134.1,192.168.134.*_

I know that this could be implemented using a WS but it would be interesting to have this functionality available on Cerberus. I let this improvement at your consideration.

Thanks in advance.

**Comment by ryltar** [comment]
- [ ] implement proxy
