### ISSUE TITLE
Variables in properties options

### ISSUE THREAD

**Issue by Heychsea** [cerberustesting/cerberus-source#1563]
Hello,

I would like to be able to put a variable like %property.Length% in the Length option.
![image](https://user-images.githubusercontent.com/26014721/33596660-b2d6f972-d99c-11e7-8266-d715faae8220.png)

Thank you.

Cerberus 1.1.14-1221

**Comment by ryltar** [comment]
Is that issue linked with #1424 ? You can now use %property.% on the length field (Snapshot of Cerberus).
