### ISSUE TITLE
wrong html title in edit testcase

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1566]
Hi, not sure why but the edit testcase page shows the wrong title and it can be confusing when using several tabs. Is it possible to fix? Thanks

![image](https://user-images.githubusercontent.com/1914659/33661774-4b57ba3a-da81-11e7-9af2-1bbde5b803c5.png)

**Comment by vertigo17** [comment]
This is linked with the fact that we include js/pages/TestDataLib.js inside TestCaseScript.jsp.
@ryltar , can you check which js function is used in the js file from testCaseScript page and either move them to js/transversalobject/DataLib.js either stop using them and use the already existing in js/transversalobject/DataLib.js
