### ISSUE TITLE
Duplicate Queue execution - Robot change

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1567]
Hello,

From the execution report by tag, I need to relaunch some executions on an other Robot. To do so, I go to Run this test case again > Duplicate New Execution > Robots Settings 

![image](https://user-images.githubusercontent.com/30227758/33759287-16bbc640-dc02-11e7-80a0-a539f40b50df.png)

If I select an other Robot the settings below are not modified. (hidden field have the same value as the previous ones) 

![image](https://user-images.githubusercontent.com/30227758/33759387-64adfc42-dc02-11e7-8363-742cacf0e542.png)

If I duplicate the execution with a new robot anyway, I can see in the Robots Settings of the duplicated execution that the change has been done. 

Maybe it should be interessting to load dynamically all the Robots properties ?

Thanks !

**Comment by vertigo17** [comment]
In order to avoid overwrite the values that are coming from the queue, I did not replace them by robot value.
In stead I disable the fields that are not used when robot is defined in order to show that they will not be used.
