### ISSUE TITLE
Testcase History

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1570]
Hello,

What do you think of setting up an '_**archive**_' for testcase that will save all the content of the testcase (header and script) and version it. That would allow to retrieve the previous testcase and restore it.

After each save, a new version would be created and added to the testcase history.

The section would be accessible from the script page (new Tab : History)
![image](https://user-images.githubusercontent.com/30227758/33770581-75706ec6-dc2e-11e7-9192-86a2c264145a.png)

Each entry would be displayed as : 
- date and time
- version # (from 0 to inf)
- a _**preview**_ button which will redirect to a _TestCaseScript.jsp_ page with the loaded previous data
=> by saving this preview, it will override the current testcase. 

This function could be accessible only with the appropriate access level. 

I believe it will help users that lose their data because of a disconnection (internet failure, expired session...), which is exactly what happened to me

**Comment by vertigo17** [comment]
Not really sure to understand the real need.
How can testcase history and version management can solve a data loss in case of internet failure ?

**Comment by Nouxx** [comment]
If the session is expired, there is no popup message or anything that warn you that if modify your testcase, everything will not be saved. In this case, maybe the latest version of the testcase would be saved anyway in the 'history' to be restored after ?

I also forgot to point out a situation that can happened sometimes but is mainly due to bad practises : I sometimes open several testcase page (Test Case Script) of the same testcase, do my modification on one tab, save it and eventually click on save on the other tab with the previous version. In that case version management would be really convenient, but it can be avoid just by not opening two tab of the same testcase as well.

Besides, when analysing a failed testcase, we would be able to know when was the last modification of its script.

**Comment by ruirpr** [comment]
> Besides, when analysing a failed testcase, we would be able to know when was the last modification of its script.

This is important. Currently we know who modified and when (this is working correctly, right?) but it would be good to know what's been changed.

**Comment by vertigo17** [comment]
Yes tracability tab under testcase header will give you who and when creation and last modification occured.
![2018-01-02 12_15_35-testcase - 0001a](https://user-images.githubusercontent.com/5342048/34482172-b399af6e-efb6-11e7-808a-eb042fd1979e.png)

On top of that, the log button gives all change even that happened on that testcase.
![2018-01-02 12_15_02-log viewer](https://user-images.githubusercontent.com/5342048/34482176-b6490854-efb6-11e7-81e1-8bba62044eaf.png)

If it does not give you the precise content that has been modified, it tells you who and when any change was performed.
I guess with that this is quite easy to ask the people that did modify the test.
On top of that every execution is keeping a lot of data from the test case definition (description, actions with value1 and value2 fields as ex). In theory, that make the historisation of the testcase at the execution level. Adding a new level of historisation seems to me very complex compared to the added value of existing solution.
I would prefer to enrish the execution structure to add potencial missing testcase data. Are there any ?

**Comment by Nouxx** [comment]
I agree with @vertigo17 eventually, we don't need to spent too much time on this.

My idea was to:
- Add a 'version' field to any testcase. As soon as a modification is made in a testcase, the version is incremented
- Display every version in the 'History' table with no need to create a new table to store these version content since it can be found in the latest executions.

I just think that the link between the version and its content will be tricky to implement and require a new table. 

However, for a better User Experience, I would recommend adding a link to the '_Filter on Last Execution_' page. When someone is trying to find history information, he would naturally go in 'Tracability' but would maybe not think to check in last executions. It would act as a Reminder. 

What do you think ?
