### ISSUE TITLE
Optimize filters 2 - condition filtering

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1571]
Hello, 

Currently, if you want to filter 2 columns, the first column will search in the entire DB  and **the second column will also search in the entire DB**. The result will be an "AND" of the 2 columns. 

Is it possible that the second filter search only in the first column results to avoid long requests ? 

![image](https://user-images.githubusercontent.com/29098010/33769713-79c4afb2-dc2b-11e7-88ca-ff00cd1e0420.png)

**Comment by ryltar** [comment]
I found two cases that it's not possible to use this condition filtering :  

- When we use a client side table
- When we load a list of invariants in the filter list (because no disctinct value of column from current sql table is done)
