### ISSUE TITLE
Change the definition of the "Description" Column in the appservice table

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1577]
Hello, 

I would like to create a new service and add a **full description** of it for other users to understand. I could not do that because the description is limited to 1000 caracters. 

Can you review this column limit  ?

![image](https://user-images.githubusercontent.com/29098010/34102272-c558052c-e3e8-11e7-8cc9-34f3b36fffee.png)

**Comment by vertigo17** [comment]
I propose to add a TEXT field as Long Description.
That Long description would only be displayed inside the Service modal.
Would it be OK ?

**Comment by Galand-V** [comment]
I will discuss it with my team members but I think the purpose would be fullflied

**Comment by Galand-V** [comment]
After discussing it, it would be a good idea !
