### ISSUE TITLE
DB propositions after installation 

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1579]
Hello, 

It seems like there is something wrong with the default DB just after a Cerberus installation : 

![image](https://user-images.githubusercontent.com/29098010/34214010-620de9c2-e5a1-11e7-8a1d-8953b03f101d.png)

![image](https://user-images.githubusercontent.com/29098010/34214048-89ba715c-e5a1-11e7-9b1d-d0ed292f2d75.png)

**Comment by vertigo17** [comment]
I only left a EXAMPLE Databse.
