### ISSUE TITLE
editing testcase header erases the test description

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1580]
If we click the Edit Test Case Header before the add step button loads completely the test description will not be loaded and sometimes this can lead to lose this kind of information. Shouldn't this button be disabled just like add step button until it loads all the test?

I've ran into this problem with the following test:
http://cerberus.siege.red/Cerberus/TestCaseScript.jsp?test=ANDROID&testcase=0017A_8.0_Sm

Regards

Cerberus Version : 1.1.15-SNAPSHOT-1237

**Comment by vertigo17** [comment]
I was not able to reproduce the issue.
Can you test on latest version and detail more the steps on how to reproduce ?
I tryed to open a 'big' test case script page and click on edit header button but modal always open with description correctly feed.

**Comment by j0hnsa** [comment]
Hello,

This issue is no longer replicated,

Thanks
