### ISSUE TITLE
Notification when the compaign is failed 

### ISSUE THREAD

**Issue by fchaabani** [cerberustesting/cerberus-source#1581]
Hello,

Is it possible to have an option to notify only when the compaign is failed ?

![image](https://user-images.githubusercontent.com/33456029/34358593-5ccb02ec-ea51-11e7-9ac1-83a1d8002c4f.png)

**Comment by vertigo17** [comment]
We need to define what failed means.
Should we apply the same rule as resultCI servlet in order to be consistent with CI Tools ?

**Comment by vertigo17** [comment]
Option was added:
![image](https://user-images.githubusercontent.com/5342048/35198484-def62fdc-feef-11e7-93fb-b3ad87bf4d79.png)
