### ISSUE TITLE
recursive calculation detected

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1583]
This is more a doubt than a bug. 

Here's the situation: 
- calculate PRODUCT1 wich is a getfromdatalib returning 136 random results
- enter a loop calculating the property AS400_P_AVAILABILITY_LINE wich is also a getfromdatalib containing

`SELECT IDENTPROD, CODORI, CODSOC, REFPRES, TAIPRES, LIBTAIP, LIBCOR, CODDSPACT, CODDSPFRA
FROM TR2008 
WHERE CODSOC = '1' 
      AND IDENTPROD = '%PRODUCT1.%system.CURRENTSTEP_INDEX%%'
      AND REFPRES = '%PRODUCT1.%system.CURRENTSTEP_INDEX%.Reference%'
      AND NUMDECLI1 = %PRODUCT1.%system.CURRENTSTEP_INDEX%.dim1% --color
      AND NUMDECLI2 = %PRODUCT1.%system.CURRENTSTEP_INDEX%.dim2% --size
      AND CODORI = 'W'`

the execution returns:

> Error on decoding SQL Script linked with a property calculation that went wrong : Recursive calculation of property PRODUCT1 detected. The past property calculated in that context is : [AS400_P_AVAILABILITY_LINE, PRODUCT1]

example execution http://192.168.134.17/Cerberus/TestCaseExecution.jsp?executionId=54025194

---- 

Second situation is exactly the same but with 135 products returned from PRODUCT1 and it works.

example execution here http://192.168.134.17/Cerberus/TestCaseExecution.jsp?executionId=54025564

---- 

So what's the thing with that error message? The only thins that occurrs to me is the json response file being too big. With 135 lines of products it is 64,931 chars in lenght. The error message gives the ideia that PRODUCT1 is being recalculated but I don't think so cince it is calculated once before. 

Thanks!

**Comment by vertigo17** [comment]
Recursive error no longer appear but Goovy error may now appear in stead (in case getFromGroovy is used):

Groovy evaluation error: java.util.concurrent.ExecutionException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 1: String too long. The given string is 70000 Unicode code units long, but only a maximum of 65535 is allowed.
