### ISSUE TITLE
Click on an hidden checkbox - Impossible?

### ISSUE THREAD

**Issue by jordan-arvato** [cerberustesting/cerberus-source#1586]
Hello,

I have a problem when i try to click on a label beside an hidden checkbox.
The click on the label call a JS function that tick or untick the checkbox.

Cerberus do not succeed to do this click action on the checkbox, but it's normal because it's hidden.
But if we want to click on the label, it doesn't work neither.
What is the best way to proceed?

Here is the JSFiddle if you want to see our html and try the JS/jQuery...
XPATH method : https://jsfiddle.net/fqxzcaud/3/
CSS Selector method : https://jsfiddle.net/fqxzcaud/4/

I'm trying to use xPath and CssSelector and none of them are working, we have 2 different result,
here is the first one : 

    - Element 'xpath=<xpath>' clicked.   
We're trying to click on the 'I have read and agreed to...' and that's not working as you can see in the screenshot.

![image](https://user-images.githubusercontent.com/34857892/34665509-b54aa99a-f460-11e7-91b4-5cc31f1f8df5.png)

    - Failed to wait because could not find element 'css=<cssSelector>'!

And we tried with the SeleniumIDE plugin on firefox and by console (JS and jQuery) and that's working well.

Thanks for your answers.
Best regards,
Jordan.

**Comment by bcivel** [comment]
Hello @jordan-arvato 
I tried to do a test on your jsfiddle and it worked fine (See the screenshot below).
Maybe what I can suggest to help you to debug is to set the execution parameter "getPageSource" to 1 or 2. Then, you will have the page source as seen by selenium during the execution.

Beware that the three most common issue for that kind of problem are : 
 - you have more than one element for the xpath specified. Cerberus will click on the first one and report it's ok.
 - your element are inside an iframe. You must switch to the iframe before (action switchToIframe)
 - your element is not fully loaded when Cerberus click on the label. Can you check the execution action response time, and try to add a wait 500 ms before to click on the title.

<img width="1126" alt="capture d ecran 2018-01-08 a 21 27 27" src="https://user-images.githubusercontent.com/5376184/34691189-20a744d6-f4bc-11e7-84b9-e44494f78464.png">
 
Thanks for the feedback

**Comment by jordan-arvato** [comment]
Hello @bcivel, thank you for your answer.

Indeed, that's working with our jsfiddle, I did the fiddle to show you that it works with js and jQuery.
Our website is not exactly the same as the fiddle, the input is hidden and our css/js are not the same.

And that's not one of the three common issue, when we try the xPath on firefox/chrome it shows only 1 result.
That's not under an iframe and I tried to add wait action before executing any actions.

Our input is hidden and just beside the label, and when click on the label is triggered, it ticks the css checkbox.

**Comment by vertigo17** [comment]
Are you able to create a fiddle in order to simulate the Cerberus issue ? Or make that page available for us to test ?
Cerberus is checking that element is visible and clickable before making the click.
On most of the case, that secure that click is really possible to be done by the end user. That allow to detect when test try to click an element that is not visible or can't be clicked from the user (even if in the DOM).

https://github.com/cerberustesting/cerberus-source/blob/2b0aee9f6017040bc971d9c36dd289d9eb6fb0d9/source/src/main/java/org/cerberus/engine/gwt/impl/ActionService.java#L371

**Comment by jordan-arvato** [comment]
@vertigo17  Here is the new fiddle with the full page :  

https://jsfiddle.net/eew3bwen/

Try with cerberus : 

![image](https://user-images.githubusercontent.com/34857892/34723828-3017d3be-f54c-11e7-88f7-846629781066.png)

![image](https://user-images.githubusercontent.com/34857892/34723899-5b74ff46-f54c-11e7-9c73-52bcaa19f24c.png)


Try with the fiddle : 

![image](https://user-images.githubusercontent.com/34857892/34724758-563fb766-f54f-11e7-9a49-9cf324410e1d.png)

Thanks for your answer.

**Comment by bcivel** [comment]
Hello @jordan-arvato ,
I did the same scenario on my side. It works fine on chrome, but not on firefox.
Can you temporarly run it on chrome to unblock the test on your side?

I can't explain why at this moment. Probably due to a bug on the gecko driver of firefox itself. I Still have some investigation to do to provide the reason and an alternative for firefox.

**Comment by jordan-arvato** [comment]
Hello @bcivel, 

Indeed that working with chrome but not with firefox, i'll run my tests with chrome for the time being.

Thank again.

**Comment by ryltar** [comment]
java.util.concurrent.ExecutionException: org.openqa.selenium.interactions.MoveTargetOutOfBoundsException: (286.5, 499.9499969482422) is out of bounds of viewport width (855) and height (455)

It seem that firefox can't scroll down to click on the element.

**Comment by ryltar** [comment]
see this issue :  https://github.com/mozilla/geckodriver/issues/776

**Comment by Galand-V** [comment]
There are several options : 
- Use Chrome web driver 
- Scrolldown with a calculateproperty with GetFromJS 
- Use Sikuli but you can launch only 1 execution on a robot
