### ISSUE TITLE
DEPLOY TYPE mandatory for application

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1588]
Hello,

Currently, deploy type is a mandatory field to create an application : 
![image](https://user-images.githubusercontent.com/18569182/34778095-899d579e-f61c-11e7-81f4-fb445a305316.png)
Is it possible to remove this constraint ? Not sure, this is really important. 
Is there any technical use of this info for executions?
User can still complete deploy type field after creation if needed.

Thank you

**Comment by vertigo17** [comment]
Hello @R-Loic that constrain is already removed on a recent commit
It will be available on next release.
