### ISSUE TITLE
Add screenshots to a manual execution

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1589]
Hello, 

It would be interesting to add screenshots to the manual executions. 

Here is my proposition : 

1) A button upload appears in condition the user detect either a FA or a KO. 

![image](https://user-images.githubusercontent.com/29098010/34782780-fe338c06-f629-11e7-8744-adee12b8c89e.png)

2) Onclick, the popin appears giving the possibility to insert a image file type

![image](https://user-images.githubusercontent.com/29098010/34782899-59c49e84-f62a-11e7-8e7c-788154acdc50.png)

3) After adding the screenshot to the execution, the image (.jpg/.jpeg/.png/...) would appears as the screenshots appears in the automatic executions 

![image](https://user-images.githubusercontent.com/29098010/34782909-625e2f06-f62a-11e7-8e25-66c49e724800.png)

4) If a user wants to see the image fullsize he can just by clicking on it

**Comment by bcivel** [comment]
Hello @Galand-V @ryltar 
I would advise to allow to add a screenshot, whatever the status.
In some case, we can ask tester to add some picture as a proof, even if the test is OK.
Anyway, it's also simpler to implement ;-)
Thanks
Benoit

**Comment by R-Loic** [comment]
Hello @ryltar ,

Just tried this feature on release 3.0.0 
manual execution, added a file : 
![image](https://user-images.githubusercontent.com/18569182/35344527-a72fe698-012d-11e8-8429-31eb307fcf80.png)
Clicked on add => nothing happened : 
![image](https://user-images.githubusercontent.com/18569182/35344571-c7a55ade-012d-11e8-89f1-ac1918584c81.png)

Could you please have a look ? 
(browser chrome)
Thanks !

**Comment by ryltar** [comment]
![image](https://user-images.githubusercontent.com/13577630/35352128-3b29c1ce-0143-11e8-8e2c-7b0b623a0b76.png)

I tried and it's work on my computer.

Can you check the cerberus_exemanualmedia_path parameter ?

**Comment by R-Loic** [comment]
Hi!
The several path seems OK.
cerberus_exemanualmedia_path is well set : /opt/cerberus-screenshots/
docker volume well set :  ./localdata/screenshots:/opt/cerberus-screenshots/

I retrieve the screenshot in my folder screenshot (execution 222)
![image](https://user-images.githubusercontent.com/18569182/35379074-2869da0c-01b5-11e8-8727-f4f0ae5a91fb.png)
But in the GUI, it does not appear :  (/Cerberus/TestCaseExecution.jsp?executionId=222)
![image](https://user-images.githubusercontent.com/18569182/35378999-f4d54032-01b4-11e8-92b7-9a54619e5a4f.png)

**Comment by ryltar** [comment]
Hum, it's very strange, I'm not able to reproduce this issue. (I'm on windows but i tried and the cerberus QA many days ago and it worked). I will re try on cerberus QA when the VM is up

**Comment by ryltar** [comment]
@R-Loic can you check your database in the table testcaseexecutionfile to check if the path is correct in the database (shoud start with 222/ )

**Comment by vertigo17** [comment]
Event better, please provide the full record to check if this is not the level that is not correctly feed.

**Comment by R-Loic** [comment]
In fact the table testcaseexecutionfile wasn't anymore present in the database. This was probably due to my configuration with docker. I switched between nico's dev version and the cerberus 3.0 version.
After re-creation of the DB container and execution of the SQL scripts, everything works fine :)
Thank you for your help!
