### ISSUE TITLE
Stop the TestCase Execution if datalib failed to calculate

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1590]
Hello, 

Is it possible to stop the TestCase execution in case of a failed datalib calculation ? 

![image](https://user-images.githubusercontent.com/29098010/34831116-47636254-f6e6-11e7-9535-da715aec07c3.png)

For example, in this testcase, the property linked to an SQL datalib calculate a customer. The datalib failed but the execution is still running.  In the screenshot below, the testcase should have stopped to the "type the customer datas in ..."

![image](https://user-images.githubusercontent.com/29098010/34831141-625350b0-f6e6-11e7-9073-65a8cf1a3ef4.png)

Also, having the error message 'Data Library entry FR_QA_CUSTOMER (23332) failed' replicate on the "step" tab with a link on the property tab could be much clearer for the user.

**Comment by vertigo17** [comment]
You can secure that the test stops on the corresponding action or control with FA by using syntax: %property.CUSTOMER% in stead of %CUSTOMER%
Please refer to documentation **5.5.5. Variables** for further details.
Message will detail which property could not be decoded.
