### ISSUE TITLE
Control 'verifyRegexInElement' is not supported for application type 'SRV'.

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1592]
Cerberus Version : 2.0.0-1237

Hello,

Could you please add this feature : Control 'verifyRegexInElement' on SRV application

**Comment by glassalle59** [comment]
Now I have these errors : 

If response is on XML Format 
Message type XML not supported for control 'verifyRegexInElement'.

If response is on JSON Format :
Message type JSON not supported for control 'verifyRegexInElement'.

**Comment by bcivel** [comment]
Hello @glassalle59 .
This should be fixed now.
Thanks
Benoit
