### ISSUE TITLE
%system.SSIP% & %system.SSPORT% are not supported for application type 'SRV'

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1593]
Cerberus Version : 2.0.0-1237

Hello,

Could you please add the use of "Selenium server IP" & "Selenium server port" variables (robot settings on Execution) on SRV application.

=> 

%system.SSIP% | Selenium server IP
%system.SSPORT% | Selenium server port

**Comment by ryltar** [comment]
Hi,

I'm not sure to understand what you want to do, because, when you launch a testcase linked to a SRV Application, you don't need to use a robot, that's why you can't use %system.SSIP% & %system.SSPORT%

**Comment by glassalle59** [comment]
Sorry, it was a mistake, you can remove the issue
