### ISSUE TITLE
Bad popup size on Test case list page

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1596]
Hello,

clicking Show/Hide button on

http://192.168.134.17/Cerberus/TestCaseList.jsp?test=ANDROID

a huge popup is diplayed.

Regards

Cerberus Version : 1.1.15-SNAPSHOT-1237

**Comment by ryltar** [comment]
Hi,
#1553
 
This issue is solved in the current version of cerberus
