### ISSUE TITLE
Can't modify property value

### ISSUE THREAD

**Issue by mviaene** [cerberustesting/cerberus-source#1597]
Hello,

Screen : "Properties" tab on "Edit Test Case" screen

Cerberus version : V2.0.0-1237

Problem : 
We can't modify the property value for a property which has a special character in its name (ex : é, à, ç, è, ...).

Workaround :
We can modify the property name and then modify its value

Best regards,
Maxime

**Comment by ryltar** [comment]
![image](https://user-images.githubusercontent.com/13577630/35036563-0a1a1486-fb75-11e7-8760-6e75bad155c9.png)

I create a property "tést", i modify the value of it and it's work and the latest version of cerberus

**Comment by mviaene** [comment]
Thank you for the feedback.

Cerberus2.1.0 is a SNAPSHOT for the moment so I'll wait the release and test again once the upgrade done.
I'll close the issue at this moment.

In the meantime, the problem isn't a big deal and I shall pay attention in the name of my properties ;)

**Comment by ryltar** [comment]
we will do a release as soon as possible :)

**Comment by vertigo17** [comment]
Release has been done.
Please reopen in case still not fixed.
