### ISSUE TITLE
Use AddToExecutionQueueV001 to test a System

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1599]
Will this be possible to use for launching tests for a system (ex: VCCRM)?

Regards

**Comment by vertigo17** [comment]
In order to do that you can create a VCCRM campaign adding as criteria parameter SYSTEM and value VCCRM.

![2018-01-18 12_14_55-testcampaign](https://user-images.githubusercontent.com/5342048/35095593-e4d33154-fc40-11e7-8c37-299bc95c0851.png)
