### ISSUE TITLE
Wrong environment loaded with rerun button

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1602]
Hello,

When I click on the Rerun button in test case script, it opens the run page with a wrong environment, it adds an ' at the end. (Execution cannot be launched)
![image](https://user-images.githubusercontent.com/18569182/35431664-a57f0bfc-027d-11e8-80a9-30569abc7b0b.png)

![image](https://user-images.githubusercontent.com/18569182/35431684-b8e1905c-027d-11e8-92fa-ce5a5a4b62c7.png)

![image](https://user-images.githubusercontent.com/18569182/35431696-c89a7874-027d-11e8-9b51-c98898dfed0a.png)

Could you have a look please ?
Thanks ! 

Cerberus Version : 3.0.0-1285

**Comment by ryltar** [comment]
Hi,

I will check that !

**Comment by ryltar** [comment]
it's fixed ! :)
