### ISSUE TITLE
order alphabetically actions and controls dropdown fields

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1604]
Hello,

Is is possible to order alphabetically the action and controls dropdown fields?

![imagem](https://user-images.githubusercontent.com/16339891/35738714-911dcc02-0827-11e8-9552-c1dc87f3d340.png)
![imagem](https://user-images.githubusercontent.com/16339891/35738753-affc8aaa-0827-11e8-9ad1-56583d1c0a3a.png)

Regards

Cerberus Version : 3.1.0-SNAPSHOT-1286

**Comment by vertigo17** [comment]
The today logic is that the list is sorted by type of actions.
That way, all click related actions are all together (click, doubleclick, rightClick, ...), then all actions linked with frame and windows, then url related.
Unknow is always on top and deprecated action/control in the bottom.
If we sort it alphabeticaly, we lose the visibility of all possible actions with no other choice that reading the full list to check if a specific action exist. That will also mix selenium action with sikuli. 

**ACTION standard sorting :**
'Unknown'
'click'
'mouseLeftButtonPress'
'mouseLeftButtonRelease'
'doubleClick'
'rightClick'
'mouseOver'
'mouseOverAndWait'
'focusToIframe'
'focusDefaultIframe'
'switchToWindow'
'manageDialog'
'openUrlWithBase'
'openUrlLogin'
'openUrl'
'openApp'
'closeApp'
'select'
'keypress'
'type'
'hideKeyboard'
'swipe'
'wait'
'waitVanish'
'callService'
'removeDifference'
'executeSqlUpdate'
'executeSqlStoredProcedure'
'calculateProperty'
'doNothing'
'getPageSource'

**ACTION alphabetically sorting :**
'calculateProperty'
'callService'
'click'
'closeApp'
'doNothing'
'doubleClick'
'executeSqlStoredProcedure'
'executeSqlUpdate'
'focusDefaultIframe'
'focusToIframe'
'getPageSource'
'hideKeyboard'
'keypress'
'manageDialog'
'mouseLeftButtonPress'
'mouseLeftButtonRelease'
'mouseOver'
'mouseOverAndWait'
'openApp'
'openUrl'
'openUrlLogin'
'openUrlWithBase'
'removeDifference'
'rightClick'
'select'
'swipe'
'switchToWindow'
'type'
'Unknown'
'wait'
'waitVanish'

**CONTROL standard sorting :**
'Unknown'
'verifyNumericEquals'
'verifyNumericDifferent'
'verifyNumericGreater'
'verifyNumericGreaterOrEqual'
'verifyNumericMinor'
'verifyNumericMinorOrEqual'
'verifyElementPresent'
'verifyElementNotPresent'
'verifyElementVisible'
'verifyElementNotVisible'
'verifyElementEquals'
'verifyElementDifferent'
'verifyElementInElement'
'verifyElementClickable'
'verifyElementNotClickable'
'verifyTextInElement'
'verifyTextNotInElement'
'verifyRegexInElement'
'verifyTextInPage'
'verifyTextNotInPage'
'verifyTitle'
'verifyUrl'
'verifyTextInDialog'
'verifyXmlTreeStructure'
'takeScreenshot'
'verifyStringEqual'
'getPageSource'
'verifyStringDifferent'
'verifyStringGreater'
'verifyStringMinor'
'verifyStringContains'

**CONTROL Alphabetically sorting :**
'getPageSource'
'takeScreenshot'
'Unknown'
'verifyElementClickable'
'verifyElementDifferent'
'verifyElementEquals'
'verifyElementInElement'
'verifyElementNotClickable'
'verifyElementNotPresent'
'verifyElementNotVisible'
'verifyElementPresent'
'verifyElementVisible'
'verifyNumericDifferent'
'verifyNumericEquals'
'verifyNumericGreater'
'verifyNumericGreaterOrEqual'
'verifyNumericMinor'
'verifyNumericMinorOrEqual'
'verifyRegexInElement'
'verifyStringContains'
'verifyStringDifferent'
'verifyStringEqual'
'verifyStringGreater'
'verifyStringMinor'
'verifyTextInDialog'
'verifyTextInElement'
'verifyTextInPage'
'verifyTextNotInElement'
'verifyTextNotInPage'
'verifyTitle'
'verifyUrl'
'verifyXmlTreeStructure'

To be honest I prefer the standard sorting as easier for choosing an action or control when you don't know all the possible actions/comtrol by heart but open for discution.

**Comment by j0hnsa** [comment]
Hi,

In my modest opinion looking at the combobox sometimes I feel lost looking for the type of action that I want to select and the alphabetical sort I'd know better where it is located and I could also scroll easier with the arrow keys to the desired action. But maybe we need to ask more users for feedback.

Regards,

**Comment by Amidius** [comment]
Hi, 

What about the combobox of applications ? in my opinion, it should be sorted alphabetically, or having a button sorting like that.

BR
