### ISSUE TITLE
error  / how to use submit again

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1605]
Hi, 
i'm not figuring out how to use the new submit again funtion in report by tag. The following error is allways displayed. What does it means? Thanks!
![image](https://user-images.githubusercontent.com/1914659/35919926-5030837a-0c0e-11e8-8442-bee430462961.png)

**Comment by vertigo17** [comment]
Just select any execution in the report by clicking the checkbox.
Then, clicking on the Submit button should automatically resubmit them.
Looks from your screenshot that even thought 26 execution were selected the button does not find them.
Is that systematic ?
I was not able to replicate on my side.

**Comment by bcivel** [comment]
I tried on my side and it happen sometimes (Not systematically). More often with few executions.

Maybe happen when the page load too quiclky (onclick function linked to the rows before the rows are generated)

**Comment by vertigo17** [comment]
Can you confirm whether servlet CreateTestCaseExecutionQueue is called when clicking on the button ?

**Comment by vertigo17** [comment]
I managed to reproduce.
It only happen when Refresh button is clicked. 1st loading of the page the feature works but as soon as button is clicked once, ReSubmit button no longuer works.
Will be fixed during the WE.
