### ISSUE TITLE
Feature to re-submit FA/KO/QU tests not working properly

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1611]
Hello,

Frequently this message is shown when re-submitting the tests on the Reporting page:

![imagem](https://user-images.githubusercontent.com/16339891/36037316-54a59b32-0db4-11e8-8122-a0dbfcfb0216.png)

It works ok if we reload the page and immediatly use this feature but looks like if some test changed the state on the queue (even if its not a test from the selected items)  this error is thrown. 

Can this be improved?

Regards
Cerberus Version : 3.1.0-SNAPSHOT-1286

**Comment by vertigo17** [comment]
duplicate from #1605
