### ISSUE TITLE
Add Authentification token management

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1617]
Hello,

We would like to start API tests but for the requests we need an authentification token.
Could you please add a feature with datalib to manage this need?

The user would create a service datalib and select the timeout for the token. Cerberus would manage if it needs a new token each time we call the datalib. I think we already discuss about this feature @vertigo17.

Thanks!

**Comment by ryltar** [comment]
We already started to work on that by adding few fields in testcaseexecutiondata table. We just need to add an other on the table testdatalib to manage the timeout. 

If the end of the testcaseexecutiontable + timeout < now, we can recalculate the datalib's data.
We just need to modify some java file to handle that !
I will think about it and how to do it !

I'll keep you informed about that !

**Comment by vertigo17** [comment]
duplicate from #1152.
I close this ticket in order to follow up the subject on #1152
