### ISSUE TITLE
How to set cookies

### ISSUE THREAD

**Issue by SeniorCanard** [cerberustesting/cerberus-source#1622]
Hello, I have the need to set a cookie in some Test Cases.
I figured out it is possible to do so in Selenium (https://www.360logica.com/blog/how-to-add-retrieve-and-delete-cookies-in-webdriver/) 
How can I do this on Cerberus ?

Thanks,

**Comment by vertigo17** [comment]
In order to allow more flexibility, I added an executeJS action that allow to execute any JS.
Cookies can now be handeled by JS.
https://www.w3schools.com/js/js_cookies.asp

**Comment by ruirpr** [comment]
Hi, we use cookies a lot using getFromJS with the following code as example:

`function createCookie(name, value, days) {
    var expires;
    if (days) {
        var date = new Date();
        date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
        expires = "; expires=" + date.toGMTString();
    }
    else {
        expires = "";
    }
    document.cookie = name + "=" + value + expires + "; path=/";
}

createCookie("lr-fullr-ab-pdp", "responsive", 1);`

It works ok!

**Comment by vertigo17** [comment]
Putting that script inside an executeJS action avoid to create a property for nothing else than executing some JS code.
That makes the testcase easier to read.
I close the issue as that should be enought.
Please @SeniorCanard , reopen in case you expected something else.
