### ISSUE TITLE
BUG : "Add screenshot manually to an automatic execution

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1623]
Hello, 

In an automatic execution, I have the following screen when I want to see the detail of the response. 

![image](https://user-images.githubusercontent.com/29098010/36419390-06cc9ed4-1632-11e8-8595-41d66624aebe.png)

**Comment by ryltar** [comment]
it's normal ! Now we use the same modal when we want to see an execution file.

**Comment by ryltar** [comment]
the modal is in read mode

**Comment by vertigo17** [comment]
What could be done is to optimize the modal display when open in read mode.
For ex : hide useless section and secure the preview is higher in the screen.

- [ ] Type and description could be in 1 single line
- [ ] Screenshot file name + "CTRL + V" line could be hidden.
