### ISSUE TITLE
[Idea] Create control without action

### ISSUE THREAD

**Issue by GrandjeanRemi** [cerberustesting/cerberus-source#1624]
Hello,

Can you allow the creation of a control without having to create an action before in TestCase ?

This would be very helpful because sometimes I am obliged to create "doNothing" actions to link control :/

Thanks !!

**Comment by vertigo17** [comment]
This is part of the model and that change could be quite heavy for an added value that seems quite small..
The only case where you are forced to attach the control to a 'donothing' action is when a step starts by a control. For any other cases, you can attach the control to the last control of the previous action.
