### ISSUE TITLE
Missing capabilities for Robot

### ISSUE THREAD

**Issue by jojo91** [cerberustesting/cerberus-source#1625]
Hi,

I'm trying to make UI test on a real device on iOS, it's been complicated but I finally succeed.
There is still one issue. When I launch my first test on an iPad4 it's working great then when I launch the same test on an iPadMini, the test won't be execute on the iPadMini but on the iPad4.
I had this issue with my local test on my mac and with cerberus.
I have fixed this issue by adding the capabilities "useNewWDA" to true on my local test but it doesn't exist on robot capabilities on cerberus. Is there any ways to correct this issue on cerberus ?

**Comment by vertigo17** [comment]
If the purpose is to add a capability in the following combo:
![capture](https://user-images.githubusercontent.com/5342048/36482227-7472e1d6-170a-11e8-9866-805affdb5ddf.PNG)
you can add them in public invariant:
![capture](https://user-images.githubusercontent.com/5342048/36482264-a4e2748a-170a-11e8-868a-f91aafdd75ed.PNG)
Click on Create Invariant and chose CAPABILITY in idname and the name of your capability in value.

**Comment by jojo91** [comment]
@vertigo17 thanks a lot, it's working now.
