### ISSUE TITLE
Testing campaign failed

### ISSUE THREAD

**Issue by jojo91** [cerberustesting/cerberus-source#1633]
Hi,

I currently have 10 test and I want to test all of them once. To do it, I created a campaign with my 10 test but when I run the campaign, I am automatically redirected to the "Execution report" page.
I found on the "Executions in queue" page that there was an error wish is : 
```
Bad answer format. Expected 'RunID = ' in the output result. Probably due to bad cerberus_url value. Check server logs
```
I found the same issue on github "https://github.com/cerberustesting/cerberus-jenkins-plugin/issues/8" but it have never been resolved.
But there is something interesting, if I go on this url, "http://MyCerberusServer/Cerberus/RunTestCase", I have this error.
```
2018-02-27 15:15:41 - 0 [|||] : 'FA' - 14 The test case failed to be submitted. Error - Parameter test is mandatory. Error - Parameter testCase is mandatory. Error - Parameter country is mandatory. Error - Parameter environment is mandatory (or use the manualURL parameter). Error - Test Case is not selected for country. 
```
I forgot to say but each test work if I ran it separately.
If someone know how to fix it, it would be great

**Comment by vertigo17** [comment]
Can you provide the value of the cerberus_url parameter (in administration / Parameter) ?
It should be in your case : 
http://MyCerberusServer/Cerberus/

That error happen when Cerberus try to trigger the execution from the queue by calling the RunTestCase Servlet and fail to call.
This is usualy due to cerberus_url not beeing correctly setup. It could be the servlet not accessible from Cerberus itself or even the servlet returning an invalid error such as 500 in case you are performing maintenance operation.

The error you get when you call directly the servlet is normal as this servlet require mandatory parameters like test, testcase, environment and country.

**Comment by jojo91** [comment]
My cerberus url parameter was "http://localhost:8080/GuiCerberusV2-2.0.0-SNAPSHOT".
I change it to http://localhost:8080/Cerberus and I have no more error in the "Executions in queue" page. But there is still an issue. When I have more than two test in my queue and when I run them. Sometimes In the execution report I have this issue.

```The test case is cancelled due to lost connection to Selenium Server! Detailed error : An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up (WARNING: The server did not provide any stacktrace information)```

My selenium server is up all the time. I don't know how to fix it.

**Comment by vertigo17** [comment]
Looks like a selenium server issue.
Maybe your selenium server does not support more than 1 execution at a time. 
Strange as by default i think selenium allow around 5 at the same time. 
Did you have a look connecting to your selenium server somewhere in localhost:4444/wd or checking the selenium server log. 

As a workaround you can configure a selenium hub between cerberus and the selenium node. 
Cerberus also allow you to configure a constrain of n simultaneous execution at a time. Use the ROBOTHOST public invariant with your robot host as value and gp1 with integer that correspond to max nb of exe at the same time. It will not fix the fact of running multiple execution at the same time but remove the error.

**Comment by jojo91** [comment]
This issue never reappeared so I close it.
