### ISSUE TITLE
Changing datalib name - autorepercussion on testcases

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1637]
Hello, 

it would be nice, when we rename a datalib to autorepercute the new name in the TC's linked

![image](https://user-images.githubusercontent.com/29098010/36793393-9a002aa6-1c9d-11e8-9b06-5cf6d68030b2.png)

the current situation : 

If you change the datalib name, you need to change it in every testcases affected

**Comment by Nouxx** [comment]
Hello,

I found out when entering the Datalib name in the Property (type : getFromDataLib), the datalib selected will be the best match on Name, System, Environment and Country. 

```
 // We get here the correct TestDataLib entry from the Value1 (name) that better match the context on system, environment and country.
        AnswerItem<TestDataLib> answer = testDataLibService.readByNameBySystemByEnvironmentByCountry(testCaseExecutionData.getValue1(),
                tCExecution.getApplicationObj().getSystem(), tCExecution.getEnvironmentData(),
                tCExecution.getCountry());
```

But I was able to create two datalib with the same Name, System, Environment and Country. 
![image](https://user-images.githubusercontent.com/30227758/37602465-b4d00632-2b8c-11e8-8742-f217348381dc.png)

I think we should first ensure that the the association (name, system, environment, country) is unique before addressing this issue.

**Comment by Nouxx** [comment]
- [ ] Add a button Rename in TestDataLib.jsp
- [ ] Create a modal with an input for the new name and the list of TC impacted by this entry
- [ ] Write 2 mass updates in testcasecountryproperties and testdatalib

FYI : the previous behaviour is normal but make sense only for internal type datalib.

**Comment by Nouxx** [comment]
a72de1f201c8ad4fe19dd3bc088a57c21214f0fd
