### ISSUE TITLE
Cannot click on a link (a)

### ISSUE THREAD

**Issue by jordan-arvato** [cerberustesting/cerberus-source#1638]
Good afternoon,

I've got an issue when i try to click on a button (add to cart), i tried a lot of css selector, xpath selector, and none of them are working, here is the page where the button is : 

[http://www.prismashop.fr/tous-les-magazines/programme-tv/tele-loisirs.html](http://www.prismashop.fr/tous-les-magazines/programme-tv/tele-loisirs.html)

That's the first button "Je m'abonne".

Here is one selector i tried to use : `//article[@id='product2017']/div[2]/div[2]/a`

Do you have any idea where it might be coming from ? and any way to correct/skip it ?

Thank you.

Regards,

Jordan

**Comment by ryltar** [comment]
can you provide a screenshot of your testcase please ? do you use this syntax xpath=//article[@id='product2017']/div[2]/div[2]/a ?

**Comment by jordan-arvato** [comment]
Here is the screenshot of my testcase, the beginning is to access the page i gave you, you don't really need to do that, but yes, i'm using xpath=....

![capture du 2018-02-28 16-40-07](https://user-images.githubusercontent.com/34857892/36796599-31618612-1ca6-11e8-8fe9-e2bca9606064.png)

After the click it should redirect to the cart but it doesn't ???

Thank you

**Comment by ryltar** [comment]
![image](https://user-images.githubusercontent.com/13577630/36854218-be06f0be-1d70-11e8-820d-1eb7a6409e2d.png)

I tried to click on add to cart button and i was correctly redirected to the cart ! :(  

![image](https://user-images.githubusercontent.com/13577630/36854391-299b9d3e-1d71-11e8-92d6-36cf83dca707.png)

**Comment by jordan-arvato** [comment]
Thank you for your answer.

Mmmmmm, what do you use for your robot ? here is mine : 

![capture du 2018-03-01 17-10-51](https://user-images.githubusercontent.com/34857892/36855371-881b215c-1d73-11e8-877b-30f2a2cf7508.png)

And that's the screenshot i have after trying to click on the "add to cart" button

![capture du 2018-03-01 17-11-46](https://user-images.githubusercontent.com/34857892/36855408-a44dd59a-1d73-11e8-8d4b-42020bd6d6a8.png)

After the click, i'm still on the product page.
Looks like it's the browser, maybe ?

**Comment by Nouxx** [comment]
Hello @jordan-arvato, 

Did you find a workaround for this issue ? 

It may come from a selenium puppet version difference on your hub. We're running our tests in Selenium 2.53, what about you?
