### ISSUE TITLE
Cannot change parameters values for one system

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1639]
Hi,
Some parameters cannot be updated for the system.
For example parameter cerberus_loopstep_max:
![image](https://user-images.githubusercontent.com/17747042/36973871-8550e820-206c-11e8-842d-8b8fb7c20fcf.png)
Although it seem to have be previously defined:
![image](https://user-images.githubusercontent.com/17747042/36973897-9fab368a-206c-11e8-96bc-fd71037bc783.png)

This is only true for some parameter, for others (for example cerberus_appium_wait_element) it is possible to change the parameter value for the system:
![image](https://user-images.githubusercontent.com/17747042/36973849-764237b2-206c-11e8-9593-aa7f3286e9cc.png)

Is this the expected behavior?
Not all parameter can be set for one system and must be the same for all?

Cerberus version: 3.2.0-SNAPSHOT-1292

**Comment by Nouxx** [comment]
Hello @ffazendeiro 

A similar ticket (#1632) has been opened last week and is now solved thanks to @ryltar.

The fix will be available in the next release.

Sorry for the inconvenience
