### ISSUE TITLE
get step number

### ISSUE THREAD

**Issue by SeniorCanard** [cerberustesting/cerberus-source#1641]
Hello,

I saw it's possible to get the index of a current looped step, by : %system.CURRENTSTEP_INDEX%  

But, is it possible to get the curent step number's ?

**Comment by ryltar** [comment]
Hello,

It's not actually possible but i will implement this for you :)

**Comment by SeniorCanard** [comment]
Perfect, thank you!

**Comment by vertigo17** [comment]
Why do you need that for ?
I ask that because there are 2 options on that implementation :
Use sort data but that changes as soon as a step is introduced 
Use step id but i don’t think it is displayed anywhere in the gui.

**Comment by ryltar** [comment]
![image](https://user-images.githubusercontent.com/13577630/37585395-4048ca5c-2b59-11e8-977e-fd32c04283b2.png)

integer is equal to the step sort.
