### ISSUE TITLE
Unable to click on native alert on landscape

### ISSUE THREAD

**Issue by jojo91** [cerberustesting/cerberus-source#1643]
Hello,

I'm currently writing tests for an app that is on iphone (only portrait) and ipad (only landscape).
After logging into my application I have a native alert that pop to ask a permission.
To handle this permission I added a "click" action with element path "Allow".
On Iphone(portrait) it works but on ipad(landscape) it doesn't.
I've seen a lot of forum with the same issue but I found no solution.

Did somebody found a solution ?

**Comment by jojo91** [comment]
It is a Apple issue and right now it can be fix by rotating the screen or by making a custom click with coordonates.
Is there any way to rotate the screen or create custom click with cerberus ?

**Comment by j0hnsa** [comment]
you can custom click by coordinates if desired, action click-> value1: coord=x:123,y:456 either a swipe works with fixed positions (CUSTOM -> 123;456;0;0).

have you tried passing the capability for the device orientation with the set up of a robot?

orientation | start in a certain orientation | LANDSCAPE or PORTRAIT 
(https://appium.io/docs/en/writing-running-appium/caps/)

It only works on emulators.. 

Regards

**Comment by jojo91** [comment]
So I first tried with the orientation capability but it didn't work. The only solution is the click with coordinates that work perfectly. Thanks a lot @j0hnsa .
