### ISSUE TITLE
Issue with GET call parameters

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1652]
Hello,

There is an issue with the URL building for GET api
From the JSON service file : 

    "HTTP-Request": "",
    "HTTP-Method": "GET",
    "ServiceType": "REST",
    "CalledURL": "xxxxxxxx/stcom/api/v1/stores/230/alerts?endDate=2018-03-13&startDate=2018-03-12&",
    "HTTP-TimeOutMs": 30000

As you can see Cerberus puts an "&" at the end when there is parameters after the ?
Could you please correct ?

*******************************************

Also it would be interesting to fill the parameters for GET call in the tab like the screenshot below : 

![image](https://user-images.githubusercontent.com/18569182/37335373-a122451a-26ae-11e8-99b2-88cd2f8e3aff.png)

Currently, parameters filled in this tab are not used for GET call.
Thank you!

Cerberus Version : 3.2-1296

**Comment by vertigo17** [comment]
Can you provide the screenshot of the definition of the service ?

**Comment by R-Loic** [comment]
![image](https://user-images.githubusercontent.com/18569182/37407370-c3e97852-2799-11e8-821f-d450af723f86.png)

Full path : /v1/stores/%storeId%/alerts?endDate=%system.TODAY-yyyy%-%system.TODAY-MM%-%system.TODAY-dd%&startDate=%system.YESTERDAY-yyyy%-%system.YESTERDAY-MM%-%system.YESTERDAY-dd%

![image](https://user-images.githubusercontent.com/18569182/37407414-e1b067ec-2799-11e8-9a3b-56042a24a9b5.png)

**Comment by R-Loic** [comment]
Just tried with the parameters in the request bodyas you you suggested, it works : 

![image](https://user-images.githubusercontent.com/18569182/37407565-47a7f740-279a-11e8-80bc-6f7df95d8ad8.png)

Could you please correct/add the others way to implement parameters ? (path + request details) 

Thank you !
