### ISSUE TITLE
too many clicks

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1653]
Hi,
the new cerberus version introduced a new behaviour after clicking "run testcase".
There now a "get to execution" and then a "refresh" .. that's two more clicks. 
I don't mind but my wrists are complaining. My workload does not like it also. 
If I did 75 clicks per day in the previous version, now I have to do 225. Is it possible to optimize this run testcase flow, please? Thanks!

**Comment by Galand-V** [comment]
Hello, 

Do you use the 'Rerun From Queue' button to avoid getting by the run page ? 

![image](https://user-images.githubusercontent.com/29098010/37353817-6ff38968-26e0-11e8-9275-c3c13b20c1f4.png)

**Comment by ruirpr** [comment]
It's at least the same amount of clicks using rerun from queue

**Comment by Galand-V** [comment]
In cliks yes, but : 

- You do not need to scroll as "rerun from queue" open the "Edit Execution Queue" popin
- The loading time from the runtestcase page is longer than the "Edit Execution Queue"

Maybe having an autorefresh every 5 seconds on the Execution Detail page until the testcase status goes to "Executing" could be a good start

![image](https://user-images.githubusercontent.com/29098010/37407073-1a9b0e50-2799-11e8-9055-d0526eed36fc.png)

**Comment by ruirpr** [comment]
The best scenario is to have a rerun button that copies exactly the execution with just one click.
current testcase rescult -> click something like direct rerun -> new result

Maybe I'm missing something but I don't see the point in "get to execution" and  "refresh", so perhaps a new button is required. 

Also it looks like the Synchroneous does the same in Y or N mode. 

Thanks!

**Comment by vertigo17** [comment]
What I can propose is to:
1/ Implement an autorefresh.on testcase execution screen
2/ Duplicate the buttons with a version that directly redirect to the result (detailExecution or reportbytag)
The synchroneous option needs to be removed. All executions are now going to the queue and as a consequence is always asynchroneous.

**Comment by ruirpr** [comment]
That would be great, thanks!

**Comment by ruirpr** [comment]
Something was implemented but it is not what we discussed. 
current situation:
execution result page -> click in run - rerun testcase -> click in run testcase and see result -> wait and nothing happens, click in refresh: 4 clicks

or

execution result page -> click in run - rerun from queue -> click and submit a new execution -> click in get to execution: 4 clicks

this is the video showing this behaviour https://ruirpr.tinytake.com/sf/MjUxNTA4OV83NTYzODcz

can you please add a button like this where I don't want to be asked anything, i just wand a rerun with the same exact settings from the actual result and go to the new result: 1 click
![image](https://user-images.githubusercontent.com/1914659/38671860-6af44a12-3e44-11e8-9d34-381e1aae1ea5.png)

**Comment by vertigo17** [comment]
the issue 'wait and nothing happens, click in refresh' has been fixed in a recent comit and will be in next release. --> This is 1 less click in the latest version.

Regarding your proposal :I would like to keep the screen as simple as possible so I prefer:
execution result page -> Click1 : click in run -> Click 2 : ReRun & See From Queue.
After click the browser will redirect to execution detail autorefreshed.
