### ISSUE TITLE
Glassfish to Tomcat Migration

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1656]
Hello,

I open this ticket to remind us to work on Tomcat migration.
We could list the tasks to do here.

- [ ] migrate Glassfish authentification to Spring Security

**Comment by vertigo17** [comment]
One of the reason behind that change is to have an application server that is more compatible with cloud env and docker/Kubernetes friendly.
An other alternative (and for sure easier) could be to move to Payara.
https://www.payara.fish/

**Comment by vertigo17** [comment]
Some details on how to install:

Création de la variable d'environnement : 
Créer un fichier setenv.sh (ou bat si Windows) dans le dossier bin contenant la ligne ci dessous:

`CATALINA_OPTS="-Dorg.cerberus.environment=prd -Xmx1024m"`

Connection JDBC : 

Dans le fichier conf/catalina/server.xml, ajouter la déclaration d'une ressource partagée

```
<GlobalNamingResources>
<Resource name="jdbc/cerberusprd"
global="jdbc/cerberusprd"
auth=“Container”
type="javax.sql.DataSource"
factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
maxTotal=“100”
maxIdle=“30”
maxWaitMillis=“10000”
username=“cerberus”
password=“toto”
driverClassName="com.mysql.jdbc.Driver"
url="jdbc:mysql://localhost:3306/Cerberus"/>
</GlobalNamingResources>
```

Dans le fichier conf/catalina/context.xml, ajouter le lien vers la resource déclarée.

```
<ResourceLink name="jdbc/cerberusprd"
global="jdbc/cerberusprd"
type="javax.sql.DataSource"/>
```

Configuration de l'authentification Realm :
Dans le fichier conf/catalina/server.xml, ajouter la déclaration

```
<Realm className="org.apache.catalina.realm.JDBCRealm"
driverName="com.mysql.jdbc.Driver"
connectionURL="jdbc:mysql://localhost:3306/Cerberus?user=cerberus&amp;password=toto"
userTable=“user” userNameCol=“Login” userCredCol=“Password”
userRoleTable=“usergroup” roleNameCol=“GroupName”>
<CredentialHandler className="org.apache.catalina.realm.MessageDigestCredentialHandler"
algorithm=“SHA-1” />
</Realm>
```
