### ISSUE TITLE
Is there a way to scroll a RecyclerView with Android

### ISSUE THREAD

**Issue by DimItelios** [cerberustesting/cerberus-source#1657]
Hi !

I'm trying to add an automatic scroll for an android app.
I don't  find any way to do this.

Does I use the swipe action ?

Could you give me a sample to know how to do this ?

**Comment by j0hnsa** [comment]
Hello,

The action corresponding to scroll would be swipe for the apps yes. On android the value 1 should be "CUSTOM" and on value 2 you should put the absolute coordinates for the scroll for instance (xstart;ystart;xend;yend) (200;1400;200;800) for a vertical swipe on Up direction.
On iOS either you can use CUSTOM like android but with relative coordinates (200;1400;0;-600) or just the direction on the value1 (UP,DOWN,LEFT,RIGHT).

ANDROID:
![imagem](https://user-images.githubusercontent.com/16339891/37462042-781d2de2-2848-11e8-8319-711305bddd28.png)
iOS:

![imagem](https://user-images.githubusercontent.com/16339891/37462067-907b549a-2848-11e8-9062-6c87f9b7fdcc.png)

Regards

**Comment by DimItelios** [comment]
Thanks for your response.
It works on my side
