### ISSUE TITLE
png screenshots vs file size

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1658]
Hi, 
screenshots are being saved in png and I notived files with 1.75Mb 
Is not possible to save them as jpg to save disk space and network bandwidth? 
Thanks!

**Comment by vertigo17** [comment]
Format of the screenshot is chosen from Selenium that only provide png format (I guess for quality reason).
Convertion could be an option but will not save any bandwidth. It will only save some disk space.

**Comment by ruirpr** [comment]
Quality between png/jpg is not relevant for a screenshot but i did not knew that selenium limitation. Thanks for the explanation!
