### ISSUE TITLE
How can i update a property during test

### ISSUE THREAD

**Issue by DimItelios** [cerberustesting/cerberus-source#1660]
Hi !

I want to open all elements from a list during my test, so i have a property "index" and I use it to click on the element on my list to open it.

![image](https://user-images.githubusercontent.com/37374199/37517120-af4491f2-2910-11e8-8a46-d817f544eff3.png)

I've created a Step on my test to select item on the list, but I want to execute again this step with the index incremented.

![image](https://user-images.githubusercontent.com/37374199/37517217-f37e7cb6-2910-11e8-9513-0f263c091dee.png)

How can I update the property Index at the end of the step ?

**Comment by vertigo17** [comment]
I beleive you should use %system.CURRENTSTEP_INDEX%
It automatically increment after every loop.

**Comment by DimItelios** [comment]
Thanks for your answer.

I test it and it works fine.

But Is it possible to do a loop inside an other loop ?

**Comment by vertigo17** [comment]
No.

**Comment by DimItelios** [comment]
Ok, thanks.

I have a last question. I want to do a swipe if element is not visible. There is "ifElementPresent" in condition but not "ifElementNotPresent". How can i do it ?

I tried to put false in second condition parameter to inverse it but it doesn't work

![image](https://user-images.githubusercontent.com/37374199/37526698-5bf463cc-2930-11e8-940c-9a2c67356137.png)

**Comment by DimItelios** [comment]
I am not sure that is the same subject.

If you see the picture, I want to do the swipe only when the item is not visible.
For my test, I want to open all item in the list, So I click on the item with index CURRENTSTEP_INDEX. And click back when it is open. So I want to swipe one time only when the new item is not visible, and click after.

So I need to do the check in Condition Operation.
![image](https://user-images.githubusercontent.com/37374199/37528363-c394d3b4-2934-11e8-980b-b4a720658e42.png)

**Comment by vertigo17** [comment]
Just added the property that will be available in next release.
Please confirm that it works.

**Comment by j0hnsa** [comment]
Hello @vertigo17 ,

I was working on the another kind of tests and I realized that this feature could be really handy (ifElementVisible) because on web tests frequently the element is present but not visible. Which makes the ifElementPresent useless on most cases. Can you confirm that ifElementVisible is going to be available on the next release?

Regards
