### ISSUE TITLE
Issue with POST call parameters

### ISSUE THREAD

**Issue by GrandjeanRemi** [cerberustesting/cerberus-source#1661]
Hello,

I try to do a POST request with parameters in url and **no body** but that don't work.
![image](https://user-images.githubusercontent.com/36671939/37657966-ae58cd28-2c4c-11e8-8c5f-97dd631d8936.png)
![image](https://user-images.githubusercontent.com/36671939/37658259-68470c36-2c4d-11e8-9d32-8f59e0eead1a.png)
I try to put the parameters in "Request" or "Request Detail" tab too but they are not taking into account when i look the service call in the execution report.

Can u check that please ?

Thanks.

Rémi.

**Comment by vertigo17** [comment]
Can you provide the 'Service Call' json file reported as output of the service call inside execution report ?

When using a POST requests, either you feed the 'Service Request' field inside 'Request' tab, either you feed 'Request Detail' tab with a list of key/values.
If you feed Service Request field, the post will be done only on that data ignoring the Request Detail Tab. 
Example :

{
  "Request": {
    "HTTP-Proxy": {
      "HTTP-Proxy": false
    },
    "HTTP-Header": {
      "cerberus-token": "36775"
    },
    **"HTTP-Request": "toto=tutu",**
    "HTTP-Method": "POST",
    "ServiceType": "REST",
    "CalledURL": "http://localhost:8080/source/GetDummyRESTCall?titi=toto",
    "HTTP-TimeOutMs": 360000
  }
}

If Service Request Field is empty, the post will be done on key values of Request Detail tab.
Example :

{
  "Request": {
    "HTTP-Proxy": {
      "HTTP-Proxy": false
    },
    "HTTP-Header": {
      "cerberus-token": "36775"
    },
    **"HTTP-Request": "",**
    "HTTP-Method": "POST",
    "ServiceType": "REST",
    **"Content": {
      "key1": "value1",
      "key3": "value3"
    },**
    "CalledURL": "http://localhost:8080/source/GetDummyRESTCall",
    "HTTP-TimeOutMs": 360000
  }
}

I managed to make both calls testing POST methods without any issues.

**Comment by GrandjeanRemi** [comment]
Service call when a put the request parameters in **Request tab** : 
{
  "Response": {
    "Header": {
      "Transfer-Encoding": "chunked",
      "Server": "Apache",
      "X-Content-Type-Options": "nosniff",
      "Connection": "close",
      "Pragma": "no-cache",
      "Date": "Tue, 03 Apr 2018 07:13:05 GMT",
      "X-Frame-Options": "DENY",
      "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",
      "Set-Cookie": "JSESSIONID=849F9957F3FAC936CCC2F3CDEE4000E6.TOM40_STORES01_RE7_EU; Path=/stcom/; HttpOnly",
      "Expires": "0",
      "X-XSS-Protection": "1; mode=block",
      "Content-Type": "application/json;charset=UTF-8"
    },
    "HTTP-Version": "HTTP/1.1",
    "HTTP-ReturnCode": 400,
    "HTTP-ResponseBody": "{\"error\":\"Bad Request\",\"error_description\":\"Required LocalDate parameter 'date' is not present\"}",
    "HTTP-ResponseContentType": "JSON"
  },
  "Request": {
    "HTTP-Proxy": {
      "HTTP-Proxy": false
    },
    "HTTP-Header": {
      "Authorization": "Bearer ****",
      "cerberus-token": "3526",
      "Accept": "application/json",
      "Accept-Language": "fr-FR",
      "Content-Type": "application/json"
    },
    "HTTP-Request": "date=2018-03-20&signed=true&labeled=true&delete=true",
    "HTTP-Method": "POST",
    "ServiceType": "REST",
    "CalledURL": "http://*****/stcom/api/v1/stores/49/alerts/items/516016/acknowledge",
    "HTTP-TimeOutMs": 30000
  }
}

Service call when a put the request parameters in **Request detail tab** : 

{
  "Response": {
    "Header": {
      "Transfer-Encoding": "chunked",
      "Server": "Apache",
      "X-Content-Type-Options": "nosniff",
      "Connection": "close",
      "Pragma": "no-cache",
      "Date": "Tue, 03 Apr 2018 07:19:20 GMT",
      "X-Frame-Options": "DENY",
      "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",
      "Set-Cookie": "JSESSIONID=0A8E94222EC557286DA2F8E3A03BB04D.TOM40_STORES01_RE7_EU; Path=/stcom/; HttpOnly",
      "Expires": "0",
      "X-XSS-Protection": "1; mode=block",
      "X-Decathlon-Api-Correlation-Id": "a32ea045-ff6f-4952-9e90-665e3c506e7d#-9223372036854771580",
      "Content-Type": "application/json;charset=UTF-8"
    },
    "HTTP-Version": "HTTP/1.1",
    "HTTP-ReturnCode": 400,
    "HTTP-ResponseBody": "{\"error\":\"Bad Request\",\"error_description\":\"Required LocalDate parameter 'date' is not present\"}",
    "HTTP-ResponseContentType": "JSON"
  },
  "Request": {
    "HTTP-Proxy": {
      "HTTP-Proxy": false
    },
    "HTTP-Header": {
      "Authorization": "Bearer ****",
      "cerberus-token": "3531",
      "Accept": "application/json",
      "Accept-Language": "fr-FR",
      "Content-Type": "application/json"
    },
    "HTTP-Request": "",
    "HTTP-Method": "POST",
    "ServiceType": "REST",
    "Content": {
      "date": "2018-03-20",
      "labeled": "true",
      "signed": "true",
      "delete": "true"
    },
    "CalledURL": "http://****/stcom/api/v1/stores/49/alerts/items/516016/acknowledge",
    "HTTP-TimeOutMs": 30000
  }
}

**Comment by vertigo17** [comment]
Content seems to be correctly feed.
I guess this is better to ask the people in charge of the service on how it should be called.
If posting the key values individualy does not work (2nd example), Maybe the post must be done putting a json structure inside the Request (I doubt that a queryString format inside a post make sense) ?

**Comment by vertigo17** [comment]
Have you tried to put the parameters 'date=2018-03-20&signed=true&labeled=true&delete=true' at the end of the Service path and leave both Request and Request Detail tab empty ?
Can you provide the 'Service call' JSON report ?

**Comment by GrandjeanRemi** [comment]
Yes i tried.

Service Call : 

{
  "Response": {
    "Header": {
      "X-Frame-Options": "DENY",
      "Keep-Alive": "timeout=15, max=100",
      "Server": "Apache",
      "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",
      "X-Content-Type-Options": "nosniff",
      "Connection": "Keep-Alive",
      "Set-Cookie": "JSESSIONID=27CE7A332563C844AE8BEC60CE343D8B.TOM40_STORES01_RE7_EU; Path=/stcom/; HttpOnly",
      "Pragma": "no-cache",
      "Expires": "0",
      "X-XSS-Protection": "1; mode=block",
      "X-Decathlon-Api-Correlation-Id": "d5eacb6a-fc94-4982-82ac-6dd8ea7df96f#-9223372036854775517",
      "Date": "Tue, 03 Apr 2018 12:10:24 GMT"
    },
    "HTTP-Version": "HTTP/1.1",
    "HTTP-ReturnCode": 204
  },
  "Request": {
    "HTTP-Proxy": {
      "HTTP-Proxy": false
    },
    "HTTP-Header": {
      "Authorization": "Bearer *****"
      "cerberus-token": "3687",
      "Accept": "application/json",
      "Accept-Language": "fr-FR",
      "Content-Type": "application/json"
    },
    "HTTP-Request": "",
    "HTTP-Method": "POST",
    "ServiceType": "REST",
    "CalledURL": "http://****/stcom/api/v1/stores/49/alerts/items/516016/acknowledge?date=2018-03-20&signed=true&labeled=true&delete=true",
    "HTTP-TimeOutMs": 30000
  }
}

Response : 
![image](https://user-images.githubusercontent.com/36671939/38248548-069a0842-3749-11e8-9875-afe2c8e6688d.png)

**Comment by vertigo17** [comment]
Well it seems the answer is 204 with empty response so in reality, the call is made correctly and works.
What we need to understand is how to fix the null pointer exception that result an FA status.
I will try to reproduce and empty response in order to simulate the issue. Until there I beleive you can set the action to 'Force Execution' PE. That will allow the test to continue.

**Comment by vertigo17** [comment]
Issue is now fixed. It was on the method that guess the response format. It was not managing the case where reponse was empty.
