### ISSUE TITLE
Launching sequential multiple test doesn't works

### ISSUE THREAD

**Issue by jojo91** [cerberustesting/cerberus-source#1663]
Hi,

When I'm launching multiple test on my iOS simulator, it doesn't work well.
I'm currently launching three test and the first work, then the second one is launching but it close itself after four seconds and then the third one launch and sometimes failed, sometimes succeed.

I don't understand why, did anybody have an idea ?

**Comment by vertigo17** [comment]
I have no idea.
We don't reproduce such issue.
Did you manage to solve it since that time ?
