### ISSUE TITLE
add sreenshot for action and for expected results

### ISSUE THREAD

**Issue by fatimatdiakhate** [cerberustesting/cerberus-source#1665]
This improvement concerns manuel testing

Cerberus Version : 3.0.0-1285

**Comment by ryltar** [comment]
https://github.com/cerberustesting/cerberus-source/releases/tag/cerberus-testing-3.1.0

since 3.1.0, attaching files to manual test is now possible !

I close this ticket. Feel free to reopen it, if i misunderstood something !
