### ISSUE TITLE
New execution for different robots

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1671]
Hi,
everytime we run a test case for the same environment/country but in a different robot it generates another execution in the tag.
This will create inconsistencies on the reports as we will have "extra" executions for the same country/environment.

![image](https://user-images.githubusercontent.com/14328346/38239289-3666de08-3724-11e8-98fc-9e6ac4e7dcdc.png)

Can you please check this situation?

Thanks.

**Comment by vertigo17** [comment]
This is to allow same testcase/country/env to be executed easily on multiple robot configuration and still beeing displayed in the report. ex : Test could be fine on firefox 47 but wrong on firefox 56.
If you want them to be grouped, you can use robot declination with the same value and they will be grouped. When robot declination is empty, it takes the robot name as declination value.
You can use variable to put the real value from the execution or put a static string.

![2018-04-03 10_59_44-robot](https://user-images.githubusercontent.com/5342048/38239864-7b86ba5a-371d-11e8-8fa0-71f9a7064417.png)

**Comment by RobertoAbraul** [comment]
Hi,

thanks for the feeback.
Robots updated and working fine now.

![image](https://user-images.githubusercontent.com/14328346/38240556-cb542d60-3727-11e8-965d-09a2fbcd9319.png)

**Comment by j0hnsa** [comment]
IMHO Looks really bad meanwhile the campaign executes (i have to use 6 different robots):

http://192.168.135.32/Cerberus/ReportingExecutionByTag.jsp?Tag=APPLICATIONS_PREPROD_2018040311
