### ISSUE TITLE
Requirement (LABEL) : Add the possibility to edit or delete label

### ISSUE THREAD

**Issue by ntennich** [cerberustesting/cerberus-source#1672]
Hello, 
Could you please add both features (Edit and Delete)  the label at the requirement tab.
![label-requirement](https://user-images.githubusercontent.com/35033728/38246879-77f1a276-3743-11e8-8cdf-41d9f1997952.PNG)

Thanks in advance. 
Nadia.

**Comment by ntennich** [comment]
could you please add 2 or 3 levels for the requirement Label please?

**Comment by vertigo17** [comment]
I added that need to #1572.
Let’s keep that issue only for edit and delete action from requirement tab.
