### ISSUE TITLE
Execution Report - horizontal scroll

### ISSUE THREAD

**Issue by akatmiranda** [cerberustesting/cerberus-source#1678]
When we have tests running with several robots the Execution Report can't show all executions, meaning by this that there is no horizontal slide in case of window overflow.

![image](https://user-images.githubusercontent.com/38046035/38495786-ccd5e776-3bf2-11e8-8791-6d5c5727a291.png)

In image there are already executions in Queue for the first 4 failed tests that aren't visible.

**Comment by vertigo17** [comment]
horizontal scrolls are at the bottom of the page ;-)
![2018-04-09 18_04_29-inbox - bdumont redoute fr - outlook](https://user-images.githubusercontent.com/5342048/38508820-bb273a08-3c0f-11e8-98b8-aa6db280f9d0.png)

**Comment by akatmiranda** [comment]
Assuming we all know what is a horizontal scroll and where it should be, i've sent my print screen where it isn't ;-)

**Comment by vertigo17** [comment]
Sorry but you will have to be more clear. 
I don’t understand what is the issue with the horizontal bar and neither what you expect.

**Comment by akatmiranda** [comment]
There are columns in this view to the right that are not visible. In this case the first 4 tests that are failed have executions in queue in other robots that we cant see.
The image submitted shows the bottom of the page without any scroll.
As a sugestion, this scroll could be useful.

**Comment by ruirpr** [comment]
Hi think he means a floating horizontal scroll like this:
![image](https://user-images.githubusercontent.com/1914659/38546188-e569b9c8-3ca3-11e8-8e5d-587815829bef.png)
