### ISSUE TITLE
Invariants creation : GUI allowing wrong data creation

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1690]
Hello,

When creating a TCSTATUS invariant, the GUI allows to add it without 'Group 1' value
![image](https://user-images.githubusercontent.com/30227758/38938266-6b8a4c20-4325-11e8-9983-2dbf6ab2619a.png)

Turns out to cause an warning message pop up in hompage.

![image](https://user-images.githubusercontent.com/30227758/38938426-c68a1ee8-4325-11e8-999d-0f817ec77617.png)

Maybe add a JavaScript verification to avoid adding it.

No big deal as well.

**Comment by vertigo17** [comment]
I fixed the javascript error and also changed the rule that display or not the column in homepage from = to Y to <> from N
That way by default, creating an invariant is displaying it in homepage.
