### ISSUE TITLE
select by row/column

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1691]
Would be nice to be able to select a complete line and a complete column for "submit again" in execution report by tag. Something like a global checkbox by row/column or clicking in tc name:
![image](https://user-images.githubusercontent.com/1914659/38939760-915b638a-4320-11e8-828e-c9c96cf00140.png)

Also, it looks like there's empty space bellow environments. Is this useful for something or can be deleted/adjusted? Thanks

**Comment by vertigo17** [comment]
When you say complete line or row, you mean the complete line excluding the OK execution or really all of them ?
Concerning the space, as you can see on your screenshot the space is used in order to display the search input on the 1st 3 columns. I don't think we can save much more.

**Comment by ruirpr** [comment]
Only the visible ones. In the example, the OK are excluded but if not filtered out, should be selected also.
