### ISSUE TITLE
chrome click action

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1692]
Hi
i've been messing arround with testing in chrome and I can't get some clicks to work
for example click in data-cerberus=button_header_search-engine does not perform any action;

My workarround is to use executeJS
```
var xPathRes = document.evaluate ("//*[@data-cerberus='button_header_search-engine']", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null);
xPathRes.singleNodeValue.click();
```

Can you investigate please? Thanks!

**Comment by ruirpr** [comment]
There's also another situation. If a data-cerberus=something is covered by other element, let's say another button, the click is done in the front element.

**Comment by vertigo17** [comment]
Regarding your second comment, this is normal, in case there are 2 elements that match the criteria, this first one is probably selected. Nothing to do on that appart from either changing the code of the site to secure it is not duplicated or change the path to an xpath.

**Comment by ruirpr** [comment]
That would make sense but i'm not talking about 2 elements mathing the criteria. They are completly diferent, just one over the other on the screen. I've been using a click by js to work arround this. I'll show you a example as soon as I find another one.

**Comment by ruirpr** [comment]
Found a strange behaviour. The retour button in delivery method does not respond when testing in chrome:
![image](https://user-images.githubusercontent.com/1914659/40418977-bc341ebe-5e7b-11e8-88d9-f6ce5d4e5432.png)

using click in data-cerberus=ContinueShopping does nothing, page does not goes back
using _executeJS var xPathRes = document.evaluate ("//*[@data-cerberus='ContinueShopping']", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null); xPathRes.singleNodeValue.click();_ also does nothing in chrome. Manually the js works. 

It's the first time i find this behaviour. Do you have any ideia why?
![image](https://user-images.githubusercontent.com/1914659/40419105-2c06f126-5e7c-11e8-892a-d214e70c1558.png)
