### ISSUE TITLE
isElementVisible condition operator

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1693]
Hello,

On the past release we we're expecting to be implemented isElementVisible (as seen on #1660 ) on the condition operators but it finally wasn't... Can this be done? the condition that checks whether the element is present or not is not suitable as the element despite not visible will be present on most cases for iOS.

Thanks in Advance
Cerberus Version : 3.4-SNAPSHOT-1319

**Comment by vertigo17** [comment]
Let's target this ASAP.
I don't see any reason why this is not possible. Can you confirm that existing control isElementVisible and isElementNotVisible has the bahaviour expected.
If correct , we will just add it to all condition operators.

**Comment by j0hnsa** [comment]
Feature implemented and working
