### ISSUE TITLE
Empty homepage

### ISSUE THREAD

**Issue by htopoff** [cerberustesting/cerberus-source#1694]
Hi,

I encountered another issue :
![2018-04-19 09_30_19-cerberus_homepage](https://user-images.githubusercontent.com/38133450/38977487-d10b7bb6-43b4-11e8-9710-02eed63b65f6.png)
Do you have an idea on what should I do ?
Thanks.

**Comment by Bigeldoth** [comment]
Hello, I have exactly the same probleme any idea ?
