### ISSUE TITLE
make reportbytag table th titles bigger

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1696]
Can you please rearrange the env/country title in reportbytag table? It currenty wastes a lot of space and uses ... so the user can't see nothing.
![image](https://user-images.githubusercontent.com/1914659/38988621-c627bd24-43cb-11e8-8069-2aaa2f442724.png)

**Comment by vertigo17** [comment]
The right side of the column is used for sorting indication.
We can't remove it and I don't see any space available to make them bigger but there should be a tooltip + you can always resize the column..
