### ISSUE TITLE
Robot Capabilities accessible on the test

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1698]
Hello,

Would it be possible to have for example %robot.CAPS.udid% capability accessible on the test?

Regards

Cerberus Version : 3.4-SNAPSHOT-1319

**Comment by vertigo17** [comment]
Can I ask you the usecase behind that need.
In case we do it it would be more under system variables.
%system.ROBOTCAPS.capname%

**Comment by j0hnsa** [comment]
Hi @vertigo17 ,

Sorry for the late reply! The usage would be for some situations where the coordinate click is needed and I have multiple devices with different screensizes.

Thanks

**Comment by vertigo17** [comment]
So if the use case is to get the real resolution of the device, it is alreaddy covered by issue #1708.
I close the issue. Please reopen and detail if you need more.
