### ISSUE TITLE
add drag and drop feature in cerberus

### ISSUE THREAD

**Issue by aurel59000** [cerberustesting/cerberus-source#1699]
Hello,

I tested if i can drag and drop in cerberus and it is not possible now.
You should add "drag and drop" action in the testCase edit page to complete cerberus possibilities. The methode drag and drop is already created in selenium.

**url: https://www.guru99.com/drag-drop-selenium.html**

_import org.openqa.selenium.By;		
import org.openqa.selenium.WebDriver;		
import org.openqa.selenium.WebElement;		
import org.openqa.selenium.chrome.ChromeDriver;		
import org.openqa.selenium.interactions.Actions;		
import org.testng.annotations.Test;		

public class DragAndDrop {				

    WebDriver driver;			

    @Test		
    public void DragnDrop()					
    {		
         System.setProperty("webdriver.chrome.driver"," E://Selenium//Selenium_Jars//chromedriver.exe ");					
         driver= new ChromeDriver();					
         driver.get("http://demo.guru99.com/test/drag_drop.html");					
         
		//Element which needs to drag.    		
        	WebElement From=driver.findElement(By.xpath("//*[@id='credit2']/a"));	
         
         //Element on which need to drop.		
         WebElement To=driver.findElement(By.xpath("//*[@id='bank']/li"));					
         		
         //Using Action class for drag and drop.		
         Actions act=new Actions(driver);					

	//Dragged and dropped.		
         act.dragAndDrop(From, To).build().perform();		
	}		
}_

**Comment by vertigo17** [comment]
Have you tried to use:
mouseLeftButtonPress
and
mouseLeftButtonRelease.

That should work.
