### ISSUE TITLE
add the name of object in title or h1 of a page

### ISSUE THREAD

**Issue by aurel59000** [cerberustesting/cerberus-source#1700]
Hello,

In order to get Cerberus better, you should:

- add the name of a selected object in the title balise in the beginning if a page
- add the name of a selected object in the h1-h2-h3-h4-h5-h6 balise in the beginning if a page

For exampe,
When i select a campaign, the name of the selected campaign is added to the title of the page : "Run test case - name of the selected campaign"

![image](https://user-images.githubusercontent.com/38555953/39043346-7c71b47e-448d-11e8-951b-f1d5bd56644d.png)

**Comment by vertigo17** [comment]
In fact most of pages are not linked to a specific object but display a list of objects.
Even the page you mention Run TestCase is not linked to a campaign.
What you mention make sens on all modal that are linked to a specific object and all of them have what you mention (not always on h1 but for sure on header of the modal).
