### ISSUE TITLE
chrome wrong resolution

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1701]
Hi, 
running a testcase with a 360x640px constrain seems not to work properly in chrome
![image](https://user-images.githubusercontent.com/1914659/39056956-f42b4008-44af-11e8-9d0f-7e6bc94aa879.png)

this is the resulting window in the vm:

![image](https://user-images.githubusercontent.com/1914659/39057290-bf5c684c-44b0-11e8-93a2-128b18ca2053.png)

and the execution results shows 
![image](https://user-images.githubusercontent.com/1914659/39057018-27bda85c-44b0-11e8-89a7-1415b4d39fcf.png)

but setting the resolution in chrome shows more:
![image](https://user-images.githubusercontent.com/1914659/39057455-2abb29b6-44b1-11e8-9502-b75fdb261e58.png)

so nothing seems to match

Is there any way arround this? Thanks!

**Comment by vertigo17** [comment]
Closed because it could not be reproduced.
