### ISSUE TITLE
Add a "LastConnexion" Column in the user table

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1702]
Hello, 

In order to have a better control on users, can you add a "lastconnexion" column in the DB? That could permit to determine if the user is still active or not. 

Current situation on our Cerberus  : 
![image](https://user-images.githubusercontent.com/29098010/39118019-99f125e0-46e8-11e8-98c3-cffd5de06afb.png)

Thank you

**Comment by vertigo17** [comment]
As a workaround, I suggest you join logevent table to get the timestamp of the last action loged in Cerberus.

**Comment by Nouxx** [comment]
You can use this SQL query:

```
select u.Login, (select max(LogEventID) from logevent where `Login`=u.Login) as last_visit
from `user` u
group by u.Login
order by last_visit asc
```

**WARNING**: this is an heavy request (it takes 1sec for a single user on our environment)

**Comment by Galand-V** [comment]
Thank you for the info 👍
