### ISSUE TITLE
Set test case default priority to 1

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1706]
Hello,

We are facing a problem in a context of continuous integration : the Jenkins pipeline is querying the **ResultCIV002** servelt to acknowledge the global result of a campaign (identified by its Tag)

This servelt response with a "results" field which can be "OK" or "KO" depending on the CI score, which is itself calculated according to the number of test case and their priority.

By default, the priority is set to 0

![image](https://user-images.githubusercontent.com/30227758/39250052-61dbfcfc-48a0-11e8-9648-22d9bd6b2b4f.png)

If the test implementers aren't aware of this behaviour, they will not pay attention to this field and the Jenkins integration will behave badly: in our situation, the campaign execution is composed only of FA (21) and NA (1) status, with a priority to 0. When calling the ResultCIV002 for this campaign, the _result_ value is OK.

```
 {  
   "NonOK_prio1_nbOfExecution":0,
   "status_PE_nbOfExecution":0,
   "TOTAL_nbOfExecution":22,
   "CI_OK_prio1":1,
   "status_CA_nbOfExecution":0,
   "status_QU_nbOfExecution":0,
   "status_FA_nbOfExecution":21,
   "message":"CI result calculated with success.",
   "status_NA_nbOfExecution":1,
   "result":"OK",
   "ExecutionStart":"2018-04-12 15:06:22.0",
   "status_OK_nbOfExecution":0,
   "messageType":"OK",
   "NonOK_prio3_nbOfExecution":0,
   "status_KO_nbOfExecution":0,
   "NonOK_prio4_nbOfExecution":0,
   "tag":"marketplace-ihm_20180412113807",
   "CI_finalResult":0,
   "CI_OK_prio3":0.20000000298023224,
   "CI_OK_prio2":0.5,
   "ExecutionEnd":"2018-04-12 15:14:41.0",
   "NonOK_prio2_nbOfExecution":0,
   "CI_OK_prio4":0.10000000149011612,
   "status_NE_nbOfExecution":0
} 
```

To avoid these problems, I am thinking of setting the default priority to 1 so that if any test case is not OK, the servlet will answer KO, which is, in my mind, the correct default behaviour.

![image](https://user-images.githubusercontent.com/30227758/39250640-918be27c-48a1-11e8-926a-56b18366896d.png)

**Comment by Nouxx** [comment]
In order to update our current campaigns more easily, I also created the #1705 ticket

Hope you will like it 😀

**Comment by Nouxx** [comment]
Update:
 
Priorities are handled in public invariants. The default one will be the one with the lowest 'Sort' value.
![image](https://user-images.githubusercontent.com/30227758/39353490-2637c640-4a08-11e8-91ed-6b6345ba6760.png)

I'll modify the default inserted data to make the most important priority sorted as first, so that it will be automatically selected in the dropdown menu.

**Comment by vertigo17** [comment]
I removed 99 prio as it doesn't make sense.
