### ISSUE TITLE
Allways Execute a step at the end of test case execution

### ISSUE THREAD

**Issue by nicodeur** [cerberustesting/cerberus-source#1709]
Add possibility to always execute a step at the end of test case execution : 

- [x] Add a new check box on a step `Force this step if Testcase is not OK`
- [x] Add possibility to create a `PostTesting` Testcase link to an application. This `PostTesting` Testcase will executed at the end of a TestCase. If `Force this step if Testcase is not OK` is checked, it will be allways executed, else only if all steps are OK.

**Comment by vertigo17** [comment]
@nicodeur , if you can test and confirm the behaviour is the one expected.
So far, just add FORCEDSTEP inside description of the step that needs to be forced.
Once validated, I will add the criteria into a dedicated data.

**Comment by nicodeur** [comment]
Hi @vertigo17 ,
I just test it, It's perfect ! You can add a criteria into a dedicated data for this feature.
