### ISSUE TITLE
Change the icon when a step is skipped due to its condition

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1712]
Hi,

When a step isn't executed due to its condition (correct behaviour then), the 'warning' icon is displayed. 

![image](https://user-images.githubusercontent.com/30227758/39312573-2dfa069c-4970-11e8-83e9-fa51b764eef7.png)

It can be misleading for new users, can it be changed ?

Thanks

**Comment by Nouxx** [comment]
- [ ] Add a new execution status "NE": Not Executed, for steps and actions
- [ ] Front adjustment: new icon & color

**Comment by vertigo17** [comment]
We will implent that at the same time as #1709.

**Comment by vertigo17** [comment]
NE status already exist but is for Manual execution status.
What I propose is to rename 
NE status to WE (Waiting Execution)
and use NE for Non Executed Execution/step/action/control.
