### ISSUE TITLE
Edit an application Object doesn't work the first time

### ISSUE THREAD

**Issue by yun59000** [cerberustesting/cerberus-source#1713]
Hi,
When you edit an object where the application name is not the first application (in alphabetic order), the application name show on screen is the first, and no change can be saved.
Exemple:
we have 2 applications: "Test" and "App"
we save an object in the application "Test" 
edit that object and see the application name

Workaround:
close the edit popin and clic on edit again, it will do the trick

Version:  Cerberus2.0.0-1237

**Comment by vertigo17** [comment]
I can't reproduce in latest version.
Can you upgrade to latest version or test and confirm it work in demo.cerberus-testing.org (taht has 3.3) ?

**Comment by yun59000** [comment]
hi, 
i cant upgrade on that particular machine because we are a lot to work on it at the same time.
I'll try on a fresh local install and keep you inform.

**Comment by yun59000** [comment]
Well we can close the issue, i've tested it on a fresh install and on the demo and i cant reproduce, looks like this is working fine :D
