### ISSUE TITLE
[Evolution] Dissociate label and requirement on all page / filters

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1716]
Is it possible to dissociate label and requirement on all page / filters ?

Add a column "Requirement" near the "Label" column. Indeed, it's very difficult to choose some test with a specific label or requirement

For example, on "Test case list" : 

<img width="1351" alt="capture d ecran 2018-04-30 a 14 14 34" src="https://user-images.githubusercontent.com/33724879/39426673-150db41c-4c81-11e8-896d-87b9b357edaf.png">

For example, on "Run Test case" : 

<img width="1354" alt="capture d ecran 2018-04-30 a 14 17 14" src="https://user-images.githubusercontent.com/33724879/39426729-4104229a-4c81-11e8-9f64-f880b9371ff7.png">

For example, on "Create campaign" page :

<img width="1059" alt="capture d ecran 2018-04-30 a 14 18 11" src="https://user-images.githubusercontent.com/33724879/39426772-66505b0e-4c81-11e8-9fb3-81968c082fdb.png">

Cerberus Version : 3.2-1296

**Comment by vertigo17** [comment]
I suggest we focus on TODO List:

- [ ] TestCase List (1 column per label type)
- [ ] TestCase Header (1 tab per label type)

Then we can improve layout on 

- [ ] RunTestCase page (show the [system] inside)
- [ ] Campaign (render the label with color and system)

**Comment by vertigo17** [comment]
![image](https://user-images.githubusercontent.com/5342048/43367042-2c58ceec-9347-11e8-9c9b-14b94092b3f2.png)
