### ISSUE TITLE
Error when an api return : 204 no content

### ISSUE THREAD

**Issue by GrandjeanRemi** [cerberustesting/cerberus-source#1717]
Hello,

When a api return the response code :  **204 no content** i have a java.lang.NullPointerException.
![image](https://user-images.githubusercontent.com/36671939/39431305-9c67d5a0-4c90-11e8-877f-b5c547f9aa0e.png)

Service call : 
`{
  "Response": {
    "Header": {
      "X-Frame-Options": "DENY",
      "Keep-Alive": "timeout=15, max=100",
      "Server": "Apache",
      "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",
      "X-Content-Type-Options": "nosniff",
      "Connection": "Keep-Alive",
      "Set-Cookie": "JSESSIONID=***; Path=/stcom/; HttpOnly",
      "Pragma": "no-cache",
      "Expires": "0",
      "X-XSS-Protection": "1; mode=block",
      "X-Decathlon-Api-Correlation-Id": "****",
      "Date": "Mon, 30 Apr 2018 14:05:52 GMT"
    },
    "HTTP-Version": "HTTP/1.1",
    "HTTP-ReturnCode": 204
  },
  "Request": {
    "HTTP-Proxy": {
      "HTTP-Proxy": false
    },
    "HTTP-Header": {
      "Authorization": "Bearer ****",
      "cerberus-token": "26092",
      "Accept-Language": "fr-FR",
      "Content-Type": "application/json"
    },
    "HTTP-Request": "{\r\n  \"stock\": 3,\r\n  \"stock_date\": \"2018-04-30T09:43:45.335Z\"\r\n}",
    "HTTP-Method": "PATCH",
    "ServiceType": "REST",
    "CalledURL": "http://***/stcom/api/v2/stores/230/items/2171562/stocks",
    "HTTP-TimeOutMs": 30000
  }
}`

Can you fix this issue please ?

Thank's

Rémi.

**Comment by GrandjeanRemi** [comment]
Yes the answer is empty.

Thx for your fast reply.

**Comment by vertigo17** [comment]
Duplicate of #1661
