### ISSUE TITLE
Executions in error remain on the reporting page

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1718]
Hello,

When a execution on the report page is in error if the robot declination is set (like a constant: A) after resubmitting the executions in error the execution in error will remain on the report despite it has already been re-executed.

Can this be checked?

Regards
Cerberus Version : 3.4-SNAPSHOT-1319

**Comment by vertigo17** [comment]
Can you provide the screenshots in order to better understand the issue. 
I suppose it remains  on 2 different columns. What are they ?
Are both entries triggered with the same robot ?

**Comment by nicodeur** [comment]
Hi,

I confirm it's already fixed by commit 591144e2e14149ef48e9cf43f1c0ee106b0fc0d8 on android and iOS.

Available at the next release.
