### ISSUE TITLE
executeCommand action only has value1 and value2 visible after saving the TC

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1727]
Hello,

executeCommand action only has value1 and value2 visible after saving the TC

Also how can we store the value  of the executed command into a property? 

The usage would be to get the device name as it would solve problems like 
https://github.com/cerberustesting/cerberus-source/issues/1698
https://github.com/cerberustesting/cerberus-source/issues/1708

![imagem](https://user-images.githubusercontent.com/16339891/40118584-42145dba-5912-11e8-9f9a-a6f8f6313459.png)

Thanks and Regards

Cerberus Version : 3.5-SNAPSHOT-1335

**Comment by vertigo17** [comment]
I believe commit https://github.com/cerberustesting/cerberus-source/commit/49ab10a9c16901b6aa292466122bc36a0a287808 add the getFromComand that will allow to get the result into the property.
Please test it on next release.
