### ISSUE TITLE
Screen size list when editing test case

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1729]
Hi,

when editing the screen size of a test case if we type only one number to get a list of sizes the list is behind the box to edit test case.

Can you please take a look?

![image](https://user-images.githubusercontent.com/14328346/40171849-75e4511a-59c4-11e8-91a2-150b5b9a1083.png)

Thanks.

**Comment by ruirpr** [comment]
Still not corrected in the last release:
![image](https://user-images.githubusercontent.com/1914659/41340254-d7b7ccde-6eee-11e8-88de-3d1a6e65beff.png)

**Comment by vertigo17** [comment]
Please purge the cache or CTRL + F5 in order to force reload (on firefox).

**Comment by ruirpr** [comment]
Ok, thanks!
