### ISSUE TITLE
BUG : tab in a Test Name

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1731]
Hello, 

if you add a test "TestExample     " with a tabulation, the link with the testcase associated in the testcase script is broken. 

Could you maybe delete the tabulation or space during the save process or permit the tab in the name ? 

Thank you

**Comment by vertigo17** [comment]
We will automaticly remove the TAB caracter on create and duplicate testcase operation (inside servlet).

**Comment by Galand-V** [comment]
Correction has been released
