### ISSUE TITLE
Can't duplicate or create new datalib

### ISSUE THREAD

**Issue by Anokasv** [cerberustesting/cerberus-source#1733]
Hello, 

We can't create new datalib or duplicate one:

![image](https://user-images.githubusercontent.com/20952253/40417392-8d1ee248-5e77-11e8-985e-7b0225c8d0a5.png)

Stays "Processing..." and datalib is not duplicated or created.

Maybe the same problem as #1723? This issue was closed.
Thank you.

Best regards,
Ana Vieira

**Comment by vertigo17** [comment]
Yes please confirm it worst in QA (pick the same datalib as problem is linked with special characters).
As a workaround, you can create/duplicate it removing special caraters and put them back via update.
If workaround is too heavy, please update Cerberus to latest SNAPSHOT.
