### ISSUE TITLE
[Problem] Unable to install Cerberus 3.4

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1734]
Hello,

I try to install Cerberus 3.4 but I have an error when executing this command : docker-compose -f default.yml up

This is the error displayed : 

<img width="871" alt="capture d ecran 2018-05-24 a 17 20 57" src="https://user-images.githubusercontent.com/33724879/40495168-de18ea5e-5f76-11e8-9df2-8a1c5801e1e8.png">

**PS : The installation of Cerberus 3.3 is OK**

**Comment by vertigo17** [comment]
This looks like a know issue on last release that do not support yet glassfish 5.
A recent comit on master fixed the issue but you need now to wait for the next 3.6 release that will fix the docker issue.
Sorry about that.
We expect to do a new release next week.

**Comment by glassalle59** [comment]
Ok, thanks for your quick reply

**Comment by vertigo17** [comment]
I close it.
Please reopen after next release if you still have the issue.

**Comment by glassalle59** [comment]
Hello, I have the same issue with the 3.5 :(

_cerberus-as-glassfish_1  | * Starting Cerberus Glassfish setup...
cerberus-as-glassfish_1  | Waiting for cerberus to start ...
cerberus-as-glassfish_1  | Successfully started the domain : cerberus
cerberus-as-glassfish_1  | domain  Location: /glassfish5/glassfish/domains/cerberus
cerberus-as-glassfish_1  | Log File: /glassfish5/glassfish/domains/cerberus/logs/server.log
cerberus-as-glassfish_1  | Admin Port: 4848
cerberus-as-glassfish_1  | Command start-domain executed successfully.
cerberus-as-glassfish_1  | Command change-admin-password failed.
cerberus-as-glassfish_1  | Authorization has been refused for credentials [user: admin] given in this request.
cerberus-as-glassfish_1  | (Usually, this means invalid user name and/or password)_
