### ISSUE TITLE
[Evolution] Delete some execution TAG

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1735]
Is it possible to add an option to delete some TAG on "EXECUTION REPORTING BY TAG"

Indeed, I have a lot of TAG and it's very difficult to find one and very long to scroll the list

<img width="691" alt="capture d ecran 2018-05-24 a 17 23 19" src="https://user-images.githubusercontent.com/33724879/40495467-8e419cdc-5f77-11e8-8698-a6d8568228f2.png">

**Comment by vertigo17** [comment]
Duplicate of #1483.
Maybe you already seen it but select is autocomplete so if you start typing some characters, it will help you to find the correct one.
Like mentioned in previous ticket. I am not very keen in deleting old data execution but we can rediscuss that ;-) What would you expect when we delete the tag ? Keeping the execution but remove the link to the tag or delete all execution attached to the tag ?

**Comment by glassalle59** [comment]
I juste want to delete some of them to gain visibility. It's difficult to navigate with executions from 3 different projects. Indeed, whatever the chosen application, all tags appear :(.

**Comment by vertigo17** [comment]
Yes but if we delete them it will disappear from everyone.
Maybe the request is more to link the tag with system and only display tags from selected systems.

**Comment by glassalle59** [comment]
Yes it will be great !

**Comment by vertigo17** [comment]
duplicate from #1358
Will be solved thanks to system management.
