### ISSUE TITLE
Special characters are not displayed correctly in the api response

### ISSUE THREAD

**Issue by GrandjeanRemi** [cerberustesting/cerberus-source#1740]
Hello,

When an api return a response contains text with some special characters, they are not displayed correctly. 

`"prevention_message_simulation": ["A?e! Tu ne peux pas pratiquer de prix en dessous du seuil de revente ? perte pour les dates s?lectionn?es. Ton prix a ?t? automatiquement arrondi au dessus du seuil de revente ? perte"]`

And the text in element don't match : 

![image](https://user-images.githubusercontent.com/36671939/40609562-532b523c-626f-11e8-9edb-dcba8ac05d18.png)

Could you fix that please ?

Rémi.

**Comment by ryltar** [comment]
Hello,

![image](https://user-images.githubusercontent.com/13577630/41280967-929ffd42-6e30-11e8-8c94-6ae3218c3697.png)

Can't reproduce this issue ! can you try with the latest release of cerberus ?

**Comment by GrandjeanRemi** [comment]
Hello,

Yes i confirm that with the latest release it's ok
