### ISSUE TITLE
[BUG] Recursive issue on override properties

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1741]
Hello, 

I have an issue on properties : I have an inherited property I want to override on a TC. The issue is the property called is the inherited and the overrided property. 

![image](https://user-images.githubusercontent.com/29098010/40708489-dcd7f96a-63f3-11e8-9876-b9d9e9ba3679.png)

![image](https://user-images.githubusercontent.com/29098010/40708510-eab69f78-63f3-11e8-8334-5a20fefcc462.png)

![image](https://user-images.githubusercontent.com/29098010/40708552-017afcea-63f4-11e8-8319-92e4675fcb49.png)

![image](https://user-images.githubusercontent.com/29098010/40708558-080529d2-63f4-11e8-8adc-bb54256af6d3.png)

When I click on the eye picto, I should have the property **item_id** linked to the datalib **"item-active-supply_not_available_commande_manu"**. 

If I launch the following TC, I have the following error message : 

![image](https://user-images.githubusercontent.com/29098010/40708787-9eba20b2-63f4-11e8-9e98-79f5bea6a72f.png)

The data found is the one linked to the inherited property and **not the override property** ! 

![image](https://user-images.githubusercontent.com/29098010/40708804-ac0c91c8-63f4-11e8-80df-c2d5a8c4e97b.png)

**Comment by Galand-V** [comment]
The issue is more simple to solve than expected : The lenght of the Datalib name is too long...

"item-active-supply_not_available_commande_manu" => Bug described above
"item-active-supply_not_availabl" => working fine

**Comment by vertigo17** [comment]
So can you reexplain what is the bug ?
Is that a recursive error no each time the datalib name is too big ?

**Comment by Galand-V** [comment]
The error message displayed seems to be wrong. 

The current definition for the datalib name SQL field needs to be enlarge (at least to 50c)
A control should be added so the user can not edit more than the DB can support for the field

**Comment by vertigo17** [comment]
My question is how can I reproduce that issue in a simple way ?
Can I reproduce by creating a property getFromDataLib with a datalib name more that 50 caraters and the error message display will report a recursive error when it should just complain that datalib does not exist ?
Are you able to create a test in prod.cerberus-testing.org so that I can better understand ?

**Comment by Galand-V** [comment]
I cannot reproduce.... 

I will close this issue as it seems to have been "fixed"
