### ISSUE TITLE
RunTestCase servlet in error when trying to run an inactive TestCase

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1743]
URL called: `...myCerberuspath.../RunTestCase?Test=MyTest&robot=MyRobot&Country=FR&TestCase=0001B&Environment=QA&outputformat=verbose-json&synchroneous=Y&manualExecution=N`

The targeted TestCase is Inactive:

![image](https://user-images.githubusercontent.com/30227758/40837178-d985d2ee-6599-11e8-8e41-f2ae8b9355c4.png)

And the answer is HTTP 500 error:

![image](https://user-images.githubusercontent.com/30227758/40837193-eaf1e7b6-6599-11e8-98ed-5541b461a994.png)

**Comment by vertigo17** [comment]
Fixed with last commit.
