### ISSUE TITLE
Issue with update and creation service library

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1746]
Hello,

We can't add a % in a service library (create or update) : 

![image](https://user-images.githubusercontent.com/18569182/40917866-fa3261ac-6804-11e8-8cdc-c9524effa77b.png)

![image](https://user-images.githubusercontent.com/18569182/40917944-36d117f2-6805-11e8-8f70-7ec87e1db921.png)

This issue is pretty critical, it makes service library feature unusable. Could you have a look please ?

Cerberus Version : 3.5 -1345

**Comment by glassalle59** [comment]
+1

**Comment by glassalle59** [comment]
On 3.6 its OK but with new service. If we try to edit an old service Sith %, the bug is already here
