### ISSUE TITLE
Deleted fields when editing datalib on Edit TC page

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1757]
Hello if we edit Datalid inside Edit testcase page instead of http://cerberus.siege.red/Cerberus/TestDataLib.jsp page. the combobox with system, type, environment,country will be empty and can't be opened.

![imagem](https://user-images.githubusercontent.com/16339891/41416399-ac99b810-6fe2-11e8-98fe-d9d03438190d.png)

on datalib page everything is fine:

![imagem](https://user-images.githubusercontent.com/16339891/41416466-d298da8c-6fe2-11e8-910f-ad4e1c27a706.png)

Regards
Cerberus Version : 3.7-SNAPSHOT-1350

**Comment by ryltar** [comment]
Hello,

this issue was fixed yesterday.

10e1a9893ae9c581a2dbe7b39afa38ab182b3139

Regards
