### ISSUE TITLE
Unbale to insert TestCaseExecutionInQueue

### ISSUE THREAD

**Issue by jdimanche** [cerberustesting/cerberus-source#1758]
Hello, we suddenly have this error while trying to execute a new test :

> Unable to insert TestCaseExecutionInQueue [id=-1, test=ORDER - SIMPLE, testCase=ORDER CREATE ACCOUNT SK5 BIM CB PAUSE 2M, country=FR, environment=PREPROD, robot=TRUE_ROBOT, robotIP=selenium-hub, robotPort=4444, browser=chrome, browserVersion=null, platform=null, manualURL=0, manualHost=null, manualContextRoot=null, manualLoginRelativeURL=null, manualEnvData=null, tag=admin..20180615-144936, screenshot=0, verbose=0, timeout=10, pageSource=0, seleniumLog=0, requestDate=null] due to null
0 execution(s) succesfully inserted to queue. 

It's most likely to be a configuration change on another system maybe, but impossible to find out.
Are you able to tell me where the misconfiguration should be?

Thank's for your help.

Jérôme.

**Comment by vertigo17** [comment]
From which action do you get that error ? How do you submit the test execution ? GUI from which screen, Direct call to a public servlet ?
Maybe you can check that robot 'TRUE_ROBOT' exist (just a guess) ?

**Comment by jdimanche** [comment]
Action : Run the test case
Submit : from the GUI : /Cerberus/RunTests.jsp
The TRUE ROBOT exist with these parameters :
- host : selenium-hub
- port : 4444
- browser Chrome

**Comment by vertigo17** [comment]
That will be hard to solve without access to your environment.
Did you feed Platform at robot level ?
Did you try to select -- custom configuration -- on Robot and feed manually the host, port and browser ?
Can you try to change testcase, or env or country ?
The idea is to identify the criteria that make the execution queue failed to be inserted.

**Comment by jdimanche** [comment]
I tried some other tests / env / countries : same issue.

I know it could be hard to solve this remotely :) here are some screenshots to make sure everything is setup correctly.

https://screenshots.firefox.com/NmW6MgFxUEYK2aHy/svlvdmdsi01
https://screenshots.firefox.com/nHg1sUQ6TGbYnp98/svlvdmdsi01
https://screenshots.firefox.com/55XeWjRyih9PYiJ4/svlvdmdsi01

**Comment by vertigo17** [comment]
Did you try to select -- custom configuration -- on Robot and feed manually the host, port and browser ?

You said it suddently stoped to work. What have changed compared to before ? Did you upgrade a version ?

Can you try to submit the execution using the /AddToExecutionQueueV003 Servlet ? feeding only test, testcase, country, env and robot parameters. That will be easier to reproduce.

**Comment by jdimanche** [comment]
I tried the custom conf but it's the same.

I know that some people change few configurations (new tests and eventually change the robot configuration) but i cannot be sure of what has been changed. That's why i check every conf but it seems fine to me.

I'm trying the AddToExecutionQueueV003

**Comment by vertigo17** [comment]
What you can check also is that Application of the test case has a system that really exist in invariant table.

**Comment by jdimanche** [comment]
The system is present in the invariant table.

if i Use AddToExecutionQueueV003 with this url :

> http://svlvdmdsi01:18080/Cerberus/AddToExecutionQueueV003?test=BIC%20-%20ORDER%20-%20SIMPLE&testcase=ORDER%20CREATE%20ACCOUNT%20SK3%20BIM%20CB&country=FR&environment=PREPROD&ss_ip=selenium-hub&ss_p=4444&browser=firefox&platform=LINUX

I have the same response :

> Unable

 to insert TestCaseExecutionInQueue [id=-1, test=BIC - ORDER - SIMPLE, testCase=ORDER CREATE ACCOUNT SK3 BIM CB, country=FR, environment=PREPROD, robot=, robotIP=selenium-hub, robotPort=4444, browser=firefox, browserVersion=null, platform=LINUX, manualURL=0, manualHost=null, manualContextRoot=null, manualLoginRelativeURL=null, manualEnvData=null, tag=admin..20180615-164050, screenshot=1, verbose=1, timeout=null, pageSource=1, seleniumLog=1, requestDate=null] due to null
0 execution(s) succesfully inserted to queue. 

Any idea of how i can debug this servlet? Or how to make sure the robot is working and reachable?

Thanks for your help

**Comment by vertigo17** [comment]
Do you have any further log with Error entry "Unable to execute query" ?
There must be a invalid data that fail to be inserted to testcaseexecutionqueue table.

**Comment by jdimanche** [comment]
Hello,

Finally i found out what was the problem, no space left on the cerberus folder... So nothing to see with the app. Thank you for your help! And sorry for your time :)

J.
