### ISSUE TITLE
Bug when creating an environment in invariants menu

### ISSUE THREAD

**Issue by mflorid** [cerberustesting/cerberus-source#1761]
When you create or edit the name of an environment with a space ex : "PREPROD UX" cerberus allow you to do it but take this space like a "+".

Than you can create an environment (Integration -> Environment) but you can't edit it when you click on the edit button nothing happens.

And finally if you try to link your new environment with your application you got an SQL Error : 

> The CountryEnvironmentParameters that you are trying to INSERT conflicts with an existing one! Please check for duplicates! com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`cerberus`.`countryenvironmentparameters`, CONSTRAINT `FK_countryenvironmentparameters_01` FOREIGN KEY (`system`, `Country`, `Environment`) REFERENCES `countryenvparam` (`system`, `Country`, `)

If you delete the space in the environment name it solves the issue. May be put an advice about the name or solve this bug :)

**Comment by vertigo17** [comment]
Putting special characters and spaces inside COUNTRY and ENVIRONMENT invariant is not a good idea.
Not only for Cerberus but also when using Public API.
We will prevent those characters to be used in invariant screen.
