### ISSUE TITLE
Historic Executions associated to a wrong testcase

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1762]
Hello, 

If you delete an existing testcase and recreate an other one with the same [Test / TestCase] ID. The new testcase will herit from the old testcase historic. 

How to reproduce : 
1) Create a TestCase with Steps
2) Launch it
3) Delete it
4) Recreate a different TestCase with the same Test / TestCase Id
5) Go to "Executions List" 

=> The historic is linked to the old Testcase

**Comment by vertigo17** [comment]
This is the expected behaviour.
When a testcase is removed, the passed executions are no longer removed. This is to save history on past campaign and executions.
If you reuse a previous testcase id, you will get the past executions from it.
