### ISSUE TITLE
Sikuli: Keyboard missing keypress

### ISSUE THREAD

**Issue by liquidparker** [cerberustesting/cerberus-source#1763]
Cerberus Version : 3.4-1335

Hello,
We dont have specify key press in Cerberus like windows bouton(home), alt, ctrl, altgr, enter touch.
We dont have the reason of the problem too
![image](https://user-images.githubusercontent.com/40383408/41762372-c6c32604-75fa-11e8-8aa2-d05f8c60d71a.png)

**Comment by vertigo17** [comment]
All Key code has been added in commit: https://github.com/cerberustesting/cerberus-extension-sikuli/commit/1a59cb5d9459c8d72ba99549e5c484a7287a8256

**Comment by Nouxx** [comment]
By trying with the latest version of Cerberus sikuli extension (build today), I wasn't able to perform the keypress with Key.HOME

The action return 'OK', but the button isn't pressed.
![image](https://user-images.githubusercontent.com/30227758/42097955-ce408f10-7bb9-11e8-840c-1ff9c75e2f16.png)

If it can help, the Sikuli server log: 
![image](https://user-images.githubusercontent.com/30227758/42097899-a3497592-7bb9-11e8-9926-f71410576a27.png)
