### ISSUE TITLE
Problem installation Cerberus 3.4

### ISSUE THREAD

**Issue by liquidparker** [cerberustesting/cerberus-source#1764]
Cerberus Version : 3.4-1335

hello,

In the file '02DeployApp.bat' you have the line: "CALL %GLASSFISHPATH%asadmin.bat deploy --target server --contextroot Cerberus --availabilityenabled=true %MYPATH%\..\source\target\Cerberus-3.4.war" 
--> this dont work. I suppress the path "\source\target" and it work

**Comment by vertigo17** [comment]
Fixed for next releases with commit: https://github.com/cerberustesting/cerberus-source/commit/655751940dd037fa0057d5fdd22f7b894180e05f
