### ISSUE TITLE
Provide a solution to count elements for the Apps

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1765]
In order to improve some testcases it would be useful to have some way to count the number of elements by xpath:
something like:
![imagem](https://user-images.githubusercontent.com/16339891/41782118-3e7e0052-7631-11e8-8c0f-06103c1ee71b.png)

either in getFromJS or Groovy would be fine

Thanks and Regards

Cerberus Version : 3.7-SNAPSHOT-1356

**Comment by Nouxx** [comment]
For webapp, one workaround comes to my mind:

inside a getFromJS property:

- add to the DOM an hidden input
- in this input, store the xpath count result

```
$('<input>').attr({type:"hidden", id:"test"}).appendTo('body');
var xpath = // your xpath expression here (count)
$('#test').html(paragraphCount);
```
getFromHTML property:
- get the value using xpath 

`xpath=(//input[@id='test'])`

It's not clean at all though, but it works

**Comment by Nouxx** [comment]
Edit: using a single getFromJS property should work fine.

Can you share the property calculcation result? 

Thanks

**Comment by j0hnsa** [comment]
Hello @Nouxx ,

Thanks for the investigation, not sure if I applied well the solution you've provided but here's the result:

cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=61016420

Regards

**Comment by vertigo17** [comment]
Adding the screenshot in order to allow the community to see the result:

![2018-06-26 15_49_08-execution detail - 0005a_8 0_sm](https://user-images.githubusercontent.com/5342048/41916559-d28e3834-7947-11e8-9c6d-0c869fb2ca63.png)

Test is executed against an Appium Android application.
Looks like an Appium issue.
Have you ever manage to execute a JS from an Android application ?
Have you on IOS ?

**Comment by j0hnsa** [comment]
I'm able to run some basic operations, like handling some strings and such...

**Comment by vertigo17** [comment]
So I guess the ticket is more to be open on Appium side.
Please open it from there and reference it here for tracability.
I would propose to close the Cerberus ticket once done.

**Comment by lucashimpens** [comment]
Creator as left the company.
