### ISSUE TITLE
Get Focus from "GetFromJson" action on the last reponsefile

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1766]
Hello, 

I have a testcase with 3 "callservice". I try to reach the 2nd responsefile but I can not. It seems like the focus stay on the first callService responsefile and does not switch to the new response file. 

Is there a way to "switch" ? 

It could be nice to switch the focus  during the execution to the last fileresponse.

**Comment by vertigo17** [comment]
I implemented a testcase to cover the feature and confirm that every control is plug to the las callService action performed.

Test works fine and as expected:
http://vm.cerberus-testing.org:28082/CerberusPROD/TestCaseExecution.jsp?executionId=57100
triggers:
http://vm.cerberus-testing.org:28081/CerberusQA/TestCaseExecution.jsp?executionId=56978
that is a testcase with 3 callServices action and controls in between that checks that last service answer is always considered.

Please detail more your bug of even better implement a testcase to describe it.
