### ISSUE TITLE
Unable to retrieve gzipped http content

### ISSUE THREAD

**Issue by sarut0bi** [cerberustesting/cerberus-source#1769]
Hi, 
I want to set a property using getfromxml with a customURL but my server respond gzipped response.
Is there a way to handle those kind of compressed reponses? 
Ty,

**Comment by vertigo17** [comment]
Any test service available from Internet that we could play and test with ?

**Comment by sarut0bi** [comment]
i did not found any public services with same behavior :/
It seems to be natively supporty by any browser and Postman.

Just in case to be able to read what my webservice returns with curl, i have to do following command with curl:
_curl -H 'Accept-Encoding: Gzip' http://XX/xx.xml | gunzip_
or
_curl --compressed http://XX/xx.xml_

**Comment by vertigo17** [comment]
Can you provide the Response and Service Call JSON files as well as screenshot of the action execution report ?
The content of those :
![2018-07-02 18_05_57-execution detail - 0012b](https://user-images.githubusercontent.com/5342048/42174433-d635bab0-7e11-11e8-867d-bd13833721ce.png)
and
![2018-07-02 18_07_36-execution detail - 0012b](https://user-images.githubusercontent.com/5342048/42174580-5f5f1f20-7e12-11e8-9d09-d1e35e9d37b6.png)

Have you tried to feed the service header with key : 'Accept-Encoding' and Value 'Gzip' ?

Having a quick look at the code, we use:
HttpClient client = HttpClientBuilder.create().build();
By default it support compression with no issue the only way to remove compression in the code is to do:
HttpClient clientWithoutCompression = HttpClientBuilder.create().disableContentCompression().build();
But we don't use the disableContentCompression() method so in theory, it should work.

**Comment by sarut0bi** [comment]
Hi,

It works using services but not using getFromXml with a specified URL in properties :)
I'll use service so!

Thanks for help,

**Comment by vertigo17** [comment]
Sorry. I misunderstood the issue.
You are right, we should use the same method to retreive the data when using getFromXml (as well as getFromJson)
This is in the backlog of issue #1267.
I will add a comment to it and close that issue.
