### ISSUE TITLE
Request: Possibility to step loop a TEST CASE SCRIPT

### ISSUE THREAD

**Issue by liquidparker** [cerberustesting/cerberus-source#1770]
Cerberus Version : 3.4-1335

In cerberus, i have test case script with several step. 
I want loop all the test case but i got no option for that, only the possibility to loop a step. 
When you add step to a test case script from import library , if you cant loop the entire test case script , its a problem.
Perhaps a new tab with test case loop can be usefull. The goal is to use property , option 'NOTINUSE'.

Thanks if its possible

![image](https://user-images.githubusercontent.com/40383408/42025357-a8fb46dc-7ac4-11e8-8f29-7ac8c2e9ce21.png)

**Comment by vertigo17** [comment]
Hello @liquidparker The best is to put all your actions into a single step and loop over it.
Another way is to duplicate the testcase with different Ids and add them into the same campaign.

**Comment by liquidparker** [comment]
Hello Cerberus,

I am ok for copy all in single step but it take lot of time and the use of import of librairy become limited but its a contourn solution yeah...
The other way to duplicate in campagn, its what i use but it dont work for use the option notinuse loop... the loop still on only 1 step and not an entire test case script.
For me its necessary evolution but as perhaps its too hard to dev...

Thks for answer anyway

**Comment by vertigo17** [comment]
I can confirm the effort to dev is significant.
But more important, it looks like the need is more linked with automating a repetitive task but not really testing a feature.
Maybe the best is to share a real usecase of a real test in order to see the best way to implement.
