### ISSUE TITLE
The environment setting for an application disappears

### ISSUE THREAD

**Issue by GrandjeanRemi** [cerberustesting/cerberus-source#1771]
Hello,

I found a bug with this following steps : 

Add a environment to an application : 
![image](https://user-images.githubusercontent.com/36671939/42027690-9a7d39c0-7aca-11e8-8411-3e199f4c53d4.png)

Go to the environment page and modify the environment (here i add a database for example) : 
![image](https://user-images.githubusercontent.com/36671939/42027237-84063db4-7ac9-11e8-9b63-c3972debda1a.png)

Return to the application page and the previously modified environment has disappeared : 
![image](https://user-images.githubusercontent.com/36671939/42027268-92fe577a-7ac9-11e8-9da5-5aa1aee31edd.png)

Can you fix that please ?

Thanks.

Rémi.

**Comment by Nouxx** [comment]
Hello @GrandjeanRemi 

What is your Cerberus version ?

**Comment by GrandjeanRemi** [comment]
Cerberus3.6-1350

**Comment by Nouxx** [comment]
I was able to reproduce this bug in the exact same version

However, it works fine in **Cerberus 3.7-SNAPSHOT-1356**

**Comment by vertigo17** [comment]
Could not reproduce either.
Please reopen once we release 3.7 if issue is not fixed.
