### ISSUE TITLE
Can't add SUBDATA when edit Datalib from TestCaseScript

### ISSUE THREAD

**Issue by nicodeur** [cerberustesting/cerberus-source#1774]
Hello,

I can't add SUBDATA when edit Datalib from TestCaseScript.

It works fine from Datalib page.

**Comment by Nouxx** [comment]
Hello,

I couldn't reproduce in QA.

Step followed:

- Find a testcase and edit its script
- Create a **getFromDataLib** property and enter an existing Data Lib
- Edit the DataLib from the TestCaseScript page 
- Add a subdata with value 'test' for each row
- Save the datalib, then the testcase.

The data were saved sucessfully.

Am I missing something ?

**Comment by nicodeur** [comment]
Effectively,

It doesn't work on Cerberus prod (3.6) but it works on QA (3.7-SNAPSHOT).

So it's already corrected for the next release.

Thanks @Nouxx 

Nicolas
