### ISSUE TITLE
Datalib - call a Service - Type should be mandatory (blank by default)

### ISSUE THREAD

**Issue by nicodeur** [cerberustesting/cerberus-source#1775]
Hello,

I created a new `datalib`, but I forgot to enter the `Type` of datalib.

When I tested it on  execution, Test is kept on `PE`state, and a stack trace appear to the log.
So 2 problems : 
* To Avoid this, I think `Type` should be mandatory.
* Sometimes when an error occured, test doesn't change his `state`to error, and is kept on `PE`

**Comment by Nouxx** [comment]
I think the type is already mandatory. The UI autofill this field with 'INTERNAL'

![image](https://user-images.githubusercontent.com/30227758/42097080-7264516a-7bb7-11e8-84b8-0279ff88224f.png)

Besides, the field 'Type' in DB can't be null

**Comment by nicodeur** [comment]
You're right, So Field select box should be blank by default

**Comment by vertigo17** [comment]
How did you manage to have type empty ?
On my side creating the datalib default to INTERNAL.
Maybe could be linked to datalib modal issue from testcase that got some regression on last release ?
Do you manage to reproduce in qa.cerberus-testing.org ?
