### ISSUE TITLE
DataLib - Edit DataLib from TC

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1777]
Hello, 

If you try to edit a datalib from a tc, all the fields are empty : 

![image](https://user-images.githubusercontent.com/29098010/42208587-d3ebcfe2-7eac-11e8-8f4d-754fa0c1c795.png)

If you save without paying attention, the type in the DB will be "NULL" , that will lead to execution stay in status pending for days. 

To reproduce : 

1) go to : http://vm.cerberus-testing.org:28082/CerberusPROD/TestCaseScript.jsp?test=GUI%20%3A%20Administration&testcase=0002A
2) go to property tab 
3) edit user datalib property

**Comment by vertigo17** [comment]
Should be already fixed in QA.
Can you confirm and close the issue ?

**Comment by Galand-V** [comment]
Corrected in QA !

Thank you
