### ISSUE TITLE
Datalib INternal Cerberus - two data set

### ISSUE THREAD

**Issue by FRBON** [cerberustesting/cerberus-source#1778]
Cerberus Version : 3.4-1335

Hello,

When I add a datalib type = Internal cerberus test data

if I want to add two data:
NOM1, PRENOM1
and
NOM2, PRENOM2

I have to put two subdata NAME and FIRST NAME.

but then when I enter in the value column
NAME1 and PRENOM1

how to add the second data

NAME2 and PRENOM2

Must add a second datalib1 which contains the second data,
each datalib can only contain one data?

or should we rather use the csv for this kind of case?

Frédéric Bonnet

**Comment by vertigo17** [comment]
Yes, you can either:
1/ add another datalib INTERNAL entry with the same name (duplicating the 1st one) --> fully administered inside Cerberus but only works when few data entries.
2/ move type to CSV and upload the csv file to Cerberus --> Data can be prepared in an excel sheet and uploaded to Cerberus.
3/ manage a database table and create a SQL datalib with SQL request and columns mapping.

If you have very few entries, pick the INTERNAL, if you start to have a bit more use CSV and SQL for even more.
