### ISSUE TITLE
SYSTEM creation with spaces in the name

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1781]
Hello, 

If you create a SYSTEM invariant with a space in the name "SYSTEM NAME", the applications / environnements created will not be visible in the concerned page after its creation. 

How to reproduce : 

1) create a system with a space in the name "LIKE SO"
2) go to application page 
3) create an application 

=> application not visible in the list 

4) go to environnement page 
5) create an environnement

=> environnement not visible in the list

Maybe users should be limited for system creation : not being allowed to create system with special caracters in it.

**Comment by vertigo17** [comment]
Already fixed in https://github.com/cerberustesting/cerberus-source/commit/81da4b3207d5a429728fa7bd21d7874362fd0cae
Will be available in next release.
