### ISSUE TITLE
All "secure data" from parameters are visible with the filters

### ISSUE THREAD

**Issue by PeillY0u** [cerberustesting/cerberus-source#1783]
By setting the mail, I realized that all "Secure data" from the parameters are visible with the filters.

Some screens for the example :

<img width="957" alt="2018-07-05_12h05_15" src="https://user-images.githubusercontent.com/5746466/42317297-40a59a82-804c-11e8-8f42-0d68581588a4.png">

<img width="958" alt="2018-07-05_12h05_46" src="https://user-images.githubusercontent.com/5746466/42317300-42650dd0-804c-11e8-87e9-4d0635e03e11.png">

**Comment by vertigo17** [comment]
Nice shot ;-)
Just fixed with last commit.
