### ISSUE TITLE
Dockerized cerberus extension?

### ISSUE THREAD

**Issue by jdimanche** [cerberustesting/cerberus-source#1787]
Hi,

You gave the dockers to run Cerberus, do you have any updated docker with this sikuli extension pre-installed before I start to do it.

Thank's
Jérôme.

**Comment by vertigo17** [comment]
no, There are currently no docker for sikuli extension.
Feel free to propose a version.
Make sure you propose it to https://github.com/cerberustesting/cerberus-extension-sikuli

**Comment by vertigo17** [comment]
Duplicate of https://github.com/cerberustesting/cerberus-extension-sikuli/issues/4
