### ISSUE TITLE
sikuli / controls possible

### ISSUE THREAD

**Issue by FRBON** [cerberustesting/cerberus-source#1789]
what are the possible controls to check that a page has the right element?
For example, verifytitle or verifytextinelement does not work with sikuli.

**Comment by vertigo17** [comment]
You can use verifyElementPresent.
If you feel a control is not supported for FAT application when it should please ask ;-)

**Comment by FRBON** [comment]
how do you know what to put with sikuli?


what to put with verifyelementpresent to verify that the following page is correct:

![image](https://user-images.githubusercontent.com/40494434/42750459-9d5500d0-88e7-11e8-83b6-044dd9ab2c8c.png)

**Comment by FRBON** [comment]
I don't find the syntax for verify for examples that récuperation is present

![image](https://user-images.githubusercontent.com/40494434/42816474-34d25e6a-89cb-11e8-882e-813fda986557.png)

The two examples next are no ok :  
verifyelementpresent Récupération
verifyelementpresent data-cerberus=Récupération

![image](https://user-images.githubusercontent.com/40494434/42816613-afc67796-89cb-11e8-8628-3a50d2974748.png)

**Comment by Nouxx** [comment]
Hello @FRBON 

As you might know, Sikuli is based on screen image recognition, which means that you can only provide Cerberus with pictures (unless you're using an hybrid Selenium/Sikuli node)

Consequently, you need to select the screenshot that you want to compare to the test case execution. Cerberus is handling images with **Application Object** ('Application' Menu)

- **Object**: name of your application object
- **Value**: (optionnal in this situation)
- **File Name**: drag and drop field to upload the image

![image](https://user-images.githubusercontent.com/30227758/42821934-04df3f8e-89da-11e8-9b29-2df9e7b438f6.png)

To call the image in Cerberus, you must use the following syntax: `%object.NameOfYourObject.pictureurl%` in the verifyElementPresent control.

**Comment by FRBON** [comment]
Hello

I do not understand this point

I put a check to verify that an image is present.

I'm doing putting a bad picture to make a knockout and the status is FA instead of knockout


![image](https://user-images.githubusercontent.com/40494434/42872191-8ec672a6-8a7c-11e8-9d70-94e2a0485f6a.png)

The result is like this : FA and not KO 

![image](https://user-images.githubusercontent.com/40494434/42872322-eb0c770e-8a7c-11e8-9241-c314bde5e334.png)

Why the result is not KO ?

FRBON

**Comment by Nouxx** [comment]
An action in Cerberus can have these status : 
- OK : the action performed well
- FA : the action didn't performed well
- NA : the action (that is searching for data) did'nt find any

A control can have these status : 
- OK : the verification returns true
- KO : the verification returns false

Consequently, an action can't be 'KO'

The FA status has more authority in the global execution result, which means that if any of your action is FA, the execution status will be FA, even if some controls are KO.

In your testcase, you're trying to click on an area that is not present on the screen, which make the action 'click' failed.

Do that make sense to you ?
