### ISSUE TITLE
Sikuli - Test already in run but execution report = FA

### ISSUE THREAD

**Issue by FRBON** [cerberustesting/cerberus-source#1794]
Hello,

with Sikuli, what is the parameter to modify so that a test does not remain for a very long time like this :   

screenshot 1

![image](https://user-images.githubusercontent.com/40494434/42885794-3e1ddc74-8aa2-11e8-93b9-2e0568292522.png)

The execution report is like this :   statut FA

screenshot 2

![image](https://user-images.githubusercontent.com/40494434/42885966-b10212d2-8aa2-11e8-8809-7258fe686f24.png)

But the execution report means it's not finish (cf screenshot 1)

**Comment by vertigo17** [comment]
That looks more like a bug where control is not updated when failed.
I will try to reproduce and fix.

**Comment by vertigo17** [comment]
Can you provide the content of the control and the full error message that unfortunatly does not appear in the screenshot (truncated) ?
Looks like there were an exception : Exception Java.lang.....

**Comment by FRBON** [comment]
Hello,
I can not reproduce the problem anymore
Now it's OK.

**Comment by vertigo17** [comment]
A recent comit have fix a similar issue but looks like this one is another exception.
I close the issue but please reopen or create a new one directly with the full error message if happens again.
