### ISSUE TITLE
Requirements (labels) aren't filtered by System

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1799]
In the **Label** > **Requirement** tab, all the labels are displayed without any filtering on the system selected although it is done for all the others labels.

![image](https://user-images.githubusercontent.com/30227758/43004267-7e01a440-8c2f-11e8-895c-03bec5d0c61e.png)

**Comment by vertigo17** [comment]
@Nouxx duplicate from #1791.
Time to rest and enjoy the week end ;-).
