### ISSUE TITLE
Labels : can't use the search bar in the parent section

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1801]
Hello,

When adding a Parent label, I coudn't use the search bar to find easily the label to add:

![image](https://user-images.githubusercontent.com/30227758/43005046-ebbddd3a-8c31-11e8-893b-3602cbf58ae5.png)

It's not possible to click or type in the searchbar

Thanks

**Comment by ryltar** [comment]
it's working now both on chrome and firefox (d18520d)
