### ISSUE TITLE
Label: view & edit the requirement from the tree

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1805]
Hello,

What do you think about adding two buttons for each element in the label tree 

- **Edit** : open the edit label modal
- **View** : view the testcase linked to this label (can also be included in the 'List' Tab)

![image](https://user-images.githubusercontent.com/30227758/43149561-fc6835ac-8f67-11e8-80b3-8537116d1406.png)

**Comment by vertigo17** [comment]
Looks duplicate of #1677 and #1672 ?
