### ISSUE TITLE
Sikuli Key ALT+F4

### ISSUE THREAD

**Issue by FRBON** [cerberustesting/cerberus-source#1808]
Hello

For close the windows with focus, i do

KeyModifier.ALT + Key.F4

![image](https://user-images.githubusercontent.com/40494434/43255706-e511204e-90ca-11e8-8a2c-676ab0b210b2.png)

The execution is OK but the windows is always open : 

![image](https://user-images.githubusercontent.com/40494434/43255969-90464584-90cb-11e8-9d67-281284812a8d.png)

The sreenshoot execution is this

![image](https://user-images.githubusercontent.com/40494434/43255782-18d5efe0-90cb-11e8-8d5d-52259cc1cca5.png)

we can see that the window has the focus, so alt + F4 should close it

**Comment by htopoff** [comment]
Hi,
you can take a screen of the closing cross:
![2018-07-27 16_05_22-sikuli key alt f4 issue 1808 cerberustesting_cerberus-source](https://user-images.githubusercontent.com/38133450/43325422-e94bf21e-91b6-11e8-9693-61562073a12c.png)
And click on picture instead of key pressing.

**Comment by FRBON** [comment]
Hello

I do that.


Thanks
