### ISSUE TITLE
Upgrade from 2.0.0 to 3.7.1

### ISSUE THREAD

**Issue by jtentelier** [cerberustesting/cerberus-source#1809]
Hello, I have got an issue when i'm trying to upgrade the glassfish server from 2.0.0 to 3.7.1, he always tells me that : 

![image](https://user-images.githubusercontent.com/41323800/43323485-12d81108-91b2-11e8-8da5-bdcb18e828f3.png)

even i have added the GLASSFISH_DOMAIN=cerberus to my glassfish docker.

here is my default.yml

![image](https://user-images.githubusercontent.com/41323800/43323571-52ef15f2-91b2-11e8-9858-c2091fa6036b.png)

do you have any clue to resolve this ?

Thank you for your help

**Comment by nicodeur** [comment]
Hello,

You have an error on you docker-compose.yml, volumes on cerberus-domain is : 
```
 - ./localdata/cerberus-domains:/glassfish5/glassfish/domains/cerberus
```
(you forgot the `s` on `domains`)


When you pull cerberus-as-glassfish:3.7.1 ? 

I pushed a fix at 11h30 am this morning on this bug, so you can try a 
```
docker pull cerberustesting/cerberus-as-glassfish:3.7.1
```
to force repull the image, and retest

**Comment by jtentelier** [comment]
Thank you for your answer, no, when i'm launching it, i'm trying it and will come back to you.

Thanks

**Comment by jtentelier** [comment]
Thank you, that works, issue can be closed :)
