### ISSUE TITLE
Manage a Robot pool to parallelize Mobile Execution

### ISSUE THREAD

**Issue by nicodeur** [cerberustesting/cerberus-source#1811]
Fell free to edit

## Goals
Goals is create a robot pool to parallelize Mobile Execution : to day, we can execute only test one by one on mobile.

Here Idea we discuss after a Cerberus Meeting : 

## UI - Robot management
Delete connector information from `Definition` part : 
![capture d ecran 2018-07-31 a 11 30 03](https://user-images.githubusercontent.com/6707556/43459291-5af06bca-94cd-11e8-8514-f31924c6e990.png)

Add an `Executors` part : Can contains 1 or several connectors. 
Add optionnels fields `Mobile Name` and `Mobile UUID`, only mandatory for mobile testing.
Add an `Executor` name (possible to edit with a double click or other ....)
<img width="590" alt="capture d ecran 2018-07-31 a 11 57 12" src="https://user-images.githubusercontent.com/6707556/43459292-5b2ae016-94cd-11e8-8361-a16365a521d5.png">

On Report, we display RobotFunctionnal and not the RobotExecutor

## Technical

Cut with 2 tables robots definition : 

_A robot fonctionnel can have 1.N RobotExecutor_

RobotFunctionnel
*----------------*
Name
Browser
Resolution
UserAgent
\+ global capabiliies

RobotExecutor
*----------------*
Name 
IP / Port / User / Password
\+ devices capabiliies ( ex : **Automator**  \~_fix it to UIAutomator for APK ? idem for iOS ?_ \~, **UUID** , **deviceName**, **systemPort** \~_manage it in the code ?_\~ , etc)

**Comment by vertigo17** [comment]
Thanks @nicodeur , can you confirm that deviceUUID and deviceName are the only 2 data necessary to feed the executor capabilities ?
NB : I will probably add an activation flag + priority number at the level of the executor.

**Comment by nicodeur** [comment]
Hi, 

Yes,  deviceUUID and deviceName are the only 2 data necessary to feed the executor capabilities

**Comment by vertigo17** [comment]
Last commit introduced the feature that can be tested. 
Only thing left to do is on the queue management screen the left to be executed on contrain3 type that always display 0.

**Comment by vertigo17** [comment]
I removed the 0 and left it empty as on the screen this is not possible and accurate to guess how many executions in the queue will be assigned on a specific robot. This is subject to change depending on execution timings.
