### ISSUE TITLE
[Bug] Problem when réexecuting all KO / FA on a campaign "Determined from Test case Group value"

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1813]
Cerberus Version : 3.6-1350

Since the evolution #1719, we can execute some campaign which contains both manual and automated test (thank you once again).

However, if some manual tests are on KO or FA status, and if I want to réexecute all tests KO / FA (automated) then even the manual tests are also impacted and will become NE (non executed)

<img width="717" alt="capture d ecran 2018-08-01 a 22 26 25" src="https://user-images.githubusercontent.com/33724879/43547041-6ac4ec98-95da-11e8-8afd-2244c6262aa9.png">

This is very problematic because it erases the previous execution of the manual test.

Is it possible to divide this menu to run either all automated tests or all manual tests?

**Comment by vertigo17** [comment]
Good idea.
I made that:

![image](https://user-images.githubusercontent.com/5342048/43550622-84123746-95e4-11e8-8cb0-2eeafc45e1d2.png)
