### ISSUE TITLE
Split properties in two categories

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1814]
Hello,

What do you think of having two types of properties? 
- **Main** : refers to the properties that are supposed to be highlighted for the business user(s) who analyse the execution 
- **Additionnal** : properties that still needs to be accessible but with less value to the scenario itself. (e.g. today date calculcation, xpath calculation, etc..)

The most notable change would be in the execution report, I'm thinking about hiding all the Additionnal properties (using a collapse).

In my current approach to test artchitecture, I try to find the best mix between **flexibility**, which often means 'a lot of properties' and **user readability**, which supposed to have a minimum amount of properties. Having these two types would allow me to have both!

The default type for a property should be 'Main'

**Comment by vertigo17** [comment]
I guess we also need to add the Rank column on execution table as well.
Let's share on that together in order to create the additional field correctly on DB.

**Comment by vertigo17** [comment]
2 small issues to fix:
1/ Shortcut link do not work when row is secondary. It scroll to primary row.
2/ Delete buttons do not delete the correct records. delete on secondary delete primary.
3/ Delete button no longuer change the background colour of the row when secondary.

**Comment by Nouxx** [comment]
Discussion about 
- the name 'Rank' : not easy to understand enough : type functionnal / technical
- the integeter nature : shoudn't be true or false
- color the button
