### ISSUE TITLE
[Enhancement] Add environment on notification email

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1815]
Hi,
Would it be possible to add the environment on the start and end notification email?
It could be added on the subject and on the notification body content.

Example for the notification subject:
_[Cerberus] Tag Execution CMS_Regression_Tests_2018080612 [CMS_Regression_Tests] started for PreProd [Environment].
[Cerberus] Tag Execution CMS_Regression_Tests_2018080612 [CMS_Regression_Tests] finished for PreProd [Environment]._

For example on the start email notification:
![image](https://user-images.githubusercontent.com/17747042/43764624-cccad4da-9a25-11e8-9848-c389974d5c97.png)

For the end email notification (the environment is present when we have failed tests but when all is ok the table with the test case not OK is not populated and the env. is not visible):
![image](https://user-images.githubusercontent.com/17747042/43765695-76261308-9a28-11e8-87e3-31d535b80f91.png)

Thanks in advance.

**Comment by vertigo17** [comment]
In fact a campaign can be linked to many environment. 
What I can propose is to add 3 variables that would include coma separated list of environment, country and robot decli. 
List would be retreived at start and end of tag execution based on list of execution/queue entries.

**Comment by ffazendeiro** [comment]
Hi,
Yes, it would be fine.
Like this we will have a little more information on the notification email. :)
Thanks!
