### ISSUE TITLE
[Enhancement] Get service call properties

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1816]
Hi,

Would it be possible to get the Service Call properties?
For example, on a POST that is expected to return error we don't have any response:
![image](https://user-images.githubusercontent.com/17747042/43767357-ce4d8080-9a2c-11e8-9511-3f58344d1282.png)

We can get the HTTP code using %system.LASTSERVICE_HTTPCODE% but cannot have access to the Service Call information (like the header for example):
![image](https://user-images.githubusercontent.com/17747042/43767550-55d6f824-9a2d-11e8-96a1-4093bc79bef8.png)

But even if the the POST returns a response, some test would be improved if we could get information from the call service header (for the example above, the field X-iofrGetServiceApp-alert would improve the test quality)

Currently a workaround is to get the file stored by the execution but this is not the best practice (if the path or the step/action changes the file will not be retrieved):
![image](https://user-images.githubusercontent.com/17747042/43768238-cab1053a-9a2e-11e8-9692-db325ad787a1.png)

Perhaps having one of the following
1. A system property like %system.LASTSERVICE_CALL% that would store the json file
2. A new property getFromServiceCall

Thanks in advance.

**Comment by vertigo17** [comment]
Target will be to create a setContent action with json system variable on last call response.
That would allow to put control in jsonpath format to that json

**Comment by vertigo17** [comment]
Already available.
