### ISSUE TITLE
Feature Request : MariaDB support

### ISSUE THREAD

**Issue by kwaio** [cerberustesting/cerberus-source#1817]
Hi,

After struggling to make the containers work with a MariaDB (1.x) external Database and talking with one of the developers, it appears they are not compatible with MariaDB for the moment due to hardcoded JDBC MySQL driver.

Could you please make the JDBC drive modular and allow overriding easily the driver to load via an environment variable (seems there was DATABASE_TYPE in the past)

That would also allow to move the database docker image provided to MariaDB too and stay in the Open-Source path without dependency to Sun Microsystems.

Thanks in advance.

**Comment by vertigo17** [comment]
Cerberus already support mariadb. In order to activate it you need to put the driver in lib folder and configure corresponding class name in server.xml config file.
