### ISSUE TITLE
Chrome tests with resolution

### ISSUE THREAD

**Issue by mbessa** [cerberustesting/cerberus-source#1818]
Hello

When lauching tests with resolution in chrome (mobile tests) browser open's and don't do anything.
Error from selenium is: **Command duration or timeout: 0 milliseconds. Exception: org.cerberus.exception.CerberusException: org.cerberus.exception.CerberusException: org.openqa.selenium.WebDriverException: unknown error: failed to change window state to normal, current state is maximized**

Here's one example: http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=62931880

This is very frequent when lauching tests with AddToQueueV03 (from GUI or API, doesn't matter), not so much when triggering single test from GUI.

chrome 64 / chromedriver 2.35 / selenium 2.45

In firefox the issue isn't present and I also tried with latest chrome and chromedriver versions but the issue still happens.

Let me know if you need more details.

Thank you in advance

**Comment by f3ltron** [comment]
We have exactly the same error. We can't change resolution in robot. We have to rollback to an hold version :(

**Comment by vertigo17** [comment]
An old version of what ? Cerberus, Selenium Server, Chromedriver or Chrome.
On my side I tested 50 executions without any Failed and error message with:
Cerberus 3.11 SNAPSHOT / Selenium 2.45 / ChromeDriver 2.35 / Chrome Version 65.0.3325.181

@mbessa can you try with latest snapshot ? If error still happen, can you try to reproduce using BrowserStack

**Comment by DevKeet** [comment]
Hello

Same issue **Exception: org.cerberus.exception.CerberusException: org.cerberus.exception.CerberusException: org.openqa.selenium.WebDriverException: unknown error: failed to change window state to normal, current state is maximized** with Cerberus 3.9 / Selenium Hub 3.14.0 / Chrome 70.0.3538.77 / ChromeDriver 2.43.600233

Images use came from https://hub.docker.com/u/selenium version 3.14.0
Same errors with selenium images version 3.141.59

Thank you

**Comment by lucashimpens** [comment]
Creator left the company
