### ISSUE TITLE
2nd condition when executing action

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1821]
Hello,

Would it be possible to have one more condition operator for the actions execution? 
For instance on iOS tests i have one popup that is showing up all the time for FR so I had to add a lot of ifElementPresent to my tests but this is causing the tests to run a lot slower for other countries where the popup never show up. Either I'll have to duplicate the tests to have specific tests for FR or if this second condition is implemented and i could use a combination of ifElementPresent and ifStringEqual (%system.country% >> FR).

What do you think?

Best Regards,

Cerberus Version : 3.8-SNAPSHOT-1359

**Comment by glassalle59** [comment]
I want too to have more than one condition per test. It is possible to add a "+" for example to a condition and so let us to have more than one condition

**Comment by lucashimpens** [comment]
Creator has left the company. (La Redoute)
