### ISSUE TITLE
can't modify a robot

### ISSUE THREAD

**Issue by cDelage** [cerberustesting/cerberus-source#1825]
when you click on the pen's button, nothing happens
![capture](https://user-images.githubusercontent.com/42372508/44724086-0ba4bd80-aad2-11e8-9d95-c8ed2050e212.PNG)

**Comment by Galand-V** [comment]
Hello, 

which version do you use ? 
I do not reproduce on the 3.7.1

![image](https://user-images.githubusercontent.com/29098010/44724223-61796580-aad2-11e8-9f96-2ead3ec661b2.png)

**Comment by ryltar** [comment]
On the QA (dev version) which introduce now robot executors :)
