### ISSUE TITLE
automationName capability is not being sent from Robot capabilities

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1828]
Hello,

When I was creating a robot to test the new feature on iOS also, it seems that not all capabilities are being sent.. Had to add --automation-name on the server arguments (launching appium) as without this capability I'm not able to execute the tests.

![imagem](https://user-images.githubusercontent.com/16339891/44996500-237fb400-afa0-11e8-8f7f-4bddf08ac666.png)
![imagem](https://user-images.githubusercontent.com/16339891/44996534-56c24300-afa0-11e8-9c3c-fc52df51bd92.png)

Best Regards

Cerberus Version : 3.8-SNAPSHOT-1382

**Comment by vertigo17** [comment]
Can you provide the json file available from Robot TAB in execution screen to see what Cerberus asked the Appium driver to consider ?
RequestedCapabilities correspond to the undecoded capabilities defined at robot level.
FinalCapabilities correspond to decoded robot capabilities + the additional automatic added capabilities.

example:

![image](https://user-images.githubusercontent.com/5342048/44999483-da3e5d00-afbd-11e8-974e-6ef92eb3b455.png)

**Comment by j0hnsa** [comment]
Hello,

The requested capability seems to be there:
{
  "FinalCapabilities": {
    "app": ["/LaredouteApps/LaRedoute_v8_10_1_437.ipa"],
    "simpleIsVisibleCheck": ["true"],
    "clearSystemFiles": ["true"],
    "xcodeOrgId": ["4U595J2NG8"],
    "fullReset": ["true"],
    "version": [""],
    "deviceName": ["e6404a7becbe8260119eedfb91e67e7937ea4d2c"],
    "xcodeSigningId": ["iPhone Developer"],
    "platform": ["MAC"],
    "showIOSLog": ["false"],
    "showXcodeLog": ["false"],
    "maxTypingFrequency": ["4"],
    "useNewWDA": ["true"],
    "automationName": ["XCUITest"],
    "browserName": ["iPhone"],
    "platformName": ["iOS"],
    "udid": ["e6404a7becbe8260119eedfb91e67e7937ea4d2c"],
    "systemPort": ["5556"]
  },
  "RequestedCapabilities": {
    "showIOSLog": ["false"],
    "simpleIsVisibleCheck": ["true"],
    "clearSystemFiles": ["true"],
    "showXcodeLog": ["false"],
    "maxTypingFrequency": ["4"],
    "xcodeOrgId": ["4U595J2NG8"],
    "useNewWDA": ["true"],
    "automationName": ["XCUITest"],
    "platformName": ["iOS"],
    "fullReset": ["true"],
    "xcodeSigningId": ["iPhone Developer"]
  }
}
but the error is thrown:
http://192.168.135.30/CerberusQA/TestCaseExecution.jsp?executionId=63896760

**Comment by vertigo17** [comment]
Sorry but I double check on the code and what appears on the json is really what is sent to Appium/Selenium.
There are no specific treatment on "automationName" appart from seting a default value to UIAutomator2 in case it is not set.
Is that only on "automationName" capability or is it more general to the others capabilities ?
Is that a new behaviour on 3.8 or was it also the case on 3.7.1 ?

**Comment by j0hnsa** [comment]
Hello,

I always needed to pass automationName , UIAutomator2 is default for Android devices for iOS XCUITest, this capability is required but I can put on server side...
Best Regards

**Comment by vertigo17** [comment]
So i understand that it was already like that in 3.7.1. 
I guess this is more an Appium issue and not sure we can do anything on Cerberus side.

**Comment by j0hnsa** [comment]
I used to pass this capability on robot definition and it worked and now it doesn't so i think that this is not appium issue... Anyway, can be solved passing --automation-Name XCUITest when launching appium.

**Comment by j0hnsa** [comment]
Problem seems to be solved on Cerberus3.9-1388 release, Thanks!
