### ISSUE TITLE
Memory issue with the "Run Test Case(And See Result)"

### ISSUE THREAD

**Issue by yun59000** [cerberustesting/cerberus-source#1829]
Hi, when i launch a nice medium test case (>5min of execution) with the "Run Test Case(And See Result)"
The memory of the browser where the exection step are displayed is increasing till the test ends or fail.
it goes in my case almost to 90%.
it looks like the execution take more and more time between action.
when i close the browser the memory goes down and the execution return to normal.
i tryed with the display in another browser and got the same result, and all of my execution settings are sets to 0 (execpt timeout: 10000)
My cerberus version is 3.7.1-1359
My selenium standalone server version is the latest: 3.14.0
My webdriver version of chromedriver is the latest: 2.41
We just update cerberus from 3.3 to the latest yesterday. and that test case was working fine with the same parameters.

**Comment by yun59000** [comment]
hi,
cerberus_featureflipping_activatewebsocketpush : Y
cerberus_featureflipping_websocketpushperiod : 1000

FYI my tests case have a lot of step case(almost 50) with a lot of objects(almost 100) and a lot of properties (almost 50 and 100 inherited).

**Comment by vertigo17** [comment]
Please reopen if still relevant.
