### ISSUE TITLE
Error on javascript execution

### ISSUE THREAD

**Issue by sarut0bi** [cerberustesting/cerberus-source#1834]
Hi,
I ve got a problem when using several variable calculated with javascript: Here is my scenario:
* I call an API 
* I calculate var1 using JSONPath 
* I calculate var2 using javascript (return %property.var1%)
* I calculate var3 using javascript (return %property.var2%)

Then always get following error when calcuate var3: 
'Failed to Execute script! Exception reached : unknown error: Runtime.evaluate threw exception: SyntaxError: Unexpected number.'

Could u help me?

**Comment by sarut0bi** [comment]
I have to stringify my return on step3 to avoid errors on step4

**Comment by sarut0bi** [comment]
![image](https://user-images.githubusercontent.com/9832657/45301891-29cade80-b512-11e8-9a06-8ae66b289fb3.png)
![image](https://user-images.githubusercontent.com/9832657/45301911-3b13eb00-b512-11e8-92ed-8440ca9490ec.png)
![image](https://user-images.githubusercontent.com/9832657/45302324-4adfff00-b513-11e8-832d-7173b5025ca6.png)

**Comment by vertigo17** [comment]
Looks like a javascript issue (not really Cerberus related). 
Have you checked 
https://stackoverflow.com/questions/42006503/invalid-shorthand-property-initializer
?

Looks like the first return is converting a string to a json object.
The Second return has the object but does not expect to return an object.
Not sure what you want to acheive but you could try
return "%property.temp2%"
for temp3
?
