### ISSUE TITLE
click dropdown with id= data-cerberus xpath= gets in the way

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1845]
![image](https://user-images.githubusercontent.com/16339891/45613697-072f4d00-ba5f-11e8-8d36-58885ccf78cc.png)

Cerberus Version : 3.8-SNAPSHOT-1384

**Comment by vertigo17** [comment]
Regression on 
vm.cerberus-testing.org:28082/CerberusPROD//TestCaseExecution.jsp?executionId=76051
