### ISSUE TITLE
When i have a failing condition on a action with "PE" to force execution 

### ISSUE THREAD

**Issue by cDelage** [cerberustesting/cerberus-source#1848]
I can't execute some action after my failing condition because when the condition failing the step are stopped.

![image](https://user-images.githubusercontent.com/42372508/45623137-9a2fad80-ba86-11e8-8f4c-43af78def8ed.png)

![image](https://user-images.githubusercontent.com/42372508/45623160-aca9e700-ba86-11e8-9b73-2103f144920b.png)

There is just one failing condition but i want to see two.

Thanks in advance.

**Comment by Nouxx** [comment]
@vertigo17, is this blocking for the release?

**Comment by vertigo17** [comment]
no
