### ISSUE TITLE
Issue with the global robothost constrain

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1856]
![image](https://user-images.githubusercontent.com/29098010/46131465-f55a6080-c23b-11e8-8783-b37f031956f0.png)

**Context :** 

- All the applications in the screenshot are using Selenium Drivers
- All the Selenium Drivers are on the same hub => 1 robot
- The ROBOTHOST value is 22
- The cerberus_queueexecution_defaultrobothost_threadpoolsize is also set to 22

**Actual Behaviour :** 

- It seems like the max poolsize parameter is determined by the sum of the "contrain2application" defined within the same application : Stores-IHM  (1+6+14 =>21)
- The RobotHost & cerberus_queueexecution_defaultrobothost_threadpoolsize parameter  is not taken into account to set the GLOBAL ROBOT max poolsize parameter
- Some of the contrains2application are not "retreived" on the page
- The poolsize defined  Env / Country / Application  is not respected : 14 instead of 10 for the PIC / PL / Stores-IHM

![image](https://user-images.githubusercontent.com/29098010/46132139-98f84080-c23d-11e8-96b4-add732c970ee.png)

Cerberus Version 3.7.1

**Comment by vertigo17** [comment]
About "contrain2application" no sum are applied to constrain at application level. Constrain2 is at application + environment/country level. 

Issue on cerberus_queueexecution_defaultrobothost_threadpoolsize has been fixed linked with #1855.

I corrected the fact that some contrains2application was not always displayed.
Also fixed an issue when robot host contains double /.
That should fix your issue and provide a better visibility on that page.

Regards the last point, I was not able to reproduce the fact that more execution than constrain2 was released. The only way to do that is to reduce the constrain level after some execution was released. In that case, Cerberus does not stop pending execution but stop releasing more execution until the nb of pending execution reduce to pool size.
