### ISSUE TITLE
Cerberus does not read special characters

### ISSUE THREAD

**Issue by Ryu26** [cerberustesting/cerberus-source#1866]
In the "Data library' we can't add special characters from Polska language, special characters are replaced by "?"

**Comment by R-Loic** [comment]
Hello,

Same issue in properties tab on script page.

**Comment by vertigo17** [comment]
Can you provide:

- 1 example of character that does not work
- The screenshot of what has been entered and the same reopen with ? (I need the exact field that is impacted)

**Comment by Ryu26** [comment]
For example, with the word "Frąckowiak" when you save your testcase, Cerberus replace by "Fr?ckowiak"

![polish01](https://user-images.githubusercontent.com/37080589/49434781-5579ff80-f7b5-11e8-9369-bb82818b2d84.PNG)

![polish02](https://user-images.githubusercontent.com/37080589/49434777-514de200-f7b5-11e8-8812-add75a03955f.PNG)

**Comment by PeillY0u** [comment]
Hello, we have the same issue with Cyrillic, Greek Ukrainian character. For exemple, you can test with this example : ε θ ϖ.

**Comment by Nouxx** [comment]
Hello @PeillY0u, 

I wasn't able to reproduce either on the latest version : Cerberus3.12-SNAPSHOT-1398

![character](https://user-images.githubusercontent.com/30227758/55937788-262f3f80-5c3a-11e9-8364-84811b849376.gif)

Maybe this issue is related to something else?
