### ISSUE TITLE
Application Object: application select

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1869]
Hello,

Currently, each time you want to select an application for a new Application Object, its display all the application and select always the first one (depending on the sorting score).

![image](https://user-images.githubusercontent.com/30227758/46466217-f73b9b00-c7ca-11e8-8bad-e9a5150e9a8f.png)

When creating a lot of Application Object in a row, it can be very painful to re-select the application. Bonus: it can't be modified after created.

My suggestion would be:
- replace the application select by select2
- put in the first result the application depending on the selected System (exactly the same than Test Case Header modal)

**Comment by Galand-V** [comment]
Or maybe create a duplicate button could be an easy solution too.
