### ISSUE TITLE
Internal server error on demo environment

### ISSUE THREAD

**Issue by evanemh** [cerberustesting/cerberus-source#1873]
Cerberus Version : 3.8-SNAPSHOT-1384

Internal server error message when accesing http://vm.cerberus-testing.org:28080/CerberusDEMO/TestCaseList.jsp

![image](https://user-images.githubusercontent.com/42602505/46808432-9ed94000-cd6c-11e8-9966-2735035a9124.png)

**Comment by vertigo17** [comment]
fixed. Database maintenance was not triggered.
I will deploy demo to latest 3.8 release and secure it does not happen.
