### ISSUE TITLE
Demo tests removed

### ISSUE THREAD

**Issue by evanemh** [cerberustesting/cerberus-source#1878]
Hello,

I created some tests (Test Adventiel), a label (ADV) and a campaign in the demo environment yesterday but I cannot find them anymore today...
Are they deleted every night? Is there a way to get them back and keep them for my demo next week?
Thanks.

**Comment by vertigo17** [comment]
Yes demo env is rebuilt every night. This is because it could be broken easilly from anyone who wants to play with the tool. 
Please get in touch via email in order to see what is the need behind and potencially open you an access to our production environment on prod.cerberus-testing.org

**Comment by evanemh** [comment]
OK, I understand. Would be nice to mention it on the demo environment though ! :)
I contact you by email at the same time for production access.
Regards,

**Comment by vertigo17** [comment]
I guess this is you who updated the message.
As all other data the new message will be reset during the night.
As a consequence, I restored, re-updated the message and performed a new snapshot in order to secure the new message is kept over time.
