### ISSUE TITLE
Add a poolsize constraint to application

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1880]
Hello,

I'd like to have a constraint at an application level, that will have more authority than the ones in ENV - COUNTRY.

Thanks

**Comment by Nouxx** [comment]
Actually, a constraint at an ENV level would also work

**Comment by vertigo17** [comment]
It already exist.
Is that issue stil relevant ?

**Comment by Nouxx** [comment]
I have to try if this poolsize:
<img width="658" alt="Screenshot 2019-04-28 at 21 56 20" src="https://user-images.githubusercontent.com/30227758/56869401-80811c00-6a00-11e9-8d11-25aee6d60e5a.png">

have an higher authority than these one:
<img width="906" alt="Screenshot 2019-04-28 at 21 59 24" src="https://user-images.githubusercontent.com/30227758/56869430-eec5de80-6a00-11e9-9cfa-f4c63b808666.png">
