### ISSUE TITLE
test API

### ISSUE THREAD

**Issue by liquidparker** [cerberustesting/cerberus-source#1882]
Cerberus Version : 3.4-1335

Hello, i want some help for test api, where we can config link and post/rest?

**Comment by R-Loic** [comment]
Hello @liquidparker ,
You can refer to the implementation on cerberus demo : 
http://vm.cerberus-testing.org:28080/CerberusDEMO/TestCaseScript.jsp?test=Examples&testcase=2000A
login :  cerberus/cerberus
For API test, you have to create a service library with your api info and then create a test case with callservice action.

**Comment by liquidparker** [comment]
Thx it help me, i post another issue/request for api
