### ISSUE TITLE
Firefox does not autoscroll to an element out of the screen

### ISSUE THREAD

**Issue by qlevert** [cerberustesting/cerberus-source#1890]
Hello,

I tried to launch a test campaign on the lastest Firefox version and Selenium.
Result : He does not scroll to an xpath out of the screen. Mouseover does not work.

I tried to downgrade Selenium(v.3.9) and Firefox(v.58) but I have the same result.  
Thanks,

**Comment by vertigo17** [comment]
Not sure to understand the issue as for me the ScrollTo Action is not implemented on Selenium Robots.
Can you provide a screeshot of the detailed execution with error reported ?
Is that ScrollTo Cerberus action or mouseOver or both ?

**Comment by qlevert** [comment]
When I launch a test on chrome, this is the result : 
![image](https://user-images.githubusercontent.com/44800518/48191365-2fdc1080-e345-11e8-8583-9659915c581d.png)

When I lauch the same test on firefox : 
![image](https://user-images.githubusercontent.com/44800518/48191436-5e59eb80-e345-11e8-8548-e37c5d2b6f7a.png)

I made some tries and firefox can't see xpath outside of the screen. In chrome, the action "ScrollTo" is automatic.
Then I tried mouseOver action in my firefox test and I can only use mouseOver in a element displayed on the screen not outside. And the action ScrollTo  is not supported for application type 'GUI'.

**Comment by huong-vuong** [comment]
I have the same error. I'm trying to click on a button which is not displayed on the screen. When I execute the test with chrome the step "click" was marked OK but nothing happens. 
![image](https://user-images.githubusercontent.com/15927754/48287942-d837c500-e46a-11e8-962a-79d3786ac889.png)

When I execute the test with Firefox, Cerberus doesn't find out the button.
![image](https://user-images.githubusercontent.com/15927754/48287964-e84fa480-e46a-11e8-966f-ebee399b05d9.png)

**Comment by vertigo17** [comment]
Sharing a bit the result of my tests so far.
I was able to replicate the issue on
firefox 56, 57 and 58 --> FA
firefox 59, 60, 61 and 62 --> OK

Thanks to browserStack, I will continue the test on all Firefox Version in order to check all of them.
If possible I will try to modify the waitForElement used on all element integration in order to support all browsers.

**Comment by huong-vuong** [comment]
@vertigo17  Thanks for your answer. With Chrome I have always the problem. I used so JS to scroll my mouse. It's worked !
@qlevert in waiting, you can add a script JS for srolling your mouse. It's worked for me :D

**Comment by vertigo17** [comment]
@huong-vuong , can you precise the version of firefox that have the issue and detail definition of the action that fail (I guess mouseOver action but with what parameter).
Idealy, a site on Internet where we can share and reproduce the issue would be even better.

**Comment by huong-vuong** [comment]
@vertigo17  I used firefox version 60.3.0
![image](https://user-images.githubusercontent.com/15927754/50907085-d072ad80-1426-11e9-97de-e51524cfe04b.png)
