### ISSUE TITLE
[BUG] Edit service on a datalibrary isn't working

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1893]
Cerberus Version : 3.8-1384

**Steps :**
- Go on a Datalibray linked to a service
- Try to edit the service

**Current result :**
Nothing happens

**Expected result :**
The service page is displayed

**Comment by vertigo17** [comment]
No longuer able to reproduce.
Can you still reproduce on latest version ?

**Comment by glassalle59** [comment]
It’s work on the last version. Thanks
