### ISSUE TITLE
[BUG][Cerberus3.8][Mobile] Parralelization, ko with control "verifyTextInElement" 

### ISSUE THREAD

**Issue by Ryu26** [cerberustesting/cerberus-source#1894]
With the parallelization with 2 robot (2 android), testcase failed on campaign when you use the control type "verifyTextInelement"

Error message : "The test case failed to be executed. More lickely due to an error in the test or in Cerberus configuration. null Exception: java.lang.NullPointerException"

![para01](https://user-images.githubusercontent.com/37080589/48133958-c43c6980-e298-11e8-846a-1a13b4b6773b.PNG)
![para02](https://user-images.githubusercontent.com/37080589/48133964-c69ec380-e298-11e8-9a75-bf521acb59cd.PNG)

**Comment by vertigo17** [comment]
Can you provide the corresponding Glassfish logs ?
