### ISSUE TITLE
Database Maintenance Exception raised when connecting to the database...

### ISSUE THREAD

**Issue by ludwigggg** [cerberustesting/cerberus-source#1898]
I have installed cerberus in Docker Version (last version 3.9)
Glassfish server is OK and also access in admin console.

On the other hand, the front-web cerberus displays an ERROR
"Database Maintenance Exception raised when connecting to the database ..." ( cf screenshot)
with URL :  url:18080/Cerberus/
                  url:18080/Domain1/ displays a 404 error.

I can't initialiase database.

Java has beeen DOWNGRADED before deploying the Docker  Image
openjdk version "1.8.0_161"

and Mysql version is 5.6.30

NOTA : The JAR FILES : 
mysql-connector-java-5.1.47-bin.jar  and mysql-connector-java-5.1.47.jar

have also been copied to this directories
/glassfish5/glassfish/lib
/glassfish5/glassfish/bin
/glassfish5//bin

and glassfish has been restarted. but nothing changes.
The JDBC connector seems not to be taken into account.

What can i do about this blocking ISSUE ?
Any Ideas ?

![cerberus-database-maintenance](https://user-images.githubusercontent.com/45165343/48698768-35104980-ebe8-11e8-9cb9-10409d83066f.jpg)

**Comment by vertigo17** [comment]
That error means that Cerberus does not manage to connect to the database.
Can you check that database is started on the correct host/port ?
Once you are sure that database is running OK (for example using the mysql workbench tool) restart the glassfish container.
Also check the parameters of yml file:
- DATABASE_HOST=cerberus-db-mysql
- DATABASE_PORT=13306
Replace cerberus-db-mysql by the IP of the mysql server (DO NOT put localhost or 127.0.0.1)

**Comment by ludwigggg** [comment]
vertigo17 > tanks for your answer

docker containers and images have been destroyed, IP ADDRESS has been modified
in default.yml

DATABASE_HOST= IP address

and deployment has been made again with docker-compose
 docker-compose -f default.yml up
Nothing changes, same error appears in web front 

LOGS EXTRACT >>

cerberus-as-glassfish_1_85519b9204e2 |   2018-11-20 16:05:01 WARN  DatabaseSpring:70 - Cannot connect to datasource jdbc/cerberusprd : java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: Communications link failure
cerberus-as-glassfish_1_85519b9204e2 | 
cerberus-as-glassfish_1_85519b9204e2 | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

Mysql is well running in a docker container:

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.6.30 MySQL Community Server (GPL)
...

root@c64163f1fae0:/# service mysql start
[info] A MySQL Server is already started.

mysql> 
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| cerberus           |
| mysql              |
| performance_schema |
+--------------------+
4 rows in set (0.01 sec)


No firewall is activated on this testing VM.

Anything else to verify ?

Best Regards,

**Comment by ludwigggg** [comment]
in docker PS : we can see expose ports are OK 👍 
[root@cerberus bin]# docker ps
CONTAINER ID        IMAGE                                          COMMAND             CREATED             STATUS              PORTS                                                        NAMES
f0adb5cce1a9        cerberustesting/cerberus-as-glassfish:latest   "/entrypoint.sh"    10 minutes ago      Up 10 minutes       8181/tcp, 0.0.0.0:14848->4848/tcp, 0.0.0.0:18080->8080/tcp   bin_cerberus-as-glassfish_1_85519b9204e2
a7d8895cd0d2        cerberustesting/cerberus-db-mysql:latest       "/bootstrap.sh"     10 minutes ago      Up 10 minutes       13306/tcp, 0.0.0.0:13306->3306/tcp                           bin_cerberus-db-mysql_1_da9d62dd31f8
81702f20a13a        portainer/portainer                            "/portainer"        3 hours ago         Up 3 hours          0.0.0.0:9000->9000/tcp                                       blissful_colden
[root@cerberus bin]#


Is there anything to change in the my.cnf inside the docker-mysql  ?


Best regards,

**Comment by ludwigggg** [comment]
Laways the same error in log Glassfish :

[2018-11-22T15:55:37.767+0100] [glassfish 5.0] [INFO] [] [] [tid: _ThreadID=26 _ThreadName=Thread-8] [timeMillis: 1542898537767] [levelValue: 800] [[
  2018-11-22 15:55:37 WARN  DatabaseSpring:70 - Cannot connect to datasource jdbc/cerberusprd : java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
]]

**Comment by ludwigggg** [comment]
SOLVED !

The file domain.xml
/glassfish5/glassfish/domains/cerberus/config/domain.xml
 issued from the docker image, was specifying "toto" as password for the cerberus database instead of "cerberus"
