### ISSUE TITLE
Keypress SEARCH doesn't work on Browserstack

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1901]
Hello,

The Keypress search doesn't work using browserstack devices... For our local devices we managed to work around this issue installing one application named GO Keyboard but for browserstack that is not possible,

Best Regards

Cerberus Version : 3.9-1388

**Comment by j0hnsa** [comment]
Hello @vertigo17,

TC implemented:
http://vm.cerberus-testing.org:28082/CerberusPROD/TestCaseExecution.jsp?executionId=93289

Best Regards

**Comment by akatmiranda** [comment]
Hi!

Is this issue a priority? 
This has high impact on campaigns since sometimes it works and sometimes it doesn't increasing campaign execution time.

BR

**Comment by lucashimpens** [comment]
Seen with La Redoute. We can close.
