### ISSUE TITLE
[VISUAL][MINOR] img from application object in test case too big

### ISSUE THREAD

**Issue by jsbaguette** [cerberustesting/cerberus-source#1906]
hello i am facing some visual bugs

when you resize window in test case if you application object has an image, the image can be really big.

maybe add a max width on it

![capture d ecran de 2018-11-27 12-17-12](https://user-images.githubusercontent.com/11556276/49078530-8f3f8900-f23e-11e8-899e-375034c7dac6.png)

**Comment by f3ltron** [comment]
i check a bit the col-lg-1 should be the probleme because when less than lg it take col-md-12 etc so a bit too big

**Comment by vertigo17** [comment]
Fixed on 4.14
