### ISSUE TITLE
Session deleted because of page crash

### ISSUE THREAD

**Issue by SeniorCanard** [cerberustesting/cerberus-source#1908]
Hello,

Since latest Cerberus versions, some Tests Cases displays the same error every time when opening specific url.

The error log is: "The test case is cancelled due to lost connection to Selenium Server! Detailed error: unknown error: session deleted because of page crash"

Characteristics:
- Always the same tests cases
- The error happens on 100% of the time
- Only in DEV and QA environments. 
- Chrome browser

**Comment by nicodeur** [comment]
Hello,

Can you give us more detail (on wich testcase step Selenium is cancelled) ?

**Comment by f3ltron** [comment]
It is impossible having log when lost connection. It doesn't publish expose log in this case
