### ISSUE TITLE
[SECURITY ?][APPLICATION OBJECT]

### ISSUE THREAD

**Issue by f3ltron** [cerberustesting/cerberus-source#1909]
I think the  is interpreted JS  in the name of the application object ?

<img width="1383" alt="capture d ecran 2018-12-07 a 10 57 25" src="https://user-images.githubusercontent.com/11556276/49640988-3d9db800-fa0f-11e8-8332-d633977c512d.png">

If yes it's a huge security issue here

**Comment by vertigo17** [comment]
I guess you made a mistake on the name of your application object. Avoid using special characters in object names as the behaiour can always be a bit weird.
Not sure to understand the huge security risk. All data access are controled by access right on server side. The only risk on putting strange names are to break the GUI (like in your example) that will not allow you more data access that you already have neither corrupt data that you are not supposed to see.

**Comment by f3ltron** [comment]
I thought the same but just a warning to be sure 👍

**Comment by f3ltron** [comment]
It's actually just break the js you can't delete it with the gui or edit it

**Comment by vertigo17** [comment]
I would suggest to clean it directly inside the database.

**Comment by f3ltron** [comment]
that's what we did. But it's a little bug we should delete it with the gui
