### ISSUE TITLE
Appium lock/unlock device

### ISSUE THREAD

**Issue by aureliendelrue** [cerberustesting/cerberus-source#1911]
Hi,

Is it possible to support [_lockDevice()_](http://appium.io/docs/en/commands/device/interactions/lock/) (before the test) and [_unlockDevice()_](http://appium.io/docs/en/commands/device/interactions/unlock/) (after test finished) commands ?

Thanks

**Comment by nicodeur** [comment]
Hi,

Is not  unlockDevice() (before the test) and lockDevice() (after test finished) ?

Do you test on iOS or on Appium device ?

**Comment by aureliendelrue** [comment]
Hi,

Oops, you're right : unlock before the test and lock after the test. I'm testing on iOS and Android devices.

Thanks

**Comment by nicodeur** [comment]
Why you don't use the unlock phone option (`stay awake`) on develop settings menu ?

![image](https://user-images.githubusercontent.com/6707556/50273597-607e9200-043b-11e9-9307-866d28ab6dcd.png)

**Comment by aureliendelrue** [comment]
@nicodeur we could use this feature but we want to lock the phone when it not in use.

**Comment by aureliendelrue** [comment]
@vertigo17 it would be great !
