### ISSUE TITLE
No build revision available to EnableEnvironment

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#1913]
This is critical and urgent.
We are not able to perform environment activation and not even deploys from Cerberus.
We are not able to "Enable Environment with new Build Revision", as the drop-down box is not showing any values.
No error messages on the logs.
Below "New Build", nothing is shown.
![image](https://user-images.githubusercontent.com/5640464/50214575-8f7fff80-0378-11e9-81ef-779c2d9ac475.png)

**Comment by Nouxx** [comment]
Regression test implemented as well : "As an admin user, I can enable a environment with new build revision"
