### ISSUE TITLE
Can not run test case using custom configuration on robot settings

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1914]
On this new version of Cerberus (**v3.10-1394**) is is not possible to run or re-run a test case using custom configuration on the robot settings.
We get the information that no execution is inserted to the queue:
![image](https://user-images.githubusercontent.com/17747042/50219801-37e99000-0388-11e9-960b-3dbbe9c42328.png)
If we select a robot (configured on the robot list), the test case is added to the queue and executed successfully.
Can you please check?
Thanks.

**Comment by vertigo17** [comment]
Should be fixed but worth testing.

**Comment by Nouxx** [comment]
The regression test case is still a work in progress, it should be up and running soon
