### ISSUE TITLE
Robothost constrain not working properly

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1915]
Hi,

On robothost I've defined the maximmum request for each robot I have and it seems that this is not working as expected:

![image](https://user-images.githubusercontent.com/16339891/50223583-8bada680-0393-11e9-81b8-fcc916c0486b.png)

I should have only 3 execs on iPhone 2 on Tablet and 3 on smartphone, and I have 18 execs pending:
![image](https://user-images.githubusercontent.com/16339891/50223649-bdbf0880-0393-11e9-962a-99e210a1bb07.png)

Can you check?

Cerberus Version : 3.10-1394

**Comment by vertigo17** [comment]
From the queue management screen, looks like the 18 executions correspond to executions that are sent to the selenium infra. Can you confirm that inside the tag you don't have any selenium execution ? Maybe a second campaign has been triggered on the same tag ?
It also seems that the constrains are respected (none are above 100%). 
Anyway, I made a fix that secure that only 1 instance of queue job runs at the same time. If job are triggered at the exact same time, that could duplicate the executions on very rare occasion.
Please test the fix and reopen if issue is still there.
