### ISSUE TITLE
DATABASE MAINTENANCE on demo environment

### ISSUE THREAD

**Issue by evanemh** [cerberustesting/cerberus-source#1918]
Demo environment is not working due to DATABASE MAINTENANCE.

Error message : 
Database is empty. A first version needs to be initialised. Please click on Initialize Database button bellow in order to initialize it. If already done, please click on Apply Next SQL button until all SQLs has been executed.
Anytime you will deploy a new version of Cerberus, you will have to come back to this page (Menu : Admin / Database Maintenance) and execute the missing SQL in order to upgrade the database.

**Comment by vertigo17** [comment]
Fixed by adding those 2 parameters on resource definition on tomcat configuration.

                validationQuery="select 1"
                testOnBorrow="true"
