### ISSUE TITLE
VerifyElementNotVisible and VerifyElementVisible not working correctly

### ISSUE THREAD

**Issue by cDelage** [cerberustesting/cerberus-source#1920]
When i do a control verifyElementNotVisible on a element present but not visible on the screen, the control status is KO because element is visible, 
And verifyElementVisible status is ok on the element non-visible.

**Comment by f3ltron** [comment]
The element is present and where is he in the viewport when he is not visible ?

**Comment by cDelage** [comment]
yes but i speak about it with @vertigo17 and the visible element is all element can be visible in page and not in viewport.

**Comment by f3ltron** [comment]
nop the element visible should stop in viewport. If you want something like present in all page. It is present not visible. Definition by name
