### ISSUE TITLE
Not succeed to install cerberus

### ISSUE THREAD

**Issue by MToussaint61** [cerberustesting/cerberus-source#1923]
Hello,

I'm currently trying to install cerberus in a windows 10 Home ( 64 bits ) with docker toolbox but i'm facing a problem.
So basicly the docker toolbox's installation worked fine.
After that i executed those commands : 
- docker pull cerberustesting/cerberus-as-glassfish 
- docker run --name <ConteneurName> cerberustesting/cerberus-as-glassfish 
but this last one failed and give me this result
![capture](https://user-images.githubusercontent.com/24276816/50893009-2b44de80-1400-11e9-9748-ecd8afee537b.PNG)
 
So do you have any idea to help me plz ?
Thanks =)

**Comment by nicodeur** [comment]
Hello,

Do you have run the database ?

Thanks to use this doc for docker-compose : https://github.com/cerberustesting/cerberus-source/tree/master/docker/compositions/cerberus-glassfish-mysql

or this one with only docker : https://github.com/cerberustesting/cerberus-source/tree/master/docker/images
(you have to run `cerberus/cerberus-db-mysql` and `cerberus/cerberus-as-glassfish`)

cerberus/cerberus-db-mysql
--




cerberus/cerberus-db-mysql
--




cerberus/cerberus-db-mysql
--




cerberus/cerberus-db-mysql
--




cerberus/cerberus-db-mysql
--
