### ISSUE TITLE
Migration test cases

### ISSUE THREAD

**Issue by huong-vuong** [cerberustesting/cerberus-source#1925]
Hello,
Some one have migrated the test cases from one to other machine ?

I used cerberus in windows, now I want to migrate to a machine linux. 
How can I migrate all my test cases ? I don't want to recreate all the test cases I wrote.

Thank you.

**Comment by vertigo17** [comment]
As long as the Linux version of Cerberus is equal or greater than the Windows version, you can just dump and restore the database from one server to another.
Optionaly, you can also copy all the media files from 1 server to another.

Dump on Windows:

mysqldump -u $MYSQLUSER cerberusdatabase > $DUMPFILE

Restore on linux:

mysql --user=$MYSQLUSER --password=$MYSQLPASS --show-warnings cerberusdatabase < $DUMPFILE

NOTE:
Import / Export a list of testcases is not yet available but is in roadmap.
Don't forget to update parameter *_url and *_path after the dump on the new server.
