### ISSUE TITLE
White screenshot

### ISSUE THREAD

**Issue by kileek** [cerberustesting/cerberus-source#1938]
Hello all,

I have a problem when i'm trying to execute some librairies to see if my script is fully functionnal.
I'm not supposed to have a white screen as a screenshot and this happened at random moment :/

See the screenshot to see the problem

![autrebug](https://user-images.githubusercontent.com/14565233/52402197-ef1aa180-2ac3-11e9-9444-55837e7dd1cb.PNG)

I have and "old" version of cerberus :

![version cerberus](https://user-images.githubusercontent.com/14565233/52402217-035e9e80-2ac4-11e9-88c3-966ebf728c2c.PNG)

![databasecerberusversio](https://user-images.githubusercontent.com/14565233/52402564-e24a7d80-2ac4-11e9-8510-e1a79bcb5306.PNG)

![capture](https://user-images.githubusercontent.com/14565233/52402587-ec6c7c00-2ac4-11e9-9719-93ad4ea96041.PNG)

I execute my test with chrome and through a VPN.

I don't know if someone has already had this problem or if someone can help me ?

Thanks you

**Comment by nicodeur** [comment]
Hello,

You can not update your cerberus version ? effectively, 3.3 is an very old.

I remember already see it by the past, but nor recently. If I good remember, refresh the page resolved the problem. Is it ?

**Comment by kileek** [comment]
I don't think to just refresh the page i'll give a shot =) it bothering me because now i can't tell it happens when i made this or this things , it just happened time to time.

I already ask for and upgrade but the admin don't have time to do that but thanks for the advice =).

**Comment by vertigo17** [comment]
Does that happen all the time ?
Do you have access to Selenium infra in order to test that the page loads from it.
From your screenshot it looks like it is not only the screenshot the does not load but page could be really empty as both controls fails.

**Comment by kileek** [comment]
Non , it just happened regulary (several times a day), and i don't have any access to the back of the cerberus server.
