### ISSUE TITLE
Rename an ApplicationObject

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1944]
Hello, 

Can you remove the constraints on the Application / Object from the applicationobject table as there is a unique ID available ?

Thank you !

**Comment by vertigo17** [comment]
If we allow multiple values for application-object, how will the engine will select the correct one ?
Beeing unique secure that there is no confusion.

**Comment by Galand-V** [comment]
Maybe I was not clear, the aim of this issue is to have the possibility to rename the name of the applicationObject

![image](https://user-images.githubusercontent.com/29098010/73257571-4c6f9d00-41c4-11ea-9219-5fa95e14092f.png)

Having multiple values for an application object could be nice to identify the paths of an entire componant / page  / function.  Maybe it could be a different type of dataLib instead of an entire different section as it is currently.
