### ISSUE TITLE
[IDEA] - Add different bug ID depending on the ENV / ROBOT / COUNTRY

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1946]
Currently, a Bug ID can be linked to a test case (one to one)

If we launch the campaign on several countries / env or robots, the bug will still be attached to all the executions. What do you think about implementing a way to have different bug ID for the same testcase.

If there's a need, we could start discussing on it !

**Comment by ruirpr** [comment]
Agree. Currently we write the country in the bugs comments.

**Comment by vertigo17** [comment]
![image](https://user-images.githubusercontent.com/5342048/72685813-fc227c00-3aed-11ea-8194-40754f70a222.png)

Every bug link can now be desactivated and date of creation and date of closure is saved.

An optional control were also added on empty description thanks to parameter : 'cerberus_testcasepage_controlemptybugdescription'

**Comment by vertigo17** [comment]
I close this issue as multiple bug is now a available.
