### ISSUE TITLE
Automatic queue cancellation

### ISSUE THREAD

**Issue by mbessa** [cerberustesting/cerberus-source#1947]
Hello,

Looks like auto queue cancellation isn't working properly or we may need help configure it properly.
Here's an example of a test that should be cleaned by automatic_queue_cancellation, currently its "STARTING" for over 17h:
![image](https://user-images.githubusercontent.com/5825695/53655080-328da900-3c47-11e9-9e13-b7cc18b9f1e0.png)

This results in unwanted queue occupation. From time to time we have to clean these executions from the queue manually, otherwise it will run out of free slots to execute tests in that hub.
This is just an example, it's not that frequent.

As for configuration, we have it set up like this:
![image](https://user-images.githubusercontent.com/5825695/53655323-c1022a80-3c47-11e9-9628-b2a5497f8adf.png)

Please let me know if you need more informations.
Thank you in advance

Cerberus Version : 3.11-1397

**Comment by vertigo17** [comment]
Can you provide the logs INFO entries of class TestCaseExecutionQueueDAO.
It should confirm if the job triggered or not.
Can you also put the output of the SQL:
SELECT TO_SECONDS(NOW()) - TO_SECONDS(DateCreated), a.* FROM cerberus.testcaseexecutionqueue a 
where TO_SECONDS(NOW()) - TO_SECONDS(DateCreated) > 3600
and state IN ('WAITING','STARTING','EXECUTING');

Thanks.

**Comment by mbessa** [comment]
LOGS:
_2019-03-04 19:35:22 INFO  TestCaseExecutionQueueDAO:2116 - No 'old' queue entries to force CANCELLED. (timeout = 3600).|#]
  2019-03-04 19:36:03 INFO  TestCaseExecutionQueueDAO:2116 - No 'old' queue entries to force CANCELLED. (timeout = 3600).|#]
  2019-03-04 19:36:46 INFO  TestCaseExecutionQueueDAO:2116 - No 'old' queue entries to force CANCELLED. (timeout = 3600).|#]
  2019-03-04 17:37:28 INFO  TestCaseExecutionQueueDAO:2116 - No 'old' queue entries to force CANCELLED. (timeout = 3600).|#]
  2019-03-04 18:37:28 INFO  TestCaseExecutionQueueDAO:2116 - No 'old' queue entries to force CANCELLED. (timeout = 3600).|#]
  2019-03-04 19:37:28 INFO  TestCaseExecutionQueueDAO:2116 - No 'old' queue entries to force CANCELLED. (timeout = 3600).|#]_


SQL output:
_TO_SECONDS(NOW()) - TO_SECONDS(DateCreated), ID, System, Test, TestCase, Country, Environment, Robot, RobotDecli, RobotIP, RobotPort, Browser, BrowserVersion, Platform, ScreenSize, ManualURL, ManualHost, ManualContextRoot, ManualLoginRelativeURL, ManualEnvData, Tag, Screenshot, Verbose, Timeout, PageSource, SeleniumLog, manualexecution, retries, RequestDate, State, Priority, comment, DebugFlag, SelectedRobotHost, ExeID, UsrCreated, DateCreated, UsrModif, DateModif
'328951', '17208153', 'THESEUS', 'PerfMon', '6001A', 'PT', 'PROD', 'Perfmon_CHROME', 'Perfmon', '', '', '', NULL, NULL, NULL, '0', NULL, NULL, NULL, NULL, 'WebMonitoring_20190228', '1', '1', '150000', '1', '1', '', '0', '2019-03-01 00:25:01', 'STARTING', '10', '', 'N', '192.168.134.155', NULL, '', '2019-03-01 00:25:01', '', '2019-03-01 00:25:01'_

Any clue?

Thanks :)

**Comment by mbessa** [comment]
Hello,

I did a quick search and found several warning logs with the messages similar to this and with different queue id's :
_2019-03-01 00:25:01 WARN  TestCaseExecutionQueueDAO:1846 - Unable to move state from STARTING to EXECUTING for execution in queue 17208153_

:)

**Comment by vertigo17** [comment]
Thanks Marco,
The WARN confirm that Cerberus failed to move the state to EXECUTING and explain why the state stayed in STARTING. The question behind is why it failed to do so.
Anyway the SQL I have provided is slightly differrent from the on used so far. I will replace it so that it better works. The one used so far is using JAVA to get the now() value that is introducing a risk and not very consistent as all timestamps are retreived from database. The purge SQL as a consequence should also be taken from the database.
