### ISSUE TITLE
"&" in Test field

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1948]
Hello,

Naming a Test with an "&" is causing problem afterward to edit the test and corresponding testcases.

![image](https://user-images.githubusercontent.com/30227758/53965499-a4576e00-40f1-11e9-9e38-f3afa75b6619.png)

JS Console returns : `Uncaught TypeError: Cannot read property 'test' of undefined`

The problem might come from the query string we're passing to the API, shouldn't we make the GUI avoid this symbol?

Thanks

**Comment by Nouxx** [comment]
We're not having the issue with the Testcase ID field since it gets 500 Error 

![image](https://user-images.githubusercontent.com/30227758/54377901-696fb000-4686-11e9-992e-9e4d204daa57.png)

After refreshing the page, **the testcase is created** but the user will not be able to edit it

**Comment by Nouxx** [comment]
- [ ] Apply the control for TestCaseID Field

**Comment by cDelage** [comment]
the issue is protected by this test case : 
GUI : Test Management  -> 0060A 
GUI : Test Management  -> 0061A
