### ISSUE TITLE
Double Click & Save on TestCase

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1949]
Hello, 

I was editing a testcase and doubleclicked on the button 'save'. The loading was not finished at the second click (properties were not loaded). It considered that property section was empty and erase all my datas. 

Is that possible to add a safety in case all datas are not loaded ? 

thank you !

**Comment by vertigo17** [comment]
Strange as double click is already protected. I was not able to reproduce.
Can you confirm it is on TestCaseScript page ?

**Comment by Galand-V** [comment]
Hello, 

Sorry for the delay. It was not a double click I guess but the behaviour is close from it. 

![issue Cerberus save](https://user-images.githubusercontent.com/29098010/62049934-95906580-b210-11e9-9f20-59e6e6424219.gif)

**Comment by Galand-V** [comment]
Hello @MorganLmd, I have tried to reproduce the error after your development and it seems like I have an issue when saving a property on the qa environment. 


![issue saving prop](https://user-images.githubusercontent.com/29098010/65703969-f825a680-e085-11e9-9f3a-31022408d10a.gif)
