### ISSUE TITLE
CerberusDEMO  unexpected error occurred

### ISSUE THREAD

**Issue by dataSyman** [cerberustesting/cerberus-source#1950]
Cerberus Version : 3.11

Oops...
Sorry but an unexpected error occurred.

Error Code : null
/CerberusDEMO

You can try to :
Logout
Back to homepage 

Page started generating on Tue Mar 12 04:29:01 CET 2019 by Cerberus 3.11 in demo and took 78471147ms - Open a bug or ask for any new feature here.

**Comment by vertigo17** [comment]
I cannot reproduce:
1/ connected to demo.cerberus-testing.org 
2/ login with cerberus
3/ Homepage is displayed OK
4/ logout
back to 2/ using admin user and got no issue.

I guess you try to connect using an old URL that uses a context root of /CerberusDEMO.
Can you secure that you don't bookmark an old URL that have vm.cerberus-testing.org/CerberusDEMO/...
and also purge your local cache and cookies on Cerberus domain and retry.
URL should be demo.cerberus-testing.org
