### ISSUE TITLE
[GUI] Application configuration by environment missing characters

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#1951]
Cerberus Version : 3.11-1397

While the database is allowing the use of 150 characters for the IP, domain, URL, URLLogin and others, by application/environment, the graphical interface is not allowing more than 35 characters.
We have some situations where we really need to use more than 35 characters.

We can update directly on the database, but if any manipulation is done on the GUI, we will loose it.

**Comment by Nouxx** [comment]
Hi!
If you're talking about this page (Application)
![image](https://user-images.githubusercontent.com/30227758/54280437-c9d3f400-4597-11e9-96ca-11632ee5b014.png)

I was able to type and save a 150 character long string on the 4 fields
However, I'm running Cerberus3.12-SNAPSHOT-1397

Am I missing something?

**Comment by gmoita** [comment]
In fact, it is ok now, so the information might have been entered on the application earlier than the latest deploy.
You can close the issue, as we are now able to insert more than 35 characters.
