### ISSUE TITLE
cerberus docker installation

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1952]
Hi, 
followed the https://cerberustesting.github.io/documentation_en.html#_cerberus_installation instructions to intall cerberus locally and fired up the whole thing with 

docker-compose -f default-with-selenium.yml up

After some time cerebrus was up and running, added a country, environment, test and testcase. Did not ran any testcase. 
When opening local GF in https://192.168.99.100:14848/Glassfish my browser frooze and cerberus was very slow. Out of nowhere the db was empty and cerebrus asking for new "initialize database". 
It's not the first time something like this happens, right after some freezing. It seems to be in loop, starting and shutdown mysql,
Could it be possible i do not have enough memory in my pc? And why the db reset? Thanks

![imagem](https://user-images.githubusercontent.com/1914659/54365418-b2b00780-4666-11e9-960c-125d48b6856b.png)
![imagem](https://user-images.githubusercontent.com/1914659/54365423-b5126180-4666-11e9-9f20-16693ab1487d.png)
![imagem](https://user-images.githubusercontent.com/1914659/54365807-7630db80-4667-11e9-9dea-a7e76f5dc881.png)

by the way, what's the default db and gf passwords?

**Comment by ruirpr** [comment]
After all, my modifications are still in the db. After closing browsers and get some memory back, cerberus is running locally again.

**Comment by ruirpr** [comment]
But then this happens 
![imagem](https://user-images.githubusercontent.com/1914659/54367991-3cfa6a80-466b-11e9-9afe-d78c0115448e.png)

and cerebrus is gone again

![imagem](https://user-images.githubusercontent.com/1914659/54368021-497ec300-466b-11e9-99f1-cacc96fc21aa.png)

**Comment by Nouxx** [comment]
Hello @ruirpr 

Do you have the full logs of the docker-compose up? I sometimes have container sucessfully launched and then exited due to errors catched later..

Regarding the default credentials for glassfish, I believe the password is empty (see. https://github.com/cerberustesting/cerberus-source/tree/master/source > readme.md)

**Comment by vertigo17** [comment]
Could you retry with 4.0 and Tomcat docker compose.
I guess it will use less memory and potential should be more stable ?
