### ISSUE TITLE
Data lib and GDPR

### ISSUE THREAD

**Issue by mflorid** [cerberustesting/cerberus-source#1957]
For now when we want to test some applicativ behavior which need us to log in we add the login iformations in data lib.

But it's obviously not GDPR compliant :)

So what i propose is to add a feature which will allow us to hide the password of our data.
What do you think about that ?

**Comment by Nouxx** [comment]
Hello,

I'm thinking about a checkbox avaible for any subdata to check if it's a password. If it is, the content will be hidden the password way

**Comment by Nouxx** [comment]
Hello! 

The encrypt checkbox has been implemented recently and it look like this : 
![image](https://user-images.githubusercontent.com/30227758/64021274-d9d69480-cb33-11e9-85cf-073ef89212e5.png)

Should we close the issue ?

**Comment by mflorid** [comment]
Does this checkbox is only available for admin ?
