### ISSUE TITLE
Validation image selon un certain pourcentage

### ISSUE THREAD

**Issue by CCornille** [cerberustesting/cerberus-source#1958]
Cerberus Version : 3.7.1-1359

Nous aurions besoin de pouvoir faire reconnaître par Cerberus une image avec un pourcentage d'exactitude variable ( 90% par exemple ) pour tester une application lourde.
En effet nous avons parfois des problèmes de netteté ou de couleurs plus pâles.

En vous remerciant.

**Comment by Nouxx** [comment]
Hello,

Qu'entendez-vous par netteté? Parles-t'on bien de la différence entre la résolution du robot et celle de l'image envoyée à Sikuli? Même question pour les couleurs

De mémoire, il y a un paramètre dans Sikuli qui gère ça. Soit on privilégie la rapidité d'exécution et donc la reconnaissance d'image est moins exigeante, soit l'inverse. je n'ai plus le nom en tête mais c'était quelque chose de la sorte: https://answers.launchpad.net/sikuli/+question/242036

Pour en avoir fait l'expérience, Cerberus ne fait pas ces appels avec le paramètre "reconnaissance exacte".

Quoiqu'il en soit, Il ne me semblerai pas incohérent de rendre ce paramètre accessible depuis la GUI de Cerberus (je pense à un paramètre)

**Comment by Showiengum** [comment]
Bonjour,

Est-il possible d'avoir un exemple d'utilisation du paramètre de similarité ?

D'autres fonctionnalités propres à SIkuli, telle que la possibilité de spécifier d'autres coordonnées pour le clic que le centre de l'image (par défaut).

**Comment by vertigo17** [comment]
The paramater cerberus_sikuli_minSimilarity has been introduced in very recent [commit](https://github.com/cerberustesting/cerberus-source/commit/128eee42b08a82f53a2abe1ac1864aa15534b758)
It will be available in next Cerberus Version.
It allows to tune the similary threshold inside Cerberus.
Sikuli default to 0.7 when not defined. 1 means exact (and should be never used)

Using that parameter will also require to use the latest version of cerberus-extension-sikuli that has not been released yet (but will very soon).

Next step (that will be follow up on a separate issue is to be able to tune that parameter at condition/aaction/control level)

**Comment by vertigo17** [comment]
Please open a dedicated issue on the missing sikuli actions.

Supported actions so far are:
openApp, closeApp (trigered automatically using application/env endpoint)
click
doubleClick
rightClick
mouseOver
wait
waitVanish
