### ISSUE TITLE
Handle case insensitive string comparaison

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1960]
Hello,

What do you think of adding a way (I'm thinking of a checkbox) to allow Cerberus to compare without having it to be case sensitive?

![image](https://user-images.githubusercontent.com/30227758/55315116-f0d16780-546b-11e9-80a3-c44bb7b0148c.png)

I faced the problem with the control VerifyStringContains but it could be applied to several others action, control or condition.

Thanks!

**Comment by ruirpr** [comment]
This could be useful. We use a lot of toLowerCase() method as workaround.

**Comment by Nouxx** [comment]
List of controls : 

- verifyStringEqual
- verifyStringDifferent
- verifyStringContains
- verifyContainsNotContains
- verifyTextInElement
- verifyTextNotInElement
- verifyTextInPage
- verifyTextNotInPage
- verifyTitle

What do you think?

**Comment by vertigo17** [comment]
We need to share how to change to caseinsensitive. 
Should we create a value3 or duplicate all controls ?

**Comment by Nouxx** [comment]
I believe it will be more user friendly to add a "isCaseSensitive" (or "value3") field on the control model. Adding new controls (e.g. verifyStringEqualCaseInsensitive) might result in having to many options and isn't going to simplify the interface in my opinion

**Comment by Nouxx** [comment]
Hello!

We didn't consider the other entity that shared methods (in the source code) especially the ConditionOper (e.g. IfTextInElement)

It might extend the scope of this issue !

**Comment by Nouxx** [comment]
Regression added and OK
