### ISSUE TITLE
Can't run a test case or a campaign

### ISSUE THREAD

**Issue by kileek** [cerberustesting/cerberus-source#1961]
Hello Guys,

Since the last week, i had an issue when i want to run a test case and i can't execute any campaign anymore.
I'm not able to determine the process to have this issue , it's literally random only when i'm executing a test case alone :/

The error message is : The test case failed to be executed. Could not start Selenium. org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally
 
And there is my Cerberus configuration 👍 
![DatabaseCerberusVersio](https://user-images.githubusercontent.com/14565233/55390448-8685f900-5537-11e9-9954-d8e6b31505fd.PNG)

![Capture](https://user-images.githubusercontent.com/14565233/55390469-96054200-5537-11e9-98d8-5c463b02687d.PNG)

![Version Cerberus](https://user-images.githubusercontent.com/14565233/55390462-8f76ca80-5537-11e9-90a8-c0bd857ece49.PNG)

I think we have to upgrade our Cerberus version right ? 

Thanks to anyone who will take time to answer me =)

**Comment by nicodeur** [comment]
Hi,

Is the problem still there?

Can you share the selenium hub/chrome node logs please ?

Nicolas
