### ISSUE TITLE
[Evolution] Allow to swipe into notifications

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1965]
Cerberus Version : 3.12-SNAPSHOT-1397

Actually we can swipe on a mobile application or web but not inside phone notifications.

Can you add this action possible ?

**Comment by nicodeur** [comment]
Hello @glassalle59 

I can propose you to create a new property 'getElementPosition'. It will mandator an id/xpath/cssseclector/etc .

It would return the position of an element on format '<x value>;<y value>'

With this information, you will can swipe on your notification by call action `swipe` with Direction `%property.name%;z;y`

Ok for you ?

**Comment by glassalle59** [comment]
Ok for me

**Comment by j0hnsa** [comment]
Yes this would be really handy:

https://github.com/cerberustesting/cerberus-source/issues/1905

BR

**Comment by nicodeur** [comment]
Thanks @j0hnsa
