### ISSUE TITLE
[New Features] Add a "verifyTextContainsInElement"

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1966]
Hello,

I'd like to use the control `verifyTextInElement` to verify if the string **Element** contains the **Text**

![image](https://user-images.githubusercontent.com/30227758/56579202-da807c80-65cf-11e9-9621-3259a39551c1.png)

My workaround is to create a property getFromJson (in my case) and switch the control to `verifyStringEqual`.

The drawback being that I need to create a property and in my case, that's the main issue!

Thanks

**Comment by GrandjeanRemi** [comment]
Hello,

You can use the control "verifyRegexInElement".

Rémi.

**Comment by Nouxx** [comment]
Thanks @GrandjeanRemi, you're right! 

I think we shouldn't bother adding a new control and close the issue then? @vertigo17

**Comment by vertigo17** [comment]
Yes ;-)
