### ISSUE TITLE
Chrome executions on robot not visible

### ISSUE THREAD

**Issue by mbessa** [cerberustesting/cerberus-source#1967]
Hello,

Testexecutions on robothost for chrome tests ran but aren't visible, aparently with new version start running somehow in background because it even creates snapshots. Firefox continues to execute and be visible as usual.
Any new configuration required for chome?

Thank you,
MB

Cerberus Version : 3.12-SNAPSHOT-1400

**Comment by mbessa** [comment]
I think I found the issue:
https://github.com/cerberustesting/cerberus-source/commit/5b57789232e3a3ac41bd29d41e3cf828242d7a68#diff-3bd6319a21bbe0a40c86e88da721e4bf
                options.addArguments("--headless");           

Can we overwrite it on Cerberus or is it possible to remove that from the code by default? This cause debug issues.

Thanks

**Comment by vertigo17** [comment]
Maybe we should temporary remove it and make it optional but can you detail more what issue it cause ?
Are the screenshot still displayed ?

**Comment by mbessa** [comment]
Testing team use live executions very frequently to debug had to spot issues from Cerberus screenshots and also as helper when there's complex scenarios and several steps prior to the step where the issue happen. 
It's not blocking but the possibility to view a live execution, makes the debug process a lot faster an efficient. Our testing team use it all the time.

Screenshot still displayed.

As you mentioned, I would suggest to make it headless by default (because it should reduce resource consumption and the complexity on robot host) but with possibility to overwrite it for some robots. If you predict the development will be long we surely appreciate to remove it temporarily, otherwise, we can wait for it a couple of days for it, no problem.

**Comment by ElFaboon59** [comment]
Hello ,

This comes from a merge request i posted some days ago. You can totally remove this chrome option. I added it in order to have a correct screen size , as the height is systematically reduced by 116 px without it. Do you want me to pull a other merge request for that ?

Regards.

**Comment by ruirpr** [comment]
Hi, this is apparently causing some tests to fail in verifyElementVisible in chrome: 
http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=74189322

OK for firefox:
http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=74189375

sorry if not related :|

**Comment by ruirpr** [comment]
Turns out it's resolution. For some reason chrome resolution is 800x600 and firefox runs in a higher resolution.

**Comment by vertigo17** [comment]
Fixed with last commit.
verbose 0 still hide the browser window.
verbose 1 and 2 will remove the headless flag and display the window.
