### ISSUE TITLE
Running tests on PL - blank page using chrome

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1971]
Hi,

when we run test cases on PL (preview or Preprod) for chrome, Home page doesn't load and test cases fail.
On firefox we don't have this issue.

http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=74376826
![image](https://user-images.githubusercontent.com/14328346/56896533-e06cd680-6a83-11e9-8b48-0ef6466ad66e.png)

Also, this not happens on PROD using chrome.

Can you plesae take a look?

Thanks.

**Comment by vertigo17** [comment]
If the issue still there ?

**Comment by RobertoAbraul** [comment]
This issue can be closed.
