### ISSUE TITLE
[IDEA] - Relaunch option on dependencies

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1977]
Hello,

Playing around with test case dependencies, I am facing a barrier to implement it in my project.

In short, I have 
- a single test case **A** that create a consumable token
- many test cases **B** that needs such token

All my testcases **B** have a dependencies on the same test case **A**.
When I launch a single test case **A** with a single test case **B** it's working fine, but there is obviously a conflict when launching several test cases **B** at the same time.

![image](https://user-images.githubusercontent.com/30227758/57149711-9f026100-6dcc-11e9-980f-e5d0a5b63ca5.png)

I believe a "Relaunch" option would be perfect to ensure that the previous test case (A) is relaunched (this new execution would used as well)

![image](https://user-images.githubusercontent.com/30227758/57149467-11bf0c80-6dcc-11e9-8162-4a0603f7bde2.png)

**Comment by vertigo17** [comment]
For that you need to create TC.A1, TC.A2, TC.A3. 
I could suggest to create some kind of test case symlink in order to avoid maintain 3 test cases. 
A1 A2 and A3 would all link to A. 
If you’re fine with that option please open a dedicated issue and close this one.

**Comment by Nouxx** [comment]
Yup, that will do the trick for me
