### ISSUE TITLE
Last execution button (same env & country) on queue modal

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1983]
Hello,

I think that a button to check last execution would be handy when we click a queued test and a modal to edit queue options opens. something like this:

![2019_06_06_14_37_06_Execution_reporting_by_tag_Firefox_Developer_Edition](https://user-images.githubusercontent.com/16339891/59038101-655cc400-886a-11e9-919c-82556543f97b.png)

what do you think?

Best Regards
Cerberus Version : 4.0-1400

**Comment by vertigo17** [comment]
Not clear from where you would like this queue modal to appear ?
Execution in Queue page, Detailed Execution page, Test Case script page, Reporting by Tag ?

**Comment by j0hnsa** [comment]
the queue modal is present on the Reporting by Tag page I'd like to have this button on that modal because it would cut a few clicks to see why the test is retrying.

**Comment by vertigo17** [comment]
Or maybe what i can propose is to find a way from reportingbytag page to either display that modal or go to last execution directly. Not sure exactly how in terms of display thought.

**Comment by vertigo17** [comment]
I propose:
![image](https://user-images.githubusercontent.com/5342048/62704353-71404000-b9eb-11e9-8730-e3a0ab00876b.png)
