### ISSUE TITLE
Execute .sh / .bat script 

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1985]
Hello,

I need to be able to perform complex actions on file coupled with FTP upload and a great workaround would be to launch a script to do it for me.

What do you think of enabling the executeCommand action on others application type (than APK) to call a script that would be stored in the cerberus server ?

Thanks !

**Comment by Nouxx** [comment]
@vertigo17, here is the current implementation: 
- executeCommand action is supported for application type : BAT,FAT,SRV)
- only supported for Linux Host OS
- only "command" field is used, "args" field is useless
- the command field should only contains the name of the script.extension (e.g. "hello_world.sh")
- the exact command isn't shown to the user
- folder, user and password are defined in parameters as well as a boolean to enable the feature

Can we move forward with this issue?
I agree on the idea of having a new action with a single field "script name" but I'm not sure about the name

**Comment by vertigo17** [comment]
Reopen in order to change the parameter name.
