### ISSUE TITLE
Execute test with Kobiton (like BrowserStack)

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1994]
Hello, for a project, I need to execute test on Kobiton (it's a farm device like BrowserStack).
=> I tried also with browserstack and its well worked

I tried to create a robot with right capabilities / host / key and right application but my test didn't work. 

**My robot:**

![image](https://user-images.githubusercontent.com/33724879/61004806-1cb39180-a367-11e9-884b-a351b2df11d4.png)

![image](https://user-images.githubusercontent.com/33724879/61005702-f7c01e00-a368-11e9-896b-6b4553b91c7c.png)

**My application:**

![image](https://user-images.githubusercontent.com/33724879/61004932-600e0000-a367-11e9-9f67-90b66f1f410c.png)

**The capabilities from Kobiton:**

String kobitonServerUrl = "https://pragma:XXXXXXXXXXX@api.kobiton.com/wd/hub";

DesiredCapabilities capabilities = new DesiredCapabilities();
// The generated session will be visible to you only. 
capabilities.setCapability("sessionName", "Automation test session");
capabilities.setCapability("sessionDescription", "");
capabilities.setCapability("deviceOrientation", "portrait");
capabilities.setCapability("captureScreenshots", true);
// The maximum size of application is 500MB
// By default, HTTP requests from testing library are expired
// in 2 minutes while the app copying and installation may
// take up-to 30 minutes. Therefore, you need to extend the HTTP
// request timeout duration in your testing library so that
// it doesn't interrupt while the device is being initialized.
capabilities.setCapability("app", "kobiton-store:35876");

capabilities.setCapability("deviceGroup", "KOBITON");
// For deviceName, platformVersion Kobiton supports wildcard
// character *, with 3 formats: *text, text* and *text*
// If there is no *, Kobiton will match the exact text provided
capabilities.setCapability("deviceName", "Galaxy S6");
capabilities.setCapability("platformVersion", "6.0.1");
capabilities.setCapability("platformName", "Android");

**Actual result:**
_The test case failed to be executed. More lickely due to an error in the test or in Cerberus configuration. The test case failed to be executed. Could not start Robot Server. org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: Unable to parse remote response: Not Found Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z' System info: host: 'fc12d74c85bb', ip: '172.19.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.13.16-100.fc25.x86_64', java.version: '1.8.0_152' Driver info: driver.version: AndroidDriver. Exception: org.cerberus.exception.CerberusException_

Can you help me plz ? 

Thanks

**Comment by glassalle59** [comment]
Pour info j'arrive bien a me connecter au device Kobiton via Appium Desktop

**Comment by nicodeur** [comment]
There was a bug when we build url when we use https.

Fix with commit 2412e403704996aaa2bc280ec1392abe959b5325

**Comment by glassalle59** [comment]
Thank you !!!!
