### ISSUE TITLE
Error on page TEST case list for Cerberus (Chrome) on Windows 10 pro

### ISSUE THREAD

**Issue by afiif13** [cerberustesting/cerberus-source#1996]
Cerberus Version : 4.0-1400
Chrome Version: Version 75.0.3770.142 (Official Build) (32-bit)

See the Cerberus information page and the error on the Test Case list option. 
![Cerberus_INFO_4 0](https://user-images.githubusercontent.com/53083983/61532685-a801e680-aa3b-11e9-8bce-aef3000cb58a.png)

![TestCaseList](https://user-images.githubusercontent.com/53083983/61532693-acc69a80-aa3b-11e9-9116-27b32ace940e.png)

How can we fix this error? The screen is stuck on processing.  Thank you

**Comment by vertigo17** [comment]
duplicate from #1998
Database structure is not OK.
