### ISSUE TITLE
Error on Application page - column App.UsrModif not found

### ISSUE THREAD

**Issue by afiif13** [cerberustesting/cerberus-source#1997]
Cerberus Version : 4.0-1400
![Application](https://user-images.githubusercontent.com/53083983/61532922-72113200-aa3c-11e9-96d4-02f5fac36cf4.png)

How can we fix the error (see screenshot) above?

![Cerberus_INFO_4 0](https://user-images.githubusercontent.com/53083983/61532957-86552f00-aa3c-11e9-86d4-79a52ac8d0c0.png)

 Thank you

**Comment by vertigo17** [comment]
duplicate from #1998
Database structure is not OK.
