### ISSUE TITLE
Error - Label screen - Cerberus.Label does not exist

### ISSUE THREAD

**Issue by afiif13** [cerberustesting/cerberus-source#1998]
Cerberus Version : 4.0-1400

See screenshot below for error:
![Label](https://user-images.githubusercontent.com/53083983/61534167-dd103800-aa3f-11e9-9eb8-3f34e654885b.png)
![Cerberus_INFO_4 0](https://user-images.githubusercontent.com/53083983/61534176-e26d8280-aa3f-11e9-988f-f0704103cdab.png)

How can we fix this error? Thank you

**Comment by vertigo17** [comment]
Well, looks like when you initialise the database, something went wrong.
Can you recreate it and check that all SQL were correctly executed ?

**Comment by afiif13** [comment]
Hi Benoit,

Thank you for your reply.

The database is up to date and all the SQL statement have been executed successfully.

![image](https://user-images.githubusercontent.com/53083983/61624703-2fdd3000-ac8a-11e9-9981-f6f7022bc06a.png)

I'll try to drop the database from mysql and re-create the users and redeploy cerberus app (on glassfish4) and let you know the results. 

I am doing this on Windows 10 pro through the manual installation (without docker) 

Thanks,
Afiif

**Comment by vertigo17** [comment]
The screen you show is just the list of SQL but it does not report the ones that executed correctly.
The only way to see if those were executed correctly is on the 1st loading of the page or on application server logs. As you propose, delete the database and initialise it again checking that every SQL appears in green.

**Comment by vertigo17** [comment]
Did you manage to reinstall the database correctly ? If so can tou close the issue ?
