### ISSUE TITLE
Test Folder page error - An unexpected problem occurred. Unable to retrieve the list of entries!

### ISSUE THREAD

**Issue by afiif13** [cerberustesting/cerberus-source#1999]
Cerberus Version : 4.0-1400

How can we fix the error in the screenshot below?

![TestFolder](https://user-images.githubusercontent.com/53083983/61534604-17c6a000-aa41-11e9-8bbc-df0a71e14fe9.png)

![Cerberus_INFO_4 0](https://user-images.githubusercontent.com/53083983/61534609-1b5a2700-aa41-11e9-9f9f-a01996aed23c.png)

Thank you.

**Comment by vertigo17** [comment]
duplicate from #1998
Database structure is not OK.
