### ISSUE TITLE
Errror on Robot page - An unexpected problem occurred. java.sql.SQLException: Column 'type' not found.

### ISSUE THREAD

**Issue by afiif13** [cerberustesting/cerberus-source#2000]
Cerberus Version : 4.0-1400

How can we fix the error in the screenshot below?

![Robot](https://user-images.githubusercontent.com/53083983/61534700-5d836880-aa41-11e9-932d-1ca7bc6a8d9d.png)

![Cerberus_INFO_4 0](https://user-images.githubusercontent.com/53083983/61534714-62e0b300-aa41-11e9-924e-8d1447ff241a.png)

Thank you.

**Comment by vertigo17** [comment]
duplicate from #1998
Database structure is not OK.
