### ISSUE TITLE
[Evolution] New control verifystringNotContains and new condition IfStringNotContains

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#2002]
Cerberus Version : 4.1-SNAPSHOT-1409

Actually we can verifystringcontains on a control and use a condition operator IfStringContains
but the opposite doesn't exist

Can you add this control ? **verifystringNotContains**

Can you add this condition operator :  **IfStringNotContains**

**Comment by vertigo17** [comment]
Already available in SNAPSHOT.
Will be in 4.1
I target to release it during the WE.

**Comment by glassalle59** [comment]
Great, thank you !
