### ISSUE TITLE
[Regression] Cannot edit and save Robot

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#2005]
Cerberus4.1-1419 

Since the last version of cerberus, I cannot edit then save a robot. The message "Processing "doesn't disappear. 

Its because of new fields :

cerberus-as-glassfish_1  | |#]
cerberus-as-glassfish_1  | 
cerberus-as-glassfish_1  | [#|2019-07-30T12:22:13.488+0000|INFO|glassfish 5.0||_ThreadID=153;_ThreadName=Thread-8;_TimeMillis=1564489333488;_LevelValue=800;|
cerberus-as-glassfish_1  |   2019-07-30 12:22:13 WARN  UpdateRobot:335 - org.json.JSONException: JSONObject["executorProxyHost"] not found.
cerberus-as-glassfish_1  | |#]
cerberus-as-glassfish_1  | 

If theses fields are empty, the save doesn't work:
- executorExtensionPort
- executorProxyHost
- executorProxyPort

**Comment by vertigo17** [comment]
Issue fixed but a workaround is to massivly update the 3 fields to 
executorExtensionPort : 0
executorProxyHost : ""
executorProxyPort : 0

using the SQL:

update robotexecutor set executorExtensionPort=0, executorProxyPort=0, executorProxyHost='' 
where executorProxyHost is null;

**Comment by glassalle59** [comment]
Fields are like this but the save is still KO

![image](https://user-images.githubusercontent.com/33724879/62192597-32b8de80-b376-11e9-850a-c9f013e186b6.png)

**Comment by vertigo17** [comment]
OK Thanks.
