### ISSUE TITLE
[Regression] Cannot search test case using filters on "Run test page"

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#2006]
Cerberus4.1-1419

**Steps :**

Go "Run test page" Cerberus/RunTests.jsp, 
Use filter on "Extended Test Case Filters" section 

**Current result:**
No result : undefined 

![image](https://user-images.githubusercontent.com/33724879/62129815-ed45d400-b2d7-11e9-827f-486b0fa3af93.png)

**Expected result:**
Results appears

**Comment by cDelage** [comment]
Fixed by commit : 48591c9d3dd631f68f049d53ca78c6d80fcaf7c8
