### ISSUE TITLE
Empty browser on robot sending incorrect capabilities 

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#2010]
Hello,

I'm trying to run tests on Android native browser but I get this error:

Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The desired should not include both of an 'appPackage' and a 'browserName'

Using the following robot (tried also to clear the browser field with the same output):
![image](https://user-images.githubusercontent.com/16339891/63415027-f4529480-c3f4-11e9-9405-eff012a5e586.png)

with android browser defined:
![image](https://user-images.githubusercontent.com/16339891/63415127-2532c980-c3f5-11e9-97bc-bcdcafcadeeb.png)

without:
![image](https://user-images.githubusercontent.com/16339891/63415204-44c9f200-c3f5-11e9-8b26-61d2e6682720.png)

I would say that the browser capability should not be sent when no browser is defined.

Can you have a look?

BR
Cerberus Version : 4.2-SNAPSHOT-1421

**Comment by vertigo17** [comment]
Are you sending the execution to an appium instance ? To Browserstack ?
What is the type of the application tested ?

If you want to test a website from android browser on a android device you should have the application type to GUI, the robot platform to ANDROID, leave the robot type to an empty value and send the execution to an appium server.

**Comment by lucashimpens** [comment]
Creator has left the company
