### ISSUE TITLE
Change ReadLabel Response

### ISSUE THREAD

**Issue by Anthony-Jhoiro** [cerberustesting/cerberus-source#2011]
Currently when calling ReadLabel Servlet, it respond with : 
* contentTable with all labels from the system 
* labelHierarchy with labels filter by type.
* other...

#### Problem is : 
In thelabelHierarchy, labels informations (color and text) are in plain HTML.
I think it could be manage a better way : like replacing html by the list of labels as they are in the contentTable.
It would make the angular implementation much easier

Thank You !

**Comment by vertigo17** [comment]
I added label object to the hierarchy part of the response. If you can confirm that the format provided in reportbytag is the expected one. Thanks.
Reopen if not what you expect.
