### ISSUE TITLE
User Agent not persisted to DB

### ISSUE THREAD

**Issue by KamalBenHilal** [cerberustesting/cerberus-source#2012]

**Comment by KamalBenHilal** [comment]
Cerberus version : 4.0
Test case : I bind an user agent to a testcase, after saving the information doesn't exist in the DataBase.
so when I execute a request sql directly in the DB, the user agent is shown in the testCase configuration.

**Comment by vertigo17** [comment]
Bug also present in 4.1
Willl be fixed in 4.2
