### ISSUE TITLE
Error when assigning a recently created invariant to a new testcase

### ISSUE THREAD

**Issue by MorganLmd** [cerberustesting/cerberus-source#2013]
https://prod.cerberus-testing.org/TestCaseExecution.jsp?executionId=164125

In this test execution, after a new invariant has been assigned to a new test case, the test case is saved. But when the test case is re-opened for verification, the status is set on "Stand by"

**Comment by vertigo17** [comment]
Did you manage to reproduce the bug manually ?
I did not on my side.
