### ISSUE TITLE
Error when not able to add testcase to queue

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2018]
Hello,

I currently can't launch a campaign from the Run page.

The "processing" loader is blocked and looking at the network console 
![image](https://user-images.githubusercontent.com/30227758/65414179-74ed2200-ddf3-11e9-848e-4997bf9208ac.png)

Can we make sure the front returns a more user friendly error?

**Comment by vertigo17** [comment]
I suppose this is a duplicate of #1835

**Comment by vertigo17** [comment]
if error because require an authentification please close it and confirm duplicated.
if a 500 error please provide a trace of the call.

**Comment by vertigo17** [comment]
Following our discution, the issue is not a duplicate of #1835.
Please provide a way to reproduce the 500 error.
Campaign name + browser.

**Comment by Nouxx** [comment]
Env : https://qa.cerberus-testing.org
Campaign : Cerberus_campaign (every fields are pre filled)
Browser : Chrome (latest)

**Comment by vertigo17** [comment]
I guess this is fixed following commit https://github.com/cerberustesting/cerberus-source/commit/7e935cd24d282987f8f0d0241c775130a0be93dd
Please reopen if not the case.
