### ISSUE TITLE
Docker composes are not working on MacOS

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#2027]
Hi,

Docker composes are not working on MacOS as is. Indeed, they use the `/etc/localtime` volume folder which is not present by default in MacOS and complain with the following error:

```
ERROR: for docker_cerberus-db-mysql_1  Cannot start service cerberus-db-mysql: b'Mounts denied: \r\nThe path /etc/localtime\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
```

In addition, I don't think this configuration is necessary because every image should have the host's timezone at runtime. You should probably remove this volume mount.

**Comment by vertigo17** [comment]
fixed with https://github.com/cerberustesting/cerberus-source/commit/8d989d238270c08798912dc210ef7f17658c3b14
Thanks.
