### ISSUE TITLE
Docker composes are not fully functional by default

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#2028]
Hi,

When running docker compose(s) as is (then without any additional configuration), we cannot execute any test case:

<img width="1070" alt="Screenshot 2019-10-23 at 00 31 32" src="https://user-images.githubusercontent.com/1511715/67339964-8e85a480-f52c-11e9-8a3c-591d8e742a94.png">

This is due to the `cerberus_url` parameter value that doesn't include the `/Cerberus` root path (`localhost:8080` vs `localhost:8080/Cerberus`)

Additionally, there is no way to set the value directly from the parameter page. When trying to set the `cerberus_url` value, we get the following error log (and the UI is waiting infinitively and needs a manual refresh):

<img width="1528" alt="Screenshot 2019-10-23 at 00 34 53" src="https://user-images.githubusercontent.com/1511715/67340135-0ce24680-f52d-11e9-983a-7402389cf146.png">

The only way to fix that is to directly update value from database.

**Comment by vertigo17** [comment]
Hello @abourdon , NullPointer on parameter change was fixed with https://github.com/cerberustesting/cerberus-source/commit/8bd860b098810c419b8bc886020272074e34bd6b
About default URL, Tomcat docker (that is now the official Application server to use does not have a context root defined).
