### ISSUE TITLE
click no longer works on input tag

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#2030]
Hi,

cerberus cannot click on input elements.
Examples:
http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=84800509
http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=84800432

Is this expected?

![image](https://user-images.githubusercontent.com/14328346/67565525-8e98c680-f71d-11e9-90b3-562f5331d80b.png)

![image](https://user-images.githubusercontent.com/14328346/67565538-948ea780-f71d-11e9-9593-a3ba5ff8ea88.png)

Cerberus4.3-SNAPSHOT-1440

Thanks

**Comment by RobertoAbraul** [comment]
Other example:
![image](https://user-images.githubusercontent.com/14328346/67565749-12eb4980-f71e-11e9-8ddb-20fe4bc172e7.png)

**Comment by RobertoAbraul** [comment]
Also,
it works fine on firefox but not in chrome.
OK: http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=84806144
NOT OK: http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=84806034

**Comment by Nouxx** [comment]
It may be linked to the version compatibility with selenium client? @vertigo17

**Comment by vertigo17** [comment]
There were no changes on selenium client side on that version (in pom.xml) so I doubt it is.
https://github.com/cerberustesting/cerberus-source/compare/cerberus-testing-4.1...cerberus-testing-4.2
Here you use Chrome/59.0.
Have you checked updating to another version of chrome + chromedriver ?
Is that systematicly on all click actions or only on some ?

**Comment by RobertoAbraul** [comment]
Hi @vertigo17,

this seems to be happening only on click actions on <input> tags.
Click on labels and divs seems to be working without problem so far.

Example:
![image](https://user-images.githubusercontent.com/14328346/67574755-f7d70480-f732-11e9-9cb3-7272ef5f8361.png)

**Comment by Nouxx** [comment]
Hi @RobertoAbraul,

Taking a closer look at the login error, I'm wondering why are you trying to click on these input? I tried only to type them in and it seems to be working fine 

OK execution on Chrome: http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=84815581 (I duplicated your testcase on a new folder)

It indeed weird that these actions doesn't work anymore

**Comment by RobertoAbraul** [comment]
Hi @Nouxx ,

in fact that can be due to a old behavior and some tests can be adapted (no longer need that click before typing), but we still have other test cases like the situation below where there is no other way to choose "VISA" without click on <input>.

http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=84791097

![image](https://user-images.githubusercontent.com/14328346/67587256-63c56700-f74b-11e9-9cde-24d6ca75a486.png)

Also, on other tests, to verify some error messages we still need that click on customer/password fields for example.
Even click on "data-cerberus" is not working if it's an <input>.
Instead cerberus is making us click on divs and labels.

Thanks.

**Comment by RobertoAbraul** [comment]
Hi @vertigo17 ,

it's necessary deploy this fix?
Issue still present today: http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=84952427

Thanks

**Comment by Nouxx** [comment]
Hi @RobertoAbraul 

Can you confirm the problem is solved by launching the same testcases from http://cerberus.qa.siege.red  please?

I'll schedule the deploy asap  

Thanks

**Comment by RobertoAbraul** [comment]
Hi @Nouxx ,

test cases are ok in QA:
http://cerberus.qa.siege.red/CerberusQA/TestCaseExecution.jsp?executionId=84937570
http://cerberus.qa.siege.red/CerberusQA/TestCaseExecution.jsp?executionId=84937572
http://cerberus.qa.siege.red/CerberusQA/TestCaseExecution.jsp?executionId=84937575
http://cerberus.qa.siege.red/CerberusQA/TestCaseExecution.jsp?executionId=84937576
http://cerberus.qa.siege.red/CerberusQA/TestCaseExecution.jsp?executionId=84937577

Thanks!
