### ISSUE TITLE
Bug Tracker - variables cannot be repeated

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#2035]
Hi,

on New Bug URL tracker it's not possible to use the same variable twice in the bug URL.
Is this behavior expected?

Examples:
**OK:** https://laredoute.atlassian.net/secure/CreateIssueDetails!init.jspa?pid=10021&issuetype=10004&components=10029&summary=%TEST%-%TESTCASE%

**NOK:**https://laredoute.atlassian.net/secure/CreateIssueDetails!init.jspa?pid=10021&issuetype=10004&components=10029&summary=%TEST%-%TEST%

![image](https://user-images.githubusercontent.com/14328346/68663135-13654c00-0536-11ea-805a-62c41ce94c99.png)

Thanks.

**Comment by vertigo17** [comment]
No ;-)
