### ISSUE TITLE
Rename a Service

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#2042]
Hello, 

Is that possible to add the possibility to rename a service ?

Currently, it is not possible because the serviceName is the Key in DB, maybe we could associate the Service to a key in database to easily manage services transformation.

**Comment by vertigo17** [comment]
We can rename it even if it is the key ;-).

**Comment by Galand-V** [comment]
Sure, you're right but it seems like the service management could be easier if a key was associated to any new entry like datalibs.
