### ISSUE TITLE
Cerberus runs testcases twice

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#2043]
Hello
In our new environment - cerberus Tomcat 4.3 -  we met issues when running a campaign. Lot of testcases stay in PE status "creating RunID".
When analizing, I found out ceberus run testcases twice (only testcases longer than 1 min)
Even with no retry setting, cerberus runs an other test case with the same queueID.

![image](https://user-images.githubusercontent.com/18569182/69525588-ba031100-0f68-11ea-983c-7eec3e38867e.png)

We can see on the screen, cerberus waits 60 sec and run the second execution.
Is there a timeout setting for http request to the robot ?
I tried to modify "cerberus_robot_timeout" setting but nothing change.

Did you meet the same issue with tomcat ? 
thanks

**Comment by vertigo17** [comment]
Cerberus does not perform any retry on execution. 
What you describe clearly could explain as the first execution last more that a minute and ends after the second one is triggered.
Did you put a proxy or network equipement on top of Cerberus that we submit a retry ?
Last time I saw that, it was that. There are an apache/nginx on top of Cerberus that was resubmiting the request following a time out.
what is the config behind parameters :
cerberus_url
cerberus_gui_url
try to point cerberus_url directly to the tomcat instance.

**Comment by R-Loic** [comment]
you're right, it was the nginx conf !!
I modified the cerberus_url and it works now with the service pod name (kubernetes) instead of the url pointing on the nginx
thanks !
