### ISSUE TITLE
PE - ForceExeStatus

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#2045]
Hi,

it seems that we no longer can "force" a PE on actions like a "openUrlWithBase".
Is this behavior expected?

![image](https://user-images.githubusercontent.com/14328346/69626149-f48bad00-103f-11ea-84c0-619863416300.png)

![image](https://user-images.githubusercontent.com/14328346/69626264-3157a400-1040-11ea-90d0-6bfb0e022191.png)

Thanks!

Cerberus Version : 4.4-SNAPSHOT-1440

**Comment by vertigo17** [comment]
fixed with https://github.com/cerberustesting/cerberus-source/commit/bb156861f5bfb741f575026b4cc1aebf0d69ba48 and https://github.com/cerberustesting/cerberus-source/commit/6de186d47646b339aea1c58bb78ca0fe6d00eb08
