### ISSUE TITLE
Service name special characters

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#2048]
Hello, 

If you add a tabulation (%09) in the service name during the creation, the service will be not editable next time. 

![image](https://user-images.githubusercontent.com/29098010/69717650-b90ae480-110c-11ea-9ebf-cceadf4bdf5a.png)

![image](https://user-images.githubusercontent.com/29098010/69717738-e788bf80-110c-11ea-88a2-f01f5ebb078f.png)

can we block the user if he wants to create a service with a tabulation ?

**Comment by vertigo17** [comment]
How did you manage to create that data into database ?
TAB in the GUI will move to the next field.

**Comment by Galand-V** [comment]
it was a simple copy paste

**Comment by vertigo17** [comment]
Hello @MorganLmd , not sure but will trim remove tab ?

**Comment by MorganLmd** [comment]
@vertigo17 yes, I've tested it with multiple and mixed tabs + spaces before and after the service name and it works well
