### ISSUE TITLE
Notification mecanism : Campaign send a passive check to monitoring tool

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#2050]
Hi,
Add the possibility for campaign to send a passive check to monitoring tool.
Currently we have some alerts for Cerberus campaign (to check if the campaign was correctly executed or if there are some failed tests) being performed on Nagios/Centreon (that monitoring will have specific SLA and is being send to monitoring tools).
Today, those alerts are active checks were Nagios/Centreon is checking on Cerberus if campaign was executed successfully (the disadvantage is that those check are done at a specified time and if campaign is still running we will have a false result).
The goal was Cerberus to be able  to call an API at the end of the campaign to update the alert as a passive check (maybe add the option for Cerberus to execute a service at the end of the Campaign - service are already implemented and working for the testcases). 
Cerberus is able to send notification which is great to keep track of some campaign execution and result but email is not the best way to handle alerts and notifications on monitoring side.
Thanks in advance.

**Comment by vertigo17** [comment]
We can for sure add a notification (Like Slack or email)
Can you please detail what protocol would be required ? 
REST JSON ? What format for the message ?

**Comment by ffazendeiro** [comment]
Hi @vertigo17 ,
Yes, REST JSON.
Maybe we can use what Cerberus has already implemented just by adding on the campaign notification tab (or add a new one ) where we could call a service.
![image](https://user-images.githubusercontent.com/17747042/70050042-f3212e00-15c5-11ea-9491-11598033d28c.png)
The service would be defined on page /AppServiceList.jsp as any other service (like this we could take advantage of what already exists). Basically it would have the same behavior as the action "callService" available on the testcase.
Thanks in advance.

**Comment by vertigo17** [comment]
Not sure this is a good idea to mix very different usage even if the technical need is the same.
I propose that we just put a type (REST) URL + Message to be called at the end of the campaign (would be done in GET and POST).
The variable to be used would be the same as the one inside the email (excluding the html ones).
I would stil be interested to share what are the specs of Centreon call in order to secure this is enought.

**Comment by ffazendeiro** [comment]
OK, sounds good.
For the service nothing special is required. It is a POST with: Service path + Headers + Body (Request in JSON).
The JSON request structure is not yet defined, it will be implemented on Centreon side, but it could be interesting to have some global (or system) variable (like the timestamp, tag, CI result from the campaign, ...). 
Thanks.

**Comment by vertigo17** [comment]
That issue will support a new notification mecanism.
It will allow
- all notifications to be done asynchronously
- all event to be able to be posted in email, log, webhook or slack
- all event to be configured with required notification
