### ISSUE TITLE
Add a comment to an action/control on manuel execution

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2052]
Hi,

Currently, we can add various files to manual executions:
![image](https://user-images.githubusercontent.com/30227758/70067599-cc2b2200-15ee-11ea-81b7-06ac132deed3.png)

What do you think of adding a comment section that would allow the tester to simply write some text easily to give the issue more description?

Thanks

**Comment by vertigo17** [comment]
Please note that you can already put a comment for each step, action and controls.

![image](https://user-images.githubusercontent.com/5342048/70938837-49bb4d00-2047-11ea-8d6c-fc3474a880b9.png)


What could be added is the same at execution level. Let me know.

![image](https://user-images.githubusercontent.com/5342048/70939098-d7973800-2047-11ea-9a78-28e028f36580.png)

**Comment by Nouxx** [comment]
Hi,

Enriching this issue with:
- be able to edit the execution description (testcase level)
- return message should be editable not just once
- remove the unecessary fields in manual (only keep Code, Description, Action, Message)

**Comment by vertigo17** [comment]
This is what to look like now:

![image](https://user-images.githubusercontent.com/5342048/71380012-f52b4b00-25cd-11ea-9b0d-85a4c7c4c0a0.png)
