### ISSUE TITLE
Set context for hybrid apps

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#2057]
Would it be possible to implement this?
http://appium.io/docs/en/commands/context/set-context/
Sometimes working with hybrid apps we can't se the elements of its webview and I think this would help.

Best Regards
Cerberus Version : 4.2-1438

**Comment by vertigo17** [comment]
Do you see that as a new action that would start when apps open a webview ?
Would NATIVE_APP be to specify on 1st parameter. 
Do we need to call the same action with a different parameter once we leave the webview ?

**Comment by lucashimpens** [comment]
Creator has left La Redoute
