### ISSUE TITLE
KeyPress without xpath - Test case execution status stays on "EXECUTING"

### ISSUE THREAD

**Issue by hananema** [cerberustesting/cerberus-source#2059]
Hollo,

I used KeyPress without defining [opt] Target element path, and after running the test case, the status stays on "EXECUTING" eventhough execution is done. It is not updated and the execution is blocked on the step with the KeyPress:

![image](https://user-images.githubusercontent.com/41586025/70808035-21212200-1dbf-11ea-8d8c-07f62369299c.png)

![image](https://user-images.githubusercontent.com/41586025/70808096-3eee8700-1dbf-11ea-886e-bd1b4a4fcc02.png)

![image](https://user-images.githubusercontent.com/41586025/70808241-8c6af400-1dbf-11ea-8160-d14c1b56788e.png)

Thanks,
Hanane

**Comment by vertigo17** [comment]
Hello @hananema can you tell what you put in '[opt] Target element path' in order to make it work ?

**Comment by hananema** [comment]
Hello @vertigo17,
I put:  xpath=/html
