### ISSUE TITLE
[Dependency][property calculation] property still takes dependency calculation eventhough dependency deleted

### ISSUE THREAD

**Issue by hananema** [cerberustesting/cerberus-source#2062]
Example: 
Test2 has Test1 as a dependency and they both have a property named prop1.

Steps to reproduce:
1- run Test1 then Test2 (Test2 takes value of Test1 for prop1)
2- delete dependency for Test2
3- rerun Test2

Expected result: prop1 should take Test2 value.
Current result: prop1 still takes Test1 value.

Regards,
Hanane

**Comment by vertigo17** [comment]
I beleive all that is inside the same campaign execution (tag).
If you executed a new tag, I guess prop1 takes Test2 value ?

**Comment by hananema** [comment]
I just tested with a different tag and it does take Test2 value.

**Comment by vertigo17** [comment]
So is that worth keeping the issue ?

**Comment by hananema** [comment]
The issue accures only incase we relaunch a testcase in a campaign after deleting the dependency. I think it should not keep the dependency property value since it was deleted.
Maybe it might be considered as a minor issue?

**Comment by vertigo17** [comment]
We can but not sure we will fix that as 
1/ adding that constrain adds complexity on dependency management.
2/ changing dependency after executing a campaign and rerun a few executions inside a campaign does not secure that the full campaign work after the dependency change.
The safer way when changing a dependency is to rerun the campaign on a new tag.

**Comment by hananema** [comment]
Ok, it is clear to me now. We have to rerun the campaign after a dependency change. You can close this issue. Thank you.
