### ISSUE TITLE
Case sensitive message improvement

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2063]
Hi,

As discussed, we should update the message to the conditions actions and controls using the new case sensitive feature this way :

`(case-sensitive)` or `(case-insensitive)` instead of `with case sensitive constraint : ''`

If no value 3 is defined, we should keep the suffix of the message empty

Thanks !

**Comment by vertigo17** [comment]
For me, even if the value 3 is not feed, we should report in the message what Ceberus has done (either case-sensitive or case-insensitive). 
Let's not leave the user guess what Cerberus has done and tell him clearly what it did.

**Comment by Nouxx** [comment]
![image](https://user-images.githubusercontent.com/30227758/72729717-24fb4d80-3b90-11ea-8179-9b0812e23f40.png)
@MorganLmd
