### ISSUE TITLE
[Enhancement] Add test folder on log for DELETE action

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#2066]
Hi,
When deleting a test case, on the log page we only have the testcase name.
If there is more than one testcase with the same name we cannot know which one was deleted with certainty.
for example:
![image](https://user-images.githubusercontent.com/17747042/71084229-bab84d00-218c-11ea-826a-6441b6c6165c.png)
would it be possible to add on the log the test folder to which the test belongs?
Thanks in advance.

**Comment by vertigo17** [comment]
Yes sure. This is quite an easy change ;-). You don't want to give it a try ?
We should also add the version number.

**Comment by vertigo17** [comment]
Solved in 4.8
