### ISSUE TITLE
Add field "Project" to test case header (builds only)

### ISSUE THREAD

**Issue by dcop7** [cerberustesting/cerberus-source#2067]
Hello,
The filed "Project" was removed. An issue was opened (https://github.com/cerberustesting/cerberus-source/issues/2046) and it was closed saying this wont be added.

However, projects are still used for builds. We have a new project that we want to associate with a build, but we can't add this new project.
Can you readd the projects GUI only for builds?

**Comment by vertigo17** [comment]
What do you mean by project for build. Project were just an attribute of a testcase and had no link to build. Can you detail what project was used for and the reason why label can’t be used in stead.

**Comment by dcop7** [comment]
In the menu "Integration" > "Build Content" the "Project" is still present.
If I try to create a new Build Content, there is a drop down list to choose a Project. But I can't insert new Projects to select in this menu.

![image](https://user-images.githubusercontent.com/2600148/73346021-075b7180-427d-11ea-838d-5a91eff15226.png)

**Comment by vertigo17** [comment]
OK Understood. I will make it as a free field instead.
