### ISSUE TITLE
Datalib : Access subdatas + rowNumber

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#2070]
Hello, 

I am not sure that this behaviour is implemented yet, but I would like to access subdatas linked to an SQL property on several rows.

I can : 
-  access subdatas on the first row
- access the key value on several rows

I cannot : 
- access the subdatas on several rows

![issues subdatas](https://user-images.githubusercontent.com/29098010/72421659-3227cf00-3781-11ea-9d18-66a709d58084.gif)

**Comment by vertigo17** [comment]
try %property.testcase.2.application%
Documentation is : 
https://qa.cerberus-testing.org/documentation/documentation_en.html#_testcase_variables

**Comment by Galand-V** [comment]
![image](https://user-images.githubusercontent.com/29098010/72716169-12721b80-3b72-11ea-99be-4b9859bd0dda.png)

This was the first thing I tried.

**Comment by vertigo17** [comment]
This is a different example ;-).
Is workingHourInfo a property ?
Is state a subdata ?
Was property calculated with at least 2 lines ?
