### ISSUE TITLE
Message 'Screenshot Too Big!!' taking screenShots inside test execution

### ISSUE THREAD

**Issue by akatmiranda** [cerberustesting/cerberus-source#2076]
Hi!

We're randomly getting 'Screenshot Too Big!!' inside testcase executions.
This happens when defined in testcase execution 'Automatic Screenshots on Error' or even setting a step with control 'takeScreenshot'.

![image](https://user-images.githubusercontent.com/38046035/72744738-0e5ff100-3ba6-11ea-8f0b-013692205b30.png)

**Comment by vertigo17** [comment]
This is due the the fact the screenshot file is too big to be saved.
You can adjust that size using parameter : cerberus_screenshot_max_size
That parameter prevent the filesystem to get too big too quickly.

**Comment by akatmiranda** [comment]
Hi!

I see. But still we have to set a limit around 15 MB to get all screenshots. We are getting images around 13, 14 MB. Normally it used to be some KB's. Is this expected?

**Comment by vertigo17** [comment]
Screenshot usually take some Kbs and yes, this is strange they are so big.
Can you provide sample of those screenshots ? They could be big in case the screenshot takes the full page on old firefox versions.
