### ISSUE TITLE
Maintenance Mode + Deployment Alerting system

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2077]
Hello,

What do you think of having a way to :
- notify all the users that an interruption of service is planned for a specific date & time
- block the access to Cerberus in the application during this interruption of service 

Using this new feature + the `/management` endpoint could be very useful for better automated deployments 

Thanks

**Comment by vertigo17** [comment]
Display a splash page when /manage API is called with stop operation is a good idea. That will prevent users to insert new execution to queue during the system stops.

Sending an email for a planned deployed of Cerberus seems out of scope.

**Comment by MorganLmd** [comment]
TNR message displayed on HomePage
