### ISSUE TITLE
Status "PE" not apdated

### ISSUE THREAD

**Issue by hananema** [cerberustesting/cerberus-source#2082]
Hello,

In a campaign launched automatically with scheduler, 3 tests stayed on status "PE" and it is not updated.
I checked in "Executions in queue" , state is "EXECUTING".

I should mention that the step where the tests keep loading calculates a property that executes an SQL request with 8 retries, 25000ms each.

Also, the campaign contains other tests with a step with the same configuration that were executed correctly with this result:
Status: NA
Error: Retried 8 time(s) with 25000ms period - Data Library entry ****  failed . The SQL performed against database *** and JDBC Ressource *** returned no data to test.

Please let me know if you need more information.

Regards,
Hanane

**Comment by vertigo17** [comment]
I will need to have the complete test definition as well as execution in order to try to reproduce.
Can you reproduce in qa environment ?

**Comment by vertigo17** [comment]
Is issue still relevant ?

**Comment by hananema** [comment]
I never faced this issue since then. So you can close the ticket, thank you.
