### ISSUE TITLE
Status "CA" not updated

### ISSUE THREAD

**Issue by hananema** [cerberustesting/cerberus-source#2083]
Hello,

I canceled a test from "Executions in queue" that was in state "Executing", the state was updated to "CANCELLED" in "Executions in queue", but nothing changed in the execution report.

Please let me know if you need more information.

Regards,
Hanane

**Comment by hananema** [comment]
Also, I cancelled a test while it was executing, the state in queue became "CANCELLED" but the test kept executing until the end.

Regards,
Hanane

**Comment by vertigo17** [comment]
This is normal, cancel a queue entry prevent the execution to be triggered but do not stop it if already started.
If you can detail what you mean by nothing happen ?
What was the report like and what did you expect it to be ?
FYI, CANCEL is supposed to remove the queue entry from the queue and make it disappear from the report (in oposition to ERROR that will also prevent the execution to start but will appear in the report as error (QE)).
The error status can be used in case you want to 'PAUSE' the queue entries. Move the queue entrie to ERROR will stop them and allow to start them again from report screen.
CANCELLED also stop but does nto allow to resubmit them from report page.

Hope this is clear ;-)

**Comment by hananema** [comment]
For the first comment, what I ment by "nothing happened" is that I still had my test in the execution report with status "PE". But maybe this happens because it already started executing.

But now I understand that forcing to error or cancel are both used for tests with status "QE" and not "PE", is that right?

If yes, what if I wanted to stop a test which already started executing (status PE) ? is that possible?

Thanks,
Hanane

**Comment by vertigo17** [comment]
Yes, when a test start to execution, on the reporting side the queue status is ignored.
So your PE execution will always be seen whatever status the queue entry is.

QE means that queue entry is in error and no execution was triggered.
A queue entry in cancelled state will just be ignored.

So far, a test that has started cannot be stopped. ;-)

**Comment by hananema** [comment]
Ok, thank you :)
