### ISSUE TITLE
FTP Service decoding property issue

### ISSUE THREAD

**Issue by fchaabani** [cerberustesting/cerberus-source#2085]
Hello,
We are facing an issue with FTP service, well when we try to use property in the request tab, Cerberus does not decode it:
Please refer to screenshot attached
![image](https://user-images.githubusercontent.com/33456029/73729413-47b36780-4735-11ea-82e5-7a5cd8dabf82.png)

![image](https://user-images.githubusercontent.com/33456029/73729453-5c8ffb00-4735-11ea-86fb-d7a2aaf6e635.png)

Thanks,

**Comment by vitoo** [comment]
+1 we need this feature to upload dynamic file :)
