### ISSUE TITLE
Kafka Parrallels executions filtering issues

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2087]
Hello,

In a basic produce then search scenario, I am facing issue when launching several executions at the same time : 

![image](https://user-images.githubusercontent.com/30227758/73834809-a7c90d00-480c-11ea-9c3b-50c0439de0ce.png)

I am producing an event with a functional key that is persisted in every topics : 
![image](https://user-images.githubusercontent.com/30227758/73834894-cb8c5300-480c-11ea-98ec-2375c7194267.png)

Then, I am searching this event on another topic with the same key 
![image](https://user-images.githubusercontent.com/30227758/73834998-faa2c480-480c-11ea-8f41-c6a8e04b8d6e.png)

When launching this testcase alone, this works perfectly;

But when bundling 10+ similar testcases in a campaign, then launch it, the filtering isn't working as expected

I'm still filtering to get a single event (with key `cerberus91091964`) but I get another random key
![image](https://user-images.githubusercontent.com/30227758/73835887-81a46c80-480e-11ea-9efb-5018f200d9a4.png)

If I increase the number of event to wait for, I get all the events and the filtering... well isn't filtering correctly 
![image](https://user-images.githubusercontent.com/30227758/73836056-c3cdae00-480e-11ea-89c2-c976c77e6dd6.png)

I'm sure this comes from lot of executions in parrallel which cause an high amount of event during a short timeframe

Thanks

**Comment by vertigo17** [comment]
Looks like the filter is not correctly filtering.
Why don't you put 
the FilterPath to something like $..header.technicalHeader.userId
the Value to cerberusXXXXXXXXX 
?

**Comment by Nouxx** [comment]
Ok MY BAD :

The problem was my jsonpath : 

`$..header[?(@.technicalHeader[?(@.userId == 'cerberus%system.EXECUTIONID%')])].functionalHeader.businessEventSubType`

should be

`$..header[?(@.technicalHeader.userId == 'cerberus%system.EXECUTIONID%')].functionalHeader.businessEventSubType`

since the nested condition aren't working on jsonpath : https://github.com/json-path/JsonPath/issues/591

Topic closed, I'll add this in the doc
