### ISSUE TITLE
Access Service Call File from TestCase

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#2088]
Hello, 

it would be nice to have the possibility to access the "Service Call" Json file so we can get some information from Response Headers such as : 
- Header Location
- Header Content-Type
- Set-Cookie

I have thought of 2 possibilities for this : 

- The first could be a "switch focus" from the "Response Body" To the "Service Call"  (next to the ServiceCall Action)

- The creation of system variables (%system.lastServiceLocation% / %system.lastServiceCookies% / %system.lastServiceContent-Type%. This option seems more sensitive from technological changes.

**Comment by vertigo17** [comment]
I prefer we switch current content to JSON Service Call structure allowing all controls on requests and response.

**Comment by vertigo17** [comment]
fixed with https://github.com/cerberustesting/cerberus-source/commit/0c85669acd19b2bd518b59085c7e305ff6741b0e
Will be inside 4.9
