### ISSUE TITLE
Impossible d'exécuter un test sur un device réel , pouvez vous m'aider 

### ISSUE THREAD

**Issue by Hamdi999** [cerberustesting/cerberus-source#2090]
cerberus 4.3
![image](https://user-images.githubusercontent.com/53051368/74048286-39ce4280-49d2-11ea-97d9-d1d32d1595ca.png)
---->  pas de log  sur appium
The test case failed to be executed. More lickely due to an error in the test or in Cerberus configuration. The test case failed to be executed. Could not start Robot Server. org.openqa.selenium.WebDriverException: Connection refused (Connection refused) Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z' System info: host: 'a29111f4333a', ip: '172.18.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1062.el7.x86_64', java.version: '1.8.0_212' Driver info: driver.version: AndroidDriver. Exception: org.cerberus.exception.CerberusException: The test case failed to be executed. Could not start Robot Server. org.openqa.selenium.WebDriverException: Connection refused (Connection refused) Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z' System info: host: 'a29111f4333a', ip: '172.18.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1062.el7.x86_64', java.version: '1.8.0_212' Driver info: driver.version: AndroidDriver.. org.cerberus.exception.CerberusException: The test case failed to be executed. Could not start Robot Server. org.openqa.selenium.WebDriverException: Connection refused (Connection refused) Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z' System info: host: 'a29111f4333a', ip: '172.18.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1062.el7.x86_64', java.version: '1.8.0_212' Driver info: driver.version: AndroidDriver.. org.openqa.selenium.WebDriverException: Connection refused (Connection refused) Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z' System info: host: 'a29111f4333a', ip: '172.18.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1062.el7.x86_64', java.version: '1.8.0_212' Driver info: driver.version: AndroidDriver

MERCI

**Comment by Nouxx** [comment]
Hello,

Il semble que Cerberus ne peux pas joindre le serveur Appium

Avez-vous plus de détails le concernant ? 
À quoi correspond `FIG LA1@0.0.0.0` ?

**Comment by vertigo17** [comment]
I guess issue is no longuer relevent.
