### ISSUE TITLE
Deeplink on Android devices

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#2092]
Hello,

Would it be possible to add a new action to cover the opening of deeplinks?
http://appium.io/docs/en/commands/mobile-command/
![image](https://user-images.githubusercontent.com/16339891/74459380-1cdab900-4e83-11ea-8f1c-8535667c8c2f.png)

Best Regards

**Comment by vertigo17** [comment]
Fixed with last comit ;-)
