### ISSUE TITLE
Issue with systems from ReadMyUser servlet

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2097]
Hello,

Selecting this systems from the Cerberus GUI
![image](https://user-images.githubusercontent.com/30227758/74732651-9f2bfa00-5242-11ea-8f59-5d7e443d01c7.png)
doesn't seem to be retrieved correctly in /ReadMyUser

https://qa.cerberus-testing.org/ReadMyUser

![image](https://user-images.githubusercontent.com/30227758/74732786-dc908780-5242-11ea-977b-e19bdff73116.png)

Are we supposed to use this endpoint ?
Thanks !

**Comment by vertigo17** [comment]
I beleive noux has administrator role. 
If so, when administrator, all system can be access. So this is normal that all system are listed.

**Comment by Nouxx** [comment]
Yes indeed, I didn’t remember, thanks !
