### ISSUE TITLE
Remove execution from report (only for manual execution)

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2099]
Hello,

What do you think of being able to remove an execution from a tag (only for manual execution) ?

This feature should be accessible from the report by tag page

Thanks

**Comment by vertigo17** [comment]
That can be done by changing the tag of the execution to another or empty value.

**Comment by vertigo17** [comment]
Hello @Nouxx is the issue still relevant ?
What would be the use case if done from the ReportByTag Page (Using the checkbox) ?
