### ISSUE TITLE
API should return the full maxTestCase value

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2100]
Hello,

Currently, a call to https://qa.cerberus-testing.org/ReadTestCase?test=benoit&getMaxTC=true returns

```
{
"messageType": "OK",
"maxTestCase": 4,
"message": "%ITEM% - %OPERATION% was finished with success!",
"sEcho": 0
}
```

Can't we just return the full `'0004A'` string? I believe the rule of adding `0` and `A` should belongs in the back

Thanks

**Comment by vertigo17** [comment]
service now return

```
{
"messageType": "OK",
"nextAvailableTestcaseId": "0001A",
"message": "%ITEM% - %OPERATION% was finished with success!",
"sEcho": 0
}
```
