### ISSUE TITLE
Change 'Y' / 'N' string fields to boolean

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2104]
Hello,

I know this is a touchy topic... but I'd like to point it out anyway :

for the testcase object, some fields are string type (e.g. `activeQA`) with the value that can be `"Y"` or `"N"`.

Handling this type in the front (cerberus-angular repo) makes us add extra steps to convert it to `boolean`, then converts it back to `string`

The Angular model is easy to understand, develop & maintain with a efficient syntax, and in this approach, a string type field should be bind to a `<input type="text">` since it's text type.
The Activation fields are currently basic **Yes** or **No** choice, so it'll work converting them in boolean

It's no big deal as well and we can totally work this around with the extra convertion, I'm just asking for your thought 

Thanks !

**Comment by vertigo17** [comment]
Please list the fields as some could safely move to boolean but some introduce risk of having a third option.
Ex : the endCampaign notification started by Y / N and now is Y / N / CIOK
Problem of moving to boolean is that when a 3rd option is necessary to add the impact could be big or model more complex.

Let's review all each of them.

**Comment by Nouxx** [comment]
In the testcase I can think of these ones :

Testcase : 
- active
- activeQA
- activeUAT
- activePROD

Step : 
- useStep
- forceExe
- inLibrary

Action : 
- forceExeStatus? (I'm not sure how this one is managed)

Control : 
- fatal

**Comment by Nouxx** [comment]
Also, for test case dependencies : 
 - active

**Comment by Nouxx** [comment]
More changes mentionned in #2124

**Comment by Nouxx** [comment]
Latest list of fields :

Testcase : 
- [ ] active
- [ ] activeQA
- [ ] activeUAT
- [ ] activePROD

Testcase dependency : 
- [ ] active

Step : 
- [ ] useStep (new title : _isUsedStep_)
- [ ] forceExe (new title : _isExecutionForced_)
- [ ] inLibrary (new title : _isLibraryStep_)

Action : 
- [ ] forceExeStatus? (new title : _isFatal_)

Control : 
- [ ] fatal (new title : _isFatal_)

**Comment by MorganLmd** [comment]
TNR verify testcase is not executed id test is not active (1 test folder !isActive with & 1 testcase)

**Comment by MorganLmd** [comment]
New issues to follow step/action/control refactoring:
#2179 for Step
#2180 for Action
#2181 for Control
