### ISSUE TITLE
Cannot change robot configurations

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#2110]
Hi,

since last cerberus update every change we try to make on robots configurations stays "processing..." and changes are not made.

![image](https://user-images.githubusercontent.com/14328346/76642517-443ca880-654b-11ea-92a5-788f8eb6b978.png)

Can you please take a look?

Cerberus4.6-SNAPSHOT-1482

Thanks

**Comment by Nouxx** [comment]
Hi,

Problem has been already notified, a fix is on its way :) 

Sorry for the inconvenience!
