### ISSUE TITLE
[REG] Export test case not working since 4.5

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#2112]
Hello,

Since the last version 4.5, I,m not able to export test case, an error page is displayed after clicking on the button.

I reproduce this on two differents configurations.

**Comment by vertigo17** [comment]
A fix was already produced. 
It is available in snapshot version and will be in 4.6

**Comment by glassalle59** [comment]
Great, thanks !

**Comment by glassalle59** [comment]
@vertigo17 Where can i get the snapshot version ?

**Comment by vertigo17** [comment]
Snapshots are available here: 
http://vm.cerberus-testing.org/delivery/

BTW, I just produced a 4.6 release.
