### ISSUE TITLE
[BUG] Cannot add new property

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#2114]
Version : 4.6
Country are well configured

I cannot add property on my test case : the country fields are empty like this 

![image](https://user-images.githubusercontent.com/33724879/77111819-5c567100-69fe-11ea-9211-1dd932e4907d.png)

When I try to save new property, nothing happens and I have errors on logs 

_cerberus_1               | 2020-03-19 20:23:49 ERROR TestCaseCountryPropertiesDAO:920 - Unable to execute query : com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`cerberus`.`testcasecountryproperties`, CONSTRAINT `FK_testcasecountryproperties_01` FOREIGN KEY (`Test`, `TestCase`, `Country`) REFERENCES `testcasecountry` (`Test`, `TestCase`, `Country`) ON)
cerberus_1               | com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`cerberus`.`testcasecountryproperties`, CONSTRAINT `FK_testcasecountryproperties_01` FOREIGN KEY (`Test`, `TestCase`, `Country`) REFERENCES `testcasecountry` (`Test`, `TestCase`, `Country`) ON)
cerberus_1               | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
cerberus_1               | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~_

**Comment by vertigo17** [comment]
hello @glassalle59 , I cannot reproduce. Can you CTRL F5 on that screen and retest ?

**Comment by glassalle59** [comment]
I will test that when I come back to home. 
But I tried to relaunch container and still not work

**Comment by glassalle59** [comment]
It's working thank you :)
