### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by sarchkak** [cerberustesting/cerberus-source#2116]
Hello i'm following the documentation to install Cerberus on my Local machine.
I'm trying to install the docker 'cerberus-glassfish-mysql' composition but i get this error message during the deployement :
cerberus-as-glassfish_1  | remote failure: Error occurred during deployment: Exception while loading the app : java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: org.apache.catalina.LifecycleException: java.lang.ClassNotFoundException: org.joda.time.ReadableInstant. Please see server.log for more details.

Could you please help me with this issue ?

**Comment by vertigo17** [comment]
cerberus-glassfish-mysql is no longuer supported and not updated since 4.3 version.
I would suggest to use the tomcat version either cerberus-as-tomcat-keycloak or cerberus-as-tomcat depending if you want to use keycloak.

**Comment by sarchkak** [comment]
Thank you for the answer. Yes i tried with the tomcat version and the docker installation is working fine.
