### ISSUE TITLE
OpenApp and Close app are not supported for application type ‘IPA’.

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#2118]
I am not able to open app and close app for iOS application

Can you add theses features like for Android please ?

**Comment by vertigo17** [comment]
Hello @glassalle59 Any news and feedback on that issue ? Should be fixed with recent comits.

**Comment by vertigo17** [comment]
Hello @glassalle59 Any news and feedback on that issue ? Should be fixed with recent comits.

**Comment by vertigo17** [comment]
I close it.
Please reopen if still not working.
