### ISSUE TITLE
Not able to change / update params in Cerberus 4.2 (NullPointerException)

### ISSUE THREAD

**Issue by BenjaminDupont** [cerberustesting/cerberus-source#2120]
Version 4.2:  
Environnement : 
https://github.com/cerberustesting/cerberus-source/tree/master/docker/compositions/cerberus-glassfish-mysql      ( localhost )

Bonjour,
j'ai visiblement un problème lorsque j'essaye de faire tourner / exécuter les tests en local avec cette version. 
J'ai l'erreur suivante 
**Error occured when calling the service to run the testcase. Service answer did not have the expected format (missing 'RunID = '). Probably due to bad cerberus_url value. URL Called: 'http://localhost:8080//RunTestCaseV001'.**

en regardant dans les paramètres, impossible de les mettre à jour :/ 

Steps to reproduce : 
1° Installation docker version 4.2
2° connexion avec le profil admin (tous les rôles / groups sont ajoutés)
3° click sur l'onglet Administration / Paramètres 
4° changement de la clef_valeur pour le param : "cerberus_gui_url" par exemple  + bouton save 

Actual Result :  loader en continue + erreur 500 (nullpointer) 
Expected result : maj des paramètres dans l'onglet Administration / paramètres sans problème

un QA qui vous veut du bien 
Merci à vous

**Comment by BenjaminDupont** [comment]
<img width="960" alt="cerberus_error" src="https://user-images.githubusercontent.com/49677337/78142486-464ca580-742d-11ea-9330-5e0a6f484de0.PNG">

**Comment by BenjaminDupont** [comment]
<img width="959" alt="cerberus_loader" src="https://user-images.githubusercontent.com/49677337/78142786-aa6f6980-742d-11ea-9b39-30faecd432a5.PNG">

**Comment by BenjaminDupont** [comment]
<img width="960" alt="update_param_cerberus_500" src="https://user-images.githubusercontent.com/49677337/78142914-d25ecd00-742d-11ea-8a38-a2e2a9b9523a.PNG">

**Comment by vertigo17** [comment]
Merci pour le ticket (et bravo pour sa redaction ;-)).
Le probleme a été identifié et corrigé à partir de la 4.3
https://github.com/cerberustesting/cerberus-source/releases/tag/cerberus-testing-4.3
Il faut monter de version et si tu peux pas tout de suite le faire, mettre à jour le parametre en bdd. (la table est parameter)
