### ISSUE TITLE
[BUG] A tap is performed when it shouldn't

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#2121]
Cerberus 4.6
Tested on Appium 1.17 / 1.16

I have a test whivh just tap on the burger menu on top right corner. He well tap on the button.
However, it always perform a second tap on the first burger submenu when it should't

I have the same test on other automation tools (with same appium version) and its worked

**My test**

![image](https://user-images.githubusercontent.com/33724879/78151349-83ea0800-7406-11ea-8297-e178730f6f08.png)

**Burger menu**

![image](https://user-images.githubusercontent.com/33724879/78151147-42595d00-7406-11ea-8a70-12054e7c8d20.png)

It click on "Call VCC" when it shouldn't

**Log appium**

[HTTP] <-- GET /wd/hub/session/17692794-7189-4487-9a78-800290c19da8 200 2 ms - 3667
[HTTP] 
[HTTP] --> POST /wd/hub/session/17692794-7189-4487-9a78-800290c19da8/element
[HTTP] {"using":"xpath","value":"//*[@label='ic menu']"}
[debug] [W3C (17692794)] Calling AppiumDriver.findElement() with args: ["xpath","//*[@label='ic menu']","17692794-7189-4487-9a78-800290c19da8"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8001/session/BFCC9CD1-951E-4683-9418-A6333026AB8A/element] with body: {"using":"xpath","value":"//*[@label='ic menu']"}
[debug] [WD Proxy] Got response with status 200: {"value":{"ELEMENT":"0F000000-0000-0000-FD02-000000000000","element-6066-11e4-a52e-4f735466cecf":"0F000000-0000-0000-FD02-000000000000"},"sessionId":"BFCC9CD1-951E-4683-9418-A6333026AB8A"}
[debug] [W3C (17692794)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"0F000000-0000-0000-FD02-000000000000","ELEMENT":"0F000000-0000-0000-FD02-000000000000"}
[HTTP] <-- POST /wd/hub/session/17692794-7189-4487-9a78-800290c19da8/element 200 475 ms - 137
[HTTP] 
[HTTP] --> POST /wd/hub/session/17692794-7189-4487-9a78-800290c19da8/element
[HTTP] {"using":"xpath","value":"//*[@label='ic menu']"}
[debug] [W3C (17692794)] Calling AppiumDriver.findElement() with args: ["xpath","//*[@label='ic menu']","17692794-7189-4487-9a78-800290c19da8"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:8001/session/BFCC9CD1-951E-4683-9418-A6333026AB8A/element] with body: {"using":"xpath","value":"//*[@label='ic menu']"}
[debug] [WD Proxy] Got response with status 200: {"value":{"ELEMENT":"0F000000-0000-0000-FD02-000000000000","element-6066-11e4-a52e-4f735466cecf":"0F000000-0000-0000-FD02-000000000000"},"sessionId":"BFCC9CD1-951E-4683-9418-A6333026AB8A"}
[debug] [W3C (17692794)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"0F000000-0000-0000-FD02-000000000000","ELEMENT":"0F000000-0000-0000-FD02-000000000000"}
[HTTP] <-- POST /wd/hub/session/17692794-7189-4487-9a78-800290c19da8/element 200 425 ms - 137
[HTTP] 
[HTTP] --> POST /wd/hub/session/17692794-7189-4487-9a78-800290c19da8/touch/perform
[HTTP] {"actions":[{"action":"tap","options":{"element":"0F000000-0000-0000-FD02-000000000000"}}]}
[debug] [W3C (17692794)] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"element":"0F000000-0000-0000-FD02-000000000000"}}],"17692794-7189-4487-9a78-800290c19da8"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: tap(options={"element":"0F000000-0000-0000-FD02-000000000000"})
[debug] [WD Proxy] Proxying [POST /wda/touch/perform] to [POST http://127.0.0.1:8001/session/BFCC9CD1-951E-4683-9418-A6333026AB8A/wda/touch/perform] with body: {"actions":[{"action":"tap","options":{"element":"0F000000-0000-0000-FD02-000000000000"}}]}
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"BFCC9CD1-951E-4683-9418-A6333026AB8A"}
[debug] [W3C (17692794)] Responding to client with driver.performTouch() result: null

**Comment by glassalle59** [comment]
[](url)

**Comment by glassalle59** [comment]
[](url)

**Comment by glassalle59** [comment]
I just found the issue ...

https://discuss.appium.io/t/issue-at-clicking-on-action-sheet-in-ios/24875/8

It is because of AUTO_ACCEPT_ALERTS on true on the robot ...

So if there is a burger menu on the app, it is not possible to use this capability :(

I not delete the issue to helps others which have the same problem

**Comment by vertigo17** [comment]
Still I will close it as it is linked to Appium.
