### ISSUE TITLE
/ReadTestCaseStep modification

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2122]
Hello,

Calling this servlet returns: 

```
{
"messageType": "OK",
"tcsActionList": [],
"step": {},
"tcsActionControlList": [],
"message": "%ITEM% - %OPERATION% was finished with success!"
}
```
Example: `https://qa.cerberus-testing.org/ReadTestCaseStep?test=GUI%20%3A%20Data&testcase=0000A&step=1`

Why the actions and controls are in different object, shouldn't we have a single (and full) step item?

Thanks

**Comment by vertigo17** [comment]
Not sure that servlet is still used.
For me we should remove it and replace by the TestCase one as accessing only the steps make no sense.
Did I miss somehting ?

**Comment by Nouxx** [comment]
It is used when fetching library steps for a system because /GetStepInLibrary ([example call](https://qa.cerberus-testing.org/GetStepInLibrary?system=CERBERUS)) doens't return all the information for a step, which make sense if the user is not adding in the test case

**Comment by vertigo17** [comment]
Yes but what is the use case ?
If we want the steps as part of a testcase, we should use ReadTestCase and have steps inside testcase correctly structured.
I beleive the use case here is when I want to add a new step inside a testcase and need to get all usedStep to pick the one I want.
If so, it make sens to have a specific servlet and I beleive this is the purpose of GetStepInLibrary  but in that case what is the usecase of the ReadTestCaseStep usage ?

**Comment by Nouxx** [comment]
Currently, when you want to add a new library step to a test case: 

- you fetch all the available steps (for a system) => /GetStepInLibrary
 the returned information are basic (no step control, only descriptions)

- for every selected library step, you fetch all the information (actions, controls, conditionOper...) of that step => /ReadTestCaseStep

This behavior isn't wrong, since it only load the necessary data, It would be less efficient to fetch all the step content for a step we are eventually not adding

**Comment by Nouxx** [comment]
Hi, 

Can we agree on the final structure of this servlet response? It has changed since I work with this endpoint but the response structure is still confusing in my opinion : 

https://qa.cerberus-testing.org/ReadTestCaseStep?test=DataSet%20%3A%20CerberusSpecificTestCase&testcase=STEPLIB1&step=1

```
{
    "messageType": "OK",
    "tcsActions": [
        {
            "conditionVal3": "",
            "conditionVal2": "",
            "controls": [],
            "value2": "",
            "conditionVal1": "",
            "test": "DataSet : CerberusSpecificTestCase",
            "value1": "100",
            "screenshotFilename": "",
            "value3": "",
            "stepId": 1,
            "description": "Wait of Step1",
            "isFatal": "",
            "sort": 1,
            "testcase": "STEPLIB1",
            "conditionOperator": "always",
            "actionId": 1,
            "action": "wait",
            "objType": "action"
        }
    ],
    "tcsActionControls": [
        {
            "conditionVal3": "",
            "conditionVal2": "",
            "value2": "a",
            "conditionVal1": "",
            "test": "DataSet : CerberusSpecificTestCase",
            "value1": "a",
            "screenshotFilename": "",
            "value3": "",
            "stepId": 1,
            "description": "exmaple of control",
            "isFatal": "N",
            "control": "verifyStringEqual",
            "sort": 1,
            "controlId": 0,
            "testcase": "STEPLIB1",
            "conditionOperator": "always",
            "actionId": 1
        }
    ],
    "step": {
        "isLibraryStep": "Y",
        "conditionVal3": "",
        "isStepInUseByOtherTestCase": false,
        "isExecutionForced": "N",
        "conditionVal2": "",
        "useStepStepSort": 0,
        "conditionVal1": "",
        "test": "DataSet : CerberusSpecificTestCase",
        "usrModif": "bdumont",
        "stepId": 1,
        "description": "STEP1",
        "libraryStepTestCase": "",
        "sort": 1,
        "testcase": "STEPLIB1",
        "usrCreated": "",
        "initialStep": 0,
        "dateCreated": "",
        "loop": "onceIfConditionTrue",
        "conditionOperator": "always",
        "libraryStepTest": "",
        "dateModif": "2019-06-25 22:01:36.0",
        "isUsedStep": "N",
        "actions": [],
        "libraryStepStepId": 0
    },
    "message": "%ITEM% - %OPERATION% was finished with success!"
}
```
