### ISSUE TITLE
Step, Action and Control field modification

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2124]
Hello,

As agreed together, here are the modification to do : 

**Step**
step > stepId
useStep > isUsedStep (_boolean_)
inLibrary > isLibraryStep (_boolean_)
useStepStep > useStepStepId
forceExe > isExecutionForced (_boolean_)
useStepTest > libraryStepTest (etc.)

**Action**
sequence> actionId
step > stepId
object > value1
property > value2
forceExeStatus > isFatal (_boolean_)

**Control**
step > stepId
sequence > actionId
controlSequence > controlId
fatal > isFatal (_boolean_)

Modification should be done as well to /ReadTestCase

**Comment by Nouxx** [comment]
linked with #2123

**Comment by Nouxx** [comment]
Example of a new Step object: 
```
{
    "sort": 1,
    "stepId": 1,
    "description": "S1",
    "test": "benoit",
    "testCase": "0002A",
    "isExecutionForced": false,
    "loop": "onceIfConditionTrue",
    "conditionOper": "always",
    "conditionVal1": "",
    "conditionVal2": "",
    "conditionVal3": "",
    "isUsedStep": false,
    "isLibraryStep": false,
    "libraryStepTest": "",
    "libraryStepTestCase": "",
    "libraryStepStepId": 0,
    "usrCreated": "",
    "usrModif": "",
    "dateCreated": "",
    "dateModif": "Jan 1, 1970 1:01:01 AM",
    "actions": [],
    "initialStep": 0,
    "isStepInUseByOtherTestCase": false
}
```

**Comment by Nouxx** [comment]
Example of a new Action object: 

```
{
    "sort": 1,
    "stepId": 2,
    "actionId": 4,
    "description": "click search icon",
    "action": "click",
    "value1": "id=com.ocito.laredoute:id/iv_search_glass",
    "value2": "",
    "value3": "",
    "conditionOper": "always",
    "conditionVal1": "",
    "conditionVal2": "",
    "conditionVal3": "",
    "fatal": true,
    "screenshotFilename": "",
    "controls": [],
    "test": "ENGINE : Action",
    "testCase": "0017B"
}
```

**Comment by Nouxx** [comment]
Example of a new Control Object:

```
{
    "sort": 1,
    "stepId": 2,
    "actionId": 11,
    "controlId": 1,
    "description": "verify we are on PLP",
    "control": "verifyElementPresent",
    "value1": "id=com.ocito.laredoute:id/tv_filter_button",
    "value2": "val2",
    "value3": "",
    "conditionOper": "always",
    "conditionVal1": "",
    "conditionVal2": "",
    "conditionVal3": "",
    "fatal": true,
    "screenshotFilename": "",
    "test": "ENGINE : Action",
    "testCase": "0017B"
}
```

**Comment by MorganLmd** [comment]
{
    "sort": 1,
    "stepId": 1,
    "description": "S1",
    "isExecutionForced": false,
    "loop": "onceIfConditionTrue",
    "conditionOper": "always", > **conditionOperator**
    "conditionVal1": "",
    "conditionVal2": "",
    "conditionVal3": "",
    "isUsedStep": false, > **isUsingStep**
    "isLibraryStep": false,
    "libraryStepTest": "",
    "libraryStepTestCase": "", > **libraryStepTestcase**
    "libraryStepStepId": 0,
    "usrCreated": "", 
    "usrModif": "",
    "dateCreated": "",
    "dateModif": "Jan 1, 1970 1:01:01 AM",
    "actions": [],
    "test": "benoit",
    "testCase": "0002A", > **testcase**
    "initialStep": 0,
    "isStepInUseByOtherTestCase": false > **isStepInUseByOtherTestcase**
}

{
    "sort": 1,
    "stepId": 2,
    "actionId": 4,
    "description": "click search icon",
    "action": "click",
    "value1": "id=com.ocito.laredoute:id/iv_search_glass",
    "value2": "",
    "value3": "",
    "conditionOper": "always", > **conditionOperator**
    "conditionVal1": "",
    "conditionVal2": "",
    "conditionVal3": "",
    "isFatal": true,
    "screenshotFilename": "",
    "controls": [],
    "test": "ENGINE : Action",
    "testCase": "0017B" > **testcase**

Ajout bdd ------------
    **"usrCreated": "", 
    "usrModif": "",
    "dateCreated": "", ** 
    last_modified > **"dateModif":, TIMESTAMP**
}

{
    "sort": 1,
    "stepId": 2,
    "actionId": 11,
    "controlId": 1,
    "description": "verify we are on PLP",
    "control": "verifyElementPresent",
    "value1": "id=com.ocito.laredoute:id/tv_filter_button",
    "value2": "val2",
    "value3": "",
    "conditionOper": "always", > **conditionOperator**
    "conditionVal1": "",
    "conditionVal2": "",
    "conditionVal3": "",
    "isFatal": true,
    "screenshotFilename": "",
    "test": "ENGINE : Action",
    "testCase": "0017B" > **testcase**

Ajout bdd ------------
    **"usrCreated": "", 
    "usrModif": "",
    "dateCreated": "", ** 
    last_modified > **"dateModif":, TIMESTAMP**
}

**Comment by MorganLmd** [comment]
New issues to follow step/action/control refactoring:
#2179 for Step
#2180 for Action
#2181 for Control
