### ISSUE TITLE
Problem execution test

### ISSUE THREAD

**Issue by liquidparker** [cerberustesting/cerberus-source#2125]
Hello,
I deploy with docker latest version of cerberus-tomcat-mysql with the command docker-compose-with-selenium.yml . 
Its running well, but when i want launch a test, i have got this error:
"12 - Examples - 0001A - FR - PROD - FA
Search for Cerberus Website
The test case failed to be executed. More lickely due to an error in the test or in Cerberus configuration. Could not contact Robot server on 192.168.99.100 using port 5555. Possible causes are invalid address of the remote server or browser start-up failure. org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: '50a8e0fc75c2', ip: '172.18.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.154-boot2docker', java.version: '1.8.0_212' Driver info: driver.version: RemoteWebDriver"

**NEws**: I launch on windows selenium and this time i have a chrome-windows opening but get an error null pointer exception 

**ajout info**: 
_type: Gui
_execution simple
_ ip docker: 192.168.99.100 (i try with different port but nothing change)
_ Cerberus Version : 4.6-1482

Can you help me solve the problem plz?

Thx,
Julien

**Comment by vertigo17** [comment]
If you use [docker-compose-with-selenium.yml](https://github.com/cerberustesting/cerberus-source/blob/master/docker/compositions/cerberus-tomcat-mysql/docker-compose-with-selenium.yml) you should run the tests against a correct IP (not localhost) and exposed port : 14444.
I guess 192.168.99.100 : 14444 in your case.
Running against host : selenium-hub on port 4444 should also work.

About the null pointer exception, can you please provide the tomcat logs that should provide a stack trace.

**Comment by liquidparker** [comment]
[catalina_out.txt](https://github.com/cerberustesting/cerberus-source/files/4502320/catalina_out.txt)

The java null pointer i get is when i use ur IP above, i join the catalina.out Logs.
You can see 2 execution, the 2nd one is after i change cerberus-url in parameter.

Thx for help

**Comment by liquidparker** [comment]
[catalina.2020-04-20.log](https://github.com/cerberustesting/cerberus-source/files/4502403/catalina.2020-04-20.log)
[Robot_server_caps.txt](https://github.com/cerberustesting/cerberus-source/files/4502405/Robot_server_caps.txt)
![Robot_host_port](https://user-images.githubusercontent.com/40383408/79735320-64087e80-82f8-11ea-87a4-0c0911a2f90a.jpg)
I post rest of information: log catalina of the day, log of robot and robot host (see join)

Thx

**Comment by liquidparker** [comment]
Problem is solve when i launch selenium separatly on my windows and not in docker

**Comment by vertigo17** [comment]
That must be linked to issue on selenium inside docker. Could be a lack of memory on Selenium docker.
