### ISSUE TITLE
Timeout issue during a new build revision

### ISSUE THREAD

**Issue by ntennich** [cerberustesting/cerberus-source#2134]
Hello Benoit,
Could you please check this timeout error on Cerberus during new bluidn on preprod?

The impact this issue is having is basically a delay of 15-30 minutes in the daily release process when deploying to Preprod. We have a few minutes delay to enable the new cerberus tests version for each country which must be done before NRT campaign can be started. So the issue is not blocking but it would be good to have the issue checked out to avoid unnecessary delays with NRT campaign. If it helps we started encountering this issue from 12th May, we did not have this issue before.

<img width="576" alt="Error" src="https://user-images.githubusercontent.com/35033728/83775127-e372c700-a686-11ea-92ce-f60f1bdf6edb.png">

thanks in advance, 
Nadia.

**Comment by Nouxx** [comment]
Hi,

12th of May corresponds to our upgrade to 4.7(release) if it can help

**Comment by vitoo** [comment]
This looks resolved
