### ISSUE TITLE
Distorted reports by abnormal QE status (then changes to FA)

### ISSUE THREAD

**Issue by paulinedessingue-lm** [cerberustesting/cerberus-source#2140]
Hi,

We are using Cerberus 4.7 and we have noticed QE statuses in our execution reports.

For example, we are launching a test campaign, the tests are pending. Several tests fall into QE status with the error message : `Error occured when calling the service to run the testcase. Service answer did not have the expected format (missing 'RunID = '). Probably due to bad cerberus_url value. URL Called: 'https://our-cerberus-url/RunTestCaseV001'`. 
When we consult the report a little later, these tests in QE are passed in FA with a real error message of the type: `Failed to wait because could not find element ... `.
The `cerberus_url` parameter is however well filled.

**Report seems distorted and users don't understand what's going on.**
Before that, we were using version 3.9 and have never encountered this kind of problem.

Below, the report just after the end of test executions and the same report an hour after :
![campaign-status-QE](https://user-images.githubusercontent.com/54071709/86139450-09598300-baf0-11ea-85c6-71c12cda8345.png)

**Comment by vertigo17** [comment]
Looks like there is a component between Cerberus and the URL 'https://our-cerberus-url/RunTestCaseV001' that either introduce a limitation or add a retry mecanism that could result some weird behaviour.
Did you take the oportunity of the version upgrade to change some infrastructure components ? Moved to Tomcat ? Adding Nginx in front of Tomcat ot adding a firewall of proxy in between ?

Can you check the logs ?
When that error occurs, the log should report both the complete URL called but also the result from the service call that could give you a clue on what component realy provide the answer to the service.

**Comment by paulinedessingue-lm** [comment]
Yes, we were on glassfish and we moved to tomcat. But we haven't changed anything else.
In the logs, I can see the following message :

> 2020-07-01 07:29:56 ERROR ExecutionQueueWorkerThread:294 - Bad answer format (could not find 'RunID = '). URL Called: https://our-cerberus-url/RunTestCaseV001?IdFromQueue=1904084&seleniumLog=0&Test=OAA+Chape&retries=3&executor=10113472&manualExecution=A&Country=OAA&Tag=OAP_ALL%40prod%40desktop%4020200701-072926&robot=Hub-selenium-3-141&timeout=3000&outputformat=verbose-txt&pageSource=1&Environment=prod&verbose=0&TestCase=0001A&screenshot=1&synchroneous=Y&robotexecutor=MAIN 

> 2020-07-01 07:29:56 ERROR ExecutionQueueWorkerThread:295 - Bad answer format (could not find 'RunID = '). Answer: < html>< body>< h1>504 Gateway Time-out</ h1>The server didn't respond in time.</ body></ html>

`https://our-cerberus-url` is the url of our openshift pod. And it's the same as that filled in the `cerberus_url` parameter.

Thanks for your help !

**Comment by vertigo17** [comment]
URL is clearly corect. If it was not all executions would end in QE....
The 2nd line of log is showing the answer received by Ceberus:
< html>< body>< h1>504 Gateway Time-out</ h1>The server didn't respond in time.</ body></ html>
It clearly does not come from Cerberus.
Next step is to find this gateway and correct its configuration in order to increase de response timeout.
Timeout needs to be at least as hight as the longest execution duration. I would suggest something around 1 hour in order to be safe.

**Comment by vertigo17** [comment]
Can you provide a feedback on the ticket ? Or close it if issue is fixed ?

**Comment by paulinedessingue-lm** [comment]
Indeed, the timeout comes from our infrastructure. I close this issue !
