### ISSUE TITLE
Could not start Robot Server - Failed to set capability on the browser 

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#2143]
Hi,

we're implementing test cases to use multibrowser on browserstack but we're facing some issues.

We need to run test cases for Yandex browser and after define the robot when we run the test case we get "Could not start Robot Server. Failed to set capability on the browser 'Yandex' due to Not supported Browser : Yandex.".
We have the same sittuation for Edge browser.

We have the following capabilities on the robot:
![image](https://user-images.githubusercontent.com/14328346/86458930-f2987380-bd1d-11ea-8247-270d48b43b1c.png)

![image](https://user-images.githubusercontent.com/14328346/86458955-faf0ae80-bd1d-11ea-9eda-0aeea95057a4.png)

Error:
![image](https://user-images.githubusercontent.com/14328346/86459066-26739900-bd1e-11ea-8b1b-85491dda8ec9.png)

If we don't define the "browser" on robot:
![image](https://user-images.githubusercontent.com/14328346/86459127-3d19f000-bd1e-11ea-9960-72e2708eb017.png)

![image](https://user-images.githubusercontent.com/14328346/86459183-5622a100-bd1e-11ea-9eb6-905aae9c3537.png)

when we execute the test case we get the following error:
![image](https://user-images.githubusercontent.com/14328346/86460047-a0585200-bd1f-11ea-9c3f-6fa715c8833a.png)

looking at robot capabilities on test case it seems that cerberus is trying to run with firefox profile
![image](https://user-images.githubusercontent.com/14328346/86460137-bfef7a80-bd1f-11ea-8e01-475f539257f1.png)

Can you please help us? 
What are we missing on cerberus side? 

Cerberus4.8-SNAPSHOT-1491

Thanks.

**Comment by vertigo17** [comment]
I added support on edge but looks like BrowserStack does not support yet Yandex in an automated way.

I tryed with 
                    capabilities = new DesiredCapabilities();
                    capabilities.setCapability("browser", "Yandex");
                    capabilities.setCapability("browser_version", "14.12");
-->
 "FinalCapabilities": {
    "browser": ["Yandex"],
    "browser_version": ["14.12"],
    "build": ["bdumont.20200620-221811"],
    "name": ["Exe : 232216"],
    "platformName": ["WINDOWS"],
    "project": ["redoute"]
  }

and got the following error from BrowserStack:

Could not start Robot Server. org.openqa.selenium.WebDriverException: Browser not permitted: {"build"=>"bdumont.20200620-221811", "browser"=>"Yandex", "name"=>"Exe : 232216", "project"=>"redoute", "browser_version"=>"14.12", "platformName"=>"WINDOWS", "acceptSslCert"=>false, "detected_language"=>"selenium/3.141.59 (java unix)", "new_bucketing"=>true, "browserName"=>"Yandex", "browser_name"=>"Yandex", "browserVersion"=>"14.12", "version"=>"14.12", "sessionName"=>"Exe : 232216", "buildName"=>"bdumont.20200620-221811", "projectName"=>"redoute", "realMobile"=>true, "browserstack.seleniumLogs"=>true, "platform"=>"WINDOWS", "browserstack.appiumLogs"=>true} (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 703 milliseconds Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: 'XPS13', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.3.0-61-generic', java.version: '11.0.5' Driver info: driver.version: RemoteWebDriver.

Indeed BrowserStack  documentation is not showing how to configure JAVA code for Yandex. Maybe you can open a ticket on theri side to see if this is targeted ?

https://www.browserstack.com/automate/java

**Comment by RobertoAbraul** [comment]
Hi,

I sent the question to browserstack team.
I will let you know when we have an answer.

Thanks.

**Comment by RobertoAbraul** [comment]
Hi @vertigo17 

Browserstack replied.
It seems that currently Yandex browser is not supported.

"Hi,

I reviewed your query and understand that you wish to test on the Yandex browser on BrowserStack, however, I would like to share that the Yandex browser is currently not supported on BrowserStack Automate. Hence you will be unable to run your tests on it on BrowserStack.

Having said that, I have also made a note of your query as a feature request and will be sure to notify you about any new developments in this regard.

Do let me know if you have any further queries, and I’ll be happy to assist you." 

If possible add support on opera too, since we have the same issue reported for Edge.
"Could not start Robot Server. Failed to set capability on the browser 'opera' due to Not supported Browser : opera."

Thanks.

**Comment by vertigo17** [comment]
OK. We will wait for BrowserStack to support it.
Opera is already supported with last comit. Please Test and confirm Opera and Edge are now working fine on BS.

**Comment by RobertoAbraul** [comment]
Hi @vertigo17 

tested on cerberus QA and for Edge we still have the same error.
"Could not start Robot Server. Failed to set capability on the browser 'Edge' due to Not supported Browser : Edge."

for opera seems to be ok, but I have to set browsername and browser on robot capabilities too, otherwise it returns error.
Do you know if this is expected?
![image](https://user-images.githubusercontent.com/14328346/86904846-2c47f080-c109-11ea-893a-eb7fd986c2ac.png)

Thanks.

**Comment by vertigo17** [comment]
For Edge : Looks like you played with private invariant.
The official list is below: (it is supposed to be **edge** and not **Edge**).
Please update the list correctly and avoid in the futur to play with private invariants.

![image](https://user-images.githubusercontent.com/5342048/86918145-8b682e00-c126-11ea-892a-11f437003964.png)

For Opera : Clearly, you are not supposed to feed the capability to have opera working. Can you provide the error message ?

**Comment by RobertoAbraul** [comment]
HI,

Thanks. Edge is now ok.
We'll avoid mess with private invariants in the future.

Opera, it's ok if we have the robot like this:
![image](https://user-images.githubusercontent.com/14328346/86921716-7fc73800-c123-11ea-97d7-13a8ab6537d8.png)

![image](https://user-images.githubusercontent.com/14328346/86921737-8655af80-c123-11ea-812a-e9f36a1ab757.png)

but if we remove browserName and browser from capabilities it returns the following error:

The test case failed to be executed. More lickely due to an error in the test or in Cerberus configuration. 
The test case failed to be executed. Could not start Robot Server. org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. 
Please check the server log for more details. Original error: OS/Browser combination invalid: {"browserstack.local"=>true, "operaOptions"=>{"args"=>[], "extensions"=>[]}, "browserstack.localIdentifier"=>"WebRun", "os"=>"OS X", "os_version"=>"Sierra", "browserName"=>"operablink", "platformName"=>"MAC", "version"=>"12.15", "acceptSslCert"=>false, "detected_language"=>"selenium/3.141.59 (java unix)", "new_bucketing"=>true, "browserstack.tunnel"=>true, "browserstack-tunnel"=>true, "browserstack.tunnelIdentifier"=>"WebRun", "browserstack-tunnelIdentifier"=>"WebRun", "osVersion"=>"Sierra", "browser"=>"operablink", "browser_name"=>"operablink", "browserVersion"=>"12.15", "browser_version"=>"12.15", "realMobile"=>true, "browserstack.seleniumLogs"=>true, "platform"=>"MAC", "browserstack.appiumLogs"=>true, "browserstack.finalTunnelFork"=>"XXXX-WebRun", "browserstack.forksUsed"=>false} 
(WARNING: The server did not provide any stacktrace information) 
Command duration or timeout: 695 milliseconds Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: 'cerb10vql.siege.red', ip: 'XXX.XXX.XXX.XXX', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-327.13.1.el7.x86_64', java.version: '1.8.0_152' Driver info: driver.version: IOSDriver Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: 'cerb10vql.siege.red', ip: '192.168.135.30', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-327.13.1.el7.x86_64', java.version: '1.8.0_152' Driver info: driver.version: IOSDriver.

Thanks.

**Comment by vertigo17** [comment]
I guess you mean that for Opera it is not working ;-).
I removed screen size management support for Opera as webdriver does not support it.
It should work now.
On Cerberus side:
![image](https://user-images.githubusercontent.com/5342048/130063124-e315a236-7976-4652-8cc0-3a79015e4c8d.png)

On BrowserStack side:
![image](https://user-images.githubusercontent.com/5342048/130063192-33ff4e50-bf4d-4389-b376-401f1175bddf.png)
