### ISSUE TITLE
User agent not set when running test case

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#2144]
Hi,

to avoid captcha on browserstack we are using user agents on each robot with "/**hash**" on the final of each user agent but for some browsers (Edge and IE) when running test cases user agent on robot is ignored and it runs the test case with a "default" user agent.

Example:
user agent set on robot Edge:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36 Edg/81.0.416.53/**hash**

![image](https://user-images.githubusercontent.com/14328346/86486312-d8c55380-bd52-11ea-9cd5-f48b5909d2b3.png)

user agent set when running test case:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36 Edg/81.0.416.53
![image](https://user-images.githubusercontent.com/14328346/86474105-0e117780-bd3a-11ea-9693-d617dd0e5bdf.png)

user agent set on robot IE:
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko/**hash**

![image](https://user-images.githubusercontent.com/14328346/86486363-ff838a00-bd52-11ea-8667-590683027796.png)

user agent when running test case:
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko
![image](https://user-images.githubusercontent.com/14328346/86474408-aa3b7e80-bd3a-11ea-8c7b-03596f4964c1.png)

It works fine for chrome and firefox robots.

![image](https://user-images.githubusercontent.com/14328346/86486417-204bdf80-bd53-11ea-9b51-3660f41da21e.png)

Do you have any ideia why this happens?
We don't find any solution for this.

Cerberus4.8-SNAPSHOT-1491

Thanks.

**Comment by vertigo17** [comment]
Unfortunatly I could not find any solution to force user agent for the following browsers:
IE, Edge, Safari
Seems that the only browsers that support that feature are:
Firefox, Chrome

For Opera, it could work but Browser Stack generate an error when I try to force profile on capabilities:

`org.openqa.selenium.WebDriverException: Could not start Browser / Emulator Reason: Unable to create directory path: {profileName: "foo",userAgent: "Mozilla\4.0 (compatible; MSIE 6.0; Windows NT 5.2; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022)\toto"} Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33' System info: host: '185-129-68-137', ip: '185.129.68.137', os.name: 'windows', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_181' Driver info: driver.version: OperaDriver (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 18.22 seconds Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: 'XPS13', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.3.0-62-generic', java.version: '11.0.5' Driver info: driver.version: RemoteWebDriver `

Maybe we could ask them if they have a way to force userAgent for IE, Edge, Safari and Opera ?

**Comment by RobertoAbraul** [comment]
Hi  @vertigo17 ,

unfortunately it seems that user agent cannot be set for IE, Edge, Safari and Opera.
The response from browserstack:

"Hi,
I reviewed multiple online resources and it seems like it is not possible to set the user agent for the browsers you mentioned (Opera, Safari, IE and Edge).

For Safari, this requires executing a system command which is not supported via Selenium. For IE, setting the user agent is not possible. Edge does not support setting the user agent either. I was unable to find sufficient documentation on setting the user agent for Opera.

https://tarunlalwani.com/post/selenium-change-user-agent-different-browsers/
https://stackoverflow.com/questions/51928758/web-driver-how-to-override-user-agent-for-microsoft-edge

I would like to share that Browserstack only supports running Selenium commands. In case you are able to set the user agent locally on your end by running an automated test on a Selenium grid, the same should also run on Browserstack.

That being said, do let me know if you have any further questions and I'll be happy to help."

Thanks.

**Comment by vertigo17** [comment]
I flag it as wontfix ;-(
