### ISSUE TITLE
Application Object value should allow more caracters

### ISSUE THREAD

**Issue by apistogram** [cerberustesting/cerberus-source#2145]
Hi there,

I am using Application object from Cerberus to manage UI object repository.
But actually the "value" text field limit is fixed to 200 caracters.

Can you modify this string field length to accept more caracters (just like an "Element path" from step's action?)

Best regards

**Comment by vertigo17** [comment]
That will be integrated inside 4.8
Limitation was only on the gui side so as a « dirty » workaround you can update directly on database or remove constrain on html layer side (using f12 and editing the code).
