### ISSUE TITLE
Token on Public API : Securing /AddToExecutionQueueV0003

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2149]
Hello,

We'd like to open our Cerberus instance on the web (to allow an external partner to use the test cases we implement as well as our Selenium infrastructure).

Our corporate security standards involves a penetration test and it might find that `/AddToExecutionQueueV0003` is a public servlet that can launch any tests.

Can we discuss about securing it? It might impact the Jenkins plugin as well

**Comment by vertigo17** [comment]
We may wait to get the list of API impacted before securing it.
We could do what has been done by /manageV001 adding a token to setup by admin users but we will also probably need to make it optional as it makes the use of the tool more complex.

**Comment by Nouxx** [comment]
The admin token might be the quickest and most easy to develop idea !

**Comment by vertigo17** [comment]
This is what I can propose grouped by public API :

/RunTestCase --> Rule 1a
/RunTestCaseV001 --> Rule 1b
/GetNumberOfExecutions --> Rule 1b
/ResultCI --> Rule 1a
/ResultCIV001 --> Rule 1a
/ResultCIV002 --> Rule 1a
/ResultCIV003 --> Rule 1a
/ResultCIV004 --> Rule 1b
/AddToExecutionQueue --> Rule 1a
/AddToExecutionQueueV001 --> Rule 1a
/AddToExecutionQueueV002 --> Rule 1a
/AddToExecutionQueueV003 --> Rule 1b

Rule 1a : API return error if cerberus_execution_token_enable = true
Rule 1b : API return error if cerberus_execution_token_enable = true and cerberus_execution_token not correct on the calls.
by default cerberus_execution_token_enable = false (no changed compared to today)

/NewRelease --> Rule 2
/NewBuildRevisionV000 --> Rule 2
/DisableEnvironmentV000 --> Rule 2
/NewEnvironmentEventV000 --> Rule 2
/GetTagExecutions --> Rule 2
/GetTestCasesV000 --> Rule 2

Rule 2 : API return error if cerberus_integration_token_enable = true and cerberus_integration_token not correct on the calls.
by default cerberus_integration_token_enable = false

/manageV001 --> Already secured with parameter cerberus_manage_token --

/ForgotPassword
/ForgotPasswordEmailConfirmation
/ChangeUserPassword
 --> Not secured as is useless when Keycloak activated and Cerberus should not be open without Keycloak

**Comment by Nouxx** [comment]
Great!

So the deprecated API (e.g. /AddToExecutionQueueV002) will not be usable if the token security is switched on? Why keeping them then?

**Comment by vertigo17** [comment]
To avoid to force people to move to the latest version of API if they don't need / want to secure the access to the API.

We will also need to create a 'private' version of the 'public' API that are used from the GUI.
This is to avoid putting the token visible from the GUI.

**Comment by vertigo17** [comment]
Finally, all Public API was secured using global apikey.
A parameter allow to disable that securisation and 5 apikey can be defined.
apikey must be sent in header request (it is no longer accepted as URL parameter)
All that is explained with curl command to use in documentation (chapter : Cerberus Public API).
It will be released in 4.11

**Comment by Nouxx** [comment]
Thanks a lot!
