### ISSUE TITLE
Problem when executing first test after install

### ISSUE THREAD

**Issue by Srein62** [cerberustesting/cerberus-source#2150]
Hello, 

I have installed cerberus (tomcat and mysql) with docker and i'm getting some trouble getting it worked.

When i use default robot, i get an error, here it is : 

The test case failed to be executed. More lickely due to an error in the test or in Cerberus configuration. Could not contact Robot server on 127.0.0.1 using port 4444. Possible causes are invalid address of the remote server or browser start-up failure. org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: '645c9a9d8f42', ip: '172.22.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-40-generic', java.version: '1.8.0_212' Driver info: driver.version: RemoteWebDriver

Here is my robot conf

![image](https://user-images.githubusercontent.com/16970464/87775490-78d8ad80-c826-11ea-8580-86a94e046c45.png)

I tried to look in the documentation but there's nothing about robot configuration.

I haven't change docker-compose or port / service name.

I have nothing when i try 127.0.0.1:4444 but i get the selenium grid console on 127.0.0.1:14444, so i tried to change the port but same error, even tried with firefox and chrome node (172.22.0.3:5555 and 172.22.0.2:5555)

Thanks for help

**Comment by vertigo17** [comment]
I beleive that all Cerberus, MySQL and selenium are inside docker.
Not sure thought if all of those docker are inside the same compose or individual containers.
You cannot use localhost or 127.0.0.1 for robot if Cerberus is inside a docker as it will try to reach the robot inside the same container and fail.
You can either use the name of the image inside the same compose or the host IP of your PC to secure request leave the container to reach the other one.

If the IP of your PC is 192.168.1.1 try to connect to 192.168.1.1:14444 and if it works, use it to configure Cerberus.

ex with the below config inside the same compose:

 # Selenium-related services
  selenium-hub:
    image: selenium/hub:latest
    expose:
      - "4444"
    ports:
      - "14444:4444"

You can use either
selenium-hub:4444
ip-of-your-pc:14444

localhost or 127.0.0.1 whatever port will never work

**Comment by Srein62** [comment]
Hello,

Thanks for the answer, i tried with both my ip and using the docker name, still the same error :( 


![image](https://user-images.githubusercontent.com/16970464/88400925-57009d00-cdc9-11ea-86bb-24f1db1bc29a.png)

When i try my ip on firefox i get 

![image](https://user-images.githubusercontent.com/16970464/88402010-ccb93880-cdca-11ea-8b0d-55ebc830946a.png)

And when i click selenium grid console looks to be good

When i go to http://10.0.2.15:14444/grid/register, here is what i have 

![image](https://user-images.githubusercontent.com/16970464/88402212-16098800-cdcb-11ea-9ccd-7da71268d972.png)

I don't know if that's normal or not, thank's for your help.

have a good day

**Comment by vertigo17** [comment]
Error is not the same ;-). It no longuer report that it cannot connect to robot host and port. 
Now it report that it cannot find the right capability. Seems that you asked for linux with firefox on version 28. 
I beleive that the docker contain linux with fitefox by I doubt version is 28 that is very old. 
Please remove the version number specified on robot and try again. 
That will let selenium choose the available version.

**Comment by Srein62** [comment]
My bad :(
Looks to be working, thanks! :)
