### ISSUE TITLE
Wait and Waitvanish specific timeout

### ISSUE THREAD

**Issue by sarchkak** [cerberustesting/cerberus-source#2153]
Hello,
Actually when i choose the action wait or waitvanish and the only parameter is an explicitWait or the element to wait (and the timeout is defined by the System timeout).
Is it possible to specify the timeout for this action?
The behavior i need to produce is wait for the element i'm giving you for at most 'Tiemout' ms.

**Comment by vertigo17** [comment]
If I understand right, you wan to specify the timeout at the action level ?

Today, timeout can be specify at various levels:
1/ Globally or by System using parameters cerberus_appium_wait_element or cerberus_selenium_wait_element
2/ For each execution using the timeout field (it can also be defined at campaign level)
![image](https://user-images.githubusercontent.com/5342048/87916149-5c7d8080-ca73-11ea-84e1-7cbfa4f71911.png)

Maybe we can add a second parameter for wait and waitVarnish action to specifically define the timeout at action level.

**Comment by sarchkak** [comment]
Yes, this is the expected behavior.

**Comment by Nouxx** [comment]
Hey,

I strongly agree with @sarchkak, having to increase my global timeout to the slowest element on my application. This have obviously a huge (and bad) impact on my test execution.

I think the **most complete** solution would be to keep the defaults timeout as expected (the one from the parameters and from the execution 1/ and 2/) and add a optional timeout value that will override whatever previous settings is set for : 
- step condition
`example: IfElementVisible = I'm waiting for a popup that can appears and if so, do several action on it`
- action
`example: click = I'm waiting for a button to be displayed`
- action condition
`example: IfElementVisible - click = I'm waiting for a message to be displayed to click on a button`
- control
`example: verifyElementPresent = I'm waiting for a banner to be displayed`
- control condition
`ok I got not example this one but It might be useful to someone else `

By default, this timeout would be `null`, and the user can choose to set it or not. We might should, by default hide the fields in the UI

**Comment by vertigo17** [comment]
Will be in 4.12

**Comment by Nouxx** [comment]
Hello, 

The 4.12 changelog mentionned: _"You can now overwrite timeout, maxSimilarity and highlightElement parameters for every step, action and control."_ but we only found the UI implementation for step (no action, no control)
I see in the QA open that the feature is implemented at every level, which is very good on our side, thanks for this job ! :)

**Comment by vertigo17** [comment]
Sorry @Nouxx I am not sure that I understood your remark. 
do you mean that you can’t find how to overwrite the parameters from action and control ?
