### ISSUE TITLE
Pre Testing - Regression - method Getpropose pre testing methode

### ISSUE THREAD

**Issue by MowglieRed** [cerberustesting/cerberus-source#2155]
Hi to all, 

We deployed the 4.8 Snapshot - build #1266 this noon and we detected a regression on the pre test management and the parameter globalactivation.

To launch the pre test we need to put false in the parameter globalactivation.
Not to launch the pre test we need to put true in the parameter globalactivation.

It concerns only the folder pre testing. 

We updated directly in the database with the help of Benoît.  
    UPDATE testcase set isActive = 0, UsrModif="Fix 200723" , DateModif = CURRENT_TIMESTAMP where isActive != 0 and Test = "Pre Testing";
   UPDATE testcase set isActive = 1, UsrModif="Fix 200723bis" , DateModif = CURRENT_TIMESTAMP where isActive != 1 and Test in ("Pre Testing") and UsrModif<>"Fix 200723";
 

Benoît and Morgan are already aware of this issue. 

Could you add on the TNR Cerberus campaign a test case on the pre testing please to ensure the next releases ? 

thanks 
peggy

**Comment by vertigo17** [comment]
Added NRT:
https://prod.cerberus-testing.org/TestCaseScript.jsp?test=ENGINE%20%3A%20Transversal&testcase=0033A

**Comment by vertigo17** [comment]
Nrt test executed correctly. 
I close the issue.
