### ISSUE TITLE
New control : VerifyElementTextContains?

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2158]
Hello,

There are currently 3 controls to interact with element (GUI,APK,IPA,SRV):

- VerifyTextElementEquals
- VerifyTextElementDifferent
- VerifyTextElementMatchRegex

What do you think of adding 'VerifyTextElementContains' ?

It can currently be done with the following regex (using `VerifyTextElementMatchRegex`) but it's less user friendly in my opinion

![image](https://user-images.githubusercontent.com/30227758/89649251-bc23ba80-d8c0-11ea-8870-16fa4fcbf9b8.png)

Thanks!

**Comment by lucashimpens** [comment]
Control has been implemented in Cerberus 4.14
