### ISSUE TITLE
Test cases versioning with git

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2159]
Hello,

Based on the feedback I'm currently having on Cerberus, be able to do version control for test cases would be a huge step forward.

The main benefit would be :
- easier for a team to work on the same test cases at the same time (no more content override)
- better track changes to identity the root cause of a non OK results
- be able to prepare the test cases for the next release while still be able to launch the previous one

This issue is more to open the discussion, I have some idea but it might need a deeper thought, some others issue could be linked to this one, such as #2074 

What do you think?

**Comment by Nouxx** [comment]
Also, in this lockdown context, I'm not able to launch any android test locally since our Cerberus instance in on the corporate network and it can't resolve my DNS address.

It may be possible to workaround but being able to launch testcases from a external repo could help me a lot when I'm working remotely

**Comment by Nouxx** [comment]
As discussed together, I believe we can close this topic?

I'd like to address then the collaboration in Cerberus in general: when several users are working on the same test case. I remember having discussed this topic already and planned a way to integrate a way to warn user before saving that the test case version has changed since they loaded the page, that seems to be a nice quick solution

**Comment by vertigo17** [comment]
Yes we can close it as we will not move the testcase referential from a database to a github structure. That would loose the ease of use of the tool.
We can create a separate issue in order to check the version consistency before saving the let the user choose between overwrite the testcase content to his version or reload the testcase. That does not seem a difficult change.
