### ISSUE TITLE
Increase test folder size 

### ISSUE THREAD

**Issue by KaoutarLKHOU** [cerberustesting/cerberus-source#2160]
Currently we cannot name our folders properly because the size limit is too short. 
Exemple : CIS - Android: Product Pager - Fab - Information

**Comment by vertigo17** [comment]
We could plan that but only after migration to latest Mariadb version.
Although, enlarging the column will probably make it harder to display the full content on every screen and reporting.
Until we do that my preco is to use the description to put more information and try to keep folder name short.
