### ISSUE TITLE
[Enhancement] Start/Stop Cerberus executor during test case execution

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#2163]
Hi,
Would it be possible to start (or reset) the executor on demand? (maybe a new action on Cerberus)
Currently, when the test execution starts, executor will start to get traffic/calls.

The ideia is to have a test to get all the calls made when we open, for example the web delivery page.
To go to the delivery page we first have to login, add a product to the basket and validate basket. So currently we have all the calls made since the first step.

We would like to start the test with the executor stopped and only start it when we validate the basket (to get only the call made to load the delivery page).
Or, another solution, the executor can be always running but we could do a "reset" (or clean) of the information get until a certain point. We would "clear" the executor info on the basket page and like this, when validating the basket it would only have those calls.

Thanks in advance!

**Comment by vertigo17** [comment]
We will do a new action 'resetNetworkTraffic' in order to iterate to a new 'page' on ProxyMod side.
