### ISSUE TITLE
Edit TestCase Header - Test case short description - Modification not saved

### ISSUE THREAD

**Issue by hananema** [cerberustesting/cerberus-source#2164]
Hello,

When the Test case short description is modified, the modification is not saved.

![image](https://user-images.githubusercontent.com/41586025/90868072-999ca180-e396-11ea-9c3c-c1bfa8d2a273.png)

Regards,
Hanane

**Comment by vertigo17** [comment]
Sorry @hananema , I could not reproduce neither in prod.cerberus-testing.org and qa.cerberus-testing.org.
Can you detail the use case ?
