### ISSUE TITLE
Robots constraint exceeds 100%

### ISSUE THREAD

**Issue by nicodeur** [cerberustesting/cerberus-source#2168]
Hello,

On `Cerberus4.7-1491` running on 1 instance.

Our robots constraint exceeds 100% (I have the impression that real robots constraint is : constraint +1)

![image](https://user-images.githubusercontent.com/6707556/91963179-d0b37100-ed0d-11ea-81e5-3b3540dfd7bd.png)

**Problem : I have many 'Connexion Lost) on my test execution (I run test on device, and device can't execute 2 tests in parallel)**

You can see here our queued settings :
![image](https://user-images.githubusercontent.com/6707556/91963952-dbbad100-ed0e-11ea-8caf-d0fbda3a9e40.png)

I don't understand because, on an other cerberus (same version  `Cerberus4.7-1491`) I have no problem with that.

Any Idea about that ?

**Comment by vertigo17** [comment]
That should be much better following last commit.
It will be integrated into next release.

**Comment by nicodeur** [comment]
Thanks for the reactivity @vertigo17  !

**Comment by vertigo17** [comment]
You’re welcome. ;-)
That was an important bug to fix
It has been released on 4.9
