### ISSUE TITLE
Rename menu entry "rapport d'exécution dans le temps" to "rapport d'exécution de cas de test dans le temps"

### ISSUE THREAD

**Issue by MowglieRed** [cerberustesting/cerberus-source#2171]
![image](https://user-images.githubusercontent.com/29864420/92404692-7151c880-f134-11ea-82c2-42686fe89170.png)

Bonjour à vous, 

Est il possible de renommer : rapport d'exécution dans le temps par rapport d'exécution d'un test case dans le temps ? (ainsi suivre l'exemple fait pour les campagnes : rapport d'une campagne dans le temps). 

merci

**Comment by vertigo17** [comment]
Une execution sous entends que c'est l'execution d'un cas de test.
Le probleme de renommer par **rapport d'exécution d'un test case dans le temps** c'est que le titre est un peu long pour un menu.

Perso je suis pas chaud à changer ca. Tu en penses quoi ?
