### ISSUE TITLE
Different structure in /UpdateTestCase

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2177]
Hello,

Currently, updating a country (invariant) is done by calling the `/UpdateTestCase` with the following structure :

```
countries: [{"country":"BE","toDelete":false},{"country":"NRT_262520","toDelete":true},{"country":"NRT_262521","toDelete":true},{"country":"CH","toDelete":false},{"country":"ES","toDelete":false},{"country":"PT","toDelete":false},{"country":"UK","toDelete":false},{"country":"RX","toDelete":false},{"country":"FR","toDelete":false}]
```

Could we switch "country" to "value" to respect the Invariant model structure ?
Thanks

**Comment by MorganLmd** [comment]
@Nouxx It should be ok now. I'm waiting for the non reg before closing the issue
