### ISSUE TITLE
/UpdateTestCase still mapped with 'testCase'

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2178]
Hello,

Currently, the /UpdateTestCase needs to be called with:

```
test: benoit
testCase: 0002A
originalTest: benoit
originalTestCase: 0002A
```

The new attribute being `testcase`, what do you think of rename every `TestCase` to `testcase`?

**Comment by MorganLmd** [comment]
As discussed with Benoit, with agree to modify TestCase -> testcase (or Testcase) : 

FROM:
test: benoit
testCase: 0002A
originalTest: benoit
originalTestCase: 0002A

TO:
test: benoit
testcase: 0002A
originalTest: benoit
originalTestcase: 0002A
