### ISSUE TITLE
Step Class and Table refactoring with columns renaming

### ISSUE THREAD

**Issue by MorganLmd** [cerberustesting/cerberus-source#2179]
### Renaming and type modifications (in parentheses):
- [x] step > stepId
- [x] conditionOper > conditionOperator
- [x] testCase > testcase
- [x] inLibrary > isLibraryStep **(BOOLEAN)**
- [x] useStep > isUsingLibraryStep **(BOOLEAN)**
- [x] useStepTest > libraryStepTest
- [x] useStepTestCase > libraryStepTestcase
- [x] useStepStep >libraryStepStepId
- [x] forceExe > isExecutionForced **(BOOLEAN)**
- [x] CondititonVal1 > CondititonValue1
- [x] CondititonVal2 > CondititonValue2
- [x] CondititonVal3 > CondititonValue3
- [x] useStepStepSort > libraryStepSort

### Step object:
```json
{
"sort": 1,
"stepId": 1,
"description": "S1",
"isExecutionForced": false,
"loop": "onceIfConditionTrue",
"conditionOperator": "always",
"conditionValue1": "",
"conditionValue2": "",
"conditionValue3": "",
"isUsingLibraryStep": false,
"isLibraryStep": false,
"libraryStepTest": "",
"libraryStepTestcase": "",
"libraryStepStepId": 0,
"usrCreated": "",
"usrModif": "",
"dateCreated": "",
"dateModif": "Jan 1, 1970 1:01:01 AM",
"actions": [],
"test": "benoit",
"testcase": "0002A",
"initialStep": 0,
"isStepInUseByOtherTestcase": false,
"libraryStepSort": 0
}
```

**Comment by Nouxx** [comment]
Hey,

I don't find `isUsedStep` in the object you shared but it's currently available for `/ReadTestCase`

**Comment by MorganLmd** [comment]
> 
> 
> Hey,
> 
> I don't find `isUsedStep` in the object you shared but it's currently available for `/ReadTestCase`

isUsedStep has been replaced by isUsingLibraryStep to better highlight that the current test is using a step from a library. And for a better coherence with the other keys refering to library too

**Comment by Nouxx** [comment]
Alright, works for me

**Comment by Nouxx** [comment]
Hello, what about `useStepStepSort` currently available?

Example [here](https://qa.cerberus-testing.org/ReadTestCase?test=benoit&testCase=0002A&withSteps=true&system=CERBERUS)

**Comment by vertigo17** [comment]
useStepStepSort --> libraryStepTest
initialStep --> to be analysed. I beleive it should be removed ??
