### ISSUE TITLE
Action Class and Table refactoring with columns renaming and adding

### ISSUE THREAD

**Issue by MorganLmd** [cerberustesting/cerberus-source#2180]
### Renaming and type modifications (in parentheses):
- [x] testCase > testcase
- [x] sequence> actionId
- [x] step > stepId
- [x] object > value1
- [x] property > value2
- [x] forceExeStatus > isFatal **(BOOLEAN)**
- [x] conditionOper > conditionOperator
- [x] last_modified > dateModif
- [x] conditionVal1 > conditionValue1
- [x] conditionVal2 > conditionValue2
- [x] conditionVal3 > conditionValue3

### New columns:
- [x] usrCreated (VARCHAR)
- [x] usrModif (VARCHAR)
- [x] dateCreated (TIMESTAMP)

### Action object:
```json
{
"sort": 1,
"stepId": 2,
"actionId": 4,
"description": "click search icon",
"action": "click",
"value1": "id=com.ocito.laredoute:id/iv_search_glass",
"value2": "",
"value3": "",
"conditionOperator": "always",
"conditionValue1": "",
"conditionValue2": "",
"conditionValue3": "",
"isFatal": true,
"screenshotFilename": "",
"controls": [],
"test": "ENGINE : Action",
"testcase": "0017B",
"usrCreated": "",
"usrModif": "",
"dateCreated": "",
"dateModif": ""
}
```

**Comment by Nouxx** [comment]
Hey, 

Could we use `ConditionOperator` instead of `ConditionOper`?

**Comment by MorganLmd** [comment]
> 
> 
> Hey,
> 
> Could we use `ConditionOperator` instead of `ConditionOper`?

Typo fixed
