### ISSUE TITLE
correct /CreateTest and /UpdateTest input format

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2184]
Hello, 

The current format to create or edit a test folder is : 
![image](https://user-images.githubusercontent.com/30227758/95076089-9b85ae80-0711-11eb-9365-660dd3783715.png)

Can we modify it so it respect the new test folder model?
- Active > isActive
- Description >description

**Comment by MorganLmd** [comment]
@Nouxx It seems it has been done in a previous commit. Could you check if it works for you please ?

**Comment by MorganLmd** [comment]
@Nouxx It should be ok now. I'm waiting for the non reg before closing the issue
