### ISSUE TITLE
[Manual Execution] Test case is OK whereas at least one step is KO 

### ISSUE THREAD

**Issue by Djamel-Catalog** [cerberustesting/cerberus-source#2189]
Hello, 

Currently, i may have a test case Ok whereas at least one step is ko. 
For me it seems to be related to the test case named "change country". 
These test case is automatically added to mine when test case is run on inter website. 
Meaning i do not have this issue for test case run on French website. 

<img width="745" alt="Cerberus execution issue " src="https://user-images.githubusercontent.com/72911182/96092956-d33be580-0ecb-11eb-8a43-5aec674d741b.PNG">

Example  : 
Test case run on Inter : http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=107583797
Visualize > "Report an abuse"  = Status OK 
Visualize > "Verify confirmation is not more displayed" = Status KO

Same test case run on FR : http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=107583795
Visualize > "Report an abuse"  = Status KO 
Visualize > "Verify confirmation is not more displayed" = Status KO

Can you please have a look  ?

Thanks, 

Djamel

**Comment by vertigo17** [comment]
Thanks Djamel. Did you share that issue with Filipe ?
Keep in mind that cummunity cannot access cerberus.siege.red URL 
Look like this is a manuel execution ? Can you reproduce the issue and describe how to reach it ?
On my side I manually executed a testcase on 4.10 and did not manage to get a testcase step OK with a control KO.

**Comment by vertigo17** [comment]
Any feedback on that issue please ? @ffazendeiro, @MowglieRed, can you check if this issue is still valid ?
