### ISSUE TITLE
Sprint screen in Cerberus

### ISSUE THREAD

**Issue by ntennich** [cerberustesting/cerberus-source#2191]
Hello Benoit, 

We had  sprint notion in Cerberus, a screen or fields (Start / End date of sprint), that allows us to identify the test cases will run in a sprint.
In which screen can I find this notion of sprint?
Best regards, 
Nadia.

**Comment by vertigo17** [comment]
Hello @ntennich ,
You can find it in :+1: 
![image](https://user-images.githubusercontent.com/5342048/96635003-959bea00-131b-11eb-8b63-3e38bc910832.png)

It allows to flag a testcase to activate only starting to a specific version of the application (or sprint) but also stop the testcase after a version (or sprint)

**Comment by ntennich** [comment]
Hello Benoit, 
thanks for your help.
it's clear on my side ;).
Nadia.
