### ISSUE TITLE
Release 4.10 : Issue on the URL opening. 

### ISSUE THREAD

**Issue by MowglieRed** [cerberustesting/cerberus-source#2203]
Bonjour à vous, 

Nous avons déployé la release 4.10 dans notre environnement d'UAT. (nous sommes toujours en glassfish). 
Suite à ce déploiement nous avons constaté une anomalie lorsque nous nous souhaitons ouvrir l'URL de cerberus : 

Lorsqu'on ouvre l'URL de connexion, nous avons cette page. L'URL a été modifié et contient en toute fin " /ReadCerberusInformation ".  
![image](https://user-images.githubusercontent.com/29864420/97620425-daadd380-1a21-11eb-8a79-5236d5c20225.png)

![image](https://user-images.githubusercontent.com/29864420/97620456-e4cfd200-1a21-11eb-8bde-4a8c5fc3de9e.png)

Nous devons supprimer /ReadCerberusInformation pour pouvoir arriver sur la page contenant l'accès au TUTORIAL.  
![image](https://user-images.githubusercontent.com/29864420/97620054-49d6f800-1a21-11eb-92f6-03cd0b053d68.png)

Nous cliquons alors sur « I just want to take a look around first » to clean the checkbox. 

Ensuite, on s'est déconnecté et reconnecté mais on retrouve la même problématique /ReadCerberusInformation.  

Ceci bloque notre déploiement. 

Merci 
Peggy

**Comment by vertigo17** [comment]
L'issue a-t-elle été reproduite en QA ?
