### ISSUE TITLE
Import tests with errors

### ISSUE THREAD

**Issue by HugoCaplin** [cerberustesting/cerberus-source#2209]
When I want to import a test in a new Cerberus Environment I get some errors.

Name steps are OK, but actions are wrong : they corresponds to another tests imported (with librairies)

The first test imported is ok : 

![2020-11-12_17h33_35](https://user-images.githubusercontent.com/61287544/98967802-33469b80-250d-11eb-851f-49ccdf09840d.png)

The second test with dependancy (librairies) with the first one : 

![2020-11-12_17h34_42](https://user-images.githubusercontent.com/61287544/98967943-5b35ff00-250d-11eb-9077-67cfaae514f4.png)

But normally, for the second test, the third step actions are : 

![2020-11-12_17h35_11](https://user-images.githubusercontent.com/61287544/98968004-6be67500-250d-11eb-98b2-172f154e932d.png)

So there is a mix between 2 tests with librairies (dependancy)

**Comment by dominique-bureau** [comment]
Follow up of this ticket.
We just discovered that in fact it is the exportation which is wrong. 
In the generated json file, there are some steps which do not belong to the exported test case. 

And of course, when we import this json , we have these foreign steps. 
So we think that the export is wrong but the import is fine.

**Comment by vertigo17** [comment]
Can you test if issue is still present in qa.cerberus-testing.org environments ?
Just try to connect on the environment and I will give the necessary credential in order to test from that environment.

**Comment by HugoCaplin** [comment]
I can't create a test in Cerberus (in order to test export/import) because there is no application linked (can't create application no more).

**Comment by vertigo17** [comment]
OK. I just added Integrator role in order to allow creation of application.
Let me know about the test result.

**Comment by vertigo17** [comment]
BTW, you need to logout and login again.

**Comment by HugoCaplin** [comment]
Same problem... even in private browser.

**Comment by vertigo17** [comment]
Your Slack account is Hugo C right ?

**Comment by HugoCaplin** [comment]
HugoCaplin
connected with hugo.caplin.partner@decathlon.com

**Comment by vertigo17** [comment]
My fault, I forgot IntegratorRO as weel. Now it is OK. I let you provide an example.
Thanks.

**Comment by vertigo17** [comment]
Any feedback on that issue ?

**Comment by HugoCaplin** [comment]
I tried to add 2 tests with dependancies (librairies) in order to be exactly in my case.
First analysis : seems there is no problem
Maybe I had to go deeply in the 2 tests cases but these environment is refresh each day. I had to do it again :)

**Comment by vertigo17** [comment]
If necessary we can also do it from prod environment. Just ask me.

**Comment by HugoCaplin** [comment]
Yes please :) 
Is this url ok to test : https://demo.cerberus-testing.org/ ?

Thanks

**Comment by vertigo17** [comment]
demo environment (just like qa environment) is refreshed every day.
If you want to avoid reenter your test every day, this is better to use prod.cerberus-testing.org

**Comment by HugoCaplin** [comment]
Ok thanks Benoit !
I will use prod envt
I let you know ;)

**Comment by HugoCaplin** [comment]
Re !
I can't connect :/ 
![2021-01-04_14h04_27](https://user-images.githubusercontent.com/61287544/103538057-ce1c8000-4e95-11eb-9ceb-50dbd5b2b377.png)
