### ISSUE TITLE
Stickers in error

### ISSUE THREAD

**Issue by HugoCaplin** [cerberustesting/cerberus-source#2214]
When I add a sticker to a test, it's added to each others tests with the same ID but different test folder : 

![2020-11-23_15h41_07](https://user-images.githubusercontent.com/61287544/99975339-62c59580-2da2-11eb-8dd5-4637cf0e6706.png)

**Comment by vertigo17** [comment]
I think the bug is more linked with the display of the column. Please confirm on opening each testcase header that only one of them has the sticker ?
A similar bug was fixed for 4.10 can you confirm which version you use ?

**Comment by HugoCaplin** [comment]
@vertigo17 
Yes it is ! only one of theses ID get the label !

We work on the last version (4.9-1538)
Happy that a fix is planned for the next version :)

**Comment by vertigo17** [comment]
4.10 is already available. If you use Keycloak (a bug was detected if you don't use it), you can already move to it in order to solve the issue.

**Comment by HugoCaplin** [comment]
Thanks @vertigo17 
Our Cerberus is in 4.10 and problem solved 👍 

Regards !
