### ISSUE TITLE
Accessing VPN applications via cerberus selenium

### ISSUE THREAD

**Issue by churchfriday** [cerberustesting/cerberus-source#2215]
if cerberus is running somewhere on your cloud instance, how can I access some local VPN applications?
From where can I set configuration?

**Comment by vertigo17** [comment]
If you are using a FREE or TRIAL instance your application needs to be accessible from Internet + you will have to open the access using your Cerberus IP (keep in mind that 1/ this IP could change from time to time 2/ you are not alone on that IP).

If you need to setup a VPN and also want to secure that the IP is only used by you, you need to register a paid plan.
