### ISSUE TITLE
Unsaved executions 

### ISSUE THREAD

**Issue by fwelonek** [cerberustesting/cerberus-source#2219]
Yesterday we ran campaigns with the tag "Sprint46_execution_reporting". 
When we returned to see the campaign reporting, nothing was recorded.
This morning I ran the campaign again with the same tag and this time it got recorded.

**Comment by vertigo17** [comment]
We will need more more information.
On which company do you work ?

**Comment by fwelonek** [comment]
hi,
There is no anomaly. 
I was making a mistake by rerunning the same tests with the same tag.
Sorry for inconvenience
