### ISSUE TITLE
Need to test 2FA website (double authentification)

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#2234]
Ie need to test a website with double authentification. To be able to connect on the application, I must enter a 6 digit code related to my secret key

Now i can get the secret key by get source page of the QRcode but I wanted to generate the code from this secret code in Cerberus

Katalon use this plugin:  https://store.katalon.com/product/28/TOTP-Generator-Keywords

Is it possible to have a solution for Cerberus ?

Here some links about TOTP : 
https://dev.to/j_sakamoto/selenium-testing---how-to-sign-in-to-two-factor-authentication-2joi
https://itnext.io/how-to-use-otp-service-in-your-automation-scripts-with-selenium-web-driver-fe81607232b5
https://letzdotesting.com/how-to-automate-two-factor-authentication-with-google-authenticator-using-selenium/

**Comment by vertigo17** [comment]
I would propose to add a getOTP property type that would take the secret as 1st parameter. Property would then get the value of the code. Would it fit the need ?
Do you have a way to test snapshot release of Cerberus on your side or access to QA in order to confirm the implementation works before next release ?

**Comment by vertigo17** [comment]
BTW, I will probably use the same library as Katalon:
<dependency>
    <groupId>org.jboss.aerogear</groupId>
    <artifactId>aerogear-otp-java</artifactId>
    <version>1.0.0.M1</version>
    <scope>compile</scope>
</dependency>

**Comment by glassalle59** [comment]
Yes it will be great.
Its difficult to. test some snapshot, is it possible to test on a dev environnement you have ?

**Comment by vertigo17** [comment]
Please log in to qa.cerberus-testing.com using your github account and I will add you the necessary roles for you to test.

**Comment by glassalle59** [comment]
It's done
