### ISSUE TITLE
Failed to click because could not find element

### ISSUE THREAD

**Issue by indraruslan** [cerberustesting/cerberus-source#2238]
Hello,

Every time I run the test case, the result is always 'Click : failed to click because could not find element http://....' unknown action error'.

Thanks

**Comment by vertigo17** [comment]
Can you please provide more details. 
Screenshot of the execution report + exact definition of the action + ideally the context with what you try to acheive. Looks like the element you define is not correct.

**Comment by indraruslan** [comment]
Hi,
The following is the image capture
![image](https://user-images.githubusercontent.com/35551189/107879231-38e7bf00-6f0a-11eb-95c5-813241818ec2.png)

**Comment by vertigo17** [comment]
I beleive that you are using the kickle SaaS instance ?
If so, can you point me to the failed execution so that I can have a look. Is it using the Cerberus Robot or the your own robot ?

**Comment by indraruslan** [comment]
Hi

I'm using local robot
