### ISSUE TITLE
bug concernant l'importation d'une scénario faite à partir de sélénium

### ISSUE THREAD

**Issue by diamile** [cerberustesting/cerberus-source#2254]
Salut je m"appel SARR DIAME .

1°) je suis entrain d'apprendre cerberus afin de faire des tests automatisés des différentes plateformes.
En effet j'ai tout le temps des erreurs ,par exemple  au niveau de niveau de page du listing des cas de test j'ai cette erreur : 
An unexpected problem occurred. java.sql.SQLException: Column 'tec.DetailedDescription' not found.

2°) Quand j'essaye d'importer un fichier sélénium j'ai cette erreur : 
Operation finished with error ! org.cerberus.exception.CerberusException: An unexpected problem occurred. com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'DetailedDescription' in 'field list'. null

3°) Quand j'essaye de creer un cas de test aussi

**Comment by vertigo17** [comment]
Bonjour,
Tes erreurs semblent liées à une mauvaise version de base de donnée.
As-tu bien fait attention d'utiliser la bonne version de MySQL et MariaDB specifié dans le fichier INSTALL ?
N'hesite pas à demander une instance SaaS TRIAL dispo via un formulaire sur le site pour eviter ces soucis d'installation.

**Comment by diamile** [comment]
Bonjour, 
merci pour votre réponse .

C'est ce que je me disais enfaite on a installé la derniére version de cerberus celle de 4.11.2  
par contre au niveau de la documentation il n"est pas specifié pour tel version de cerberus il nous tel version de MySQL et MariaDB . 
Je viens de m'incrire sur cerberus afin d'obtenir une instance Saas TRIAL .

**Comment by vertigo17** [comment]
Parfait. L'instance sera créé dans la journée.
La doc incite à aller [la](https://github.com/cerberustesting/cerberus-source/blob/master/INSTALL)

```
MySQL 5.6.xx or MariaDb 10.1.xx
Java JDK 11
Tomcat 9
```

**Comment by diamile** [comment]
Bonjour,
Parfait ça marche enfaite j'ai decouvert un nouveau  bug concernant le testCase , une fois l'importation du fichier sélénium sur cerberus, tous les boutons qui pourraient m'aider à personaliser mon cas de test sont desactivé . 

J'ai crée un scénario sur sélénium , apres importation quand j'essaye de lancer le test j"ai cette erreur :  Failed to wait because could not find element 'css=#row-hotline-24280 .hidden-sp > .btn-success'! et ça bloque mes testes avez-vous une idée ?

**Comment by vertigo17** [comment]
C'est plutot que tes xpath/css ne fonctionnement pas.
Si tu les as pris de Selenium IDE, ils sont peut-être differents de ceux de la page que tu testes. Ou non compatibles avec Selenium.
Il faut reprendre les xpath en les testant en reel et les adapter en fonction du context. Cerberus te remontes le html et sceenshot au moment ou l'action failed pour aider à comprendre le context qui fait que l'element n'est pas trouvé.

J'ai vu que tu n'utilise pas l'instance Saas du coup j'ai pas pu regarder tes tests.Impossible de t'aider sans plus de detail.

Pour forcer de continuer l'execution d'une action tu peux mettre 'Force Execution' à PE.
A un niveau control il y a une info fatal à mettre à N pour que le test continue.
