### ISSUE TITLE
Failed to process xml response

### ISSUE THREAD

**Issue by Cyril-Bellotti** [cerberustesting/cerberus-source#2262]
Hello,

By using SOAP API calls we have a sticking point in processing the xml response. We are unable to target one item in the response. we have tested several ways without success.

Our test : 
![Castest1](https://user-images.githubusercontent.com/60349932/120799642-4f5c6980-c53f-11eb-9cec-4edd153e1a46.PNG)

What we target : 
![property1](https://user-images.githubusercontent.com/60349932/120799871-90547e00-c53f-11eb-85b9-c2adde9c91ae.PNG)

A file response API example : 
```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <processReturn xmlns="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="DDRResponse">
      <advantagesDDR xsi:nil="true" />
      <cardHolder>
        <accountNumber>999999</accountNumber>
        <accountStatus>0</accountStatus>
        <bankNumber xsi:nil="true" />
        <cardNumber>93010017000034659</cardNumber>
      </cardHolder>
    </processReturn>
  </soap:Body>
</soap:Envelope>
```

The result of the test : 
![response1](https://user-images.githubusercontent.com/60349932/120799776-7450dc80-c53f-11eb-86c9-8f6f12251422.PNG)

Thank's for your help.

**Comment by AdeoPierreBoudelle** [comment]
@vertigo17 a reproduit le problème ici :
https://prod.cerberus-testing.com/TestCaseExecution.jsp?executionId=335581

**Comment by ffazendeiro** [comment]
Hi,
SOAP XML are a little trick to get due to the manespace on the response.
For @vertigo17 example we need to tweak a little bit the xpath using option l_ocal-name()_.
Instead of a direct xpath **//cardNumber** you can use **//*[local-name()='cardNumber']** and it will work:
https://prod.cerberus-testing.com/TestCaseExecution.jsp?executionId=338871
Then the value is correctly returned.
Hopes it helps.

**Comment by vertigo17** [comment]
Thanks @ffazendeiro I am sure it will help a lot ;-)
@Cyril-Bellotti I believe that fix the issue ?

**Comment by AdeoPierreBoudelle** [comment]
Thanks a lot @ffazendeiro and @vertigo17 !
I confirm that it fixed this issue. Now we can extract data from the response and work with it :-)
