### ISSUE TITLE
Campaign filters are not working with Type field

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2281]
How to reproduce (in https://qa.cerberus-testing.com):
- create a campaign that filter on label 'Cerberus_GUI' and on type 'AUTOMATED'

![image](https://user-images.githubusercontent.com/30227758/127130517-7ee1812d-029d-4b16-82ea-4098c46a3890.png)
![image](https://user-images.githubusercontent.com/30227758/127130496-8282b24d-b59e-449c-9577-5b644cc29f5c.png)

- create a campaign that filter on label 'Cerberus_GUI' and on type 'MANUAL'

![image](https://user-images.githubusercontent.com/30227758/127130602-6f58ee22-41a2-430f-af5c-bb0bacfe05ef.png)
![image](https://user-images.githubusercontent.com/30227758/127130621-72b38902-c58c-4d13-ac75-85c8f70e2170.png)

- you should have 180 testcases defined for each campaign, switch any testcases from this selection to MANUAL (from the testcase menu)
- check the first campaign, it will be still 180 testcases
![image](https://user-images.githubusercontent.com/30227758/127130759-2dcf923f-82fc-4d12-90c7-0c48f03a10b7.png)

- check the second campaign, it will be still 180 testcases 

![image](https://user-images.githubusercontent.com/30227758/127130802-d68cd1df-0704-40b5-b78c-985549edca5e.png)

**Comment by vertigo17** [comment]
Bug was there since May 19th, 2020. ;-(
