### ISSUE TITLE
Icons are not visible through out the cerberus instance

### ISSUE THREAD

**Issue by anchalbhanwala** [cerberustesting/cerberus-source#2283]
Cerberus Version : 4.11.2-1583
Chrome Version 
![image](https://user-images.githubusercontent.com/85665536/127656546-96119184-3a4c-41b4-960a-214573662e3b.png)

Icons are not visible through out the instance. Refer the screenshots below for one of the screen
![image](https://user-images.githubusercontent.com/85665536/127656703-c1c5ec6d-d40f-4cc7-be85-9598f7f03a73.png)

**Comment by vertigo17** [comment]
I am also on Chrome 92 and can't reproduce on both 4.11.2 and 4.12
Maybe CTRL+F5 (clean cache) ?

**Comment by anchalkumra** [comment]
I cleared cache and still its the same . Below is the console error that i see
![image](https://user-images.githubusercontent.com/60463423/128008020-633a1f81-b61b-41fe-acab-724cdce8e71d.png)

**Comment by anchalbhanwala** [comment]
I cleared cache also and its still the same. Below error is what i see in the console.
![image](https://user-images.githubusercontent.com/85665536/128008277-28b34732-8ee9-4ea8-8a7d-9c8d4df3d434.png)

**Comment by vertigo17** [comment]
Ok thanks for the logs. I will check directly on your instance and get back to you.

**Comment by vertigo17** [comment]
Sorry but even on your instance I cannot replicate.
Both files loads with 200 return code and icons display correctly.

**Comment by anchalbhanwala** [comment]
I tried couple other browsers and its not working on any. 
1- Could you share the url on which your are trying to replicate the defect with the screenshot ?
My instance url is : http://abhanwala.cerberus-testing.com/Homepage.jsp
2- I can see one icon displayed on my instance shown below . 
It needs more investigation . 
![image](https://user-images.githubusercontent.com/85665536/128194531-34710a63-dcee-47f6-8427-f4f3cd15ebb7.png)

**Comment by vertigo17** [comment]
I used the same URL from a icognito window on Chrome using login cerberus-bdu (admin for support purpose).

![image](https://user-images.githubusercontent.com/5342048/128242055-8d9c428a-9a04-4f35-a5f2-8915c145437d.png)

From Chrome 92 

![image](https://user-images.githubusercontent.com/5342048/128242121-5886f3b1-9ac8-484e-8ffe-4245aedc4833.png)

Agreed this is worth investigating in order to understand ;-).
Are you behind a proxy that could block some URL ?

Can you try from a different laptop of mobile ?

**Comment by vertigo17** [comment]
I may have found something.
On my side when loading the homepage, I download only woff front files:
![image](https://user-images.githubusercontent.com/5342048/129482856-6a282c86-8860-4f75-910b-6cd90afc0b0e.png)

If I filter on console, I don't get any ttf files like you do on your side.
Can you confim the result of network filtering when loading the homepage with both filtering on woff and ttf text ?

If you confirm you only have woff results and no ttf, next step will be to determine why on your system ttf files are download or why ttf files are not there.

**Comment by vertigo17** [comment]
Can you also check if those 2 files can be downloaded from your browser ?

http://abhanwala.cerberus-testing.com/dependencies/FontAwesome-4.5.0/fonts/fontawesome-webfont.ttf?v=4.5.0

http://abhanwala.cerberus-testing.com/dependencies/FontAwesome-4.5.0/fonts/fontawesome-webfont.woff2?v=4.5.0

None of them are protected by Keycloak and should answer 200 and download the fonts on your desktop (that what happens on mine).

**Comment by anchalbhanwala** [comment]
I will check and let you know tomorrow

**Comment by anchalbhanwala** [comment]
Here's what is displayed upon filtering woff and ttf respectively on network .
![image](https://user-images.githubusercontent.com/85665536/129521817-ad927584-86de-4316-9aca-1414be74234e.png)
![image](https://user-images.githubusercontent.com/85665536/129521901-afce9c49-aabe-4595-bee2-0630a1562690.png)

Also, the 2 links you shared are blocked per my companies policies  .

**Comment by vertigo17** [comment]
If I understand right, issue is confirmed as being your company rules that block that content ?
If so you can ask them to white list the domain to avoid the issue ?

**Comment by anchalbhanwala** [comment]
yes. Working with the team on it.

**Comment by vertigo17** [comment]
No particular issue in testing Angular web applications. It is currently daily testing the next version of cerberus frontend that will also use Angular.
