### ISSUE TITLE
[Test execution] Steps running repeatadly

### ISSUE THREAD

**Issue by hananema** [cerberustesting/cerberus-source#2297]
Hello,

I've noticed today a weird behaviour in version Cerberus4.13-SNAPSHOT-1640 Build 20210910-133717.
when I execute a test, the steps are executed repeatadly.
execution: automated
env: uat
country: fr
robot: firefox
I think it is a display issue, the step that is running is displayed repeatadly until we refresh the page. then the new step that is running will be displayed repeatadly with all previous steps.
Here is a video about the issue.
Let me know if you need more information.
[screen-capture.zip](https://github.com/cerberustesting/cerberus-source/files/7170610/screen-capture.zip)

**Comment by vertigo17** [comment]
Probably a consequence of latest comit.
@MorganLmd can you have a look ?
