### ISSUE TITLE
Testcase Script : Fatal parameter default value at 'true' 

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#2298]
## What

When adding a new action from the test case script page, the  "Fatal" parameter is by default at 'false'. 

The issue with this parameter is that the execution will continue until the next control and the error message will not be as precised as if the testcase stopped on the real blocking action. 

## What to do ? 

Set the fatal value by default to 'true'

## TestCase to create from GUI 

- Create a testcase 
- Add an action
- save the testcase
- Check the 'Fatal' boolean is at true

**Comment by mflorid** [comment]
When you want to work to put a lot of test is such a pain when you realize you forget to change one by one this parameter.

It could be good to have this feature ! :)

**Comment by vertigo17** [comment]
Agree. We will fix that for next release.

The rule should be:

Actions Fatal default to true.
--> When an action fail, most of the time, there is no point to continue the test (unless specific)
Control Fatal default to false.
--> When a control fail, most of the time this is worth to perform the other controls to get a full view on all controls.
