### ISSUE TITLE
Property calculation goes wrong: long property

### ISSUE THREAD

**Issue by CVERNAY** [cerberustesting/cerberus-source#2300]
**What**
At the execution of a test case, the calculation of a property goes wrong. However, the calculation of this property has already worked.
Since middle of august, we face this issue.
The property is "long". Maybe it's the problem.

## What to do ?

Fix this issue in order to be able to calculate the property again.

Please contact me for more informations. I can give you some examples.

**Comment by vertigo17** [comment]
There is too few element in order to fix that issue.
If still relevant, please reopen or open a new issue with at least some trace + the full error message on the property.
