### ISSUE TITLE
[Erratum][Cerberus chrome extension] elements in menu displaying after a right click not detected

### ISSUE THREAD

**Issue by hananema** [cerberustesting/cerberus-source#2309]
Hello,
I had 2 issues with cerberus chrome extension for Erratum:
1) elements in a menu displaying after a right click are not detected:
![image](https://user-images.githubusercontent.com/41586025/136174572-35da9c9c-b0f1-407c-adc9-bb3992075d3f.png)
instead a click is performed.

2) impossible to retrieve the correct erratum for an element on which a right/left click opens a popin. The popin displays and the erratum copied is not the good one
![tempsnip](https://user-images.githubusercontent.com/41586025/136176097-f7445913-ed94-41a4-aa49-fd3669992bfe.png)

Regards,
Hanane

**Comment by MorganLmd** [comment]
issue transferred to the extension repository => https://github.com/cerberustesting/cerberus-chrome-extension
