### ISSUE TITLE
[Cerberus4.13][step condition doWhile] condition verified before action is done

### ISSUE THREAD

**Issue by hananema** [cerberustesting/cerberus-source#2328]
Hello,

This issue happens for 4.13 version.
When a test has a doWile condition in a step, it seems like this condition is verified before the actions were done.

Steps to reproduce:
1- create a test with a condition doWhile "IfNumericMinorOrEqual" comparing between "property" and ​"value"
2- the step should contain a service call (rest or soap)
3- the property used in the condition should be a getFromXML/getFromJson property and should be calculated during the steps actions and after the service call
4- execute test case

Expected: all iterations should succeed
Result: first step failes since the getFromXML/getFromJson property couldn't be calculated

I created a test to reproduce this issue:
https://prod.cerberus-testing.com/TestCaseExecution.jsp?executionId=387643

This issue is blocking for us.

Please let me know if you need more information

**Comment by hananema** [comment]
@MorganLmd

**Comment by vertigo17** [comment]
Hello @hananema confirmed. We will take care of it.

**Comment by vertigo17** [comment]
Should be fixed.
