### ISSUE TITLE
[Cerberus4.13] After importing a Step Lib, index of Step on testcase is set to zero

### ISSUE THREAD

**Issue by akatmiranda** [cerberustesting/cerberus-source#2329]
On a testcase we import a Step Library from another testcase. The index of that step is set to zero.
Opening that step on the original testcase it will always open the first step instead of the desired step.

Please refer to image:
![Lib_Zero](https://user-images.githubusercontent.com/38046035/145575962-fc376969-ccbd-4e3f-b446-fec9a5d04004.png)

**Comment by vertigo17** [comment]
Hello @akatmiranda  confirmed. We will take care of it.

**Comment by vertigo17** [comment]
Issue was fixed.

**Comment by vertigo17** [comment]
There is still this regression :
https://prod.cerberus-testing.com/TestCaseExecution.jsp?executionId=389494
