### ISSUE TITLE
[Cerberus4.13] 'Folder Description' field loses inputed value when creating a new Folder

### ISSUE THREAD

**Issue by akatmiranda** [cerberustesting/cerberus-source#2330]
When creating a new folder we can add a description to that folder on 'Folder Description' field.
After creating the folder, field 'Folder Description' has value 'true'.

Please refer to images:
![New_FolderTest](https://user-images.githubusercontent.com/38046035/145576680-19fb305f-c08e-449d-8c93-9e9ce16f44f4.png)
![New_FolderTestTrue](https://user-images.githubusercontent.com/38046035/145576693-387df634-27e1-456e-8aab-85940c3ba088.png)

**Comment by vertigo17** [comment]
Hello @akatmiranda  confirmed. We will take care of it.
