### ISSUE TITLE
Unexpected error on running cerberus-tomcat-keycloak-mysql (4.13.1)

### ISSUE THREAD

**Issue by ArtemSukhomlyn** [cerberustesting/cerberus-source#2341]
Cerberus Version : 4.13.1
![image](https://user-images.githubusercontent.com/14799785/147738639-aed007fc-082f-441a-b4f4-99415c895954.png)
Here all looks fine. But when I tried to open licalhost:8080 I get the following error
![image](https://user-images.githubusercontent.com/14799785/147738397-1784167d-7e16-4439-986d-d00a6d9a4a5a.png)
Console state
![image](https://user-images.githubusercontent.com/14799785/147738576-3825d2e5-e360-455a-953c-2b9b1a6ab444.png)

**Comment by vertigo17** [comment]
Hello @ArtemSukhomlyn , looks like your database is down. Cerberus complains that it cannot find a valid database.
Maybe you can try to restart the full composition and check that database is up and still have the schema created.

**Comment by vertigo17** [comment]
Helllo @ArtemSukhomlyn did you manage to solve your issue ?

**Comment by vertigo17** [comment]
Any news @ArtemSukhomlyn ?

**Comment by ArtemSukhomlyn** [comment]
Sorry, we are defending Ukraine and resisting russion invasion

**Comment by vertigo17** [comment]
Of course Artem, I didn' know you were from Ukraine.
We are shaken by this war and Russia aggression that has no sense.
Hope you and your family are all safe and this unbelievable situation ends.
