### ISSUE TITLE
INSTALLATION FAILED

### ISSUE THREAD

**Issue by aminelux** [cerberustesting/cerberus-source#2342]
Bonjour tout le monde ,
j'aimerai bien si quelqu'un peut m'aider a compléter l'installation de cerberus testing , vu que je maitrise pas trop docker .
Merci d'avance,

**Comment by vertigo17** [comment]
Hello @aminelux ,

Pas besoin de maitriser docker pour utiliser Cerberus.
Pour une installation sans Keycloak (sans doute à privilegier pour commencer), tu peux utiliser la composition: 
https://github.com/cerberustesting/cerberus-source/tree/master/docker/compositions/cerberus-tomcat-mysql

Celle ci te permettra de demarrer un Cerberus avec MySQL. Si tu prends la composition with-selenium, tu auras également la partie robot Selenium avec.

Sinon, le plus simple c'est de demander une instance TRIAL:
https://cerberus-testing.com/start/
Il faut juste remplir le formulaire et apres qqs jours, on t'envoie les informations pour se connecter à ton instance.
L'avantage c'est que tu n'aura rien à installer.
