### ISSUE TITLE
Wrong library hyperlinks

### ISSUE THREAD

**Issue by ksinapayen** [cerberustesting/cerberus-source#2358]
Hello,
The library hyperlinks is misleading: it always leads to the first step
![image](https://user-images.githubusercontent.com/98951047/152342941-a8cada58-4b40-4143-818f-21b2bba1a2ad.png)

Cerberus version: 4.13

**Comment by vertigo17** [comment]
That should already bee fixed on 4.13.1 and latest snapshot.
Are you able to confirm ?

**Comment by ksinapayen** [comment]
Thank you for your reply, this issue can be closed.
We will install the next major release (4.14?) and open a new issue if necessary.
