### ISSUE TITLE
[LR][Database] Redefine campaign column size on campaign table

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-source#2373]
Hi,
In our CI-CD pipeline we are using the same name for the campaign as for the application (to maintain coherence and to be easier to identify). 
As the application row in application table is set as VARCHAR(200) and row campaign in table campaign is set to VARCHAR(45) we cannot have campaigns with the same name as the application if name is above 45 characters.
In this context, would it be possible to update/redefine campaign row from table campaign to VARCHAR(45) type?

Thanks,
Filipe

**Comment by vertigo17** [comment]
Hello Filipe,
You mean resize campaign column to 200 digits like in application table ?

**Comment by ittaLaRedoute** [comment]
Hi @vertigo17 ,
Yes, to have the same number of characters available as the application :)
Thanks.
