### ISSUE TITLE
[LR] Error : "Exception: java.lang.NumberFormatException: For input string:"

### ISSUE THREAD

**Issue by RoydDevs** [cerberustesting/cerberus-source#2374]
Hi,

I've some test cases which correctly worked for few weeks, but since few days I've an error that blocks me.

When I execute the test cases, this error occurs: 
![image](https://user-images.githubusercontent.com/51986543/160567498-52b20885-a2cd-4674-b59e-5ac2345c0c41.png)

The state of the test set to "FA" but I always have this screen, and it loads without stopping:
![image](https://user-images.githubusercontent.com/51986543/160567634-1d7fdf01-ca0b-4372-a020-1506542124e2.png)

When it executes during a campaign, the behavior is a little bit different. In the resume of the campaign, I've impacted test cases shown like that : 
![image](https://user-images.githubusercontent.com/51986543/160567915-dd054fcb-d556-4b6c-ac0d-5e2154bb41e3.png)

And I can't click on orange boxes to see details of the execution, nothing happens: 
![CerberusErreur](https://user-images.githubusercontent.com/51986543/160568914-5a3f1ddc-ebc0-4288-8006-915e83ceeb19.gif)
The full message: 
![image](https://user-images.githubusercontent.com/51986543/161499890-e910dbb0-2817-47d9-b9ad-67bddc043766.png)

The problem appeared few days after La Redoute updated Cerberus to version 4.13.1-1689

If you need more information don't hesitate to call me

Thanks
Mathieu Sirère

**Comment by vertigo17** [comment]
Problem was linked to the fact the failed action got the timeout overwrite option checked but with no value defined. 
workaround before the fix is to uncheck the corresponding option at action level of define a propper timeout value.
