### ISSUE TITLE
password in clear inside test case execution reports

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#2386]
Hi,

I wanted to report something you probably already know, but we need to know if there is a workaround or an upcoming fix about it.

For a lot of test cases, we need a connection.
For instance we have created a datalib with a service account like following :
<img width="1193" alt="Capture d’écran 2022-05-10 à 14 14 11" src="https://user-images.githubusercontent.com/14962879/167625723-6a3e020e-46aa-4031-9bb2-9ac15ffe8f7b.png">

First question : If I'm right, every cerberus user can see it ?

Then, when you are using it in the test case itself, you only see the property name, so, it's good on this part.
<img width="1127" alt="Capture d’écran 2022-05-10 à 12 42 47" src="https://user-images.githubusercontent.com/14962879/167656774-5222b419-4503-4932-b030-8e935d4c5e2c.png">

But when the test case is executed, you can see the password in clear inside the report : 
<img width="814" alt="Capture d’écran 2022-05-10 à 12 43 12" src="https://user-images.githubusercontent.com/14962879/167657030-392836dc-3ec2-4454-98d4-fb6b6d2d23f3.png">

Is that possible to have the possibility to completely hide the fields inside the report, when they are marked as "encrypt" inside a datalib ?

Thanks.

**Comment by vertigo17** [comment]
Hello @ping0uin, that feature is part of latest 4.14

From changelog:

_Secrets managements. All subdata flagged as encrypted, will be hidden from execution results. All Properties name that contain PASSW will also automatically have its content hidden from execution reports._

Also consider that the password will be hidden only if it contains more than 3 digits.
