### ISSUE TITLE
[LR] Supported Database Management Systems

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-source#2394]
Hello,

We are trying to understand which databases Cerberus supports (Cerberus internal DB).
Does it work only with MySQL or does it support for example PostgreSQL or other DBMS's?

Thank you!

**Comment by vertigo17** [comment]
Supported databases are MySQL 5.6.xx or MariaDb 10.1.xx
(appears on INSTALL file)
