### ISSUE TITLE
Export testcase / import testcase (JSON format)

### ISSUE THREAD

**Issue by bcivel** [cerberustesting/cerberus-source#260]
When developping features, we make new tests on dev version that we need to do again in all environment. This feature will allow to make it simpler, doing the test once and importing it where we want.

> We can also imagine to deliver the Cerberus testcases to the community.
> 
> And this is also a good way to ask people which need new feature to give us a testcase in that format before we do the development.
- [ ] Export
- [ ] Import

**Comment by vitoo** [comment]
Too bad we need import right now :)

**Comment by MHN-DK** [comment]
Beeing able to export a whole campaign or a test case (with its dependencies) would be very usefull when we are working with a partner.
And of course, on the other side, we need to be able to import ;-)
