### ISSUE TITLE
Implement Appium Connector

### ISSUE THREAD

**Issue by bcivel** [cerberustesting/cerberus-source#393]
In order to allow execution on other dependencies (like Appium), 
- [x] Modify Robot object (ID,Name, IP, Port, description, List<RobotCapability>) > No needs to do that. Robot is an object a bit like testcase, ie during the execution, a new object Session will take a picture of the robot information with some more information (like testcaseexecution vs testcase).
- [x] Create RobotCapability object (ID, RobotID, Capability, Value) in order to give more flexibility defining capabilities.
- [x] Give the possibility to add more Capabilities from the GUI, without any code.
- [x] Split the Webdriver method and the selenium method into two class (to be able to use the webdriver with selenium server and appium server without duplicating code).
- [x] Create Session and SessionCapabilities objects. Session is the picture of robot during the execution, and sessionCapabilities is the picture of RobotCapabilities.
- [ ] Set the (only the new) Run test page to add a new Capabilities tab from the Robot Settings panel to be able to see the capabilities for a given Robot.

As first step, I take the IP field of the countryenvironmentparameter table to store the path where is stored the application.

**Comment by abourdon** [comment]
Oops, too fast :-)

Development is done but we have to keep an hard coded section to get compliant with legacy code.

See: https://github.com/vertigo17/Cerberus/blob/master/source/src/main/java/org/cerberus/engine/execution/impl/SeleniumServerService.java#L355

It could be great to inform users to use robot capabilities section to set the hard coded values and to be able to remove this dirty code

As soon as this code is removed we can close this issue.

Regards,
Aurélien

**Comment by abourdon** [comment]
Code removed, but we still cannot close this issue because of missing the last improvement:

Set the (only the new) Run test page to add a new Capabilities tab from the Robot Settings panel to be able to see the capabilities for a given Robot.

**Comment by bcivel** [comment]
I close the issue because we won't develop the last item (add capabilities to run page).
For that specific needs, we advice to use set a robot, which is a more generic solution.
