### ISSUE TITLE
Test execution engine: add post test

### ISSUE THREAD

**Issue by abrennet** [cerberustesting/cerberus-source#394]
Hello,
In case of KO execution, it will be good to have the cerberus params, as ip address control and other.
example: 
testcase 5076A.
ko execution: http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=16215498
control in url made ko status, so we don't have ip address as url control killed execution.
regards

**Comment by vertigo17** [comment]
Feature already introduced in latest release.
