### ISSUE TITLE
[EDIT TESTCASE] Use all step of a testcase

### ISSUE THREAD

**Issue by giyome** [cerberustesting/cerberus-source#411]
In some testcase description, I would to use all step of an another testcase.

![hp_83](https://cloud.githubusercontent.com/assets/4654481/4738671/be1bf72c-59fe-11e4-959f-
4220d5378783.gif)

**Comment by bushybuffalo** [comment]
Hi, has there been any progress regarding this feature request ?
I was the discussing this matter earlier this afternoon with @abourdon as there are several people in my team who would really like to see it coming to Cerberus.
I see that it is currently listed in #575, still I have another idea:
We could create composite test cases, using test cases as their steps. 
Example:
I have a "login" test case, and a "check item in todo-list" test case.
To acces my todo-list page, I need to log in the app.
Currently, I have to drag and drop each step of the "login" test case in the "check item in todo-list" test case to log in the app.
Even if we get an option to add all the steps of the "login" test case at once, there might be a large amount of steps in this login tests cases, and it will take a lot of space on the screen, making it less obvious to determine the "core" part of our test case, which is to check an item in the list.
Using composite tests cases, we would still have a "login" test case, and a "check item in todo-list" test case, but the latter would not worry about logging in the app.
They would then be used as steps in a parent composite test case, "login" being followed by "check item in todolist".
One downside is that it increases the number of test cases in a test, but it also makes it easier to see what a test case does.
What do you think ?

**Comment by bcivel** [comment]
linked #1827
From Cerberus 4.0, it's possible to link testcase to achieve want you need to do
