### ISSUE TITLE
Be able to correctly display the property content on the execution detail page

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#435]
It could be great to correctly display the property content on the execution detail page, whatever the property content type. For instance, in case of XML value, then content is interpreted and then badly displayed. Here under an example with the comparison between what is the property content (from Firebug) and what is displayed from Cerberus:

![screen](https://cloud.githubusercontent.com/assets/1511715/4919907/0e82300a-64fe-11e4-8ec9-16ab0c1ce762.PNG)

In addition, it could be greater if Cerberus could displayed these information following the content type and then be able to colorize and format text acording to its type

Related to #269

**Comment by bcivel** [comment]
fixed on the new page
