### ISSUE TITLE
The verifyTextInElement control doesn't work on Select elements

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#485]
The verifyTextInElement control doesn't work on Select elements.

After investigation, it's due to the `WebDriverService#getValueFromHTML()` which throws a `ClassCastException` by doing an incorrect cast from `org.openqa.selenium.WebElement` from `org.openqa.selenium.support.ui.Select`

**Comment by htopoff** [comment]
Hi, 
I try to check which choice is selected on a <select> item with "verifyTextInElement" but it says that it can't find the element...
How can I test this ?
