### ISSUE TITLE
Integration options by global access

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#511]
It would be good to have Integration options (Status and Environments) by a global view, that could be based on the user access to the system.
This is an enhancement requirement.

I'm thinking on a rule to show information if user has access to the servlet and listing all the information related to the systems that the user as access to.
If the user does not have access to a system, no information would be shown related to that system.
On the systems menu, an entry like '*ALL' could be used, but could be something else.

**Comment by bcivel** [comment]
As discussed, it could be good to solve it giving the possibility to display the information on multiple system instead of one by one.

The change could be : 
> Change the selectbox (in the header) to allow to select multiple systems. (display only the allowed systems and not all the systems in this selectbox).
> On all the pages, show information based on the systems selected.

**Comment by vertigo17** [comment]
Closed with system management in 4.1
