### ISSUE TITLE
Call Soap with Attachment no more possible

### ISSUE THREAD

**Issue by bcivel** [cerberustesting/cerberus-source#550]
linked to #522 and #533

**Comment by abourdon** [comment]
@bcivel Is this bug still present?

**Comment by gjolie** [comment]
@bcivel @abourdon Has this bug been fixed? I need to test a SOAP Call with attachment, but it seems it's still not possible yet.

**Comment by abourdon** [comment]
Hi @gjolie,

No not yet. But I understand this is quite critical for you. I set priority to major and ask to the community to take your need into account.

@bcivel, @vertigo17 could you please have a look?

Regards,
Aurélien
