### ISSUE TITLE
Default reporting execution filters by user and system

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#551]
Since there are a lot of different systems which we need to see the execution reporting, it would be very nice to have default filters by user and system.
That would allow different filters for specific systems, avoiding to change filters every time we try to check executions on a different system.
Example: checking a build on system GUI is different from system CRM.
My suggestion is to use table `usersystem`, instead of table `user`.

Also, I verify that, on ReportingExecution page, button "Set As My Default Filter" is not saving the information.

**Comment by bcivel** [comment]
Hello @gmoita,
Is this issue still necessary? I guess since you use executionReportingByTag, you don't need this feature anymore.
Thanks.
Benoit

**Comment by bcivel** [comment]
The page doesn't exist anymore
