### ISSUE TITLE
Add the possibility to stop a campaign launched through Cerberus

### ISSUE THREAD

**Issue by MichaelWil** [cerberustesting/cerberus-source#585]
Hi,

When you run a whole campaign through the function "Run multiple tests" you have currently no way to stop this campaign.
You can stop all the tests that are running by clicking on "Admin", "Monitoring" and "Reset queue" but no way to stop ONLY a specific campaign.

Can you please fix that ?

Thanks.

**Comment by bcivel** [comment]
followed in this thread #914
