### ISSUE TITLE
Test case execution not taking "From Build/Rev" and "To Build/Rev" into account

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#595]
Cerberus Version : 1.1.3-SNAPSHOT

When executing a test case for a specific build/revision, the pre testing information is not taken into account.
Example-> test case PAGE VCCRM main/0001A for BE UAT should execute the following test cases: Pre Testing/0000A, 0001A, 0002A and 0003A
Example-> the same test case for BE QA should execute the following test cases: Pre Testing/0000A, 0001A, 0002A and 0003C

No matter the environment selected, it is always executed 0003A.

This will cause an issue in the future, as we need to change the pre testing behaviour.

**Comment by bcivel** [comment]
Today, the from build/rev to build/rev parameters are used at the testcase level before to start the execution to allow the execution or not.

What you expect is a bit different as you'd like to choose automatically one or another pretest regarding the from/to build/rev parameters.

I change the tag to enhancement

**Comment by gmoita** [comment]
Hi.
We have this need (it was needed when I've opened the issue) because the pretesting information is to be changed.
I was expecting that the behaviour could be similar, which is not.
If this is not solved quickly, then I'll have to say to the customer that he cannot change the application behaviour, as the test cases will just not work.
Alternatively, I'll have to deactivate the pretesting and change 669 test cases to include the pretesting behaviour, which is different from one country to another.
Also, I'm hoping that if the pretesting test case is not active, then it is not executed at all.
I consider this a bug and would like to have it working ASAP, to start testing it.

**Comment by bcivel** [comment]
I confirm that if a pretest is unactive, it won't be taken into account. 
Adding a different behavior in a pretest than the behavior in real testcase will be a mess to manage.
As you need temporarly to run one or another pretest regarding the version of your application, I would advice that you activate the new pretest and unactivate the old one manually running the campaign.
For the dev of this feature, we can start thinking something more generic which should work for testcase and pretest (something like a testcase version)

**Comment by gmoita** [comment]
Temporary solution it is not valid as the test cases will work on QA but will fail on UAT and PROD (I have tests running every 10 minutes in PROD), until the new version is moved to forward.
I'll check if I can do it other way, temporarly.
