### ISSUE TITLE
Not possible to view executions for Non-GUI applications on ExecutionStatus page

### ISSUE THREAD

**Issue by cjmachado** [cerberustesting/cerberus-source#613]
Related to #573 (which is currently closed).

It's not possible to view the executions of a Non-GUI application on ExecutionStatus page. Issue #573 fixed the problem on ExecutionReportingByTag but it's still not fixed on ExecutionStatus.

**Comment by vertigo17** [comment]
Status page is no longer maintained.
Please open a new ticket if you don't agree and feel the old status page is still necessary.
