### ISSUE TITLE
Ooops when copying step case from library

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#646]
Steps to reproduce: 
- add a new step to a testcase and choose usestep
- choose a step
- click on the checkbox usestep: warning dialog shows "Do you want to break the link between steps? If you select yes, when you save this test case, all actions and controls will be copied to the current test case." -> OK
- save TC: error
  ![oops500](https://cloud.githubusercontent.com/assets/1914659/11535788/557c951a-990d-11e5-93ef-408494d1c134.jpg)

**Comment by bcivel** [comment]
linked to #334
