### ISSUE TITLE
Property overwrite

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#656]
When a property is saved with a name already in use in TC, Cerberus delete previous properties without warning (for the same country).
Is this a feature or a bug?

**Comment by mbessa** [comment]
I think this is related so I add to this thread... 
If you have a property ex: test and try to rename it to TEST the property is deleted when you save TC. Neither property is present in test case after Save it.

In this case is really a bug, could you take a look at this issue?
Thanks

**Comment by abourdon** [comment]
Duplicates from #955. I prefer closing this one because of more details from #955.
