### ISSUE TITLE
Create new step from 1 library : import properties

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#666]
Cerberus Version : 1.1.3-SNAPSHOT

When we "save as" a test, properties are imported inside TC
When we create new step from a library, properties are ghosted to library by default.

Would be nice to give the option : "use step" + "use property"

Cheers,
PF

**Comment by abourdon** [comment]
Properties are used from the test case that contains the used step. If want to override it, then create a new property with the same name from the test case.

**Comment by pfoucray** [comment]
Yes, of course.
but if you have 10 properties to override, and have to copy this step several times, then I could be handy.
but it's fine like that :) that was just an idea
