### ISSUE TITLE
Refactor GUI : page User.

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#670]
Cerberus Version : 1.1.3-SNAPSHOT

Hi.
We get several requests to reset Cerberus user password.
We can set the password to be changed next time the user logs on, but we cannot reset the user's password.
Can you please implement this feature?

**Comment by vertigo17** [comment]
Please use a database update to perform that.
UPDATE user SET Password = SHA(newPass) , Request = Y WHERE Login LIKE ?
We will start implementing that once we refactor the user management page to the new standard.

**Comment by gmoita** [comment]
Usually I do it...
My purpose is to request an enhancement, so others can do it without manipulating the database.
As long as it is planned to be done, it suites for me.

**Comment by Foudro** [comment]
New page accessible via UserManager2.jsp. 

Do you still need this feature or the reset password previously implemented is enough?

**Comment by bcivel** [comment]
@Foudro I guess you're talking about feature to reset the user password?

For my point of view, no needs anymore since the forgot password investigation.
@gmoita could you confirm nobody request anymore to reset their password?
