### ISSUE TITLE
Obtain status response code and text

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#681]
Could it be possible to have a new  to Action or Type to get the response status code and response status text from a XMLHttpRequest?
Actually today there is a workaround using the type getFromJS and some JS code but it is not very  efficient because we have to do a new request and it does not work for .xml pages because some scripts cannot be executed.

**Comment by vertigo17** [comment]
Can you provide more detail on the action expected ?
For example provide the javascript that you execute or the testcase you want to simplify with this new action.

**Comment by ffazendeiro** [comment]
The main goal is to get the http response to check if the page is correctly loaded (response code 200 and text OK). Currently we are checking if the URL is correct but in some situation the URL stays the same and the page is not correctly loaded (for example a page with 404 Not Found error). To check if the page is correctly loaded we can also check if a certain element is present but this is not very reliable because the page can change and the element can no longer be present or being modified or have a different xpath.
The JS use is to get the http request is:
_var httpResponse = new XMLHttpRequest();
httpResponse.open("GET","%GET_URL%",false);
httpResponse.send( null );
return httpResponse.status;_
or using _return httpResponse.statusText_ to get the response text.
This works fine for example in .aspx pages but it does not work for .xml pages.
Seems that Cerberus needs a body tag to execute any JS.

**Comment by abourdon** [comment]
Can be done by using the `callService` action with a REST service.
