### ISSUE TITLE
step with Property unexistent still get it from another step attached to another TC

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#689]
Cerberus Version : 1.1.4-SNAPSHOT

Here's a tricky one.

1) You get a TC with a step with a property. That property isn't in the properties at the bottom of the TC page. The step is alone (no "use step", no link to any library). So the step will warn : property missing.

2) If you have another step in the same TC, and this other step is refering to another TC (usestep) and in this other TC you find the property first missing, then, the property won't be missing anymore !

3) Execution of the TC will seek for the property in the linked library, containing the missing property.

As a result : So to say : your step will show "property missing" (red warning panel) while the property will be found !

Hope it's clear enough !

**Comment by abourdon** [comment]
I agree this behaviour is quite weird. It is an edge effect of the property computation engine strategy. @vertigo17 @bcivel : what do you think to fix it? But if yes, then it could be a huge edge effect with existing test cases that use this "no-desirable-but-maybe-used" feature

**Comment by vertigo17** [comment]
I am not sure this is still the case.
On the old page we were not displaying the inherited properties.
Now we do so that should not be a huge effort not to disply the error if it exist on that list.
BTW, it may already be the case.

**Comment by vertigo17** [comment]
Just checked and the issue no longuer exist.

![2017-03-29 20_10_06-test case](https://cloud.githubusercontent.com/assets/5342048/24469447/c60947a8-14bb-11e7-8dff-7673302d7ba5.png)

The steps 1 & 2 are both useSteps.
No properties are defined on the testcase (all of them are in inheritedProperties).

%property.CHECK_MNT_ART_FAC% exist in used Steps --> No error reported.
%property.CHECK_MNT_ART_FAe%  do not exist --> Error reported.
