### ISSUE TITLE
TestAdmin autorities not working correctly

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#690]
Cerberus Version : 1.1.4-SNAPSHOT

We've been reported by some users (non TestAdmin users) that they are able to change test cases from "WORKING" to other status, which is not supposed to happen, according to previous requests and to the documentation.
When trying to change a test case from any status to "WORKING", the same user is not allowed to change the test case (this is the expected behaviour).
Please correct this.

**Comment by vertigo17** [comment]
Can you detail with which action/screen you manage to do those WORKING testcase changes with users that do not belong to TestAdmin ?
We need more detail.

**Comment by gmoita** [comment]
Action can be performed on TestCase page.
A user that is not TestAdmin can change the test case from WORKING to anything else (FULLY_IMPLEMENTED, for example) and save the test case.
After that, he can change the test case behaviour without anyone being "alerted".
However, the user cannot move the test case to WORKING if he is not TestAdmin.

**Comment by vertigo17** [comment]
I understood this is on the TestCase.jsp screen (not on the new TestCaseScript.jsp).
Correct ?

**Comment by gmoita** [comment]
It is on TestCase.jsp

**Comment by vertigo17** [comment]
I changed the new testcase page in order to secure that rule.
The scenario described is n longuer possible on the new page. Maybe still possible on the old one but it will soon disappear so we will not fix it.
