### ISSUE TITLE
Refactor GUI : page RunTest

### ISSUE THREAD

**Issue by vertigo17** [cerberustesting/cerberus-source#703]
Still Pending : 
- [x] Translate the page in french
- [x] labels come from documentation table

**Comment by ffazendeiro** [comment]
Hi,
Noticethat iIf we record a custom robot settings and after a new execution the values are not saved and the fields are disable:
![image](https://cloud.githubusercontent.com/assets/17747042/18707636/e5d33240-7fee-11e6-8247-8fa6de36d6b6.png)

**Comment by bcivel** [comment]
Still Pending : 
- [ ] Translate the page in french
