### ISSUE TITLE
manual execution no more possible

### ISSUE THREAD

**Issue by bcivel** [cerberustesting/cerberus-source#739]
Follow up
- [x] Display Button OK/KO/FA on execution detail when status is NE
- [x] Make the result message editable
- [ ] Allow to save screenshot
- [x] Back implementation for update
- [x] Create QU status for queued executions and redirect NE execution to manual execution page.

**Comment by abourdon** [comment]
@bcivel : Is this bug still present?

**Comment by bcivel** [comment]
Manual execution doesn't work at all. I rename the issue accordingly

**Comment by R-Loic** [comment]
Hello, 
Is this issue still present ?
Could you please have a look ?
Thank you !

**Comment by pfoucray** [comment]
Hi,
we just noticed the same, needing to make a demo for a client.
Do you have any idea of when the feature might come back ?

Best Regards,
Paul
