### ISSUE TITLE
Automatically update the license header

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#744]
It could be great if license headers will be automatically check and generated in order to be sure that every files are compliant with the license.

I've made a try on the [origin/license](https://github.com/vertigo17/Cerberus/commit/9a9d7f365bc5c85137a5a8144105745b2c769b05) branch by using the [com.mycila:license-maven-plugin](http://code.mycila.com/license-maven-plugin/) and if you agree, with could merge it to master.

Regards,
Aurélien

**Comment by abourdon** [comment]
@bcivel @vertigo17 this one could be quickly resolved if you go back to me ;-)

Cheers,
Aurélien

**Comment by bcivel** [comment]
go

**Comment by abourdon** [comment]
So it's resolved.

To sum up this commit:

- The `com.mycila:license-maven-plugin` is used to manage our license headers
- Any commit will fail if at least one file does not have a correct license header
- License header is represented by the current `source/licenseheader.txt` file. So beware if you want to modify this file. Note that **comments has been removed, because automatically handled by plugin in order to fit with other file type as Java (it works file XML files for instance). This file only contains license header text. So, do NOT directly use it with your IDE as usual** (especially for you @bcivel and @vertigo17), but prefer use the following commands:
- Two useful commands:
        - `mvn license:check` to check if headers are correctly set on files
        - `mvn license:format` to automatically add or modify files to correspond to the `source/licenseheader.txt` file
- Read the plugin configuration for more details (into the `source/pom.xml` file)

Regards,
Aurélien
