### ISSUE TITLE
Link to TestData

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#747]
In the test run properties, would it be possible to add a link do the respective testdata/testdatalib already filtered?
For example, click on the P_PA_RDT_AVL would open the testdata page already filtered by P_PA_RDT_AVL. 
![getfromtestdata](https://cloud.githubusercontent.com/assets/1914659/14911188/9c31531c-0deb-11e6-97f6-0a641d22d658.jpg)

Thanks!!

**Comment by vertigo17** [comment]
We can do that but only on testdatalib that will replace TestData.

**Comment by ruirpr** [comment]
OK, it will help, thanks!

**Comment by vertigo17** [comment]
I close this one as #1363 has a better specification.
