### ISSUE TITLE
Use JPA for data access

### ISSUE THREAD

**Issue by nmervaillie** [cerberustesting/cerberus-source#750]
Development could be more efficient if you used JPA for data access instead of plain jdbc.

I can submit a pull request as a showcase

**Comment by abourdon** [comment]
Can be closed as there is a new pull request which use JPA and Spring Data Repository with a full concrete example: https://github.com/cerberustesting/cerberus-source/pull/1232

Thanks for the nice work @nmervaillie ;-)

Aurélien
