### ISSUE TITLE
Action KeyPress / Minor Bug

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#760]
Cerberus Version : 1.1.4-SNAPSHOT

When you just put a valid Xpath using KeyPress, Execution goes Pending (action never ends)

Regards,
PF

**Comment by vertigo17** [comment]
Can you provide the example of testcase that generate that issue ?
Test + TestCase + PE Execution ID
Thanks

**Comment by pfoucray** [comment]
Hi,
here's what I have
I changed the TC in between, but still got the execution report :
http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=32222682

regards,
pf

**Comment by abourdon** [comment]
Cannot reproduced
