### ISSUE TITLE
TC Script Beta / Delete Action + Contrôls --> Bug

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#761]
Cerberus Version : 1.1.4-SNAPSHOT

When trying to delete 1 action with contrôls, get the following message in red box on top of page

PARSERERROR - SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

EDIT / Sometimes it works, sometimes not.

regards,
PF

**Comment by vertigo17** [comment]
I cannot reproduce the issue.
Please provide a testcase where we can replicate with action to delete to reproduce.

**Comment by pfoucray** [comment]
My bad,
did not mention it was on the beta page.
So you just add one action, type any description to it, press twice enter to add a control. Type any description.
Try to delete the action (which includes the contrôl automaticaly)
click save script.
Get the error

regards,
pf

**Comment by bcivel** [comment]
fixed
