### ISSUE TITLE
Test execution ends when timeout is exceeded.

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#765]
Test execution ends when timeout is exceeded. 
![image](https://cloud.githubusercontent.com/assets/17747042/15253728/7d582e2a-192b-11e6-80be-4dcafe69424e.png)
For some actions it would make sense that when the timeout is reach the test should be able to continue (go to the next action or control).
For example: In action openUrlWithBase sometimes the page takes a longer time to load than the set timeout (for example due to an synch tag). In this case it would make sense to continue executing the test.
This would only be applicable to some Web related action like openUrl, openUrlLogin or openUrlWithBase

**Comment by vertigo17** [comment]
Can you share with Michael and propose a rule ?
I can propose to you both f you agree : 
we create 3 new parameters : 
selenium_defaultWait_openUrl
selenium_defaultWait_openUrlWithBase
selenium_defaultWait_openUrlLogin
if param = FA, we fail the action if not, we would leave the execution to the next action.
Please confirm or propose a new rule.

**Comment by ffazendeiro** [comment]
Hi,
The implementation of those three new parameters would be a very good idea. This way we could better manage the default timeout for those unique actions.
Nonetheless could those actions not be blocking to the tests? Meaning that if the action is not complete after the defined timeout the test should continue (that action could perhaps have the status FA) and would proceed to the next action/control.
In the end the global result of the test would be OK. It would not consider the fail openUrl action (this action is not considered critical and there will be always a control or another action after it). Not sure about the impact of this last request (may lead to false OK perhaps but the idea is to bypass pages that takes too long to be fully loaded due to external elements). What do you think?
Thanks.

**Comment by bcivel** [comment]
cerberus_action_wait_default  > Default value, (Integer in ms)
cerberus_selenium_pageLoadTimeout (Integer in ms)
cerberus_selenium_implicitlyWait (Integer in ms)
cerberus_selenium_setScriptTimeout( Integer in ms)
cerberus_selenium_wait_element (cerberus_appium_wait_element ) (Integer in ms)
cerberus_action_openURL_behaviour_on_timeout  (default FA, or OK)
cerberus_action_openURLWithBase_behaviour_on_timeout (default FA, or OK)
cerberus_action_openURLLogin_behaviour_on_timeout (default FA, or OK)

**Comment by abourdon** [comment]
Hi @ffazendeiro,

Your issue is strongly related to the use of openUrl* actions. These actions wait for the complete load of the associated page to go ahead.

Thanks to #819, you can (by specifying it) now ignore action failures and go ahead the test case execution. This improvement can help you to deal with openUrl* actions which fall in timeout. Is it ok for you?

Nevertheless, it could be interesting to let user to set properties listed by @bcivel. I removed those which are not necessaries thanks to #819 resolution.

Regards,
Aurélien
