### ISSUE TITLE
Refactor GUI : page Database Maintenance

### ISSUE THREAD

**Issue by vertigo17** [cerberustesting/cerberus-source#789]

**Comment by bcivel** [comment]
Changed menu and style.
kept functionnal as it was. Will be refactored (probably removed) managing the database with liquibase.

**Comment by bcivel** [comment]
Forgot the translation :-)

**Comment by vertigo17** [comment]
Database maintenance translation is optional (because when database is initialised, documentation table does not exist).
This is even safer to leave that page in english only.
