### ISSUE TITLE
home page / last tags

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#806]
Cerberus Version : 1.1.4-SNAPSHOT

Here's an evolution that could be handy :) (top prio)
It would be so good to have our "customized tags" updated everytime the campaign is ran.
Lotta people have tags like "testname_yyyymmddhh" and the customized is only available for one day (if you run your campaign everyday)

What about subscribing to a campaign, that finaly generates a tag, and then put the last execution tag on home page?

keep up the good work :)
regards,
PF

**Comment by abourdon** [comment]
Solution is to always use the same tag for your campaign and see the execution report by tag changing day after day.

Closing this one.

**Comment by vertigo17** [comment]
Well I don't agree with that last comment. Even if it will work ;-).
For me we should keep tag to identify a set of execution in a limited timing.
Longuer term will be to save the campaign information on each execution (no matter the tag) and beeing able to filter the latest tags on that campaign.
We will reopen a ticket like that later as this is currently not the priority.

**Comment by pfoucray** [comment]
Indeed.
Moreover, if you always keep the same tag, then you don't directly have access to previous campaigns (you can only see TC by TC the histo of execution).
But I strongly agree on the mix : only one tag campaign with a filter by date. That's even better !!

Hope you guys are doing well, missing you ;)
Pf
