### ISSUE TITLE
Restrict the right to create UseStep in library

### ISSUE THREAD

**Issue by MichaelWil** [cerberustesting/cerberus-source#812]
Hi,

Today it seem that too many persons can create UseStep. As a matter of fact the current library is so huge that it's quite difficult to find the UseStep wanted.

So the first step is to restrict the right not to allow anybody to create new UseStep.
Should this specific right only allowed for "Test Admin" or for a new specific group ... i'll let you choose the better way.

Taking into account that this 1st step will be followed by another one aiming as ease th search (specific search engine ?).

Thanks

**Comment by abourdon** [comment]
I don't think it is a good idea to restrict this common usage to a set to user. @bcivel, @vertigo17 I propose to close this one

**Comment by bcivel** [comment]
I would agree with @MichaelWil.
It could be useful to restrict to test admin user to avoid duplication in libraries

**Comment by vertigo17** [comment]
We will create a new group for that purpose.
TestStepLibrary: The group will allow to flag a step as Step Library (Clicking on 'Is Library' Button at Step level). User that belong to that group will also be allowed to modify steps that are flaged as beeing In library ('Is Library' button checked at Step level) and allow to modify useSteps.
