### ISSUE TITLE
Improve the search of a specific usestep in the library

### ISSUE THREAD

**Issue by MichaelWil** [cerberustesting/cerberus-source#817]
Hi,

When you are in a testcase a button "Show/hide library" is displayed. When you click on it there is huge number of labels that are displayed.
Currently there's no other way to search for a specific use step to use the scroll bar.
Could you please try to add one or both solutions 
1- put a search engine working on each place of the whole label (not only the 1st word)
2- add radio button to select the required chanel (mainsite/mobile/apps) and then it'll only displayed the concerned use step.

Fell free to come back to me if you need any clarifications.

Thanks and regards.

**Comment by Foudro** [comment]
related to #575

**Comment by bcivel** [comment]
Hi @MichaelWil ,
On the new page, you have now a search engine for use step searching as requested.
Thanks
Benoit
