### ISSUE TITLE
Create Object Library

### ISSUE THREAD

**Issue by bcivel** [cerberustesting/cerberus-source#856]
It could be useful to store the object into specific library. Today, to use this kind of functionnality, people usually use properties, which does not really make sense.

This library could be at the application level (not sure yet if we should put it at the country level) in a  new table with a format like (ID, Application, Object, Value).

Object from the library could be called from the action field with a specific identifier (object=)

> For example
> Action : Click     Object :  object=LoginPage_PasswordField
> Would be decoded by the engine id=password

Waiting your feedback and a conception review to validate or not this feature.

**Comment by abourdon** [comment]
I agree, this feature could be interesting especially to reuse action from other test case.

I would go further by defining an object as the combo between an `Application` and a `Country`. Especially because action is sometimes related to a country. But, warning, it could be hard to understand difference between an `Object` and a `Property` because we could do the same things with either.

Regards,
Aurélien

**Comment by bcivel** [comment]
To specify a bit, I identified that changes : 

Step 1 : 
- Database Change 

Create table **ApplicationObject**

ID _INT_
Application _varchar(200)_
Object _varchar(150)_
Value _text_
ScreenshotFileName _varchar(250)_
UsrCreated _varchar(45)_
DateCreated _timestamp_
UsrModif _varchar(45)_
DateModif _timestamp_

_Unicity on Application,Object_
_ForeignKey on Application name_

- Engine change 

New identifier _object=_ that pick object on ApplicationObject

- GUI Change

New page ApplicationObject to be created

Step 2:
- GUI Change

Testcase that display picture if exist

- Store Files

I propose that we give the possibility to upload/manage screenshot

**Comment by Foudro** [comment]
**Application Object**

- [ ] New Page of Application Objects
- [ ] Upload photos

**Variables**

- [ ] New Service that group the interpreted variable of Cerberus
- [ ] New Service that translate variable in application object data
- [ ] Modify Property Service so it understand the new syntax
- [ ] Add autocompleter for variable in TestCase.jsp
- [ ] Add autocompleter for variable in TestCaseScript.jsp
- [ ] Differenciation of end of variable or not in autocomplete

**Comment by bcivel** [comment]
Complete. Thanks @Foudro
