### ISSUE TITLE
Test execution fail with new Selenium version

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#859]
We are having a lots of test FA with the new version of Selenium (2.53).
Seems that now cerberus is not able to write on some text box if it is not in front.
With the 2.44 version it could write with no problem:
![image](https://cloud.githubusercontent.com/assets/17747042/16765668/4ef33eae-482d-11e6-8e24-b9f77d95a5ab.png)
Test execution with new Selenium version (2.53):
http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=34233264
Test execution with old Selenium version (2.44):
http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=34233217

New version have also some difficulties on clicking on some elements. for example, although in the test it say it clicked on the element //div[@data-cerberus='dropdown_plpProduit_brandFilter1']/dl (brand filter drop box) this one is not expanded:
![image](https://cloud.githubusercontent.com/assets/17747042/16765965/f213334a-482e-11e6-98a9-28b6421db120.png)
Test execution: http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=34233918

**Comment by abourdon** [comment]
Since https://github.com/cerberustesting/cerberus-source/commit/ae9d5898ef42eb41ad68e4636c05246cf1530b59, installation instruction list the compatible version between Selenium and browsers.
