### ISSUE TITLE
TC Page / new use-step empty before save

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#870]
Cerberus Version : 1.1.5-SNAPSHOT

When creation of a new library into libraries TC that will change order of libraries, if you change "use-step" into a child TC, it'll show empty (no action and control) until you save your TC.
Not a big deal ;)

Regards,
PF

**Comment by bcivel** [comment]
Hi @pfoucray ,
We won't solved as this page is now deprecated, and will be removed in short term.
Thanks for the contribution
Benoit
