### ISSUE TITLE
How verifyElementClickable / verifyElementNotClickable  works? 

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#895]
Hi, 
you can see in this execution http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=35723216 that verifyElementNotClickable fails and cerberus says it is clickable. 
So, if it is, cerberus should be able to click on it. But when trying to do that in execution http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=35724393 cerberus says that could not find the element.
It seems contradictory. 

page tested: http://preprod.laredoute.fr/ppdp/prod-500461981.aspx?docid=00000000000001 and the element is the disabled add to basket button in redoute vendor.

**Comment by bcivel** [comment]
Hello,
There was a mistake on the verifyElementNotClickable implementation. In fact, today, it wait for the visibility of the element without checking the clickability. So it why it said element was clickable even if it wasn't.
It is corrected with my last commit

**Comment by bcivel** [comment]
Sorry, i will revert my commit. Previous implementation was the good one.
I will chec if we have bug in selenium 2.53

**Comment by bcivel** [comment]
Hi @ruirpr ,
VerifyElementNotVisible, VerifyElementNotClickable, VerifyElementNotPresent are now waiting until the invisibility of the element, the disablility of the element or the absence of the element.
