### ISSUE TITLE
Refactor GUI : page SOAP Library

### ISSUE THREAD

**Issue by vertigo17** [cerberustesting/cerberus-source#898]

**Comment by Foudro** [comment]
New SQL and SOAP Libraries pages accessible via : 
SqlLibrary2.jsp and SoapLibrary2.jsp

For Soap I'm not sur that truncate the enveloppe in the table is the best way to display this cell but I didn't find a better way to display it. (Tooltip and scroll aren't great, for now the only way to see the full envelope is to click on edit or show)

**Comment by bcivel** [comment]
Hello @Foudro ,Looks good thanks.
Small bugs : 
- when trying to create or update sql library with % in the script, the entry is not created and the modal never disapear.
- encoding problem with special character (' , " at least)
