### ISSUE TITLE
Is REST/json api call implemented ?

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#907]
Hello,

Can we already do Rest/json api call ?
We can do Soap call within TestDataLib, but i dont know if we can do REST call.

Thank you

Victorien

First DRAFT of spec:
1/ Actions
- [x] callService

2/ Properties
- [x] Secure that getFromXml is plugged to result from callService
- [x] Move Value1 to Value2 and Value2 to Value1 in order to have Value2 optional. Today Value1 is optional. When Value2 is not feeded, we take the current XML result.
- [x] Secure that getFromJson is plugged to result from callService
- [x] Move Value1 to Value2 and Value2 to Value1 and make Value2 optional. When Value2 is not feeded, we take the current JSON result.

3/ Library
- [x] Rename SoapLibrary to Service Library in order to mutualise the SOAP/RESTXML/RESTJSON requests.
- [x] Add type SOAP/REST
- [x] Add method POST/GET
- [x] Update engine in order to support REST. Adding http client maven dep.
- [x] Add header table with key / value / enable
- [x] Add body table with key / value / enable
- [x] Save request structure in a clever way save only data called.
- [x] Solve refresh file on websocket
- [x] timeout call parameter. cerberus_callservice_timeoutms default to 60000 ms
- [x] activate traca header parameter. cerberus_callservice_enablehttpheadertoken
- [x] Get answer Code and content-type.
- [x] Merge structure with SOAP Calls
- [x] GUI - Solving encoding issue on Service Path
- [x] GUI - add header and content on service modal
- [x] Guess content type from http header answer

4/ Controls
- [x] Enable support for verifyElementPresent verifyElementNotPresent verifyTextInElement verifyTextNotInElement control also for JSON data.

**Comment by bcivel** [comment]
Hello Vito,

Unfortunatelly, for the moment, you can only use the getFromJson property type, putting an URL as value1 and a jsonPath expression as value2.

We target to implement Rest/json call to get data from dataLib, but also to test rest/json services (which is a different implementation). We can implement in priority regarding your needs.

Are you targetting to test Rest/JSON service, or you only need to call rest/json to get data?

**Comment by vitoo** [comment]
Hello Benoit,

We test Rest API using postman/newman currently.

Thanks for the tips with getFromJson, it will be enough for now.

Best regards

**Comment by vertigo17** [comment]
First DRAFT of spec:
1/ Actions
- [ ] callRestJson
- [ ] callRestJsonWithBase
- [ ] callRestXml
- [ ] callRestXmlWithBase

2/ Properties
- [ ] Secure that getFromXml is plugged to result from callRestXml & callRestXmlWithBase
- [ ] Move Value1 to Value2 and Value2 to Value1 in order to have Value2 optional. Today Value1 is optional. When Value2 is not feeded, we take the current XML result.
- [ ] Secure that getFromJson is plugged to result from callRestJson & callRestJsonWithBase
- [ ] Move Value1 to Value2 and Value2 to Value1 and make Value2 optional. When Value2 is not feeded, we take the current JSON result.

**Comment by abourdon** [comment]
I don't really understand what these actions will do. Is any action will be linked to a given SOAP or HTTP library? If yes, do we also need to develop the HTTP library interface?

In addition, I propose to remove the 'Rest' word. Actually, we just want to make calls over SOAP or HTTP protocols and not especially following the REST architecture.

Regards,
Aurélien

**Comment by abourdon** [comment]
My bad, my mail client was not displaying the entire message... so forget my first paragraph...

Just remove remove the 'Rest' word will be enough ;-)

**Comment by abourdon** [comment]
I will also add the neee to handle HTTP headers (from request and response) from the HTTP TestDataLib interface.

**Comment by vitoo** [comment]
Some useful requirements 
___
HTTP method : GET, POST, PUT, PATCH, DELETE 
And some other rare/new method : COPY HEAD OPTIONS LINK UNLINK PURGE LOCK UNLOCK PROPFIND VIEW
___
Dynamic header (be able to set variables, parameters)
ex : 
```
Authorization: %authorization%,
CodePays: %codepays%,
Content-Type: application/json
```

___
Dynamic optional body (ex : json )

```
{
    "numberPlate":"%numberPlate%",
    "specificNumber":"%specificNumber%",
}
```
___
Be able to get the HTTP response code (200, 404,500...) to control it
Be able to control the json response 

To set a variable from the json response and reuse it in a another Http request

**Comment by abourdon** [comment]
I agree with @vitoo requirements

**Comment by ping0uin** [comment]
Hi,

Any news about this issue?
Did you start to implement it or not at all?

Thanks a lots for your answer.
Regards.
Marc.

**Comment by bcivel** [comment]
Hi @ping0uin 
Still a lot of pending stuff to do.
You can already call simple HTTP using GET and parse XML or JSON.
Full implementation will be definitly one of the next priority for Cerberus

**Comment by vertigo17** [comment]
Closing now the issue as it should be fully functional.
Please reopen other issue in case some features are missing or not properly working.
