### ISSUE TITLE
Be able to tune the number of simultaneous executions by "execution group"

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#914]
Now, we are using a **single execution queue** to handle any Cerberus execution. Thus, there is a single parameter, the `cerberus_execution_threadpool_size`which is responsible to limit number of simultaneous Cerberus executions.

Tomorrow we would tune the number of simultaneous Cerberus executions by "execution group", or let's say more simpler: by **tag** (or maybe by: (application, country and environment)).
Then the problem is: how could we tune a single execution queue, associated to a global parameter, for a dedicated tag?

We could address this need by **dedicating one execution queue by a given tag**.

Then, this way, we could:
- Handle different number or simultaneous execution by tag
- Remove the need to priorize Cerberus executions, as any execution will be associated to a tag (or not if it is an unitary execution) and then to a specific execution queue and not to a single common one.

Let me know,
Aurélien

**Comment by bcivel** [comment]
So if I understand well, you propose to : 
- don't use anymore a **singleton** to manage the queue, but to instantiate _new queue object every time_ we have a new tag for example. 
- The size of each queue can be different regarding the capacity of the tested application (set in parameter and overridable at the execution).
- Each queue can be paused or canceled independently (simply killing the object).
- you use this queuing process for all execution submitted by the GUI. RunTest servlet is no more called by the GUI but only by script or queuing process. 

it make sense for me.

**Comment by vertigo17** [comment]
I think we need to share that feature live before implementing as in m point of view we should make no link between the queues and capacity to treat the queues.

**Comment by abourdon** [comment]
Todo:

- [ ] Conception schemas
- [ ] Set _Proceeded_ mechanism to _State_ mechanism
- [ ] Handle multiple `ExecutionThreadPool` from `ExecutionThreadPoolService`
- [ ] Add pool size parameter from the Application's Environment page and makes `ExecutionThreadPool` aware of changes

**Comment by abourdon** [comment]
The two new servlet `ReadExecutionPools` and `RemoveExecutionPool` have been added in order to get execution pools statistics and remove execution pool.

Last comment has been updated with additional actions.

**Comment by abourdon** [comment]
A queue can now be fully removed and paused/resumed, thanks to the `ManageExecutionPool` (formerly `RemoveExecutionPool`).

Hereafter an example of usage:

HTTP verb: `POST`
Request body: 
```bash
{
    "action": "PAUSE",
        "executionPoolKey": {
            "system" : "MySystem",
            "application" : "MyApplication",
            "country": "FR",
            "environment": "PROD"
        }
}
```

Then the execution thread pool associated to the system _MySystem_, application _MyApplication_, country _FR_ and environment _PROD_ will be put in pause.

**Comment by abourdon** [comment]
The `ReadExecutionPool` servlet is now created to get information about a given Execution thread pool.

Hereafter an example of usage:

HTTP verb: `POST`
Request body: 
```json
{
    "system" : "MySystem",
    "application" : "MyApplication",
    "country": "FR",
    "environment": "PROD"
}
```

From now, this servlet gives the list of queued/executing tasks registered to the requested Execution thread pool:

```json
{
    "QUEUED": [ ... ],
    "EXECUTING": [ ... ]
}
```

**Comment by abourdon** [comment]
The `UpdateExecutionInQueueState` servlet is now created to handle `TestCaseExecutionInQueue`'s `State` settings.

Hereafter an example of usage:

HTTP verb: POST
Request body:
```json
{
    "state": "WAITING",
    "ids": [1, 2, 3]
}
```

Expected result:

```json
{
    "inError": [2]
}
```

**Comment by abourdon** [comment]
GUI are now usable with the following actions:
- Set selected executions in queue state to WAITING or CANCELLED in order to respectively put execution in queue in waiting for execution or cancel queued execution in queue from execution
- Run selected in waiting execution in queue
- Delete selected execution in queue

From commits fb85a7dcc9e4a207c5fe69714ecefc02f6e8698b 427ced2017ae09b3383374be81cc14045188762e

**Comment by abourdon** [comment]
A queue pie can be now clicked and the execution pending table will be filtered

**Comment by abourdon** [comment]
@bcivel, @vertigo17: I'm going to close the last task for this issue : only use the execution thread pool for any execution submitted by the GUI. Then, RunTestCase will not be directly called from GUI, even if only one execution has been submitted.

Could you please (re)confirm this action? Then I will commit change (minor modification, can be reset easily)

Regards,
Aurélien

**Comment by abourdon** [comment]
This issue can be closed as behaviour is as expected and no errors has been reported after a long time use.
