### ISSUE TITLE
Which selector to use with Appium iOS ?

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#926]
Hello :)
## Environment:

Cerberus 1.1.5 / Cerberus 1.1.6-SNAPSHOT
## Issue :

In Android Apps, they are many id to select elements. In iOS app we see with the inspector that they are name, label attributes instead of id. 

It looks like the `name=text` cerberus selector is not compatible with Appium 1.5.x  (not found error). 

Which selector should we use in cerberus with Appium iOS ?

Thanks,

Victorien

**Comment by bcivel** [comment]
Hello @vitoo 
Selectors _name=_, _id=_ and _xpath=_ should still works on appium 1.5.x.
Are you sure the element you're looking for is present? Do you have a bit more details for us to analyze?
Thanks
Benoit

**Comment by bcivel** [comment]
Hi @vitoo 
I close that issue. Fell free to reopen if you have problem.
Thanks
Benoit

**Comment by vitoo** [comment]
Yes, we dont test iOS theses days

**Comment by vitoo** [comment]
Hello, @bcivel 

Can you give an example of selector that you use with iOS ?

We only could use the xpath, `xpath=//UIAApplication[1]/UIAWindow[1]/UIASecureTextField[1]`

Can't use with success the name= ...

**Comment by bcivel** [comment]
Hi @vitoo 
In our test, we mainly use xpath to select element : 

 - For example : 
`xpath=//XCUIElementTypeButton[@label='topbar ico back ios']`

I'll have a try to validate the selection by name still working or not. I'll keep you informed.
Anyway, you can already try to reduce your xpath using 
`xpath=//UIASecureTextField[@name='vitoo']`

**Comment by vitoo** [comment]
hi @bcivel 

it works with @label but not @name for me 

`xpath=//*[@label='email']`

**Comment by bcivel** [comment]
@vitoo , can you clarify which message do you have when you said not working? I guess you have the message "could not find element xpath=//tototutu....."

Below an example here where selecting element using name is working.
So, I have one doubt : 
 - Are you sure you don't have another element with the same name that the one you try to reach? If yes, Appium will try to use the first one it find, and then fail if element not visible for exemple.

<img width="828" alt="capture d ecran 2017-01-31 a 11 38 55" src="https://cloud.githubusercontent.com/assets/5376184/22461737/bd68e470-e7aa-11e6-9570-d4755b92ec08.png">

Could you use the execution option `page Source on every action` to get the source and verify element you're trying to reach is present and unique.

**Comment by vitoo** [comment]
Yes i'm wrong i think it was `name=toto`
`xpath=//*[@name='toto']`  is working 

are you using iphone simulator on Mac ? 

It's very slow on a Mac Mini, the simulator is always rebooting, it takes much times between 2 tests

**Comment by bcivel** [comment]
OK, so I'll check `name=toto` to give you feedback.

We currently use real device. In the past, we checked on emulator and we saw that it was a bit slow but usable. But it was on a macpro. I can understand on a mac mini, running xcode, appium, emulator is too much consuming.

**Comment by vitoo** [comment]
On a real device, it looks like the app must be signed with a developper profile, maybe built in a debug mode

Our dev build the .ipa in release mode, really tricky & borring ... do you know about it?

**Comment by bcivel** [comment]
Yep, it's a bit tricky :-)

You can find documentation on settings and tools to install there:
https://cerberustesting.github.io/documentation_en.html#_appium

**Comment by vitoo** [comment]
YUNO index page ? https://cerberustesting.github.io/ 😃

**Comment by vitoo** [comment]
We are stuck with Xcode 7, it's bad ?

**Comment by bcivel** [comment]
No, It's not a shame :-)

In fact, the documentation we did explain how to install environnment to test on ios10 because it was missing on the web (because too recent).
If you're still on ios7/8/9, it's not necessary to migrate xcode, appium....and the all stack.

You have plenty of documentation. We will update ours to put some link (for example http://toolsqa.com/mobile-automation/appium/appium-test-on-real-ios-device/ )

So yes, you need to sign your app with developper account, and install some extra tools like ios-debug-proxy...etc

**Comment by vitoo** [comment]
Okay i've OS X el capitan, v10.11.5, i'm following the doc
