### ISSUE TITLE
Labels // And / Or

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#930]
Cerberus Version : 1.1.6-SNAPSHOT-928

Hi,

Thx for the Label feature in the Test Case List Page !
That would be awsome if we could choose "and" or "or" in the filters.

Here is an example from Microsoft Excel !

![cerberus labels and or feature](https://cloud.githubusercontent.com/assets/16115517/18705149/56abb872-7fed-11e6-990b-cb3717dff378.png)

Keep up the nice work !
Best regards,
PF

**Comment by abourdon** [comment]
Hi @pfoucray,

Sorry but we only trust in open source softwares. So what about [LibreOffice Calc](https://fr.libreoffice.org/discover/calc/)? :-D 

Nice issue, we will work on it.

Regards,
Aurélien

**Comment by bcivel** [comment]
Hi @pfoucray 
As discussed, it make no sense for most of the columns to filter with AND (for exemple, you will never find a testcase that is active=Y and active=N).
The only columns where it make sense is label (in testcaselist page), because it contains a list of testcaselabel.

**Comment by abourdon** [comment]
Currently, the filter action can be used to, as its name indicate, filter data. In the test case list page, labels can be filtered as any other attribute (test name, application, etc.).
Each time a filter is applied, then result is restricted to the combination of all filters. At a time, we can so have all the possibility we want to have. For different filter combination at a time, it is also possible to open additional tabs to the same page.

**Comment by simondz** [comment]
Hi @bcivel 

Is it possible to search on the testcase list page for OR and AND and 'AND Exclusive' requests on labels (just on labels)?

For example :
> If the search contains [LABEL01 I LABEL02] the result returns the CT containing at least one of the 2 labels
> If the search contains [LABEL01 LABEL02] the result returns the CT containing these 2 labels
> If the search contains [LABEL01 + LABEL02] the result returns the TC containing only these 2 labels
