### ISSUE TITLE
Error timeout javascript

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#947]
Hello,

Since the last release, I have sometimes error for javascript : 

![errorjs](https://cloud.githubusercontent.com/assets/18569182/18879803/ecdbed2a-84d5-11e6-8ffb-37e0a2ded523.JPG)

there is a timeout for this property whereas for another test case everything is OK : 

![jsok](https://cloud.githubusercontent.com/assets/18569182/18879859/1c72515a-84d6-11e6-999b-c819b0cbe6f4.JPG)

Test case OK : 
http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=37115291

Test case FA : 
http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=37115289

For my campaign (35 test cases) 6 are FA because of this error and the others are always OK. (Javascript control is the same)

Thank you

Cerberus Version : 1.1.6-SNAPSHOT

**Comment by bcivel** [comment]
Should be fixed removing since you're able to tune the timeout of the implicit wait.
