### ISSUE TITLE
Timeout of 180 min

### ISSUE THREAD

**Issue by MichaelWil** [cerberustesting/cerberus-source#950]
Hi,

In some executions a specific instruction was add right after the "PE" for the "Exe RC" file which is "Stop page loading if applied".

In some cases this instruction is not working properly as it may be processing up to 180 min as you can see in this execution.

http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=37148634.

Can you please take a look and advise ?

THanks in advance.

Another issue will be open to avoid using that instruction.

**Comment by pfoucray** [comment]
Same there.
Adding a screen shot :
![image](https://cloud.githubusercontent.com/assets/16115517/20662608/5b6e56b6-b554-11e6-8e0b-c258b888b038.png)
In this TC, element isn't found in the page. Should fail after timout. But it won't.

Keep up the good work !
Best regards,
PF

**Comment by pfoucray** [comment]
I got here a very good example. Scenario is : you are on a product page, want to click on color (then would be click on size and click on button add product to basket".
1st example : we get 180minuts timeout. Xpath is visible and clickable. --> BUG
2nd example : we get 2minuts timeout. Xpath is not visible, not clickable. --> expected cerberus behaviour

1)
![image](https://cloud.githubusercontent.com/assets/16115517/20703486/180e821a-b61c-11e6-8324-21187f81e1f1.png)

2)
![image](https://cloud.githubusercontent.com/assets/16115517/20703573/75f3d826-b61c-11e6-8806-26fd47e95201.png)

Best Regards,
PF

**Comment by bcivel** [comment]
Should be fixed adding an extra timeout control on click action (which was the unique one that fail due to some selenium bug)
Don't hesitate to reopen if you find one case again
