### ISSUE TITLE
Skip Control Feature / Bug

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#969]
Cerberus Version : 1.1.6-SNAPSHOT

Hi,

when using the skip control feature, if your control goes NA, then the skip control feature isn't realy skipped.

For instance : you have an sql request that return no data, you'll get NA.
Execution will first calculate the property, and finaly read all the steps, actions and control.
Arrived at the skipped control, it'll show NA because the property was already NA.

![skip control na](https://cloud.githubusercontent.com/assets/16115517/19266624/a4cf4eb6-8faa-11e6-881d-cefbb697c136.png)

regards,
PF

**Comment by vertigo17** [comment]
The clean way to implement this is to create ConditionOper and ConditionVal1 at control level.
We should avoid to hard code that skipControl do not decode value1 and value2.

**Comment by vertigo17** [comment]
Please no longuer use skipAction or SkipControl feature and use the conditionOper = never in order to desactivate the execution of the control or action.
