### ISSUE TITLE
Need new feature to update Elastic Search

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#970]
Hello, 

I'm working on Elastic search and I need to update it from Cerberus.
I have to use curl PUT and POST actions.

here, you will find examples of scripts I will use to update ES.  Could you please add this feature on Cerberus ?

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html

thank you.

Cerberus Version : 1.1.6-SNAPSHOT

**Comment by abourdon** [comment]
From my point of view, this feature is not specific to ElasticSearch, but related to the need to make and check calls over HTTP, as the #907 explains.

**Comment by bcivel** [comment]
Hello @R-Loic 
I close the issue as we follow the development of this feature with the ticket #907 
Don't hesitate to join the discussion on this issue.
Thanks
Benoit
