### ISSUE TITLE
"Run the same test case again" => can it select the same robot  ?

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#973]
Hi,

It does not select any robot, "Custom configuration" is selected, with parameters input disabled 

![image](https://cloud.githubusercontent.com/assets/995694/19354866/87daed82-9168-11e6-9e64-a8ef44a1ce12.png)

Thanks for your help 

Victorien

**Comment by bcivel** [comment]
Hello @vitoo 
It should be fixed now.
Note that if you use "run the same test again", the robot settings (at least for IP/PORT) will be those  recorded as your preferences.
Thanks
Benoit
