### ISSUE TITLE
New Control and/or Action : SQL verify data exists / SQL Select

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#974]
Cerberus Version : 1.1.6-SNAPSHOT

Hi,

First proposition :
A control : same spirit as HTML Selenium "verify element present", we could use
"SQL verify data exists".

Indeed, today, when we use SQL Select (calcultate property + ExecuteSql property), if we try to select a data in a row that doesn't exist, it ends with a "NA" (could not find the data blablabla).
So what we do today is in the step
1. Action "calculate property" ExecuteSql with a select count(*)
2. Control : verify string different from "0" (zero) fatal (Y)
3. Action"calculate property" ExecuteSql with a select
   --> this way we get KO instead of NA

Second proposition (to be developped further more) :
Same as for selenium click (verify element present, visible, clickable then only click), we could have a "Select action" (verify data exists, select).

(this little roman is a special dedication to my beloved Ben C !!)
Thanks for all the work,
best regards,
PF

**Comment by abourdon** [comment]
As you said, there is a way to do it right now, by two processes instead of one. I propose to close this issue as we have more priority ones. Maybe we could come back later if there are other users who want this feature.
