### ISSUE TITLE
Action Wait and "Lost connexion to selenium server"

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#977]
Cerberus Version : 1.1.6-SNAPSHOT

Hi,

Cerberus is communicating wrong error message on fails with "Wait" action.
Suggestion is : Selenium Timeout is inferior to Cerberus timeout. It looks like something similar.

EDIT : I confirm that when you have a click "failing", it's Timeout is 2minuts and then Cerberus behaves normaly, giving screenshot on error and source code of the page.

Exemple : Waiting for some element (wait + Xpath). Element doesn't arrive (website broken),
- Cerberus shows "CA" "Lost connexion to selenium server" --> no screenshot, no source
- instead of "FA" "could no find element" --> screenshot + source

![timeout lost connexion](https://cloud.githubusercontent.com/assets/16115517/19473189/ce2906f0-952a-11e6-8c47-2af23f962ea8.png)
[selenium_log.txt](https://github.com/vertigo17/Cerberus/files/535912/selenium_log.txt)

Best Regards,
PF

**Comment by bcivel** [comment]
Fixed.
