### ISSUE TITLE
Button "Create New Chain Event and Send Notification" is always disabled

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#980]
We are not able to send the notification for New Chain execution.
Button is always disabled.

![image](https://cloud.githubusercontent.com/assets/5640464/19520169/33f5392c-9607-11e6-9f6b-2c6b9ced7107.png)

**Comment by bcivel** [comment]
Hi @gmoita 
fixed in QA
<img width="603" alt="capture d ecran 2016-10-22 a 00 26 04" src="https://cloud.githubusercontent.com/assets/5376184/19613652/1cd5f6a8-97ee-11e6-8c02-6537c20d7995.png">
