### ISSUE TITLE
Action openUrlWithBase not working

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#982]
Hi,
For QA Cerberus version (Cerberus1.1.7-SNAPSHOT-957) the action openUrlWithBase isnot working.
For exaple test case execution:
http://192.168.134.197/CerberusQA/ExecutionDetail.jsp?id_tc=36702115
the base URL is defined as the mainpage (preprod/laredoute.fr in this case). It should add to the URL /plp/cat-334.aspx but it stays at the base url.

**Comment by bcivel** [comment]
fixed
