### ISSUE TITLE
Glassfish is detecting potential connection leaks

### ISSUE THREAD

**Issue by cjmachado** [cerberustesting/cerberus-source#983]
Cerberus-1.1.7-SNAPSHOT-957
Environment: QA

Glassfish is detecting a potential connection leak when running a campaign in QA environment. Stack trace is:

[#|2016-10-21T16:34:03.203+0200|WARNING|glassfish3.1.2|javax.enterprise.resource.resourceadapter.com.sun.enterprise.resource.pool|_ThreadID=120;_ThreadName=Thread-2;|A potential connection leak detected for connection pool CerberusMySQLqa. The stack trace of the thread is provided below : 
com.sun.enterprise.resource.pool.ConnectionPool.setResourceStateToBusy(ConnectionPool.java:324)
com.sun.enterprise.resource.pool.ConnectionPool.getMatchedResourceFromPool(ConnectionPool.java:816)
com.sun.enterprise.resource.pool.ConnectionPool.resizePoolAndGetNewResource(ConnectionPool.java:793)
com.sun.enterprise.resource.pool.ConnectionPool.getResourceFromPool(ConnectionPool.java:760)
com.sun.enterprise.resource.pool.ConnectionPool.getUnenlistedResource(ConnectionPool.java:632)
com.sun.enterprise.resource.pool.ConnectionPool.internalGetResource(ConnectionPool.java:526)
com.sun.enterprise.resource.pool.ConnectionPool.getResource(ConnectionPool.java:381)
com.sun.enterprise.resource.pool.PoolManagerImpl.getResourceFromPool(PoolManagerImpl.java:245)
com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:170)
com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:338)
com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:301)
com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:190)
com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:165)
com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:160)
com.sun.gjc.spi.base.DataSource.getConnection(DataSource.java:113)
org.cerberus.database.DatabaseSpring.connect(DatabaseSpring.java:66)
org.cerberus.crud.dao.impl.ParameterDAO.readWithSystem1ByKey(ParameterDAO.java:491)
org.cerberus.crud.service.impl.ParameterService.readWithSystem1ByKey(ParameterService.java:183)
org.cerberus.engine.execution.impl.SeleniumServerService.getTimeoutSetInParameterTable(SeleniumServerService.java:467)
org.cerberus.engine.execution.impl.SeleniumServerService.startServer(SeleniumServerService.java:108)
org.cerberus.engine.execution.impl.ExecutionStartService.startExecution(ExecutionStartService.java:397)
org.cerberus.engine.execution.impl.RunTestCaseService.runTestCase(RunTestCaseService.java:56)
org.cerberus.servlet.zzpublic.RunTestCase.doGet(RunTestCase.java:342)
javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
(...)

**Comment by bcivel** [comment]
Hi Guys,
I add a quick look and closed connection where it was missing.
Could you run campaign again to confirm that doesn't happen anymore?
Thanks
Benoit

**Comment by bcivel** [comment]
Hello @cjmachado 
Any news about this issue? 
It should not happen again but can you confirm you did'nt find it again? 
Can we close the issue?
Thanks
Benoit
