### ISSUE TITLE
Test case stays with status PE

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#984]
Hi,
Test case stays with status PE trying to calculate a property.
This property is a DataLib property set with nature NOTINUSE. All the 15 available account may be in used and test should return NA (has there are no more accounts available) but it stay with status PE.
Test case execution:
http://192.168.134.197/CerberusQA/ExecutionDetail.jsp?id_tc=36702361

Test for QA Cerberus version: Cerberus 1.1.8-SNAPSHOT-957
Thanks.

**Comment by bcivel** [comment]
should not happen anymore
