### ISSUE TITLE
Refactor way Cerberus get Image for sikuli testing

### ISSUE THREAD

**Issue by bcivel** [cerberustesting/cerberus-source#986]
Today, we split the picture url by the "." to get the extension.
The idea is to detect mimetype and file extension automatically, that will allow to use Application object.

**Comment by bcivel** [comment]
Done.
Adding apache tika, to detect automatically the mimetype and the extension of the input stream.

**Comment by vitoo** [comment]
@bcivel can you give an example to call sikuli picture ?
I haven't understand the %Object.Nom.PictureUrl%
We use this expression in val1 field ? 


Thank you

Victorien

**Comment by bcivel** [comment]
Hello @vitoo 
Beware, the %Object.Nom.PictureUrl% is not available on 1.1.7. It's available since a couple of commits only.

To use sikuli, you have now 2 methods : 
- since 1.1.2 : action: click    object: picture=http://url/to/your/picture.png
- since 1.1.8 (not published yet) : action: click    object: picture=%Object.Nom.PictureUrl%

To use the object, you must fill the applicationObject table.

On which version did you try? 1.1.7 or 1.1.8-SNAPSHOT ?

**Comment by vitoo** [comment]
Yes last 1.1.8

Finally works in old TestCase.jsp, but there is a little bug in TestCaseScript.jsp

When we add action, it doesnt save the object field
