### ISSUE TITLE
New syntax for variables in TestCase

### ISSUE THREAD

**Issue by Foudro** [cerberustesting/cerberus-source#988]
We have now new variable syntax in TestCase.jsp and TestCaseScript.jsp.
We define variable by puting '%' around it, and variables are specified with '.' like an object. 

For example :
%object.myobject.pictureurl% will be interpreted by the engine of cerberus as : 
It's an object from ApplicationObject,
its name is myobject,
and I want its picture url.

The list of variables is defined as above : 
- [x]  %property.myproperty% : Get the property "myproperty"
- [x]  %property.myproperty% : Get the key subdata of the1st row of property "myproperty" (myproperty is a testDataLib)
- [x]  %property.myproperty.5.subdata% : Get the subdata of the 5th row of property "myproperty" (myproperty is a testDataLib)
- [x]  %property.myproperty.subdata% : Get the subdata of the1st row of property "myproperty" (myproperty is a testDataLib)
- [x]  %property.myproperty.5% : Get the key subdata of the5th row of property "myproperty" (myproperty is a testDataLib)
- [x]  %object.myobject.value% : Get the value of the ApplicationObject myobject
- [x]  %object.myobject.picturepath% : Get the path where is stored the picture of the ApplicationObject myobject
- [x]  %object.myobject.pictureurl% : Get the cerberus url of the picture of the ApplicationObject myobject
- [x]  %system.VARIABLE% : Get the cerberus system variable.

**Comment by vitoo** [comment]
It works in old TestCase.jsp, but there is a little bug in TestCaseScript.jsp : When we add action, it doesnt save the object field

**Comment by vitoo** [comment]
Object auto completion doesnt work anymore here 
When i click on object i didnt get the childs options 
![image](https://cloud.githubusercontent.com/assets/995694/19808031/1dd4420a-9d23-11e6-94ab-e19a31baedb7.png)

![image](https://cloud.githubusercontent.com/assets/995694/19808072/4b82c1c2-9d23-11e6-99c9-2d9ff145bb54.png)


Is it from me ?

**Comment by Foudro** [comment]
Maybe it is because you don't have any application object in the application of the test case. An application object is linked to an application, so it is not accessible in another application.

**Comment by Foudro** [comment]
- [ ] Remove the option in the autocompletion if its sublist is empty

**Comment by vitoo** [comment]
Yes i have application object
![image](https://cloud.githubusercontent.com/assets/995694/19808458/44373acc-9d25-11e6-8e56-cf6ac22fb2ea.png)

It worked with yesterday commit. It works with last commit for you ?

**Comment by vitoo** [comment]
Well its works again 😩

**Comment by Foudro** [comment]
I'm not able to reproduce, maybe your browser is behaving differently, I'll try to find out what's happening
