### ISSUE TITLE
Pass %COUNTRY% in SQL datalib ?

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#989]
Hi,

Can we pass country's testcase parameter in SQL datalib?
ex:
`select * from dataset_vehicle where country = '%COUNTRY%'`

i got 500 error when typing '%' char in SQL : 

![image](https://cloud.githubusercontent.com/assets/995694/19809702/b178fada-9d2a-11e6-81d7-f2b47038e74b.png)

**Comment by ruirpr** [comment]
Yes you can. Try the following: 
- create your datalib but leave the script field empty and save
- open your recently created datalib and add the scrip with the %

As you can see we use that approach
![image](https://cloud.githubusercontent.com/assets/1914659/19815553/5b7d7028-9d3b-11e6-92ad-5755dbfff812.png)

**Comment by bcivel** [comment]
Thanks @Rui for the workaround. Unfortunatelly, it didn't help as it was a regression introduced in the 1.1.7 release.

@vitoo ,
It's now solved with the last commit.
