### ISSUE TITLE
Environment List - Column Filters

### ISSUE THREAD

**Issue by mbessa** [cerberustesting/cerberus-source#990]
Hello,

Found a bug in Environment.jsp page filters:

If a filter is applied for instance to "Country" column, it will apply a filder to maintenanceEnd (please check screenshot)
![image](https://cloud.githubusercontent.com/assets/5825695/19928529/b19cfdf2-a0f6-11e6-94c7-0ac174c152e6.png)

This also happen to the other columns.

Please also correct minor misspell in "Edit Environment > Databases" JDBC **Ressource** - Resource 

Thanks,
MB

Cerberus Version : 1.1.6-SNAPSHOT-928

**Comment by vertigo17** [comment]
Fixed the typo but could not reproduce the issue in prod.
