### ISSUE TITLE
Can't edit TestCase

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#991]
Hello,

Javascript error in the new test case editor 

Click : ![image](https://cloud.githubusercontent.com/assets/995694/19932169/4d940a80-a10f-11e6-89ac-c50f308ce8f2.png)

![image](https://cloud.githubusercontent.com/assets/995694/19932148/396cdc58-a10f-11e6-8974-01741304f126.png)

Thank you

**Comment by vertigo17** [comment]
Fixed with commit https://github.com/cerberustesting/cerberus-source/commit/3e12f97a90a7c5be8079cffbf6092d4c769d4192
