### ISSUE TITLE
Behavior : Re-executing tagged test case doesnt update the execution report by tag ?

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#993]
Hi,

I've noticed that with last version when we re-execute a test case, the execution report by Tag doesnt take the last execution of this tagged test case, but only first execution.

Before we could relaunch failed execution and see evolution of the report. 

Is this a new behaviour ?

Thanks

**Comment by vertigo17** [comment]
@vitoo Confirmed this is a regression.

**Comment by bcivel** [comment]
Fixed with my last commit.
Beware now, the sort is no more automatically on the columns test, testcase in the reporting page.
But you can define it manually and save the configuration.
