### ISSUE TITLE
Can the regex control use regex flag ?

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#995]
Hi,

Can the control verifyRegexInElement use regex flag ?

like : 'gi'
ex :
> (test_patern)**gi**

Thanks

**Comment by cjmachado** [comment]
Yes, it can. For instance:

(?i)bla

Will perform a case insensitive search for "bla" . Check the JDK javadocs for more information: https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html

**Comment by vitoo** [comment]
Thanks it works :)

We should document this regex control
