### ISSUE TITLE
GET SUBDATA FROM DATALIB - SYNTAX ERROR

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#996]
Hello,

I have an issue with the following synthax for datalib : %TOTO.SIZE%
But this one is OK : %TOTO(SIZE)%
You will find below execution result : 

http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=38541987

![datalib](https://cloud.githubusercontent.com/assets/18569182/19972327/f6f605ce-a1e1-11e6-9b08-db4fe1c8ca5a.JPG)

Thank you
Cerberus Version : 1.1.6-SNAPSHOT

**Comment by vertigo17** [comment]
Could not reproduce on last version.
Do you replicate in QA ? Does syntax %TOTO.SIZE% never works or only sometimes ?

**Comment by vertigo17** [comment]
@R-Loic Can we close the issue ?
Do you manage to replicate ?

**Comment by R-Loic** [comment]
Hello @vertigo17 ,
This error did not happen again. I think you can close this issue.
Thank you
