### ISSUE TITLE
Soap response / request not displayed 

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#997]
Hello,

In execution result page, sometimes the soap response and request links are not displayed : 
![response](https://cloud.githubusercontent.com/assets/18569182/19975807/a787b60c-a1ed-11e6-95d8-dadd6db23c85.JPG)

http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=38544627

The normal display is  : 
![responseok](https://cloud.githubusercontent.com/assets/18569182/19975842/c5a86348-a1ed-11e6-9a54-54530f7a0969.JPG)

Thank you

Cerberus Version : 1.1.6-SNAPSHOT

**Comment by vertigo17** [comment]
Does that issue always happen on that testcase execution or it happens only sometimes in a random way ?
How often ?

**Comment by R-Loic** [comment]
It happens in a random way.

Below you will find an execution with "soap response" at the wrong place : 

192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=38765383
