### ISSUE TITLE
New Feature / %SYS_PROPERTIES%

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#999]
Cerberus Version : 1.1.6-SNAPSHOT

Hi,

The %SYS_PROPERTIES% are often very handy ! So Handy that we'd use more if had them !
For instance, as you can see in the screenshot below, we manage Campaigns and their results in a seperate SQL Table. And we want more information about execution itself !!
![sys_properties](https://cloud.githubusercontent.com/assets/16115517/20052967/b0d0b5c4-a4d6-11e6-972e-8156292af3c5.png)
For example :
- SYS_EXESTARTTIME
- SYS_EXEENDTIME
- SYS_EXEENVIRONMENT
- SYS_EXEBROWSER
- SYS_TESTCASE (already in the newest version ?)
- SYS_TEST
- SYS_STEPxx_STATUS (OK / KO /FA / NA) : **THAT** would be crazy !

Anybody feel free to add ideas :)

PS : don't forget to party on issue 1000 (next one :p)
Best Regards,
PF

**Comment by vertigo17** [comment]
SYS_EXEENDTIME make no sense as the execution end  time is not known until we reach the end of the execution.

SYS_EXESTARTTIME --> %SYS_EXESTART%
SYS_EXEBROWSER --> %SYS_BROWSER%
SYS_TEST --> %SYS_TEST%
just been implemented.

SYS_EXEENVIRONMENT --> %SYS_ENV%
SYS_TESTCASE --> %SYS_TESTCASE%
Was already implemented

Still to implement : 
SYS_STEPxx_STATUS --> %SYS_STEP.n.STATUS%
not sure if n should be step id or step sort.

**Comment by vertigo17** [comment]
n should be the sort information.

**Comment by vertigo17** [comment]
Syntax will be %SYS_STEP.n.RETURNCODE%
